-- Critical path: P ≠ NP via SPDP rank separation
import PallLean.SPDPDefs
import PallLean.TuringMachine
import PallLean.Compiler
import PallLean.TseitinDefs
import PallLean.Tseitin
import PallLean.NPWitness
import PallLean.IdentityMinor
import PallLean.TagMonomial
import PallLean.CoeffDisjoint
import PallLean.ProductDeriv
import PallLean.BinomialBound
import PallLean.BinomialBound2
import PallLean.MultilinearSPDP
import PallLean.PneqNP
import PallLean.Leibniz
import PallLean.Profile

-- Paper-faithful God-Move / extraction route scaffold
import PallLean.GodMoveMonotonicity
import PallLean.GodMoveExtraction
import PallLean.GodMoveRoute
import PallLean.GodMoveMonotonicityML
import PallLean.GodMoveExtractionML
import PallLean.GodMoveCompilerRoute
import PallLean.TypeAnonymity
import PallLean.ProfileSpaceBound
import PallLean.TypeAnonymityDirect
import PallLean.ProfilePermutation
import PallLean.ProfileSpace
import PallLean.WidthRank
import PallLean.TypeAnonymityProof
import PallLean.CompiledSoS
import PallLean.RepresentationInvariance
import PallLean.PneqNP_SoS
import PallLean.PneqNP_v2
import PallLean.CompilerInvariance
import PallLean.CellPartition
import PallLean.VariableSplitting
import PallLean.PrivateVars
import PallLean.PaperPartition
