/-
  PallLean/Paper93/Direct/AdjacencyMlProj.lean

  Agent M9 of M (parallel) — Direct membership of the *multilinear
  projection* of the `shift · iterDerivList` of the compiled Cook-Levin
  adjacency factor `1 - X_i · X_j` in Agent I4's multilinear-projection
  closure of Agent I3's shift closure of the singleton submodule
  generated by `SPDP.iterDerivList S (1 - X_i · X_j)`.

  ## Scope

  Agent M8 (`PallLean/Paper93/Direct/AdjacencyShiftDeriv.lean`, commit
  `{M8}`) supplies, at the compiled Cook-Levin adjacency factor
  `1 - X_i · X_j`:

      adjacency_shift_deriv_mem :
        ∃ σ : Fin 4 ↪ Fin n,
          shift * SPDP.iterDerivList S (1 - X_i · X_j)
              ∈ shiftClosure (adjacencyDerivSubmodule i j S)
                             shift.totalDegree.

  Agent I4 (commit `736c1db`, `PallLean/Paper93/Closure/MlProjClosure.lean`)
  supplies the **multilinear-projection closure** of a submodule:

      mlProjClosure W  :=  W.map mlProjLM
          where  mlProjLM = MultilinearSPDP.mlProjLinearMap (Fin n) ℚ

  together with the definitional equality
  `mlProjClosure W = W.map mlProjLM` and the structural facts that
  `mlProjClosure` preserves finite-dimensionality and does not increase
  finrank.

  Agent M9 composes these two inputs to produce the **post-`mlProj`**
  membership statement consumed downstream when the SPDP generator
  construction `g ↦ mlProj (shift * g)` is applied to
  `g = SPDP.iterDerivList S (1 - X_i · X_j)`: the result lies in the
  `mlProj`-closure of the I3 shift closure of the singleton submodule
  generated by the iterated derivative.

  ## What this file delivers

  * `adjacency_mlProj_mem` — existence of an embedding
    `σ : Fin 4 ↪ Fin n` along which
        `mlProj (shift · SPDP.iterDerivList S (1 - X_i · X_j))`
    lies in Agent I4's `mlProjClosure` of Agent I3's shift closure of
    the singleton submodule generated by the iterated derivative.

  The embedding `σ` is supplied by reuse of the canonical adjacency
  embedding `adjacencyEmbedding hn4 i j hij` from Agent G2; it is not
  used in the `mlProj`-closure membership proof itself but is threaded
  through the signature for chain compatibility with M6, M7, M8, and
  downstream consumers that want to bundle the M9 deliverable with an
  adjacency-embedding witness.

  ## Proof recipe

    (i)   Agent M8 (`adjacency_shift_deriv_mem`) provides an embedding
          `σ` together with
              `shift * SPDP.iterDerivList S (1 - X_i · X_j)`
                ∈ `shiftClosure (adjacencyDerivSubmodule i j S)
                                shift.totalDegree`.
    (ii)  Agent I4 (`mlProjClosure_def`) unfolds
              `mlProjClosure W = W.map mlProjLM`.
    (iii) `Submodule.mem_map_of_mem` sends the M8 witness through the
          linear map `mlProjLM`, producing
              `mlProjLM (shift * SPDP.iterDerivList S (…))`
                ∈ `W.map mlProjLM = mlProjClosure W`.
    (iv)  Identify `mlProjLM x = MultilinearSPDP.mlProj x` via the
          definitional equality
              `mlProjLM = MultilinearSPDP.mlProjLinearMap (Fin n) ℚ`
          (so the linear-map application unfolds to the underlying
          `mlProj` function by the `mlProjLinearMap.toFun` field).

  ## Kernel-only

    * No `sorry`.
    * No bespoke axioms.
    * Verified by `lake build`.

  Expected `#print axioms`:
      [propext, Classical.choice, Quot.sound]
-/
import PallLean.Paper93.Direct.AdjacencyShiftDeriv
import PallLean.Paper93.Closure.MlProjClosure

namespace PallLean.Paper93.Direct

open MvPolynomial
open PallLean.Paper93
open PallLean.Paper93.Closure
open PallLean.Paper93.Spanning

/-! ## Main M9 deliverable -/

/-- **Agent M9: direct membership of `mlProj (shift · iterDerivList)`
for the compiled adjacency factor in Agent I4's multilinear-projection
closure.**

For every Turing-machine parameter tuple `(M, n, hn, htb, hns)` with
`hn4 : n ≥ 4`, every pair of distinct indices `(i, j)` with
`hij : i ≠ j`, every derivative-index list `S : List (Fin n)`, every
polynomial shift `shift : MvPolynomial (Fin n) ℚ`, and arbitrary side
conditions `_hS`, `_hshift` (threaded through for chain compatibility
with the SPDP generating-shape constraints used downstream), there
exists an embedding `σ : Fin 4 ↪ Fin n` along which

    MultilinearSPDP.mlProj
        (shift * SPDP.iterDerivList S (1 - X_i · X_j))
      ∈ mlProjClosure
          (shiftClosure (adjacencyDerivSubmodule i j S)
                        shift.totalDegree).

Composition recipe:

  (i)   Agent M8 (`adjacency_shift_deriv_mem`) gives an embedding `σ`
        and
            `shift * SPDP.iterDerivList S (1 - X_i · X_j)`
              ∈ `shiftClosure (adjacencyDerivSubmodule i j S)
                              shift.totalDegree`.

  (ii)  Agent I4 (`mlProjClosure_def`) unfolds
            `mlProjClosure W = W.map mlProjLM`.

  (iii) `Submodule.mem_map_of_mem` transports the M8 witness across
        the linear map `mlProjLM`, and `mlProjLM = MultilinearSPDP.mlProj`
        definitionally as a function (the linear-map `toFun` is the
        plain `mlProj`). -/
theorem adjacency_mlProj_mem
    (M : TuringMachine.DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (i j : Fin n) (hn4 : n ≥ 4)
    (S : List (Fin n))
    (shift : MvPolynomial (Fin n) ℚ)
    (hij : i ≠ j)
    (hS : S.length ≤ Nat.log 2 n)
    (hshift : shift.vars ⊆ S.toFinset) :
    ∃ σ : Fin 4 ↪ Fin n,
      MultilinearSPDP.mlProj
          (shift *
            SPDP.iterDerivList S
              (1 - MvPolynomial.X i * MvPolynomial.X j :
                  MvPolynomial (Fin n) ℚ))
        ∈ mlProjClosure
            (shiftClosure (adjacencyDerivSubmodule i j S)
                          shift.totalDegree) := by
  -- Step 1 (Agent M8): obtain an embedding σ and the shift-times-
  -- derivative's membership in the shift closure of the singleton
  -- submodule generated by the iterated derivative.
  obtain ⟨σ, hShiftDerivMem⟩ :=
    adjacency_shift_deriv_mem M n hn htb hns i j hn4 S shift hij hS hshift
  refine ⟨σ, ?_⟩
  -- Step 2: unfold `mlProjClosure` to `W.map mlProjLM`.
  rw [mlProjClosure_def]
  -- Step 3: push the M8 witness through the linear map `mlProjLM`.
  -- `mlProjLM` is, by definition, `MultilinearSPDP.mlProjLinearMap (Fin n) ℚ`
  -- whose `toFun` is `MultilinearSPDP.mlProj`. Hence the linear-map
  -- application `mlProjLM x` evaluates (by the `LinearMap` coercion
  -- chain) to `MultilinearSPDP.mlProj x`.
  --
  -- We transport the M8 membership `x ∈ shiftClosure …` to
  --     `mlProjLM x ∈ (shiftClosure …).map mlProjLM`
  -- via `Submodule.mem_map_of_mem`, and identify
  --     `mlProjLM x = MultilinearSPDP.mlProj x`
  -- on the goal side by `show`.
  have hMapMem :
      mlProjLM
          (shift *
            SPDP.iterDerivList S
              (1 - MvPolynomial.X i * MvPolynomial.X j :
                  MvPolynomial (Fin n) ℚ))
        ∈ (shiftClosure (adjacencyDerivSubmodule i j S)
                        shift.totalDegree).map (mlProjLM (N := n)) :=
    Submodule.mem_map_of_mem hShiftDerivMem
  -- Identify `mlProjLM x = MultilinearSPDP.mlProj x` on the goal.
  show MultilinearSPDP.mlProj
      (shift *
        SPDP.iterDerivList S
          (1 - MvPolynomial.X i * MvPolynomial.X j :
              MvPolynomial (Fin n) ℚ))
    ∈ (shiftClosure (adjacencyDerivSubmodule i j S)
                    shift.totalDegree).map (mlProjLM (N := n))
  -- `mlProjLM` applied to a polynomial literally unfolds to
  -- `MultilinearSPDP.mlProjLinearMap (Fin n) ℚ`, which in turn has
  -- `toFun = MultilinearSPDP.mlProj`; this is a definitional equality
  -- modulo the `LinearMap.coe_mk`/`DFunLike.coe` unfolding, which we
  -- discharge by direct substitution.
  have hEq :
      mlProjLM
          (shift *
            SPDP.iterDerivList S
              (1 - MvPolynomial.X i * MvPolynomial.X j :
                  MvPolynomial (Fin n) ℚ))
        = MultilinearSPDP.mlProj
            (shift *
              SPDP.iterDerivList S
                (1 - MvPolynomial.X i * MvPolynomial.X j :
                    MvPolynomial (Fin n) ℚ)) := rfl
  rw [← hEq]
  exact hMapMem

-- Suppress unused-variable lints on the cookLevinQ-shape parameters
-- retained in the public signature for downstream chain compatibility.
attribute [nolint unusedArguments] adjacency_mlProj_mem

/-! ## Kernel-only axiom trace

The deliverable should depend only on
`[propext, Classical.choice, Quot.sound]`, i.e. only the standard
Mathlib kernel axioms. No bespoke axiom is introduced; all content
routes through Agent M8 (`adjacency_shift_deriv_mem`) composed with
Agent I4 (`mlProjClosure_def` / `Submodule.mem_map_of_mem`). -/

#print axioms adjacency_mlProj_mem

end PallLean.Paper93.Direct
