/-
  PallLean/Paper93/Direct/AdjacencyShiftDeriv.lean

  Agent M8 of M (parallel) — Direct membership of the *shift-times-
  iterated-derivative* of the compiled Cook-Levin adjacency factor
  `1 - X_i · X_j` in Agent I3's shift closure of the singleton
  submodule generated by `SPDP.iterDerivList S (1 - X_i · X_j)`.

  ## Scope

  Agent I3 (commit `295e346`, `PallLean/Paper93/Closure/ShiftClosure.lean`)
  supplies, for any submodule `W : Submodule ℚ (MvPolynomial (Fin n) ℚ)`
  and any degree bound `ℓ : ℕ`, the **shift closure** submodule

      shiftClosure W ℓ  :=
          ⨆ s : { s // s.totalDegree ≤ ℓ }, W.map (mulByPoly s.1)

  together with the pointwise membership lemmas

      mul_mem_shiftClosure          :  f ∈ W → s.totalDegree ≤ ℓ
                                       → f * s ∈ shiftClosure W ℓ
      shift_mul_mem_shiftClosure    :  f ∈ W → s.totalDegree ≤ ℓ
                                       → s * f ∈ shiftClosure W ℓ

  Agent M8 runs in parallel with the (not-yet-landed) Agent M7 and
  packages the specific application of Agent I3 needed at the compiled
  adjacency factor `1 - X_i · X_j`:

      shift * SPDP.iterDerivList S (1 - X_i · X_j)
          ∈ shiftClosure (span {SPDP.iterDerivList S (1 - X_i · X_j)})
                         shift.totalDegree

  where `S : List (Fin n)` is the derivative index list and `shift` is
  a polynomial shift. The statement is parameterised by the full
  Turing-machine tuple `(M, n, hn, htb, hns)` and the adjacency indices
  `(i, j)` with `hij : i ≠ j` and `hn4 : n ≥ 4`, matching the
  Cook-Levin-shape signature used throughout `Paper93.Direct.*`.

  Per the task specification, the result is an existence statement:
  the M8 deliverable exhibits the shift closure witness together with
  a bound on the shift degree (we choose the tautological choice
  `ℓ = shift.totalDegree`, which is the tightest value making the
  I3 membership lemma fire).

  ## What this file delivers

  * `adjacency_shift_deriv_mem` — existence of an embedding
    `σ : Fin 4 ↪ Fin n` and a degree bound such that
    `shift * SPDP.iterDerivList S (1 - X_i · X_j)` lies in Agent I3's
    shift closure of the singleton submodule generated by the
    iterated derivative.

  The embedding `σ` is supplied by reuse of the canonical adjacency
  embedding `adjacencyEmbedding hn4 i j hij` from Agent G2; it is not
  used in the shift closure membership proof itself but is threaded
  through the signature for chain compatibility with M6
  (`AdjacencyDirect.lean`) and downstream consumers that want to
  bundle the M8 deliverable with an adjacency-embedding witness.

  ## Kernel-only

    * No `sorry`.
    * No bespoke axioms.
    * Verified by `lake build`.

  Expected `#print axioms`:
      [propext, Classical.choice, Quot.sound]
-/
import PallLean.Paper93.Closure.ShiftClosure
import PallLean.Paper93.Spanning.AdjacencyCase
import PallLean.SPDPDefs

namespace PallLean.Paper93.Direct

open MvPolynomial
open PallLean.Paper93
open PallLean.Paper93.Closure
open PallLean.Paper93.Spanning

/-! ## Setup: the singleton submodule carrying the iterated derivative

We work with the singleton submodule generated by the iterated
derivative of the compiled adjacency factor. This is the minimal
`W` that contains the iterated derivative and hence the minimal
shift-closure envelope into which the shift-times-derivative lands. -/

/-- The singleton ℚ-submodule spanned by the iterated derivative of
the compiled Cook-Levin adjacency factor `1 - X_i · X_j` along the
derivative-index list `S`. -/
noncomputable def adjacencyDerivSubmodule
    {n : ℕ} (i j : Fin n) (S : List (Fin n)) :
    Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
  Submodule.span ℚ
    ({ SPDP.iterDerivList S
          (1 - MvPolynomial.X i * MvPolynomial.X j :
              MvPolynomial (Fin n) ℚ) } :
        Set (MvPolynomial (Fin n) ℚ))

/-- The generator lies in the singleton submodule. -/
theorem iterDerivList_adjacency_mem_submodule
    {n : ℕ} (i j : Fin n) (S : List (Fin n)) :
    SPDP.iterDerivList S
        (1 - MvPolynomial.X i * MvPolynomial.X j :
            MvPolynomial (Fin n) ℚ)
      ∈ adjacencyDerivSubmodule i j S := by
  unfold adjacencyDerivSubmodule
  exact Submodule.mem_span_singleton_self _

/-! ## Main M8 deliverable -/

/-- **Agent M8: direct membership of the shift-times-derivative of
the compiled adjacency factor in Agent I3's shift closure.**

For every Turing-machine parameter tuple `(M, n, hn, htb, hns)` with
`hn4 : n ≥ 4`, every pair of distinct indices `(i, j)` with
`hij : i ≠ j`, every derivative-index list `S : List (Fin n)`, every
polynomial shift `shift : MvPolynomial (Fin n) ℚ`, and arbitrary side
conditions `hS`, `hshift` (threaded through for chain compatibility
with the SPDP generating-shape constraints used downstream), there
exists an embedding `σ : Fin 4 ↪ Fin n` along which

    shift * SPDP.iterDerivList S (1 - X_i · X_j)
        ∈ shiftClosure (adjacencyDerivSubmodule i j S) shift.totalDegree.

The embedding is the canonical adjacency embedding from Agent G2
(`adjacencyEmbedding hn4 i j hij`), retained in the conclusion for
downstream chain compatibility with Agent M6's adjacency-case
deliverable. The shift closure membership follows directly from
Agent I3's pointwise lemma `shift_mul_mem_shiftClosure` applied to
the generator of the singleton submodule at the tautological degree
bound `ℓ := shift.totalDegree`. -/
theorem adjacency_shift_deriv_mem
    (M : TuringMachine.DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (i j : Fin n) (hn4 : n ≥ 4)
    (S : List (Fin n))
    (shift : MvPolynomial (Fin n) ℚ)
    (hij : i ≠ j)
    (_hS : S.length ≤ Nat.log 2 n)
    (_hshift : shift.vars ⊆ S.toFinset) :
    ∃ _σ : Fin 4 ↪ Fin n,
      shift *
          SPDP.iterDerivList S
            (1 - MvPolynomial.X i * MvPolynomial.X j :
                MvPolynomial (Fin n) ℚ)
        ∈ shiftClosure (adjacencyDerivSubmodule i j S) shift.totalDegree := by
  -- Silence unused-argument linter on `M, hn, htb, hns`.
  let _ := M; let _ := hn; let _ := htb; let _ := hns
  -- Produce the canonical adjacency embedding from Agent G2.
  refine ⟨adjacencyEmbedding hn4 i j hij, ?_⟩
  -- The generator lies in the singleton submodule.
  have hGenMem :
      SPDP.iterDerivList S
          (1 - MvPolynomial.X i * MvPolynomial.X j :
              MvPolynomial (Fin n) ℚ)
        ∈ adjacencyDerivSubmodule i j S :=
    iterDerivList_adjacency_mem_submodule i j S
  -- The shift has total degree ≤ itself (tautology).
  have hShiftDeg : shift.totalDegree ≤ shift.totalDegree := le_refl _
  -- Apply Agent I3's `shift_mul_mem_shiftClosure`.
  exact shift_mul_mem_shiftClosure
    (adjacencyDerivSubmodule i j S)
    shift.totalDegree
    hGenMem
    hShiftDeg

-- Suppress unused-variable lints on the cookLevinQ-shape parameters
-- retained in the public signature for downstream chain compatibility.
attribute [nolint unusedArguments] adjacency_shift_deriv_mem

/-! ## Kernel-only axiom trace

The deliverable should depend only on
`[propext, Classical.choice, Quot.sound]`, i.e. only the standard
Mathlib kernel axioms. No bespoke axiom is introduced. -/

#print axioms adjacency_shift_deriv_mem

end PallLean.Paper93.Direct
