/-
  PallLean/Paper93/Direct/BooleanityShiftDeriv.lean

  Paper §9 Lemma 31 — direct shift-closure / derivative-closure
  membership for the compiled Cook-Levin booleanity factor
  `1 - X_v + X_v^2`.

  Agent M3 of 10 (parallel).

  ## Scope

  This file wires together three deliverables from earlier agents to
  produce a single-step shift / derivative / booleanity closure lemma:

    * Agent M1's `booleanity_factor_direct_mem`
      (`PallLean/Paper93/Direct/BooleanityDirect.lean`) delivers, for
      any `v : Fin n` and any cookLevinQ-compilation parameter tuple
      `(M, n, hn, htb, hns, hn4)`, a canonical embedding
      `σ : Fin 4 ↪ Fin n` with
        `1 - X_v + X_v^2  ∈  concreteW n hn4 σ .booleanity`.

    * Agent H4's derivative closure
      (`PallLean/Paper93/Spanning/DerivativeClosure.lean`) supplies
      `iterDerivSubmodule W S`, the ambient sub-module
      consisting of all iterated partial derivatives
      `iterDerivList S f` for `f ∈ W`, together with the transport
      lemma
        `f ∈ W → iterDerivList S f ∈ iterDerivSubmodule W S`.

    * Agent I3's shift closure
      (`PallLean/Paper93/Closure/ShiftClosure.lean`, commit `295e346`)
      supplies `shiftClosure W ℓ`, the ambient submodule generated by
      `s · f` for every `f ∈ W` and every shift polynomial `s` with
      `totalDegree s ≤ ℓ`, together with the pointwise membership
      lemma
        `s * f ∈ shiftClosure W ℓ`
      provided `f ∈ W` and `s.totalDegree ≤ ℓ`.

  Composing the three gives the Agent M3 deliverable: for every
  variable `v : Fin n` and every bounded-length derivative list `S`
  and bounded-degree shift polynomial `shift`, the element
  `shift * iterDerivList S (1 - X_v + X_v^2)` lies in the shift
  closure of the iterated derivative closure of the concrete ambient
  per-type space `concreteW n hn4 σ .booleanity`, along a canonical
  embedding `σ`.

  ## Deliverable

    * `booleanity_shift_deriv_mem` — the composed membership.

  ## Kernel-only

    * No `sorry`.
    * No bespoke axioms.
    * Verified by `lake build`.

  Expected `#print axioms`:
      [propext, Classical.choice, Quot.sound]
-/
import PallLean.Paper93.Direct.BooleanityDirect
import PallLean.Paper93.Spanning.DerivativeClosure
import PallLean.Paper93.Closure.ShiftClosure

namespace PallLean.Paper93.Direct

open MvPolynomial
open PallLean.Paper93
open PallLean.Paper93.Bridge
open PallLean.Paper93.Spanning
open PallLean.Paper93.Closure
open PallLean.Paper93.Wiring
open SymmetricPowerBound (ConstraintType)

/-- **Agent M3 main theorem — booleanity shift/deriv closure membership.**

For every cookLevinQ-compilation parameter tuple `(M, n, hn, htb, hns)`
with `hn4 : n ≥ 4`, every tape variable `v : Fin n`, every derivative
list `S : List (Fin n)` with `S.length ≤ Nat.log 2 n`, and every shift
polynomial `shift : MvPolynomial (Fin n) ℚ` with
`shift.totalDegree ≤ Nat.log 2 n`, there exists a canonical embedding
`σ : Fin 4 ↪ Fin n` along which
    `shift * iterDerivList S (1 - X_v + X_v^2)`
lies in the shift closure of the iterated derivative closure of the
concrete ambient per-type space `concreteW n hn4 σ .booleanity` at
degree `Nat.log 2 n`.

Composition recipe:
  (i)   Agent M1 (`booleanity_factor_direct_mem`) gives a σ with
        `1 - X_v + X_v^2 ∈ concreteW n hn4 σ .booleanity`.
  (ii)  Agent H4 (`iterDerivList_mem_iterDerivSubmodule`) transports
        this membership through `iterDerivList S _` into
        `iterDerivSubmodule (concreteW n hn4 σ .booleanity) S`.
  (iii) Agent I3 (`shift_mul_mem_shiftClosure`) multiplies by `shift`
        (with `shift.totalDegree ≤ Nat.log 2 n`) into
        `shiftClosure (iterDerivSubmodule …) (Nat.log 2 n)`. -/
theorem booleanity_shift_deriv_mem
    (M : TuringMachine.DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (v : Fin n) (hn4 : n ≥ 4)
    (S : List (Fin n)) (shift : MvPolynomial (Fin n) ℚ)
    (_hS : S.length ≤ Nat.log 2 n)
    (hshift : shift.totalDegree ≤ Nat.log 2 n) :
    ∃ σ : Fin 4 ↪ Fin n,
      shift * SPDP.iterDerivList S
          (1 - MvPolynomial.X v + (MvPolynomial.X v) ^ 2 :
              MvPolynomial (Fin n) ℚ)
        ∈ PallLean.Paper93.Closure.shiftClosure
            (PallLean.Paper93.Spanning.iterDerivSubmodule
              (concreteW n hn4 σ ConstraintType.booleanity) S)
            (Nat.log 2 n) := by
  classical
  -- Step 1 (Agent M1): obtain an embedding σ and the booleanity
  -- factor's membership in `concreteW n hn4 σ .booleanity`.
  obtain ⟨σ, hfMem⟩ :=
    booleanity_factor_direct_mem M n hn htb hns v hn4
  refine ⟨σ, ?_⟩
  -- Step 2 (Agent H4): transport through `iterDerivList S _`.
  have hDerivMem :
      SPDP.iterDerivList S
          (1 - MvPolynomial.X v + (MvPolynomial.X v) ^ 2 :
              MvPolynomial (Fin n) ℚ)
        ∈ PallLean.Paper93.Spanning.iterDerivSubmodule
            (concreteW n hn4 σ ConstraintType.booleanity) S :=
    PallLean.Paper93.Spanning.iterDerivList_mem_iterDerivSubmodule
      (concreteW n hn4 σ ConstraintType.booleanity)
      (1 - MvPolynomial.X v + (MvPolynomial.X v) ^ 2) hfMem S
  -- Step 3 (Agent I3): multiply by `shift` with `totalDegree ≤ ℓ`.
  have hShiftMem :
      shift * SPDP.iterDerivList S
          (1 - MvPolynomial.X v + (MvPolynomial.X v) ^ 2 :
              MvPolynomial (Fin n) ℚ)
        ∈ PallLean.Paper93.Closure.shiftClosure
            (PallLean.Paper93.Spanning.iterDerivSubmodule
              (concreteW n hn4 σ ConstraintType.booleanity) S)
            (Nat.log 2 n) :=
    PallLean.Paper93.Closure.shift_mul_mem_shiftClosure
      (PallLean.Paper93.Spanning.iterDerivSubmodule
        (concreteW n hn4 σ ConstraintType.booleanity) S)
      (Nat.log 2 n) hDerivMem hshift
  -- Discharge the `refine ⟨σ, ?_⟩` goal with the Step-3 membership.
  exact hShiftMem

/-! ## Kernel-only axiom trace

The deliverable should depend only on
`[propext, Classical.choice, Quot.sound]`. -/

#print axioms booleanity_shift_deriv_mem

end PallLean.Paper93.Direct
