/-
  PallLean/Paper93/Direct/TransitionLeftShiftDeriv.lean

  Paper §9 Lemma 31 — direct shift-closure / derivative-closure
  membership for the compiled Cook-Levin transitionLeft factor
  `transitionLeftAmbientFactor σ = X (σ 0) : MvPolynomial (Fin n) ℚ`.

  Agent M13 of M (parallel).

  ## Scope

  This file wires together three deliverables from earlier agents to
  produce a single-step shift / derivative / transitionLeft closure
  lemma, mirroring Agent M3's `booleanity_shift_deriv_mem`
  (`PallLean/Paper93/Direct/BooleanityShiftDeriv.lean`) at the
  transitionLeft constraint type:

    * Agent M12's `transitionLeft_factor_direct_mem`
      (`PallLean/Paper93/Direct/TransitionLeftDirect.lean`) delivers, for
      any cookLevinQ-compilation parameter tuple
      `(M, n, hn, htb, hns, q, i, j)` with `hn4 : n ≥ 4`, a canonical
      embedding `σ : Fin 4 ↪ Fin n` with
        `transitionLeftAmbientFactor σ
              ∈ concreteW n hn4 σ .transitionLeft`,
      where `transitionLeftAmbientFactor σ = X (σ 0)` is the rename
      of Agent A's `transitionTemplate = X 0` along `σ`.

    * Agent H4's derivative closure
      (`PallLean/Paper93/Spanning/DerivativeClosure.lean`) supplies
      `iterDerivSubmodule W S`, the ambient sub-module consisting of
      all iterated partial derivatives `iterDerivList S f` for
      `f ∈ W`, together with the transport lemma
        `f ∈ W → iterDerivList S f ∈ iterDerivSubmodule W S`.

    * Agent I3's shift closure
      (`PallLean/Paper93/Closure/ShiftClosure.lean`, commit `295e346`)
      supplies `shiftClosure W ℓ`, the ambient submodule generated by
      `s · f` for every `f ∈ W` and every shift polynomial `s` with
      `totalDegree s ≤ ℓ`, together with the pointwise membership
      lemma
        `s * f ∈ shiftClosure W ℓ`
      provided `f ∈ W` and `s.totalDegree ≤ ℓ`.

  Composing the three yields the Agent M13 deliverable: for every
  bounded-length derivative list `S` and bounded-degree shift polynomial
  `shift`, the element
    `shift * iterDerivList S (transitionLeftAmbientFactor σ)`
  lies in the shift closure of the iterated derivative closure of the
  concrete ambient per-type space `concreteW n hn4 σ .transitionLeft`,
  along a canonical embedding `σ`.

  ## Deliverable

    * `transitionLeft_shift_deriv_mem` — the composed membership.

  ## Kernel-only

    * No `sorry`.
    * No bespoke axioms.
    * Verified by `lake build`.

  Expected `#print axioms`:
      [propext, Classical.choice, Quot.sound]
-/
import PallLean.Paper93.Direct.TransitionLeftDirect
import PallLean.Paper93.Spanning.DerivativeClosure
import PallLean.Paper93.Closure.ShiftClosure

namespace PallLean.Paper93.Direct

open MvPolynomial
open PallLean.Paper93
open PallLean.Paper93.Bridge
open PallLean.Paper93.Spanning
open PallLean.Paper93.Closure
open PallLean.Paper93.Wiring
open SymmetricPowerBound (ConstraintType)

/-- **Agent M13 main theorem — transitionLeft shift/deriv closure
membership.**

For every cookLevinQ-compilation parameter tuple
`(M, n, hn, htb, hns)` with `hn4 : n ≥ 4`, every transitionLeft-factor
parameterisation `(q, i, j)`, every derivative list `S : List (Fin n)`
with `S.length ≤ Nat.log 2 n`, and every shift polynomial
`shift : MvPolynomial (Fin n) ℚ` with
`shift.totalDegree ≤ Nat.log 2 n`, there exists a canonical embedding
`σ : Fin 4 ↪ Fin n` along which
    `shift * iterDerivList S (transitionLeftAmbientFactor σ)`
lies in the shift closure of the iterated derivative closure of the
concrete ambient per-type space `concreteW n hn4 σ .transitionLeft` at
degree `Nat.log 2 n`.

Composition recipe:
  (i)   Agent M12 (`transitionLeft_factor_direct_mem`) gives a σ with
        `transitionLeftAmbientFactor σ
              ∈ concreteW n hn4 σ .transitionLeft`.
  (ii)  Agent H4 (`iterDerivList_mem_iterDerivSubmodule`) transports
        this membership through `iterDerivList S _` into
        `iterDerivSubmodule (concreteW n hn4 σ .transitionLeft) S`.
  (iii) Agent I3 (`shift_mul_mem_shiftClosure`) multiplies by `shift`
        (with `shift.totalDegree ≤ Nat.log 2 n`) into
        `shiftClosure (iterDerivSubmodule …) (Nat.log 2 n)`.

The per-instance parameters `(q, i, j)` from the cookLevinQ-shape
signature are retained in the public signature for downstream chain
compatibility with Agent M12 (`TransitionLeftDirect`). They are not
used in the proof — the transitionLeft factor polynomial at the
ambient `Fin n` level depends only on the coordinate embedding `σ` and
the constraint type `.transitionLeft`, uniformly in `(q, i, j)`. -/
theorem transitionLeft_shift_deriv_mem
    (M : TuringMachine.DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (q : Fin M.numStates) (i : Fin n) (j : Fin n) (hn4 : n ≥ 4)
    (S : List (Fin n)) (shift : MvPolynomial (Fin n) ℚ)
    (_hS : S.length ≤ Nat.log 2 n)
    (hshift : shift.totalDegree ≤ Nat.log 2 n) :
    ∃ σ : Fin 4 ↪ Fin n,
      shift * SPDP.iterDerivList S
          (transitionLeftAmbientFactor σ : MvPolynomial (Fin n) ℚ)
        ∈ PallLean.Paper93.Closure.shiftClosure
            (PallLean.Paper93.Spanning.iterDerivSubmodule
              (concreteW n hn4 σ ConstraintType.transitionLeft) S)
            (Nat.log 2 n) := by
  classical
  -- Step 1 (Agent M12): obtain an embedding σ and the transitionLeft
  -- factor's membership in `concreteW n hn4 σ .transitionLeft`.
  obtain ⟨σ, hfMem⟩ :=
    transitionLeft_factor_direct_mem M n hn htb hns q i j hn4
  refine ⟨σ, ?_⟩
  -- Step 2 (Agent H4): transport through `iterDerivList S _`. The
  -- per-derivative transport lemma fires on the M12 membership.
  have hDerivMem :
      SPDP.iterDerivList S
          (transitionLeftAmbientFactor σ : MvPolynomial (Fin n) ℚ)
        ∈ PallLean.Paper93.Spanning.iterDerivSubmodule
            (concreteW n hn4 σ ConstraintType.transitionLeft) S :=
    PallLean.Paper93.Spanning.iterDerivList_mem_iterDerivSubmodule
      (concreteW n hn4 σ ConstraintType.transitionLeft)
      (transitionLeftAmbientFactor σ) hfMem S
  -- Step 3 (Agent I3): multiply by `shift` with `totalDegree ≤ ℓ`.
  -- Agent I3's `shift_mul_mem_shiftClosure` places the product into
  -- the shift closure at degree `Nat.log 2 n`.
  exact
    PallLean.Paper93.Closure.shift_mul_mem_shiftClosure
      (PallLean.Paper93.Spanning.iterDerivSubmodule
        (concreteW n hn4 σ ConstraintType.transitionLeft) S)
      (Nat.log 2 n) hDerivMem hshift

-- Suppress unused-variable lints on the cookLevinQ-shape parameters
-- retained in the public signature for downstream chain compatibility.
attribute [nolint unusedArguments] transitionLeft_shift_deriv_mem

/-! ## Kernel-only axiom trace

The deliverable should depend only on
`[propext, Classical.choice, Quot.sound]`, i.e. only the standard
Mathlib kernel axioms. No bespoke axiom is introduced. -/

#print axioms transitionLeft_shift_deriv_mem

end PallLean.Paper93.Direct
