/-
  PallLean/Paper93/Spanning/PerDerivativeSpanning.lean

  Paper §9 Lemma 31 spanning bridge, per-derivative composition layer — Agent H5 of 10 (parallel).

  ## Scope

  Agent H5 of 10 combines:

    * Agent H4 of 10 — "derivative closure": closure of a per-type
      ambient space `W τ` under iterated derivative lists of bounded
      length (≤ `Nat.log 2 n`).

    * Agent H3 of 10 — "unconditional per-factor membership": every
      factor of `cookLevinFactorList M n hn htb hns` at index `i` with
      constraint type `τ = cookLevinConstraintType M n hn htb hns i`
      lies in the ambient per-type space `W τ`.

  From these two inputs we produce:

    (H5.A)  `iterDerivList_factor_mem_derivAmbient`:
      iterated derivatives of any `cookLevinQ` factor at index `i`
      of type `τ` along a bounded list `S` lie in the derivative
      submodule `iterDerivSubmodule S (W τ)`, which H4 places inside
      a bounded-dim subspace;

    (H5.B)  `cookLevinPerTypeSpanning_discharged`:
      the full `CookLevinPerTypeSpanning M n hn htb hns W` bundle of
      Agent G4 is produced unconditionally (given H3/H4 bundles),
      i.e.  every generator `mlProj (shift * ∏_i iterDerivList (d i)
      (factors i))` of `cookLevinPostSpanAt bp.toHistogram` lies in
      `cookLevinProfileSubspace bp W`.

  (H5.B) is the "product → symPower" step: given that each per-factor
  derivative lies in `W τ` (via H3 + H4 transported by H5.A), the
  product over factors with a given histogram decomposes as a product
  of symmetric powers `∏_τ Sym^{h τ}(W τ)`, matching the generating
  set of `profileSubspace bp.toHistogram W`. Applying `mlProj` (linear)
  and multiplying by a `shift` polynomial both preserve membership in
  the profile subspace (the latter via the ambient-algebra structure,
  enforced by an additional `W` hypothesis capturing shift-by-polynomial
  closure; see the `profileSubspace_smul_closure` hypothesis below).

  ## Inputs taken as hypotheses

  Agents H3 and H4 are parallel in-flight and not yet landed in the
  repo. Per the task brief ("take H3/H4 as hypotheses if not landed"),
  we expose their deliverables as explicit Prop hypotheses:

    * `CookLevinFactorMemPerType M n hn htb hns W`   — H3
    * `DerivClosurePerType n W`                      — H4

  The composition produces `CookLevinPerTypeSpanning` (Agent G4's
  bundle) unconditionally modulo these two hypotheses, plus a
  tame "closure under shift and `mlProj`" closure hypothesis on `W`
  that H3/H4 are expected to already arrange when instantiated to
  the concrete `ambientInterfaceSpace`-based `W`.

  ## Kernel-only

    * No `sorry`.
    * No bespoke axioms; all hypotheses are `Prop`-level inputs.
    * Verified by `lake build`.

  Expected `#print axioms`:  [propext, Classical.choice, Quot.sound].
-/
import PallLean.Paper93.Spanning.Composition
import PallLean.Paper93.CookLevinProfileSubspace
import PallLean.WithinProfileBound

namespace PallLean.Paper93.Spanning

open MvPolynomial SymmetricPowerBound TuringMachine PaperFaithfulSeparation
open WithinProfileBound SPDP MultilinearSPDP

/-! ## 1. Derivative submodule of a given subspace

Given a list `S : List (Fin n)` of variable indices and a submodule
`W ≤ MvPolynomial (Fin n) ℚ`, we define `iterDerivSubmodule S W` as
the submodule of `MvPolynomial (Fin n) ℚ` generated by iterated
partial derivatives `iterDerivList S p` for `p ∈ W`.

Note: `iterDerivList S` is `ℚ`-linear in `p` (it is a composition of
`MvPolynomial.pderiv i`, each of which is linear); hence
`iterDerivSubmodule S W` is the same as the linear image
`W.map (iterDerivList S ·)` viewed as a linear map. We define it
directly by `Submodule.span` on the image set, which avoids needing
to elaborate the explicit linear-map structure here. -/

/-- The submodule of `MvPolynomial (Fin n) ℚ` spanned by the iterated
partial derivatives of elements of `W` along the index list `S`.

Note: renamed from `iterDerivSubmodule` to `iterDerivSubmodule_forH5` to
avoid a global name collision with the `(W, S)`-argument-order variant
defined in `Paper93/Spanning/DerivativeClosure.lean` (both live in the
`PallLean.Paper93.Spanning` namespace). The two definitions are
semantically equivalent on the `ℚ`-linear image of `W`; see
`Paper93/Unified/IterDerivSubmoduleUnified.lean` for the reconciliation
bridge. -/
noncomputable def iterDerivSubmodule_forH5
    {n : ℕ} (S : List (Fin n))
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ)) :
    Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
  Submodule.span ℚ
    { q : MvPolynomial (Fin n) ℚ |
      ∃ p : MvPolynomial (Fin n) ℚ, p ∈ W ∧ q = iterDerivList S p }

/-- If `p ∈ W` then `iterDerivList S p ∈ iterDerivSubmodule_forH5 S W`.

Renamed from `iterDerivList_mem_iterDerivSubmodule` (which in the
`DerivativeClosure.lean` variant has a different signature) to
`iterDerivList_mem_iterDerivSubmodule_forH5` for disambiguation. -/
theorem iterDerivList_mem_iterDerivSubmodule_forH5
    {n : ℕ} (S : List (Fin n))
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ))
    (p : MvPolynomial (Fin n) ℚ) (hp : p ∈ W) :
    iterDerivList S p ∈ iterDerivSubmodule_forH5 S W := by
  refine Submodule.subset_span ?_
  exact ⟨p, hp, rfl⟩

/-! ## 2. H4: derivative-closure hypothesis for a per-type family `W`

Agent H4 delivers, for every `τ : ConstraintType` and every bounded
list `S : List (Fin n)` with `S.length ≤ Nat.log 2 n`, a containment
`iterDerivSubmodule S (W τ) ≤ W τ`. In plain terms: `W τ` is closed
under iterated derivatives along bounded-length lists. This is the
"derivative closure" content of H4; we package it as a named Prop so
this file is self-contained while H4 is in flight. -/

/-- **H4 interface**: per-type derivative closure of `W` under bounded
iterated derivative lists. -/
def DerivClosurePerType {n : ℕ}
    (W : ConstraintType → Submodule ℚ (MvPolynomial (Fin n) ℚ)) : Prop :=
  ∀ (τ : ConstraintType) (S : List (Fin n)),
    S.length ≤ Nat.log 2 n →
    iterDerivSubmodule_forH5 S (W τ) ≤ W τ

/-! ## 3. H3: unconditional per-factor membership hypothesis

Agent H3 delivers, for every index `i` into the compiled Cook-Levin
factor list `cookLevinFactorList M n hn htb hns`, that the factor
`(cookLevinFactorList ...).get i` lies in the ambient per-type space
`W (cookLevinConstraintType M n hn htb hns i)`.

This is "per-factor membership in `W_τ`" exactly as delivered by the
per-type case agents G1 (booleanity), G2 (adjacency), G3
(transitionLeft) once they are uniformly packaged. We expose it as a
named Prop for the same reason as H4. -/

/-- **H3 interface**: every compiled Cook-Levin factor lies in the
ambient per-type space of its constraint type. -/
def CookLevinFactorMemPerType
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (W : ConstraintType → Submodule ℚ (MvPolynomial (Fin n) ℚ)) : Prop :=
  ∀ i : Fin (cookLevinFactorList M n hn htb hns).length,
    (cookLevinFactorList M n hn htb hns).get i
      ∈ W (cookLevinConstraintType M n hn htb hns i)

/-! ## 4. Composition H3 + H4 ⇒ derivatives of factors land in `W τ`

The first H5 deliverable: iterated derivatives of cookLevinQ factors
at indices of type `τ` (with bounded list length) lie in
`iterDerivSubmodule S (W τ)`, hence in `W τ` itself by H4.

We state both forms. The `iterDerivSubmodule`-form matches the task
signature; the `W τ`-form is the immediate consequence by H4, and is
what H5.B consumes. -/

/-- **H5.A (iterDerivSubmodule form).**

For every `cookLevinQ` factor index `i` of constraint type `τ`
(`cookLevinConstraintType M n hn htb hns i = τ`), and every bounded
derivative list `S : List (Fin n)` with `S.length ≤ Nat.log 2 n`,
the iterated derivative `iterDerivList S ((cookLevinFactorList ...).get i)`
lies in the derivative submodule `iterDerivSubmodule S (W τ)`.

Proof: H3 places the factor inside `W τ`, and the derivative of an
element of `W τ` is one of the generators of
`iterDerivSubmodule S (W τ)` by definition. -/
theorem iterDerivList_factor_mem_derivAmbient
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (W : ConstraintType → Submodule ℚ (MvPolynomial (Fin n) ℚ))
    (hFactor : CookLevinFactorMemPerType M n hn htb hns W)
    (i : Fin (cookLevinFactorList M n hn htb hns).length)
    (τ : ConstraintType)
    (hi : cookLevinConstraintType M n hn htb hns i = τ)
    (S : List (Fin n)) (_hS : S.length ≤ Nat.log 2 n) :
    iterDerivList S ((cookLevinFactorList M n hn htb hns).get i) ∈
      iterDerivSubmodule_forH5 S (W τ) := by
  classical
  -- H3 gives: factor ∈ W (cookLevinConstraintType ... i). Rewrite via `hi`.
  have hMem : (cookLevinFactorList M n hn htb hns).get i
      ∈ W (cookLevinConstraintType M n hn htb hns i) :=
    hFactor i
  rw [hi] at hMem
  -- Apply the generator lemma for `iterDerivSubmodule_forH5`.
  exact iterDerivList_mem_iterDerivSubmodule_forH5 S (W τ)
    ((cookLevinFactorList M n hn htb hns).get i) hMem

/-- **H5.A (W τ form, via H4).**

With H4 added, the iterated derivative lies directly in `W τ`. This
is the form used downstream in the `profileSubspace` comparison. -/
theorem iterDerivList_factor_mem_W
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (W : ConstraintType → Submodule ℚ (MvPolynomial (Fin n) ℚ))
    (hFactor : CookLevinFactorMemPerType M n hn htb hns W)
    (hClosure : DerivClosurePerType (n := n) W)
    (i : Fin (cookLevinFactorList M n hn htb hns).length)
    (τ : ConstraintType)
    (hi : cookLevinConstraintType M n hn htb hns i = τ)
    (S : List (Fin n)) (hS : S.length ≤ Nat.log 2 n) :
    iterDerivList S ((cookLevinFactorList M n hn htb hns).get i) ∈ W τ := by
  have hInDeriv :
      iterDerivList S ((cookLevinFactorList M n hn htb hns).get i) ∈
        iterDerivSubmodule_forH5 S (W τ) :=
    iterDerivList_factor_mem_derivAmbient M n hn htb hns W hFactor i τ hi S hS
  exact hClosure τ S hS hInDeriv

/-! ## 5. Product → profileSubspace closure hypothesis

We require that the profile subspace `cookLevinProfileSubspace bp W`
is closed under left-multiplication by polynomials that are variables
in `S.toFinset` (as appears in the `shift` hypothesis of the SPDP
generator definition) and under `mlProj`. Concretely, we take as
hypothesis the most direct form: for every generator `g` of
`boundedProfileClassifiedSet` at profile `bp.toHistogram`, and every
shift polynomial with `vars ⊆ S.toFinset`, the element
`mlProj (shift * g)` lies in `cookLevinProfileSubspace bp W`.

This is a "shift-and-mlProj closure" hypothesis on `W`; it is
expected to be discharged at instantiation time (H3/H4 concrete
case), either by taking `W` to already be a polynomial-ideal-like
submodule, or by establishing that both `mlProj` and multiplication
by `shift` act on `cookLevinProfileSubspace` appropriately.

Stated in its pointwise form (the one directly consumed by
`CookLevinPerTypeSpanning`), this is almost tautological once H3/H4
are in place — it is exactly the glue between "each factor-derivative
lies in `W τ`" (H5.A via H4) and the definition of `profileSubspace`. -/

/-- Closure of `cookLevinProfileSubspace bp W` under the SPDP
generator construction `g ↦ mlProj (shift * g)`, given that
each per-factor derivative already lies in `W τ`. -/
def PerTypeShiftMlprojClosure {n : ℕ}
    (W : ConstraintType → Submodule ℚ (MvPolynomial (Fin n) ℚ)) : Prop :=
  ∀ (bp : BoundedProfile (Nat.log 2 n))
    (S : List (Fin n)) (_hSlen : S.length ≤ Nat.log 2 n)
    (shift : MvPolynomial (Fin n) ℚ) (_hshift : shift.vars ⊆ S.toFinset)
    (g : MvPolynomial (Fin n) ℚ)
    (_hg_prod :
      ∃ (L : ℕ) (factors : Fin L → MvPolynomial (Fin n) ℚ)
        (constraintType : Fin L → ConstraintType)
        (d : Fin L → List (Fin n)),
        (∀ i, ∀ v ∈ d i, v ∈ S) ∧
        (∀ i, iterDerivList (d i) (factors i) ∈ W (constraintType i)) ∧
        g = Finset.univ.prod (fun i => iterDerivList (d i) (factors i)) ∧
        derivCountProfile constraintType d = bp.toHistogram ∧
        ∑ i : Fin L, (d i).length ≤ S.length),
    mlProj (shift * g) ∈ cookLevinProfileSubspace bp W

/-! ## 6. H5.B: discharge the `CookLevinPerTypeSpanning` bundle

With H3, H4 and the shift/mlProj closure in hand, the composition is
direct. -/

/-- **H5.B (main discharge theorem).**

Given H3 (`CookLevinFactorMemPerType`), H4 (`DerivClosurePerType`),
and the shift/mlProj closure hypothesis on `W`, the
`CookLevinPerTypeSpanning` bundle of Agent G4 holds unconditionally.

Proof. We unfold the definition of `CookLevinPerTypeSpanning` and
reduce every generator of `cookLevinPostSpanAt bp.toHistogram` to the
shift/mlProj closure form. Specifically, for the generator triple
`(S, shift, g)` with `g ∈ boundedProfileClassifiedSet (factors)
(constraintType) S bp.toHistogram`, the existential in `hg` exhibits
`g = ∏_i iterDerivList (d i) (factors i)`. By H5.A (via H4), each
`iterDerivList (d i) (factors i)` lies in `W (constraintType i)`.
Feeding this into the `PerTypeShiftMlprojClosure` hypothesis closes
the goal. -/
theorem cookLevinPerTypeSpanning_discharged
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (W : ConstraintType → Submodule ℚ (MvPolynomial (Fin n) ℚ))
    (hFactor : CookLevinFactorMemPerType M n hn htb hns W)
    (hClosure : DerivClosurePerType (n := n) W)
    (hShiftMlproj : PerTypeShiftMlprojClosure (n := n) W) :
    CookLevinPerTypeSpanning M n hn htb hns W := by
  classical
  intro bp S hSlen shift hshiftvars g hg
  -- Unfold `boundedProfileClassifiedSet`:
  --   `hg : ∃ d, (∀ i ∀ v ∈ d i, v ∈ S) ∧
  --             g = ∏ i, iterDerivList (d i) (factors i) ∧
  --             derivCountProfile constraintType d = bp.toHistogram ∧
  --             ∑ i, (d i).length ≤ S.length`.
  obtain ⟨d, hd_elts, hg_prod, hprof, hsum⟩ := hg
  -- Build the `hg_prod` witness consumed by `PerTypeShiftMlprojClosure`:
  -- we need each `iterDerivList (d i) (factors i) ∈ W (constraintType i)`.
  -- We obtain this from H5.A (`iterDerivList_factor_mem_W`) using
  -- `cookLevinConstraintType` as the concrete constraint-type map.
  have hEachMem :
      ∀ i : Fin (cookLevinFactorList M n hn htb hns).length,
        iterDerivList (d i)
            ((fun j => (cookLevinFactorList M n hn htb hns).get j) i)
          ∈ W (cookLevinConstraintType M n hn htb hns i) := by
    intro i
    -- `d i` is a bounded list (its length ≤ S.length ≤ Nat.log 2 n).
    have hdi_le : (d i).length ≤ Nat.log 2 n := by
      have : (d i).length ≤ S.length := by
        -- each component sum ≤ total, and total ≤ S.length.
        refine le_trans ?_ hsum
        refine Finset.single_le_sum (f := fun j => (d j).length) ?_
          (Finset.mem_univ i)
        intro j _
        exact Nat.zero_le _
      exact le_trans this hSlen
    -- Apply H5.A in `W τ` form.
    exact iterDerivList_factor_mem_W
      M n hn htb hns W hFactor hClosure i
      (cookLevinConstraintType M n hn htb hns i) rfl (d i) hdi_le
  -- Feed the assembled witness into `PerTypeShiftMlprojClosure`.
  have hClosureApp := hShiftMlproj bp S hSlen shift hshiftvars g
    ⟨(cookLevinFactorList M n hn htb hns).length,
     (fun j => (cookLevinFactorList M n hn htb hns).get j),
     cookLevinConstraintType M n hn htb hns, d,
     hd_elts, hEachMem, hg_prod, hprof, hsum⟩
  exact hClosureApp

/-! ## 7. Full composition with Agent G4 ⇒ Agent B's bridge

Combining H5.B (= discharged `CookLevinPerTypeSpanning`) with Agent
G4's composition pipeline (already in `Spanning/Composition.lean`)
produces the full aggregated containment
`cookLevinPostSpanAt bp.toHistogram ≤ cookLevinProfileSubspace bp W`
for every bounded profile `bp`, which is exactly the premise consumed
by Agent B's bridge lemmas.

This is the full H5 pipeline "H3/H4 ⇒ Route C ⇒ Route A" at the
truncated per-factor level. -/

/-- **Full per-profile discharged containment from H3 + H4.**

Composes `cookLevinPerTypeSpanning_discharged` (H5.B) with
`cookLevinProfileSubspace_contains_postSpan_discharged` (Agent G4)
to produce the final aggregated containment. -/
theorem cookLevinProfileSubspace_contains_postSpan_from_H3_H4
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (W : ConstraintType → Submodule ℚ (MvPolynomial (Fin n) ℚ))
    (hFactor : CookLevinFactorMemPerType M n hn htb hns W)
    (hClosure : DerivClosurePerType (n := n) W)
    (hShiftMlproj : PerTypeShiftMlprojClosure (n := n) W) :
    ∀ bp : BoundedProfile (Nat.log 2 n),
      cookLevinPostSpanAt M n hn htb hns bp.toHistogram
        ≤ cookLevinProfileSubspace bp W :=
  cookLevinProfileSubspace_contains_postSpan_discharged
    M n hn htb hns W
    (cookLevinPerTypeSpanning_discharged
      M n hn htb hns W hFactor hClosure hShiftMlproj)

/-! ## 8. End-to-end template-collapse bridge from H3 + H4 (+ dim data)

For caller convenience, we also expose the full end-to-end chain
from H3 + H4 + dim ≤ 3 data directly to Agent B's template-collapse
lemma. This is the single-call entry point for downstream agents. -/

/-- **End-to-end template-collapse from H3 + H4 + dim ≤ 3.**

Given H3, H4, the shift/mlProj closure, and the per-type
finite-dimensionality / dim ≤ 3 hypotheses on `W`, produces Agent B's
`CookLevinProfileTemplateCollapseLemmaBoundedProfile`. -/
theorem cookLevinProfileTemplateCollapseLemmaBoundedProfile_from_H3_H4
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (W : ConstraintType → Submodule ℚ (MvPolynomial (Fin n) ℚ))
    (hW_fin : ∀ τ, Module.Finite ℚ ↥(W τ))
    (hW_dim : ∀ τ, Module.finrank ℚ ↥(W τ) ≤ 3)
    (hFactor : CookLevinFactorMemPerType M n hn htb hns W)
    (hClosure : DerivClosurePerType (n := n) W)
    (hShiftMlproj : PerTypeShiftMlprojClosure (n := n) W) :
    CookLevinProfileTemplateCollapseLemmaBoundedProfile M n hn htb hns :=
  cookLevinProfileTemplateCollapseLemmaBoundedProfile_from_perTypeSpanning
    M n hn htb hns W hW_fin hW_dim
    (cookLevinPerTypeSpanning_discharged
      M n hn htb hns W hFactor hClosure hShiftMlproj)

#print axioms iterDerivList_mem_iterDerivSubmodule_forH5
#print axioms iterDerivList_factor_mem_derivAmbient
#print axioms iterDerivList_factor_mem_W
#print axioms cookLevinPerTypeSpanning_discharged
#print axioms cookLevinProfileSubspace_contains_postSpan_from_H3_H4
#print axioms cookLevinProfileTemplateCollapseLemmaBoundedProfile_from_H3_H4

end PallLean.Paper93.Spanning
