import PallLean.Paper93.DeepMath.PathB.ComputationalDepthBlackHoleMERATraceDynamics

/-!
# Black-hole MERA admissibility audit: the oracle-loading obstruction

`ComputationalDepthBlackHoleMERATraceDynamics` isolated the two laws that would turn a dynamical
horizon into an exponential decision-time lower bound:

1. SAT semantics forces linear horizon precision;
2. reconstruction charge cannot be bypassed by the forward decision dynamics.

This file attempts to derive those laws from the current concrete ingredients: exact Boolean
semantics, deterministic finite-boundary MERA evolution, and locally reversible/isometric time steps.
The attempt exposes a decisive missing condition.

The trace interface does not charge the input encoder.  Therefore, for *every* Boolean target, the
encoder may compute the target first, load that one answer bit into the boundary, and let the MERA
dynamics perform the identity map for one step.  The resulting trajectory is exact, deterministic,
two-state, one-step, and isometric.  It also has a valid zero-precision horizon.  No property of the
subsequent MERA dynamics can distinguish this trace from a genuinely easy computation.

Theorems below machine-check the consequences.

* `oracleLoadedTrace` gives this cheap isometric trace for an arbitrary target.
* `oracleLoadedZeroHorizon` gives it a finite zero-precision horizon satisfying no-shortcut.
* Any admissibility law forcing linear precision must reject this trace.
* Hence an input-loading/compiler condition is logically prior to the black-hole laws.  It must prove
  that boundary preparation itself is generated by uniform local computation rather than an oracle
  call to the target.
* Regulated divergence also does not imply no-shortcut: an arbitrarily expensive horizon can be
  attached to a one-step easy trajectory while the forward computation ignores it.

This is a genuine obstruction, not a claim that the dynamical route is impossible.  It sharpens the
next construction target to an operational, charged, uniform input-to-MERA compiler.  Nothing here
proves or assumes `P ≠ NP`.
-/

namespace PallLean.Paper93.DeepMath.PathB.BlackHoleMERAAdmissibilityAudit

open PallLean.Paper93.DeepMath.PathB.PvsNPNFrameRestrictedMERADecoder
open PallLean.Paper93.DeepMath.PathB.PvsNPNFrameRestrictedMERADecoder.BoundedBondLocalMERADecoderFamily
open PallLean.Paper93.DeepMath.PathB.BlackHoleMERATraceDynamics

/-! ## Local/isometric evolution is not enough -/

/-- Every time step of a trace is reversible on its boundary state.  For finite state spaces this is
the discrete injective/isometric condition needed by the audit. -/
def HasIsometricEvolution {M : MERAFamily} {n : Nat}
    {Input : Type*} {target : Input → Bool}
    (T : MERADecisionTrace M n Input target) : Prop :=
  ∀ time, Function.Injective (T.step time)

/-- A fixed two-state bounded-bond MERA family.  At every `n ≥ 2` its causal-cone rank can hold one
Boolean answer bit. -/
def answerBitMERA : MERAFamily :=
  profileSaturatedFamily 2 1 (by omega)

/-- **Oracle-loading trace.**  For an arbitrary target, the uncharged encoder loads `target input`
directly into a single boundary bit.  The subsequent MERA evolution is the identity for one step.

The construction is intentionally adversarial: it identifies the exact place where target complexity
can be hidden when boundary preparation is not operationally constrained. -/
def oracleLoadedTrace {Input : Type*} (target : Input → Bool)
    (n : Nat) (hn : 2 ≤ n) :
    MERADecisionTrace answerBitMERA n Input target where
  BoundaryState := Bool
  encode := target
  step := fun _ state => state
  decode := id
  decisionTime := 1
  correct := fun _ => rfl
  boundary_card_le := by
    change 2 ≤ 2 ^ (1 * Nat.log 2 n)
    have hlog : 1 ≤ Nat.log 2 n := by
      rw [Nat.le_log_iff_pow_le (by omega) (by omega)]
      simpa using hn
    exact le_trans (by norm_num : 2 ≤ 2 ^ 1)
      (Nat.pow_le_pow_right (by omega) (by simpa using hlog))

@[simp] theorem oracleLoadedTrace_time {Input : Type*} (target : Input → Bool)
    (n : Nat) (hn : 2 ≤ n) :
    (oracleLoadedTrace target n hn).decisionTime = 1 := rfl

/-- The oracle-loaded trace is locally reversible/isometric: every dynamic update is the identity. -/
theorem oracleLoadedTrace_isometric {Input : Type*} (target : Input → Bool)
    (n : Nat) (hn : 2 ≤ n) :
    HasIsometricEvolution (oracleLoadedTrace target n hn) := by
  intro _ _ _ h
  exact h

/-! ## A zero-precision horizon survives every target -/

/-- A valid finite zero-precision horizon on the oracle-loaded trace. -/
def oracleLoadedZeroHorizon {Input : Type*} (target : Input → Bool)
    (n : Nat) (hn : 2 ≤ n) :
    DynamicalHorizon (oracleLoadedTrace target n hn) where
  formationTime := 0
  formation_le_decision := by simp [oracleLoadedTrace]
  precisionBits := 0
  reconstructionCost := 1
  regulatedDivergence := by norm_num

@[simp] theorem oracleLoadedZeroHorizon_precision {Input : Type*} (target : Input → Bool)
    (n : Nat) (hn : 2 ≤ n) :
    (oracleLoadedZeroHorizon target n hn).precisionBits = 0 := rfl

/-- The cheap horizon also satisfies no-shortcut: its unit charge fits inside the one-step decision. -/
theorem oracleLoadedZeroHorizon_noShortcut {Input : Type*} (target : Input → Bool)
    (n : Nat) (hn : 2 ≤ n) :
    NoHorizonShortcut (oracleLoadedZeroHorizon target n hn) := by
  simp [NoHorizonShortcut, oracleLoadedZeroHorizon, oracleLoadedTrace]

/-- At every nontrivial input length, the oracle-loaded exact isometric trace refutes linear horizon
precision for *any* target. -/
theorem oracleLoadedTrace_refutes_linearPrecision
    {Input : Type*} (target : Input → Bool) (n : Nat) (hn : 2 ≤ n) :
    ¬ LinearHorizonPrecision (oracleLoadedZeroHorizon target n hn) := by
  simp [LinearHorizonPrecision, oracleLoadedZeroHorizon]
  omega

/-! ## What any successful admissibility law must do -/

/-- Any target-specific admissibility predicate whose forcing law is strong enough for the exponential
chain must reject the oracle-loaded trace.  Thus the missing content is not inside the horizon
arithmetic: it is an operational restriction on boundary preparation. -/
theorem forcingLaw_rejects_oracleLoadedTrace
    {Input : Type*} (target : Input → Bool) (n : Nat) (hn : 2 ≤ n)
    (Admissible : HorizonAdmissibility answerBitMERA n Input target)
    (hforce : ∀ T H, Admissible T H → LinearHorizonPrecision H) :
    ¬ Admissible (oracleLoadedTrace target n hn) (oracleLoadedZeroHorizon target n hn) := by
  intro hadmit
  exact oracleLoadedTrace_refutes_linearPrecision target n hn
    (hforce (oracleLoadedTrace target n hn)
      (oracleLoadedZeroHorizon target n hn) hadmit)

/-- In particular, no admissibility condition that accepts every exact trace with isometric evolution
can force linear horizon precision. -/
theorem exact_isometric_admissibility_cannot_force_precision
    {Input : Type*} (target : Input → Bool) (n : Nat) (hn : 2 ≤ n)
    (Admissible : HorizonAdmissibility answerBitMERA n Input target)
    (haccept : ∀ (T : MERADecisionTrace answerBitMERA n Input target) (H : DynamicalHorizon T),
      HasIsometricEvolution T → Admissible T H) :
    ¬ (∀ T H, Admissible T H → LinearHorizonPrecision H) := by
  intro hforce
  have hadmit := haccept (oracleLoadedTrace target n hn)
    (oracleLoadedZeroHorizon target n hn)
    (oracleLoadedTrace_isometric target n hn)
  exact oracleLoadedTrace_refutes_linearPrecision target n hn
    (hforce (oracleLoadedTrace target n hn)
      (oracleLoadedZeroHorizon target n hn) hadmit)

/-! ## Regulated divergence does not derive no-shortcut -/

/-- Attach an `n`-bit, cost-`2^n` regulated horizon to the one-step constant-false trace.  This horizon
is finite and satisfies the divergence law, but the forward computation simply ignores it. -/
def expensiveIgnoredHorizon (n : Nat) : DynamicalHorizon (easyFalseTrace n) where
  formationTime := 0
  formation_le_decision := by simp [easyFalseTrace]
  precisionBits := n
  reconstructionCost := 2 ^ n
  regulatedDivergence := le_rfl

@[simp] theorem expensiveIgnoredHorizon_cost (n : Nat) :
    (expensiveIgnoredHorizon n).reconstructionCost = 2 ^ n := rfl

/-- **No-shortcut is independent.**  At positive lengths the expensive horizon's charge exceeds the
one-step decision time.  Local deterministic dynamics plus regulated divergence therefore do not imply
that forward decision must pay reconstruction cost. -/
theorem regulatedDivergence_does_not_imply_noShortcut
    {n : Nat} (hn : 1 ≤ n) :
    ¬ NoHorizonShortcut (expensiveIgnoredHorizon n) := by
  simp [NoHorizonShortcut, expensiveIgnoredHorizon, easyFalseTrace]
  have : 1 < 2 ^ n := (Nat.one_lt_pow_iff (by omega)).mpr (by omega)
  omega

/-! ## The next concrete compiler socket -/

/-- The operational property now known to be necessary: a trace's initial boundary state must be
prepared without evaluating the target as an oracle.

This is deliberately an interface, not a fake definition of polynomial computation.  A future
construction must instantiate it with a uniform local gate/tensor compiler and charge both preparation
and evolution. -/
def HonestInputPreparation {M : MERAFamily} {n : Nat}
    {Input : Type*} {target : Input → Bool}
    (T : MERADecisionTrace M n Input target) : Prop :=
  ∃ PreparationCode : Type,
    ∃ prepare : PreparationCode → Input → T.BoundaryState,
      T.encode ∈ Set.range prepare

/-- A full black-hole route must add a nontrivial, complexity-bounded refinement of
`HonestInputPreparation` that excludes oracle loading.  Merely requiring the existence of arbitrary
code is vacuous: every encoder is represented by a singleton code. -/
theorem weak_honestInputPreparation_is_vacuous
    {M : MERAFamily} {n : Nat} {Input : Type*} {target : Input → Bool}
    (T : MERADecisionTrace M n Input target) :
    HonestInputPreparation T := by
  refine ⟨Unit, fun _ => T.encode, ?_⟩
  exact ⟨(), rfl⟩

/-!
## Honest endpoint

The requested SAT laws cannot be derived from the current local/isometric MERA trace axioms.  The
machine-checked oracle-loading trace is an exact countermodel for every target, and regulated horizon
cost is independent of forward decision time.

The next viable build must therefore replace the arbitrary `encode` and `step` functions with a
uniform finite gate/tensor language, charge the input preparation circuit, forbid target-oracle gates,
and prove semantics-preserving compilation.  Only after that operational compiler exists can horizon
formation be a derived property rather than an admissibility declaration.
-/

end PallLean.Paper93.DeepMath.PathB.BlackHoleMERAAdmissibilityAudit

#print axioms PallLean.Paper93.DeepMath.PathB.BlackHoleMERAAdmissibilityAudit.oracleLoadedTrace_isometric
#print axioms PallLean.Paper93.DeepMath.PathB.BlackHoleMERAAdmissibilityAudit.oracleLoadedTrace_refutes_linearPrecision
#print axioms PallLean.Paper93.DeepMath.PathB.BlackHoleMERAAdmissibilityAudit.forcingLaw_rejects_oracleLoadedTrace
#print axioms PallLean.Paper93.DeepMath.PathB.BlackHoleMERAAdmissibilityAudit.exact_isometric_admissibility_cannot_force_precision
#print axioms PallLean.Paper93.DeepMath.PathB.BlackHoleMERAAdmissibilityAudit.regulatedDivergence_does_not_imply_noShortcut
#print axioms PallLean.Paper93.DeepMath.PathB.BlackHoleMERAAdmissibilityAudit.weak_honestInputPreparation_is_vacuous
