import PallLean.Paper93.DeepMath.PathB.ComputationalDepthACC0RankCellCollapse

/-!
# Bounded support footprint ⇒ low observer rank

A structured-`MOD` rank-shrink fragment based on the **support footprint** — the set of coordinates touched by *some*
gate, `footprint = ⋃_j supports j`.  A coordinate outside the footprint lies in no support, so its cell pattern is the
zero vector; only footprint coordinates carry information.  Hence the observer rank is bounded by the footprint size,
**independent of the gate count**:

```
cellRank supports L ≤ |footprint supports|,        2^{|footprint|} < |L|  ⇒  low holonomy correlation.
```

This is the honest "intersection / support dimension" rank bound: a `MOD` layer that collectively reads only `t` input
coordinates (however many gates) has observer rank `≤ t`.  (Note: a mere *pairwise* intersection bound does **not**
bound the rank — disjoint supports have small pairwise intersections yet full rank — so the genuine bound is the total
footprint.)

## What is proved (clean axioms, no `sorry`)

* `footprint` — the union of all supports; **`cellPatternVec_eq_zero_of_not_mem_footprint`** (off-footprint patterns
  vanish).
* **`cellRank_le_footprint`** — `cellRank supports L ≤ |footprint supports|`.
* **`footprint_rank_cell_collapse`** / **`footprint_low_correlation`** — `2^{|footprint|} < |L| ⇒ RankCellCollapse ⇒`
  low holonomy correlation.

## Honest scope

A genuine rank-shrink fragment distinct from the block/clustered/support-span family: it shrinks the rank to the
*coordinate footprint*.  It does **not** force low rank for wide overlapping `MOD` whose footprint is large under any
restriction — that is the open rank-shrink wall (the rank analogue of the `MOD` no-absorbing-value wall).  Nothing here
is `NEXP ⊄ ACC⁰` or `P ≠ NP`.  See `ACC_ROADMAP.md`, `ACC_THEOREM_MAP.md`, `WHAT_IS_PROVED.md`.
-/

namespace PallLean.Paper93.DeepMath.PathB.ACC0FootprintRank

open scoped Classical
open Finset
open PallLean.Paper93.DeepMath.PathB.ACC0CellCollapseRoute
open PallLean.Paper93.DeepMath.PathB.ACC0RankBridge
open PallLean.Paper93.DeepMath.PathB.ACC0RankCellCollapse

variable {k n : ℕ}

/-- The **support footprint**: the coordinates touched by some gate, `⋃_j supports j`. -/
def footprint (supports : Fin k → Finset (Fin n)) : Finset (Fin n) :=
  Finset.univ.biUnion supports

/-- **Off-footprint coordinates have the zero cell pattern (proved).** -/
theorem cellPatternVec_eq_zero_of_not_mem_footprint (supports : Fin k → Finset (Fin n)) (i : Fin n)
    (hi : i ∉ footprint supports) : cellPatternVec supports i = 0 := by
  funext j
  have hij : i ∉ supports j := fun hmem =>
    hi (Finset.mem_biUnion.mpr ⟨j, Finset.mem_univ j, hmem⟩)
  simp only [cellPatternVec, Pi.zero_apply, if_neg hij]

/-- **Bounded footprint ⇒ bounded observer rank (proved): `cellRank ≤ |footprint|`.**  Off-footprint coordinates
contribute the zero pattern, so the cell span is generated by the `≤ |footprint|` footprint patterns. -/
theorem cellRank_le_footprint (supports : Fin k → Finset (Fin n)) (L : Finset (Fin n)) :
    cellRank supports L ≤ (footprint supports).card := by
  have hle : cellSpan supports L ≤ Submodule.span (ZMod 2)
      (↑((footprint supports).image (cellPatternVec supports)) : Set (Fin k → ZMod 2)) := by
    rw [cellSpan, Submodule.span_le]
    intro p hp
    rw [Finset.mem_coe, Finset.mem_image] at hp
    obtain ⟨v, _, rfl⟩ := hp
    by_cases hvf : v ∈ footprint supports
    · exact Submodule.subset_span
        (by rw [Finset.mem_coe, Finset.mem_image]; exact ⟨v, hvf, rfl⟩)
    · rw [cellPatternVec_eq_zero_of_not_mem_footprint supports v hvf]
      exact Submodule.zero_mem _
  calc cellRank supports L = Module.finrank (ZMod 2) (cellSpan supports L) := rfl
    _ ≤ Module.finrank (ZMod 2) (Submodule.span (ZMod 2)
          (↑((footprint supports).image (cellPatternVec supports)) : Set (Fin k → ZMod 2))) :=
        Submodule.finrank_mono hle
    _ ≤ ((footprint supports).image (cellPatternVec supports)).card :=
        finrank_span_finset_le_card _
    _ ≤ (footprint supports).card := Finset.card_image_le

/-- **Bounded-footprint rank-cell collapse (proved): `2^{|footprint|} < |L| ⇒ RankCellCollapse`.** -/
theorem footprint_rank_cell_collapse (supports : Fin k → Finset (Fin n)) (L : Finset (Fin n))
    (hf : 2 ^ (footprint supports).card < L.card) : RankCellCollapse supports L :=
  lt_of_le_of_lt
    (Nat.pow_le_pow_right (by norm_num) (cellRank_le_footprint supports L)) hf

/-- **Bounded-footprint `MOD` layers fail to correlate when `2^{|footprint|} < |L|` (proved).**  A layer reading only
`|footprint|` coordinates cannot track the holonomy parity on a larger live set, regardless of gate count. -/
theorem footprint_low_correlation (supports : Fin k → Finset (Fin n)) (g : (Fin k → ℕ) → Bool)
    (L : Finset (Fin n)) (hf : 2 ^ (footprint supports).card < L.card) :
    LowHolonomyCorrelation supports g :=
  rank_cell_collapse_implies_low_holonomy_correlation supports g L
    (footprint_rank_cell_collapse supports L hf)

end PallLean.Paper93.DeepMath.PathB.ACC0FootprintRank

#print axioms PallLean.Paper93.DeepMath.PathB.ACC0FootprintRank.cellPatternVec_eq_zero_of_not_mem_footprint
#print axioms PallLean.Paper93.DeepMath.PathB.ACC0FootprintRank.cellRank_le_footprint
#print axioms PallLean.Paper93.DeepMath.PathB.ACC0FootprintRank.footprint_low_correlation
