import PallLean.Paper93.DeepMath.PathB.ComputationalDepthMachineSemantics

/-
# Hypercomputational boundary term

This file formalizes the strongest honest use of the book's
hypercomputational N-Frame term `L_H(H(φ_obs))`.

The term can be used to define a stronger observer class: a boundary oracle
that returns satisfying witnesses when they exist.  In that extended model SAT
search is shallow.  This is the precise sense in which a hypercomputational
observer can "see" NP.

The same construction does **not** prove classical `P = NP` or `P ≠ NP`,
because the oracle-free machine model has changed.  To get a classical closure
one would need a compiler from the hypercomputational term back into an
ordinary polynomial-budget search machine.  The final section isolates exactly
that bridge and proves that, under `DeepSATSearch`, such a compiler cannot
exist.
-/

namespace SATDepthMachine

/-! ## Hypercomputational SAT boundary term -/

/-- A hypercomputational boundary term for SAT search.

This is the Lean version of using `L_H(H(φ_obs))` as a non-Turing channel:
`boundaryOracle φ` is allowed to return a satisfying assignment without being
generated by an oracle-free polynomial machine.

The two correctness fields say it is exactly a SAT-witness oracle:

* soundness: returned witnesses really satisfy the formula;
* completeness: every satisfiable formula receives some returned witness.
-/
structure HypercomputationalSATBoundaryTerm where
  boundaryOracle : CNF -> Option RawAssignment
  sound :
    ∀ φ a, boundaryOracle φ = some a -> Satisfies φ a
  complete :
    ∀ φ, Satisfiable φ ->
      ∃ a : RawAssignment, boundaryOracle φ = some a ∧ Satisfies φ a

/-- The machine surface induced by a hypercomputational SAT boundary term.

Every coded search program has access to the same boundary oracle.  The step
count is intentionally constant: the computational work has been moved into the
non-Turing `L_H` channel. -/
def hyperBoundaryMachineModel
    (H : HypercomputationalSATBoundaryTerm) : MachineModel where
  searchRun := fun _code φ => H.boundaryOracle φ
  searchSteps := fun _code _φ => 1
  decisionRun := fun _code φ => checkSearchOutput φ (H.boundaryOracle φ)
  decisionSteps := fun _code _φ => 1
  verifierCode := fun code => code
  verifier_run := by
    intro code φ
    rfl
  verifier_steps := by
    intro code φ
    rfl

/-- A constant-budget search machine in the hyper-boundary model. -/
def hyperBoundarySearchMachine
    (H : HypercomputationalSATBoundaryTerm) :
    SearchMachine (hyperBoundaryMachineModel H) where
  code := 0
  budget := fun _n => 1
  polyBudget := by
    refine ⟨0, 1, ?_⟩
    intro n
    simp
  steps_le_budget := by
    intro φ
    exact Nat.le_refl ((hyperBoundaryMachineModel H).searchSteps 0 φ)

/-- The hyper-boundary search machine is correct for SAT search. -/
theorem hyperBoundarySearchCorrect
    (H : HypercomputationalSATBoundaryTerm) :
    SearchCorrect (hyperBoundaryMachineModel H)
      (hyperBoundarySearchMachine H) := by
  intro φ hsat
  exact H.complete φ hsat

/-- A hypercomputational boundary term makes SAT search shallow in its own
extended observer model. -/
theorem hyperBoundaryShallowSATSearch
    (H : HypercomputationalSATBoundaryTerm) :
    ShallowSATSearch (hyperBoundaryMachineModel H) :=
  ⟨hyperBoundarySearchMachine H, hyperBoundarySearchCorrect H⟩

/-- A constant-budget decision machine in the hyper-boundary model. -/
def hyperBoundaryDecisionMachine
    (H : HypercomputationalSATBoundaryTerm) :
    DecisionMachine (hyperBoundaryMachineModel H) where
  code := 0
  budget := fun _n => 1
  polyBudget := by
    refine ⟨0, 1, ?_⟩
    intro n
    simp
  steps_le_budget := by
    intro φ
    exact Nat.le_refl ((hyperBoundaryMachineModel H).decisionSteps 0 φ)

/-- The hyper-boundary decision machine decides SAT in the extended observer
model. -/
theorem hyperBoundaryDecidesSAT
    (H : HypercomputationalSATBoundaryTerm) :
    DecidesSAT (hyperBoundaryMachineModel H)
      (hyperBoundaryDecisionMachine H) := by
  intro φ
  change checkSearchOutput φ (H.boundaryOracle φ) = true ↔ Satisfiable φ
  rw [checkSearchOutput_true_iff]
  constructor
  · intro h
    rcases h with ⟨a, horacle, hsat⟩
    exact ⟨a, hsat⟩
  · intro hsat
    exact H.complete φ hsat

/-- A hypercomputational boundary term also puts SAT decision in polynomial
time for the extended observer model. -/
theorem hyperBoundarySATDecisionInP
    (H : HypercomputationalSATBoundaryTerm) :
    SATDecisionInP (hyperBoundaryMachineModel H) :=
  ⟨hyperBoundaryDecisionMachine H, hyperBoundaryDecidesSAT H⟩

/-! ## Why this is not classical closure -/

/-- A classical compilation bridge from a hypercomputational boundary term back
into an oracle-free machine model.

This is the missing bridge one would need to turn "the hyper-observer sees NP"
into a claim about the ordinary Turing/polynomial observer surface.  It is kept
as data because the boundary oracle is precisely the non-Turing ingredient. -/
structure HyperBoundaryToClassicalCompiler
    (H : HypercomputationalSATBoundaryTerm)
    (U : MachineModel) where
  compiled : SearchMachine U
  preserves_correctness :
    SearchCorrect (hyperBoundaryMachineModel H)
      (hyperBoundarySearchMachine H) ->
        SearchCorrect U compiled

/-- If the hypercomputational boundary term can be compiled into an ordinary
polynomial search machine, then ordinary SAT search is shallow. -/
theorem shallowSATSearch_of_hyperBoundaryCompiler
    (H : HypercomputationalSATBoundaryTerm)
    (U : MachineModel)
    (K : HyperBoundaryToClassicalCompiler H U) :
    ShallowSATSearch U :=
  ⟨K.compiled, K.preserves_correctness (hyperBoundarySearchCorrect H)⟩

/-- Under deep classical SAT search, no such oracle-free compilation bridge can
exist. -/
theorem no_hyperBoundaryCompiler_of_deepSATSearch
    (H : HypercomputationalSATBoundaryTerm)
    (U : MachineModel)
    (hdeep : DeepSATSearch U) :
    ¬ Nonempty (HyperBoundaryToClassicalCompiler H U) := by
  intro hK
  rcases hK with ⟨K⟩
  exact hdeep (shallowSATSearch_of_hyperBoundaryCompiler H U K)

/-- A hypercomputational observer seeing SAT and an oracle-free observer being
deep are compatible statements because they concern different machine models. -/
theorem hyperBoundarySeesSAT_with_classicalDeep
    (H : HypercomputationalSATBoundaryTerm)
    (U : MachineModel)
    (hdeep : DeepSATSearch U) :
    ShallowSATSearch (hyperBoundaryMachineModel H) ∧ DeepSATSearch U :=
  ⟨hyperBoundaryShallowSATSearch H, hdeep⟩

/-! ## Axiom trace -/

#print axioms hyperBoundarySearchCorrect
#print axioms hyperBoundaryShallowSATSearch
#print axioms hyperBoundaryDecidesSAT
#print axioms hyperBoundarySATDecisionInP
#print axioms shallowSATSearch_of_hyperBoundaryCompiler
#print axioms no_hyperBoundaryCompiler_of_deepSATSearch
#print axioms hyperBoundarySeesSAT_with_classicalDeep

end SATDepthMachine
