import PallLean.Paper93.DeepMath.PathB.ComputationalDepthNonLocalActionHolonomyConservation

/-!
# Noncommutative action holonomy audit: the expander residual is abelian

Non-local action words have the right multiplicative capacity, but the natural
expander residual needs only linearly many binary slots.  The next possible
invariant is therefore the interaction structure among those actions: perhaps
SAT forces noncommuting relations even when raw word length stays polynomial.

This file tests that idea on the exact residual family already used by Route G.
Each residual coordinate is generated by a Boolean toggle.  The toggles are
involutions and commute pairwise; whole action words commute as well.  Yet their
orbit from the zero boundary is exactly the full Boolean cube, and expansion
makes every one of those `2^r` points occur as a genuine Tseitin residual.

Thus neither the number of outcomes nor pairwise commutator holonomy supplies a
lower bound here.  The full residual action is the elementary abelian group
`(Z/2Z)^r`, with a polynomial description and `2^r` elements.  Any successful
relation invariant must use richer continuation semantics than coordinate
translations and must distinguish SAT from easy Boolean cubes.
-/

namespace PallLean.Paper93.DeepMath.PathB.NoncommutativeActionHolonomyAudit

open SATDepthMachine
open ExpanderSATQueryContinuation
open NonLocalActionHolonomyConservation

abbrev Assignment (r : ℕ) := Fin r → Bool
abbrev BinaryWord (r : ℕ) := Fin r → Fin 2

/-- The all-zero observer boundary. -/
def zeroAssignment (r : ℕ) : Assignment r := fun _ ↦ false

/-- One local binary action: letter `1` toggles coordinate `i`; letter `0`
acts identically. -/
def coordinateAction {r : ℕ} (i : Fin r) (letter : Fin 2)
    (state : Assignment r) : Assignment r :=
  fun j ↦ if finTwoEquiv letter then
    if j = i then !state j else state j
  else state j

/-- Local coordinate actions are involutions. -/
theorem coordinateAction_involutive {r : ℕ} (i : Fin r) (letter : Fin 2)
    (state : Assignment r) :
    coordinateAction i letter (coordinateAction i letter state) = state := by
  funext j
  cases hletter : finTwoEquiv letter <;>
    by_cases hji : j = i <;>
      simp [coordinateAction, hletter, hji]

/-- **All local coordinate actions commute**, including repeated coordinates
and either binary letter. -/
theorem coordinateAction_commute {r : ℕ}
    (i j : Fin r) (a b : Fin 2) (state : Assignment r) :
    coordinateAction i a (coordinateAction j b state) =
      coordinateAction j b (coordinateAction i a state) := by
  by_cases hij : i = j
  · subst j
    funext k
    cases ha : finTwoEquiv a <;>
      cases hb : finTwoEquiv b <;>
        by_cases hki : k = i <;>
          simp [coordinateAction, ha, hb, hki]
  · funext k
    cases ha : finTwoEquiv a <;>
      cases hb : finTwoEquiv b <;>
        by_cases hki : k = i <;>
          by_cases hkj : k = j <;>
            simp_all [coordinateAction]

/-- Simultaneous product of all enabled coordinate toggles in one binary word.
Because the local actions commute, order is immaterial. -/
def coordinateWordAction {r : ℕ} (word : BinaryWord r)
    (state : Assignment r) : Assignment r :=
  fun i ↦ if finTwoEquiv (word i) then !state i else state i

/-- Whole non-local action words commute under composition. -/
theorem coordinateWordAction_commute {r : ℕ}
    (u v : BinaryWord r) (state : Assignment r) :
    coordinateWordAction u (coordinateWordAction v state) =
      coordinateWordAction v (coordinateWordAction u state) := by
  funext i
  cases hu : finTwoEquiv (u i) <;>
    cases hv : finTwoEquiv (v i) <;>
      simp [coordinateWordAction, hu, hv]

/-- Every word action is itself an involution. -/
theorem coordinateWordAction_involutive {r : ℕ}
    (word : BinaryWord r) (state : Assignment r) :
    coordinateWordAction word (coordinateWordAction word state) = state := by
  funext i
  cases h : finTwoEquiv (word i) <;>
    simp [coordinateWordAction, h]

/-- Pointwise `Fin 2 ≃ Bool`: binary action words are exactly Boolean
boundary vectors. -/
def binaryWordEquivAssignment (r : ℕ) : BinaryWord r ≃ Assignment r where
  toFun := fun word i ↦ finTwoEquiv (word i)
  invFun := fun state i ↦ finTwoEquiv.symm (state i)
  left_inv := by
    intro word
    funext i
    simp
  right_inv := by
    intro state
    funext i
    simp

/-- Acting on the zero boundary returns exactly the Boolean vector encoded by
the word. -/
theorem coordinateWordAction_zero {r : ℕ} (word : BinaryWord r) :
    coordinateWordAction word (zeroAssignment r) =
      binaryWordEquivAssignment r word := by
  funext i
  cases h : finTwoEquiv (word i) <;>
    simp [coordinateWordAction, zeroAssignment,
      binaryWordEquivAssignment, h]

/-- Consequently the commuting orbit from zero contains all `2^r` Boolean
boundaries. -/
theorem coordinateWordOrbit_surjective (r : ℕ) :
    Function.Surjective
      (fun word : BinaryWord r ↦ coordinateWordAction word (zeroAssignment r)) := by
  intro state
  refine ⟨(binaryWordEquivAssignment r).symm state, ?_⟩
  change coordinateWordAction ((binaryWordEquivAssignment r).symm state)
    (zeroAssignment r) = state
  rw [coordinateWordAction_zero]
  simp

/-- Number of states in the commuting orbit is exactly `2^r`. -/
theorem coordinateWordOrbit_rank_eq_two_pow (r : ℕ) :
    BranchSpanningDynamicHolonomy.familyImageRank
      (fun word : BinaryWord r ↦ coordinateWordAction word (zeroAssignment r)) =
      2 ^ r := by
  rw [familyImageRank_eq_card_of_surjective _
    (coordinateWordOrbit_surjective r)]
  simp only [Fintype.card_fun, Fintype.card_fin, Fintype.card_bool]

/-- Pairwise commutator holonomy for the coordinate-word action family. -/
def HasNoncommutingWordPair (r : ℕ) : Prop :=
  ∃ u v : BinaryWord r, ∃ state : Assignment r,
    coordinateWordAction u (coordinateWordAction v state) ≠
      coordinateWordAction v (coordinateWordAction u state)

/-- The commutator invariant is identically zero for the full coordinate cube. -/
theorem no_noncommuting_coordinate_word_pair (r : ℕ) :
    ¬ HasNoncommutingWordPair r := by
  rintro ⟨u, v, state, hne⟩
  exact hne (coordinateWordAction_commute u v state)

/-! ## Exact expander calibration -/

variable {V Edge ι : Type}
variable [Fintype V] [DecidableEq V]
variable [Fintype Edge] [DecidableEq Edge]
variable [Fintype ι] [DecidableEq ι]

/-- Every natural expander residual has a commuting binary action word code,
without using expansion. -/
theorem expanderResidual_has_commuting_word_code
    (G : TseitinGraph V Edge) (readSet : ι → V)
    (x : Edge → ZMod 2) :
    ∃ word : BinaryWord (Fintype.card ι),
      expanderResidualBits G readSet x =
        coordinateWordAction word (zeroAssignment (Fintype.card ι)) := by
  let state := expanderResidualBits G readSet x
  refine ⟨(binaryWordEquivAssignment (Fintype.card ι)).symm state, ?_⟩
  rw [coordinateWordAction_zero]
  simp [state]

/-- Under expansion, every commuting word orbit point is realized by a genuine
Tseitin residual. -/
theorem every_commuting_word_is_expanderResidual
    (G : TseitinGraph V Edge) {c : ℕ} (hc : 1 ≤ c)
    (hexp : G.HasExpansion c)
    (readSet : ι → V) (hread : Function.Injective readSet)
    (hmed : 2 * Fintype.card ι ≤ Fintype.card V)
    (word : BinaryWord (Fintype.card ι)) :
    ∃ x : Edge → ZMod 2,
      expanderResidualBits G readSet x =
        coordinateWordAction word (zeroAssignment (Fintype.card ι)) := by
  exact expanderResidualBits_surjective G hc hexp readSet hread hmed
    (coordinateWordAction word (zeroAssignment (Fintype.card ι)))

/-- **No-go calibration.**  The expanded residual family fills an exponential
orbit while its entire word-action representation has zero pairwise
commutator holonomy. -/
theorem expander_full_orbit_with_zero_commutator
    (G : TseitinGraph V Edge) {c : ℕ} (hc : 1 ≤ c)
    (hexp : G.HasExpansion c)
    (readSet : ι → V) (hread : Function.Injective readSet)
    (hmed : 2 * Fintype.card ι ≤ Fintype.card V) :
    (∀ word : BinaryWord (Fintype.card ι),
      ∃ x : Edge → ZMod 2,
        expanderResidualBits G readSet x =
          coordinateWordAction word (zeroAssignment (Fintype.card ι))) ∧
      ¬ HasNoncommutingWordPair (Fintype.card ι) := by
  constructor
  · exact every_commuting_word_is_expanderResidual
      G hc hexp readSet hread hmed
  · exact no_noncommuting_coordinate_word_pair _

/-!
## Audit verdict

The concrete Route-G expander residual does not force noncommutative action.
It is an exponential orbit of commuting involutions, with exactly one generator
per residual coordinate.  Hence a lower bound based on outcome count,
generator count, or pairwise commutators cannot separate it from easy Boolean
cubes.

The next viable invariant must detect context-sensitive higher relations among
*future SAT continuations*—for example a solver-relative syntactic/action
quotient whose relation complexity is proved polynomial for every P trace but
superpolynomial for one NP-complete family.  Proving that latter pair remains
the genuine lower-bound frontier.
-/

end PallLean.Paper93.DeepMath.PathB.NoncommutativeActionHolonomyAudit

#print axioms PallLean.Paper93.DeepMath.PathB.NoncommutativeActionHolonomyAudit.coordinateAction_commute
#print axioms PallLean.Paper93.DeepMath.PathB.NoncommutativeActionHolonomyAudit.coordinateWordOrbit_rank_eq_two_pow
#print axioms PallLean.Paper93.DeepMath.PathB.NoncommutativeActionHolonomyAudit.no_noncommuting_coordinate_word_pair
#print axioms PallLean.Paper93.DeepMath.PathB.NoncommutativeActionHolonomyAudit.expander_full_orbit_with_zero_commutator
