import PallLean.Paper93.DeepMath.PathB.ComputationalDepthObserverClassSemantics

/-!
# The intrinsic-invariant bridge — exactly what a "collapse-cost" theorem must say

A recurring proposal is that some geometric/algebraic quantity `I` (holographic horizon charge, minimal bond
dimension, dynamic entanglement flow, SPDP rank, …) *equals* the deterministic collapse cost of `SAT`.  This file
states, and machine-checks, **exactly what such a bridge must be** — and proves the glue, so the open content is
pinned to two precisely-stated properties and nothing else.

## The shape (HAL's formulation, made precise)

An invariant is a function `Inv : Machine → ℕ → ℕ` — `Inv M n` is the quantity generated by decider `M` on inputs
of length `n`.  The bridge is the conjunction of:

* **`InvSound`** — every *polynomial-time* decider of the SAT boundary has a *polynomially-bounded* invariant.
  This is the P-side "no shortcut" calibration: `Inv D n ≤ poly(time_D(n))`.  It must hold for **every** correct
  decider — every encoding, algorithm, variable order, gauge, simulation — which is exactly why it is hard, and
  exactly where the proposed candidates (SPDP etc.) failed: one representation being geometrically large says
  nothing, because `Inv` must be small on *all* poly deciders.
* **`InvHard`** — every correct SAT-boundary decider (poly or not) has a *superpolynomial* invariant.  Writing
  `I_SAT n := inf { Inv M n | M decides the SAT boundary }`, this is exactly "`I_SAT` is superpolynomial" — the
  intrinsic, representation-independent SAT lower bound.

`invariant_bridge` proves: `InvSound ∧ InvHard → ¬ PolyCollapse SATV` (the SAT boundary is not in P).  With
Cook–Levin, `PneqNP_from_invariant` gives `P ≠ NP`.

## What is proved here, and what is NOT

The **glue is proved** (pure logic).  `InvSound` and `InvHard` are **not** — they are the two fenced properties,
and together they are separation-strength.  `single_representation_insufficient` records HAL's warning formally:
exhibiting *one* decider (or representation) with a large invariant does **not** give `InvHard`, which quantifies
over *all* deciders.  No candidate invariant is shown here to satisfy `InvSound` (the calibration) — that is the
missing bridge, stated exactly.

Nothing here is `NEXP ⊄ ACC⁰` or `P ≠ NP`.
-/

namespace PallLean.Paper93.DeepMath.PathB.ObserverInvariantBridge

open PallLean.Paper93.DeepMath.PathB.ObserverClassSemantics
open PallLean.Paper93.DeepMath.PathB.ComposableMachine (Machine Decides)
open PallLean.Paper93.DeepMath.PathB.PvsNPSeparatingInvariant (PolyBounded)

/-- An abstract complexity invariant: `Inv M n` = the quantity decider `M` generates on length-`n` inputs. -/
abbrev Invariant := Machine → ℕ → ℕ

/-- **P-side calibration.**  Every polynomial-time decider of `SATV`'s boundary has a polynomially-bounded
invariant.  (The "no-shortcut" upper bound `Inv D ≤ poly(time_D)`, required of *every* correct poly decider.) -/
def InvSound (SATV : NPObs) (Inv : Invariant) : Prop :=
  ∀ (M : Machine) (T : ℕ → ℕ), PolyBounded T → Decides M (acceptBool SATV) T → PolyBounded (Inv M)

/-- **Intrinsic SAT lower bound.**  Every correct decider of `SATV`'s boundary has a superpolynomial invariant —
equivalently, `I_SAT := inf { Inv M | M decides the boundary }` is superpolynomial. -/
def InvHard (SATV : NPObs) (Inv : Invariant) : Prop :=
  ∀ (M : Machine) (T : ℕ → ℕ), Decides M (acceptBool SATV) T → ¬ PolyBounded (Inv M)

/-- **The bridge (glue proved).**  A calibrated (`InvSound`), SAT-hard (`InvHard`) invariant forces the SAT
boundary out of P.  The proof: a poly decider would have a poly invariant (`InvSound`) and a superpoly invariant
(`InvHard`) at once. -/
theorem invariant_bridge (SATV : NPObs) (Inv : Invariant)
    (hSound : InvSound SATV Inv) (hHard : InvHard SATV Inv) :
    ¬ PolyCollapse SATV := by
  intro hcol
  obtain ⟨M, T, hT, hD⟩ := hcol
  exact hHard M T hD (hSound M T hT hD)

/-- **Capstone.**  With Cook–Levin, a calibrated SAT-hard invariant yields `P ≠ NP`.  Every hypothesis is explicit:
the invariant `Inv`, its two properties, and `CookLevin`. -/
theorem PneqNP_from_invariant (SATV : NPObs) (Inv : Invariant)
    (hSound : InvSound SATV Inv) (hHard : InvHard SATV Inv) (hCL : CookLevin SATV) :
    ¬ PeqNP :=
  (sat_separation_of_cookLevin SATV hCL).mp (invariant_bridge SATV Inv hSound hHard)

/-- **HAL's warning, formal.**  A single decider (or representation) with a large invariant does not give
`InvHard`: that predicate must survive minimization over *all* correct deciders.  Concretely, `InvHard` implies the
one-decider fact, but the converse fails in general — the one-decider fact is strictly weaker, so it cannot close
the bridge. -/
theorem single_representation_insufficient (SATV : NPObs) (Inv : Invariant)
    (hHard : InvHard SATV Inv) :
    (∃ M T, Decides M (acceptBool SATV) T ∧ ¬ PolyBounded (Inv M))
      ∨ ¬ ∃ M T, Decides M (acceptBool SATV) T := by
  by_cases h : ∃ M T, Decides M (acceptBool SATV) T
  · obtain ⟨M, T, hD⟩ := h
    exact Or.inl ⟨M, T, hD, hHard M T hD⟩
  · exact Or.inr h

/-! ## HAL's finer form: `Inv ≤ poly(time)` ⇒ `InvSound` (a sum/composition of polynomials is a polynomial) -/

/-- Monotone transport of polynomial boundedness. -/
theorem polyBounded_of_le {g h : ℕ → ℕ} (hle : ∀ n, g n ≤ h n) (hh : PolyBounded h) : PolyBounded g := by
  obtain ⟨c, k, hc⟩ := hh
  exact ⟨c, k, fun n => (hle n).trans (hc n)⟩

/-- If `T` is polynomially bounded, so is `n ↦ c·(T n + n + 1)^k`. -/
theorem polyBounded_time_comp {T : ℕ → ℕ} (c k : ℕ) (hT : PolyBounded T) :
    PolyBounded (fun n => c * (T n + n + 1) ^ k) := by
  obtain ⟨cT, kT, hTb⟩ := hT
  refine ⟨c * (cT + 2) ^ k, (max kT 1) * k, fun n => ?_⟩
  have hA : 1 ≤ n + 1 := Nat.succ_le_succ (Nat.zero_le n)
  have h3 : 1 ≤ (n + 1) ^ (max kT 1) := Nat.one_le_pow _ _ hA
  have hbase : T n + n + 1 ≤ (cT + 2) * (n + 1) ^ (max kT 1) := by
    have h1 : T n ≤ cT * (n + 1) ^ (max kT 1) :=
      (hTb n).trans (Nat.mul_le_mul (le_refl cT) (Nat.pow_le_pow_right hA (le_max_left kT 1)))
    have h2 : n + 1 ≤ (n + 1) ^ (max kT 1) := by
      conv_lhs => rw [← pow_one (n + 1)]
      exact Nat.pow_le_pow_right hA (le_max_right kT 1)
    have hexp : (cT + 2) * (n + 1) ^ (max kT 1)
        = cT * (n + 1) ^ (max kT 1) + (n + 1) ^ (max kT 1) + (n + 1) ^ (max kT 1) := by ring
    rw [hexp]; omega
  calc c * (T n + n + 1) ^ k
      ≤ c * ((cT + 2) * (n + 1) ^ (max kT 1)) ^ k :=
        Nat.mul_le_mul (le_refl c) (Nat.pow_le_pow_left hbase k)
    _ = c * (cT + 2) ^ k * (n + 1) ^ ((max kT 1) * k) := by rw [Nat.mul_pow, ← pow_mul]; ring

/-- **HAL's `traceInv_le_time`.**  `Inv D ≤ poly(time_D + n)` for every correct decider — the finer, faithful
form of the P-side calibration. -/
def InvTimeBounded (SATV : NPObs) (Inv : Invariant) : Prop :=
  ∀ (M : Machine) (T : ℕ → ℕ), Decides M (acceptBool SATV) T →
    ∃ c k, ∀ n, Inv M n ≤ c * (T n + n + 1) ^ k

/-- `InvTimeBounded` (`Inv ≤ poly(time)`) implies `InvSound` (poly time ⇒ poly invariant). -/
theorem invSound_of_timeBounded (SATV : NPObs) (Inv : Invariant)
    (h : InvTimeBounded SATV Inv) : InvSound SATV Inv := by
  intro M T hT hD
  obtain ⟨c, k, hb⟩ := h M T hD
  exact polyBounded_of_le hb (polyBounded_time_comp c k hT)

/-- **Capstone, from HAL's finer hypotheses.**  `Inv ≤ poly(time)` for all deciders, `InvHard`, and Cook–Levin
give `P ≠ NP`. -/
theorem PneqNP_from_timeBounded (SATV : NPObs) (Inv : Invariant)
    (hTB : InvTimeBounded SATV Inv) (hHard : InvHard SATV Inv) (hCL : CookLevin SATV) :
    ¬ PeqNP :=
  PneqNP_from_invariant SATV Inv (invSound_of_timeBounded SATV Inv hTB) hHard hCL

end PallLean.Paper93.DeepMath.PathB.ObserverInvariantBridge
