import PallLean.Paper93.DeepMath.PathB.ComputationalDepthDynamicSPDPAudit

/-!
# Holographic dynamic SPDP: a causal fixed-observer interface

This file implements the non-naive dynamic-SPDP proposal left open by
`ComputationalDepthDynamicSPDPAudit`: project the **actual computation trace** to a fixed finite observer
space and charge cumulative boundary innovation there.

The crucial restrictions are fields of `CausalObserver` rather than prose:

* `observe` is a function of the real machine configuration (there is no attached independent sheet);
* `step_commutes` makes the projected evolution causal;
* `output_factors` makes the projection decision-sufficient;
* `Observer` is a fixed finite type for the machine, so no uncharged real precision is available.

`projectedInnovation` counts clocked steps at which the observed boundary state changes.  The main positive
theorems are:

* `observe_iterate`: the observer trace is generated by its own fixed transition;
* `projected_output_correct`: the final projected state gives exactly the machine's answer;
* `projectedInnovation_le_runtime`: cumulative projected innovation is bounded by actual runtime;
* `Rprojected_PUpper`: every fixed causal observer family clears the all-`P` upper gate;
* `holographic_satLower_imp_notInP` / `holographic_PneqNP`: a super-polynomial SAT lower bound for this
  quantity would imply `SAT ∉ P` / `P ≠ NP` through the existing invariant interface.

The last theorem is deliberately conditional.  This file turns “holographic projection of the boundary in a
fixed observer space” into an ordinary finite causal object, but it does **not** prove that SAT forces
super-polynomial projected innovation.  Since projected innovation is bounded by runtime, that lower bound is
the unrestricted time-lower-bound breakthrough itself.

## Honest scope

A concrete surviving dynamic-SPDP candidate and its `PUpper`/cash-out theory.  No `SATLower` hypothesis is
discharged; no claim of `P ≠ NP` is made.
-/

namespace PallLean.Paper93.DeepMath.PathB.HolographicDynamicSPDP

open PallLean.Paper93.DeepMath.PathB.PvsNPSeparatingInvariant

/-- A fixed finite, causal, decision-sufficient observer of a machine's configuration boundary. -/
structure CausalObserver (M : ClockedMachine) where
  Observer : Type
  observerFintype : Fintype Observer
  observerDecEq : DecidableEq Observer
  observe : M.Config → Observer
  observedNext : Observer → Observer
  observedOutput : Observer → Bool
  step_commutes : ∀ c, observe (M.next c) = observedNext (observe c)
  output_factors : ∀ c, observedOutput (observe c) = M.output c

attribute [instance] CausalObserver.observerFintype CausalObserver.observerDecEq

/-- Causality iterated for any number of machine steps. -/
theorem observe_iterate {M : ClockedMachine} (O : CausalObserver M) (c : M.Config) (t : Nat) :
    O.observe (M.next^[t] c) = O.observedNext^[t] (O.observe c) := by
  induction t with
  | zero => rfl
  | succ t ih =>
      rw [Function.iterate_succ_apply', Function.iterate_succ_apply', O.step_commutes, ih]

/-- Decision sufficiency: reading the final projected boundary state returns exactly the machine decision. -/
theorem projected_output_correct {M : ClockedMachine} (O : CausalObserver M) (x : List Bool) :
    O.observedOutput (O.observedNext^[M.runtime x] (O.observe (M.init x))) = M.decide x := by
  rw [← observe_iterate O]
  exact O.output_factors _

/-- Cumulative holographic boundary innovation along one actual run: one charge exactly when the fixed
observer state changes at a clocked transition. -/
def projectedInnovation {M : ClockedMachine} (O : CausalObserver M) (x : List Bool) : Nat :=
  ((Finset.range (M.runtime x)).filter (fun t =>
    O.observe (M.next^[t + 1] (M.init x)) ≠ O.observe (M.next^[t] (M.init x)))).card

/-- Projection cannot create more charged innovations than there are actual clocked transitions. -/
theorem projectedInnovation_le_runtime {M : ClockedMachine} (O : CausalObserver M) (x : List Bool) :
    projectedInnovation O x ≤ M.runtime x := by
  unfold projectedInnovation
  exact (Finset.card_filter_le _ _).trans_eq (Finset.card_range _)

/-- Worst-case projected innovation over all Boolean inputs of length `n`. -/
def RprojectedFor {M : ClockedMachine} (O : CausalObserver M) (n : Nat) : Nat :=
  (Finset.univ : Finset (Fin n → Bool)).sup
    (fun a => projectedInnovation O (List.ofFn a))

/-- A uniform choice of one fixed causal observer for every clocked machine.  This is the type required to
instantiate the existing separating-invariant interface. -/
abbrev ObserverFamily := ∀ M : ClockedMachine, CausalObserver M

/-- The resource induced by a fixed causal observer family. -/
def Rprojected (F : ObserverFamily) (M : ClockedMachine) (n : Nat) : Nat :=
  RprojectedFor (F M) n

/-- Every causal fixed-observer projected-innovation resource is polynomially bounded on every polynomial-time
machine.  This is the genuine `PUpper` half of the proposal. -/
theorem Rprojected_PUpper (F : ObserverFamily) : PUpper (Rprojected F) := by
  intro M hM
  obtain ⟨c, k, hclock⟩ := hM
  refine ⟨c, k, fun n => ?_⟩
  apply Finset.sup_le
  intro a _
  calc
    projectedInnovation (F M) (List.ofFn a) ≤ M.runtime (List.ofFn a) :=
      projectedInnovation_le_runtime _ _
    _ ≤ c * ((List.ofFn a).length + 1) ^ k := hclock _
    _ = c * (n + 1) ^ k := by rw [List.length_ofFn]

/-- A holographic projected-innovation lower bound for `L` would already exclude `L` from `P`.  The lower
bound is an explicit hypothesis: this is the remaining breakthrough, not something supplied by projection. -/
theorem holographic_satLower_imp_notInP (F : ObserverFamily) (L : List Bool → Bool)
    (hLower : SATLower (Rprojected F) L) : ¬ InP L :=
  no_InP_of_invariant (Rprojected F) L (Rprojected_PUpper F) hLower

/-- Conditional P-vs-NP cash-out for a fixed causal holographic observer family. -/
theorem holographic_PneqNP (F : ObserverFamily) (L : List Bool → Bool)
    (hLNP : InNP L) (hLower : SATLower (Rprojected F) L) : ¬ PeqNP :=
  PneqNP_of_invariant (Rprojected F) L hLNP (Rprojected_PUpper F) hLower

/-- Exact statement of the unresolved gate in super-polynomial form. -/
theorem holographic_lower_iff (F : ObserverFamily) (L : List Bool → Bool) :
    SATLower (Rprojected F) L ↔
      ∀ M, Decides M L → ∀ c k : Nat, ∃ n,
        c * (n + 1) ^ k < Rprojected F M n :=
  satLower_iff (Rprojected F) L

end PallLean.Paper93.DeepMath.PathB.HolographicDynamicSPDP

#print axioms PallLean.Paper93.DeepMath.PathB.HolographicDynamicSPDP.observe_iterate
#print axioms PallLean.Paper93.DeepMath.PathB.HolographicDynamicSPDP.projected_output_correct
#print axioms PallLean.Paper93.DeepMath.PathB.HolographicDynamicSPDP.Rprojected_PUpper
#print axioms PallLean.Paper93.DeepMath.PathB.HolographicDynamicSPDP.holographic_PneqNP
