import PallLean.Paper93.DeepMath.PathB.ComputationalDepthRankContractionAccounting
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas

/-!
# Rank-restriction no-go for independently branched parity observers

A parity observer is generated by one output-column vector per free input coordinate.  Querying a set of coordinates
deletes those generators from the residual linear map.  This file proves the decisive linear-algebra bound: deleting
`q` generators can reduce span rank by at most `q`.

Combined with the exact branch accounting, independent exploration of all `2^q` restrictions can therefore never
beat the original `2^R` parity observer state space by rank contraction alone.  Any surviving observer-path algorithm
must reuse work across branches, exploit a nonlinear gate collapse, or use a separator factorization not represented
by independent rank-state enumeration.
-/

namespace PallLean.Paper93.DeepMath.PathB.ParityRankRestrictionNoGo

open scoped Classical
open PallLean.Paper93.DeepMath.PathB.RankContractionAccounting

variable {F V : Type*} [Field F] [AddCommGroup V] [Module F V]

/-- Rank of the span generated by a finite family of observer columns. -/
noncomputable def generatorRank (F : Type*) [Field F] (s : Finset V) [Module F V] : ℕ :=
  Set.finrank F (↑s : Set V)

/-- **Deleting `q` generators loses at most `q` rank (proved).** -/
theorem generatorRank_union_le (kept deleted : Finset V) :
    generatorRank F (kept ∪ deleted) ≤ generatorRank F kept + deleted.card := by
  unfold generatorRank Set.finrank
  rw [Finset.coe_union, Submodule.span_union]
  have hdim := Submodule.finrank_sup_add_finrank_inf_eq
    (Submodule.span F (↑kept : Set V)) (Submodule.span F (↑deleted : Set V))
  have hdeleted : Module.finrank F (Submodule.span F (↑deleted : Set V)) ≤ deleted.card :=
    finrank_span_finset_le_card deleted
  omega

/-- A strict super-unit rank drop is impossible when restriction merely deletes queried input columns. -/
theorem not_superunit_rank_drop (kept deleted : Finset V) :
    ¬ generatorRank F kept + deleted.card < generatorRank F (kept ∪ deleted) := by
  exact Nat.not_lt_of_ge (generatorRank_union_le kept deleted)

/-- **Independent parity restriction branching cannot win by rank contraction alone (proved).**  With initial rank
the union rank, residual rank the kept rank, and one binary query per deleted generator, the exact accounting is at
least the original observer-state count. -/
theorem independent_rank_branching_no_speedup (kept deleted : Finset V) :
    2 ^ generatorRank F (kept ∪ deleted) ≤ rankBranchWork deleted.card (generatorRank F kept) := by
  apply no_speedup_of_rank_loss_le_query
  simpa [Nat.add_comm] using generatorRank_union_le kept deleted

end PallLean.Paper93.DeepMath.PathB.ParityRankRestrictionNoGo

#print axioms PallLean.Paper93.DeepMath.PathB.ParityRankRestrictionNoGo.generatorRank_union_le
#print axioms PallLean.Paper93.DeepMath.PathB.ParityRankRestrictionNoGo.not_superunit_rank_drop
#print axioms PallLean.Paper93.DeepMath.PathB.ParityRankRestrictionNoGo.independent_rank_branching_no_speedup
