import PallLean.Paper93.DeepMath.PathB.ComputationalDepthNFrameTowerExternalNameLanguageBarrier

/-!
# N-Frame tower: bounded answer-feedback no-go

The external-name audit left one fully finite proposal: run the alleged SAT
solver on a candidate formula, negate its Boolean answer, and emit one of the
two constant formulas `yesCNF` or `noCNF`.  Then ask quotation to make the
candidate agree with that feedback output.

This file calculates that proposal exactly.

* The rejection-coded output is satisfiable exactly when the solver rejects
  the candidate.
* A semantic fixed point for that output is therefore exactly the SAT liar law,
  hence exactly a finite solver misclassification.
* A literal syntactic fixed point is stronger, but it still immediately gives
  the same misclassification.
* Per machine, semantic feedback fixed points exist exactly when that machine
  is not a correct SAT decider.
* Uniformly supplying them for all certified polynomial machines exists exactly
  when `SATDecisionInP` is false; the reverse construction again uses classical
  choice of an already-missed formula.

So bounded pre-evaluation avoids both unbounded halting and tableau size only by
computing the solver's answer first.  The demanded feedback fixed point is not
then generated by Kleene quotation: its consistency condition is precisely the
counterexample that the separation argument needed to construct.
-/

namespace PallLean.Paper93.DeepMath.PathB.NFrameTowerBoundedAnswerFeedbackNoGo

open SATDepthMachine
open PallLean.Paper93.DeepMath.PathB.PvsNPDynamicHolonomyQueryTranscriptBridge
open PallLean.Paper93.DeepMath.PathB.NFrameTowerSolverDiagonalizationFrontier
open PallLean.Paper93.DeepMath.PathB.NFrameTowerKleeneQuotationAudit
open PallLean.Paper93.DeepMath.PathB.NFrameTowerHaltingReflectionNoGo

attribute [local instance] Classical.propDecidable

/-! ## The concrete finite feedback formula -/

/-- Negate the solver's answer on `φ`, then answer-code that bit as one of the
two fixed finite CNFs. -/
def rejectionCodedCNF
    (U : MachineModel) (code : Nat) (φ : CNF) : CNF :=
  truthCodedCNF (! U.decisionRun code φ)

/-- The emitted finite CNF is satisfiable exactly when the solver rejected the
candidate. -/
theorem rejectionCodedCNF_satisfiable_iff
    (U : MachineModel) (code : Nat) (φ : CNF) :
    Satisfiable (rejectionCodedCNF U code φ) ↔
      U.decisionRun code φ = false := by
  rw [rejectionCodedCNF, truthCodedCNF_satisfiable_iff]
  cases U.decisionRun code φ <;> simp

/-- Feedback always emits one of the same two fixed formulas. -/
theorem rejectionCodedCNF_eq_yes_or_no
    (U : MachineModel) (code : Nat) (φ : CNF) :
    rejectionCodedCNF U code φ = yesCNF ∨
      rejectionCodedCNF U code φ = noCNF := by
  cases h : U.decisionRun code φ
  · exact Or.inl (by simp [rejectionCodedCNF, truthCodedCNF, h])
  · exact Or.inr (by simp [rejectionCodedCNF, truthCodedCNF, h])

/-! ## Semantic and syntactic feedback fixed points -/

/-- The weakest feedback consistency condition: the candidate and the emitted
formula have the same SAT truth. -/
structure SemanticAnswerFeedbackFor
    (U : MachineModel) (M : DecisionMachine U) where
  formula : CNF
  semantic_fixedpoint :
    Satisfiable formula ↔
      Satisfiable (rejectionCodedCNF U M.code formula)

/-- A semantic feedback fixed point is exactly the liar law on its candidate. -/
theorem semanticAnswerFeedback_iff_liarOn
    (U : MachineModel) (M : DecisionMachine U) (φ : CNF) :
    (Satisfiable φ ↔ Satisfiable (rejectionCodedCNF U M.code φ)) ↔
      LiarOn U M.code φ := by
  unfold LiarOn
  rw [rejectionCodedCNF_satisfiable_iff]

/-- Hence every semantic feedback fixed point is a genuine finite
misclassification. -/
theorem SemanticAnswerFeedbackFor.not_correctOn
    {U : MachineModel} {M : DecisionMachine U}
    (F : SemanticAnswerFeedbackFor U M) :
    ¬ CorrectOn U M.code F.formula :=
  (liarOn_iff_not_correctOn U M.code F.formula).mp
    ((semanticAnswerFeedback_iff_liarOn U M F.formula).mp
      F.semantic_fixedpoint)

/-- The stronger literal proposal: the candidate CNF is syntactically equal to
the rejection-coded output. -/
structure SyntacticAnswerFeedbackFor
    (U : MachineModel) (M : DecisionMachine U) where
  formula : CNF
  syntactic_fixedpoint :
    formula = rejectionCodedCNF U M.code formula

/-- Literal feedback equality implies semantic feedback consistency. -/
def SyntacticAnswerFeedbackFor.toSemantic
    {U : MachineModel} {M : DecisionMachine U}
    (F : SyntacticAnswerFeedbackFor U M) :
    SemanticAnswerFeedbackFor U M where
  formula := F.formula
  semantic_fixedpoint :=
    iff_of_eq (congrArg Satisfiable F.syntactic_fixedpoint)

/-- Therefore a correct SAT decider has neither a semantic nor a syntactic
answer-feedback fixed point. -/
theorem no_semanticAnswerFeedback_of_decidesSAT
    (U : MachineModel) (M : DecisionMachine U)
    (hM : DecidesSAT U M) :
    ¬ Nonempty (SemanticAnswerFeedbackFor U M) := by
  rintro ⟨F⟩
  exact F.not_correctOn (hM F.formula)

theorem no_syntacticAnswerFeedback_of_decidesSAT
    (U : MachineModel) (M : DecisionMachine U)
    (hM : DecidesSAT U M) :
    ¬ Nonempty (SyntacticAnswerFeedbackFor U M) := by
  rintro ⟨F⟩
  exact no_semanticAnswerFeedback_of_decidesSAT U M hM ⟨F.toSemantic⟩

/-! ## Exact per-machine and uniform calibration -/

/-- An already-known finite counterexample supplies the semantic fixed point;
the feedback construction itself did not discover that counterexample. -/
def semanticAnswerFeedbackOfCounterexample
    {U : MachineModel} (M : DecisionMachine U) (φ : CNF)
    (hfail : ¬ CorrectOn U M.code φ) :
    SemanticAnswerFeedbackFor U M where
  formula := φ
  semantic_fixedpoint :=
    (semanticAnswerFeedback_iff_liarOn U M φ).mpr
      ((liarOn_iff_not_correctOn U M.code φ).mpr hfail)

/-- Per machine, semantic feedback fixed points exist exactly when the machine
already fails to decide SAT. -/
theorem semanticAnswerFeedback_iff_not_decidesSAT
    (U : MachineModel) (M : DecisionMachine U) :
    Nonempty (SemanticAnswerFeedbackFor U M) ↔ ¬ DecidesSAT U M := by
  constructor
  · rintro ⟨F⟩ hM
    exact F.not_correctOn (hM F.formula)
  · intro hnot
    rcases exists_finite_counterexample_of_not_decidesSAT M hnot with
      ⟨φ, hfail⟩
    exact ⟨semanticAnswerFeedbackOfCounterexample M φ hfail⟩

/-- One semantic answer-feedback fixed point for every certified polynomial
machine. -/
structure UniformSemanticAnswerFeedback (U : MachineModel) where
  feedback : ∀ M : DecisionMachine U, SemanticAnswerFeedbackFor U M

/-- A uniform feedback family rules out a polynomial SAT decider. -/
theorem no_SATDecisionInP_of_uniformSemanticAnswerFeedback
    {U : MachineModel} (F : UniformSemanticAnswerFeedback U) :
    ¬ SATDecisionInP U := by
  rintro ⟨M, hM⟩
  exact no_semanticAnswerFeedback_of_decidesSAT U M hM ⟨F.feedback M⟩

/-- Assuming the lower bound, classical choice of each missed formula packages
the uniform family.  This is not an effective feedback constructor. -/
noncomputable def uniformSemanticAnswerFeedbackOfNoSATDecisionInP
    {U : MachineModel} (hno : ¬ SATDecisionInP U) :
    UniformSemanticAnswerFeedback U where
  feedback := by
    intro M
    have hnot : ¬ DecidesSAT U M := by
      intro hM
      exact hno ⟨M, hM⟩
    exact (semanticAnswerFeedback_iff_not_decidesSAT U M).mpr hnot |>.some

/-- **Bounded answer-feedback frontier.**  Uniform semantic feedback is exactly
the desired SAT decision lower bound. -/
theorem uniformSemanticAnswerFeedback_iff_no_SATDecisionInP
    (U : MachineModel) :
    Nonempty (UniformSemanticAnswerFeedback U) ↔ ¬ SATDecisionInP U := by
  constructor
  · rintro ⟨F⟩
    exact no_SATDecisionInP_of_uniformSemanticAnswerFeedback F
  · intro hno
    exact ⟨uniformSemanticAnswerFeedbackOfNoSATDecisionInP hno⟩

end PallLean.Paper93.DeepMath.PathB.NFrameTowerBoundedAnswerFeedbackNoGo

#print axioms PallLean.Paper93.DeepMath.PathB.NFrameTowerBoundedAnswerFeedbackNoGo.rejectionCodedCNF_satisfiable_iff
#print axioms PallLean.Paper93.DeepMath.PathB.NFrameTowerBoundedAnswerFeedbackNoGo.semanticAnswerFeedback_iff_liarOn
#print axioms PallLean.Paper93.DeepMath.PathB.NFrameTowerBoundedAnswerFeedbackNoGo.no_syntacticAnswerFeedback_of_decidesSAT
#print axioms PallLean.Paper93.DeepMath.PathB.NFrameTowerBoundedAnswerFeedbackNoGo.semanticAnswerFeedback_iff_not_decidesSAT
#print axioms PallLean.Paper93.DeepMath.PathB.NFrameTowerBoundedAnswerFeedbackNoGo.uniformSemanticAnswerFeedback_iff_no_SATDecisionInP
