import PallLean.Paper93.DeepMath.PathB.MatrixInducedProjectionAttempt
import PallLean.Paper93.DeepMath.PathB.ZeroProfileNormalFormInstantiationProgress
import PallLean.Paper93.DeepMath.PathB.SATDeciderGaugeRankMonotoneCriterion

/-!
# Non-flat singleton-quotient GodMove candidate

The flat `piPhi` attempt is identity and cannot be the compressor.  This file
builds the first genuinely non-flat Cook--Levin polynomial projection already
available in the Path-B machinery: quotienting by the zero-profile singleton
shift subspace.

This is not yet the final GodMove compressor.  What it proves is exactly the
next structural milestone:

* the candidate is an idempotent linear projection;
* it kills the singleton-shift obstruction;
* it is not the identity / not flat `piPhi` at paper scale;
* it has the residual-closure package needed by the zero-profile quotient
  normal-form route;
* the remaining GodMove fields reduce to the known SPDP image-containment,
  P-side collapse, and NP-preservation obligations for this specific non-flat
  projection.
-/

namespace PallLean.Paper93.DeepMath.PathB

open PaperFaithfulSeparation
open TuringMachine
open MultilinearSPDP

/-- The singleton-quotient projection specialized to the exact Cook--Levin
SAT-decider polynomial space.  This is the first concrete non-flat candidate:
it quotients by the singleton-shift subspace generated by the Cook--Levin
factor list. -/
noncomputable def singletonQuotientSATGauge
    (M : DTM) (n : Nat) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    SATDeciderGaugeMap M n hn2 htb hns :=
  zeroProfileQuotientBySingletonShiftProjection
    (fun i => (WithinProfileBound.cookLevinFactorList M n hn2 htb hns).get i)

/-- The singleton-quotient candidate is an idempotent projection. -/
theorem singletonQuotientSATGauge_idempotent
    (M : DTM) (n : Nat) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    (singletonQuotientSATGauge M n hn2 htb hns).comp
        (singletonQuotientSATGauge M n hn2 htb hns) =
      singletonQuotientSATGauge M n hn2 htb hns := by
  unfold singletonQuotientSATGauge
  exact zeroProfileQuotientBySingletonShiftProjection_idempotent
    (fun i => (WithinProfileBound.cookLevinFactorList M n hn2 htb hns).get i)

/-- The singleton-quotient candidate kills every singleton-shift row. -/
theorem singletonQuotientSATGauge_killsSingletonShifts
    (M : DTM) (n : Nat) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    ZeroProfileProjectionKillsSingletonShifts
      (fun i => (WithinProfileBound.cookLevinFactorList M n hn2 htb hns).get i)
      (singletonQuotientSATGauge M n hn2 htb hns) := by
  unfold singletonQuotientSATGauge
  exact zeroProfileQuotientBySingletonShiftProjection_killsSingletonShifts
    (fun i => (WithinProfileBound.cookLevinFactorList M n hn2 htb hns).get i)

/-- Identity fixes all zero-profile shift rows. -/
theorem identitySATDeciderGauge_fixesShiftRows
    (M : DTM) (n : Nat) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    CookLevinZeroProfileProjectionFixesShiftRows M n hn2 htb hns
      (identitySATDeciderGauge M n hn2 htb hns) := by
  intro q _hq
  rfl

/-- The singleton-quotient candidate does not fix all shift rows for the actual
Cook--Levin factor list. -/
theorem not_singletonQuotientSATGauge_fixesShiftRows
    (M : DTM) (n : Nat) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    ¬ CookLevinZeroProfileProjectionFixesShiftRows M n hn2 htb hns
      (singletonQuotientSATGauge M n hn2 htb hns) :=
  not_CookLevinZeroProfileProjectionFixesShiftRows_of_killsSingleton_actual
    M n hn2 htb hns
    (singletonQuotientSATGauge M n hn2 htb hns)
    (singletonQuotientSATGauge_killsSingletonShifts M n hn2 htb hns)

/-- Therefore the singleton-quotient candidate is not the identity map. -/
theorem singletonQuotientSATGauge_ne_identity
    (M : DTM) (n : Nat) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    singletonQuotientSATGauge M n hn2 htb hns ≠
      identitySATDeciderGauge M n hn2 htb hns := by
  intro h
  have hfix : CookLevinZeroProfileProjectionFixesShiftRows M n hn2 htb hns
      (singletonQuotientSATGauge M n hn2 htb hns) := by
    rw [h]
    exact identitySATDeciderGauge_fixesShiftRows M n hn2 htb hns
  exact not_singletonQuotientSATGauge_fixesShiftRows M n hn2 htb hns hfix

/-- Since flat `piPhi` is identity on the Cook--Levin space, the singleton
quotient is also not the flat `piPhi` candidate. -/
theorem singletonQuotientSATGauge_ne_piPhi
    (M : DTM) (n : Nat) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    singletonQuotientSATGauge M n hn2 htb hns ≠
      satDeciderGaugeMapPiPhi M n hn2 htb hns := by
  intro h
  apply singletonQuotientSATGauge_ne_identity M n hn2 htb hns
  rw [h, satDeciderGaugeMapPiPhi_eq_id]

/-- The singleton quotient has the ambient residual-closure package already
proved by the zero-profile machinery. -/
theorem singletonQuotientSATGauge_residualClosureWithBudget_ambient
    (M : DTM) (n : Nat) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    CookLevinZeroProfileProjectionResidualClosureWithBudget
      M n hn2 htb hns
      (singletonQuotientSATGauge M n hn2 htb hns) n := by
  unfold singletonQuotientSATGauge
  exact cookLevinZeroProfileSingletonQuotientResidualClosureWithBudget_ambient
    M n hn2 htb hns

/-- Candidate-specific rank-monotonicity obligation for the singleton quotient.
This is the exact field needed to promote the concrete non-flat projection into
a SAT-decider gauge. -/
def SingletonQuotientSATGaugeRankMonotonicityObligation
    (M : DTM) (n : Nat) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) : Prop :=
  SATDeciderGaugeSPDPSubspaceImageContainment M n hn2 htb hns
    (singletonQuotientSATGauge M n hn2 htb hns)

/-- The image-containment obligation gives rank monotonicity for the concrete
singleton-quotient candidate. -/
theorem singletonQuotientSATGauge_rankMonotonicity_of_imageContainment
    (M : DTM) (n : Nat) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (hcontain : SingletonQuotientSATGaugeRankMonotonicityObligation
      M n hn2 htb hns) :
    SATDeciderGaugeRankMonotonicity M n hn2 htb hns
      (singletonQuotientSATGauge M n hn2 htb hns) :=
  satDeciderGaugeRankMonotonicity_of_spdpSubspaceImageContainment
    M n hn2 htb hns (singletonQuotientSATGauge M n hn2 htb hns) hcontain

/-- Candidate-specific P-side collapse obligation. -/
def SingletonQuotientSATGaugePSideObligation
    (M : DTM) (n : Nat) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) : Prop :=
  SATDeciderGaugePSideBound M n hn2 htb hns
    (singletonQuotientSATGauge M n hn2 htb hns)

/-- Candidate-specific NP identity-minor preservation obligation. -/
def SingletonQuotientSATGaugeNPObligation
    (M : DTM) (n : Nat) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) : Prop :=
  SATDeciderGaugeNPIdentityMinorPreservation M n hn2 htb hns
    (singletonQuotientSATGauge M n hn2 htb hns)

/-- If the three candidate-specific obligations are proved, the singleton
quotient supplies the integrated rich-projection target. -/
theorem cookLevinRichProjectionTarget_of_singletonQuotient_obligations
    (M : DTM) (n : Nat) (hn : n ≥ 2 ^ 804) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (hcontain : SingletonQuotientSATGaugeRankMonotonicityObligation
      M n hn2 htb hns)
    (hP : SingletonQuotientSATGaugePSideObligation M n hn2 htb hns)
    (hNP : SingletonQuotientSATGaugeNPObligation M n hn2 htb hns) :
    CookLevinRichProjectionTarget M n hn hn2 htb hns := by
  exact ⟨singletonQuotientSATGauge M n hn2 htb hns,
    singletonQuotientSATGauge_rankMonotonicity_of_imageContainment
      M n hn2 htb hns hcontain,
    hP,
    hNP⟩

/-- If the singleton quotient satisfies its three candidate-specific
obligations, it gives the non-flat matrix-polynomial realization interface for
any matrix-level gauge. -/
theorem nonflatMatrixPolynomialProjectionRealization_of_singletonQuotient_obligations
    (M : DTM) (n : Nat) (hn : n ≥ 2 ^ 804) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (A : Matrix (Fin n) (Fin n) ℝ)
    (𝒥 : Finset (Finset (Fin n)))
    (hmatrix : IsAmplituhedronGauge A 𝒥)
    (hcontain : SingletonQuotientSATGaugeRankMonotonicityObligation
      M n hn2 htb hns)
    (hP : SingletonQuotientSATGaugePSideObligation M n hn2 htb hns)
    (hNP : SingletonQuotientSATGaugeNPObligation M n hn2 htb hns) :
    NonflatMatrixPolynomialProjectionRealization M n hn hn2 htb hns A 𝒥 := by
  refine ⟨hmatrix, singletonQuotientSATGauge M n hn2 htb hns, ?_, ?_, hP, hNP⟩
  · intro hflat
    exact singletonQuotientSATGauge_ne_piPhi M n hn2 htb hns hflat
  · exact singletonQuotientSATGauge_rankMonotonicity_of_imageContainment
      M n hn2 htb hns hcontain

/-! ## Axiom audit anchors -/
#print axioms singletonQuotientSATGauge_idempotent
#print axioms singletonQuotientSATGauge_killsSingletonShifts
#print axioms not_singletonQuotientSATGauge_fixesShiftRows
#print axioms singletonQuotientSATGauge_ne_identity
#print axioms singletonQuotientSATGauge_ne_piPhi
#print axioms singletonQuotientSATGauge_residualClosureWithBudget_ambient
#print axioms singletonQuotientSATGauge_rankMonotonicity_of_imageContainment
#print axioms cookLevinRichProjectionTarget_of_singletonQuotient_obligations
#print axioms nonflatMatrixPolynomialProjectionRealization_of_singletonQuotient_obligations

end PallLean.Paper93.DeepMath.PathB
