import PallLean.Paper93.DeepMath.PathB.RouteBTouchedLocalAlphabetKR
import PallLean.Paper93.DeepMath.PathB.ZeroProfileCompressedSpanProgress

/-!
# Route B touched monomial-shift KR seam

The SPDP row definition in the Lean infrastructure allows an arbitrary shift
polynomial `m`, but the paper's matrix rows are generated by monomial shifts;
general polynomial shifts are then linear combinations of those rows.  This
file makes that reduction explicit for the touched/untouched Cook--Levin split.

This is necessary for the final local-normal-form classifier: a finite local
word cannot encode arbitrary rational coefficients in `m`.  Coefficients belong
in the ambient linear span, while the finite KR/local normal form classifies the
monomial-shift rows.
-/

set_option exponentiation.threshold 1024

namespace PallLean.Paper93.DeepMath.PathB

open PaperFaithfulCompilation
open PaperFaithfulSeparation
open TuringMachine
open Step4Compiler
open scoped BigOperators

/-- Product of variables for a monomial shift support. -/
noncomputable def touchedShiftMonomial
    {N : ℕ} (T : Finset (Fin N)) : MvPolynomial (Fin N) ℚ :=
  T.prod (fun v => MvPolynomial.X v)

/-- The exact touched/untouched allocated product appearing after the split. -/
noncomputable def touchedAllocatedSplitProduct
    (M : DTM) (n : ℕ) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (S : List (Fin (cookLevinTableau M n hn2 htb hns).numVars))
    (alloc : cookLevinConstraintIdx M n hn2 htb hns →
      List (Fin (cookLevinTableau M n hn2 htb hns).numVars)) :
    MvPolynomial (Fin (cookLevinTableau M n hn2 htb hns).numVars) ℚ :=
  ((Finset.univ : Finset (cookLevinConstraintIdx M n hn2 htb hns)).filter
    (fun i => i ∈ cookLevinTouchedConstraints M n hn2 htb hns S)).prod
      (fun i => SPDP.iterDerivList (alloc i)
        (cookLevinConstraintFactor M n hn2 htb hns i)) *
    ((Finset.univ : Finset (cookLevinConstraintIdx M n hn2 htb hns)).filter
      (fun i => i ∉ cookLevinTouchedConstraints M n hn2 htb hns S)).prod
        (fun i => SPDP.iterDerivList (alloc i)
          (cookLevinConstraintFactor M n hn2 htb hns i))

/-- The touched split row with a multilinear monomial shift support `T`. -/
noncomputable def touchedMonomialSplitRow
    (M : DTM) (n : ℕ) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (S : List (Fin (cookLevinTableau M n hn2 htb hns).numVars))
    (T : Finset (Fin (cookLevinTableau M n hn2 htb hns).numVars))
    (alloc : cookLevinConstraintIdx M n hn2 htb hns →
      List (Fin (cookLevinTableau M n hn2 htb hns).numVars)) :
    MvPolynomial (Fin (cookLevinTableau M n hn2 htb hns).numVars) ℚ :=
  touchedSplitRow M n hn2 htb hns S (touchedShiftMonomial T) alloc

/-- Monomial-shift touched split KR data.

This is the paper-faithful row basis: cover every admissible touched split row
whose shift is a multilinear monomial supported inside the derivative window
`S`.  Arbitrary polynomial shifts are recovered by linearity in
`touchedSplitKRData_of_touchedMonomialShiftKRData`. -/
def CookLevinTouchedMonomialShiftKRData
    (M : DTM) (n : ℕ) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) : Prop :=
  ∃ G : Finset (MvPolynomial
      (Fin (cookLevinTableau M n hn2 htb hns).numVars) ℚ),
    G.card ≤ n ^ 200 ∧
    ∀ (S : List (Fin (cookLevinTableau M n hn2 htb hns).numVars))
      (T : Finset (Fin (cookLevinTableau M n hn2 htb hns).numVars))
      (alloc : cookLevinConstraintIdx M n hn2 htb hns →
        List (Fin (cookLevinTableau M n hn2 htb hns).numVars)),
      S.length = Nat.log 2 n →
      T ⊆ S.toFinset →
      SPDP.isBlockAdmissible (cookLevinTableau M n hn2 htb hns).partition S →
      (∀ i, ∀ v ∈ alloc i, v ∈ S) →
      (∀ i, ∀ v ∈ alloc i,
        v ∈ ((cookLevinTableau M n hn2 htb hns).constraints.get i).support) →
      (∀ i, (alloc i).length ≤ 6) →
      (∀ i, i ∉ cookLevinTouchedConstraints M n hn2 htb hns S → alloc i = []) →
      touchedMonomialSplitRow M n hn2 htb hns S T alloc ∈
        Submodule.span ℚ (↑G : Set (MvPolynomial
          (Fin (cookLevinTableau M n hn2 htb hns).numVars) ℚ))

/-- A general shift row is spanned by multilinear monomial-shift rows supported
on the same window. -/
theorem touchedSplitRow_mem_span_monomialRows_of_vars_subset
    (M : DTM) (n : ℕ) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (S : List (Fin (cookLevinTableau M n hn2 htb hns).numVars))
    (m : MvPolynomial (Fin (cookLevinTableau M n hn2 htb hns).numVars) ℚ)
    (alloc : cookLevinConstraintIdx M n hn2 htb hns →
      List (Fin (cookLevinTableau M n hn2 htb hns).numVars))
    (hmvars : m.vars ⊆ S.toFinset) :
    touchedSplitRow M n hn2 htb hns S m alloc ∈
      Submodule.span ℚ
        (↑(zeroProfileShiftMonomialImagesOn S.toFinset
          (touchedAllocatedSplitProduct M n hn2 htb hns S alloc)) :
          Set (MvPolynomial
            (Fin (cookLevinTableau M n hn2 htb hns).numVars) ℚ)) := by
  classical
  unfold touchedSplitRow touchedAllocatedSplitProduct
  exact mlProj_mul_mem_span_shiftMonomialImagesOn_of_vars_subset
    S.toFinset m
    (((Finset.univ : Finset (cookLevinConstraintIdx M n hn2 htb hns)).filter
      (fun i => i ∈ cookLevinTouchedConstraints M n hn2 htb hns S)).prod
        (fun i => SPDP.iterDerivList (alloc i)
          (cookLevinConstraintFactor M n hn2 htb hns i)) *
      ((Finset.univ : Finset (cookLevinConstraintIdx M n hn2 htb hns)).filter
        (fun i => i ∉ cookLevinTouchedConstraints M n hn2 htb hns S)).prod
          (fun i => SPDP.iterDerivList (alloc i)
            (cookLevinConstraintFactor M n hn2 htb hns i)))
    hmvars

/-- Monomial-shift KR data implies the exact touched split KR data by linearity
in the shift polynomial. -/
theorem touchedSplitKRData_of_touchedMonomialShiftKRData
    (M : DTM) (n : ℕ) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (hMono : CookLevinTouchedMonomialShiftKRData M n hn2 htb hns) :
    CookLevinTouchedSplitKRData M n hn2 htb hns := by
  classical
  rcases hMono with ⟨G, hcard, hcover⟩
  refine ⟨G, hcard, ?_⟩
  intro S m alloc hlen hdeg hmvars hadm hall hcompat hlenAlloc hout
  have hspanMono := touchedSplitRow_mem_span_monomialRows_of_vars_subset
    M n hn2 htb hns S m alloc hmvars
  refine (Submodule.span_le.mpr ?_) hspanMono
  intro q hq
  change q ∈ zeroProfileShiftMonomialImagesOn S.toFinset
      (touchedAllocatedSplitProduct M n hn2 htb hns S alloc) at hq
  unfold zeroProfileShiftMonomialImagesOn at hq
  rcases Finset.mem_image.mp hq with ⟨T, hT, rfl⟩
  have hTsubset : T ⊆ S.toFinset := Finset.mem_powerset.mp hT
  exact hcover S T alloc hlen hTsubset hadm hall hcompat hlenAlloc hout

/-- Uniform monomial-shift touched KR data at paper scale. -/
def Step247UniformTouchedMonomialShiftKRData : Prop :=
  ∀ (M : DTM) (n : ℕ) (_hn : n ≥ 2 ^ 804) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n),
    CookLevinTouchedMonomialShiftKRData M n hn2 htb hns

/-- Uniform monomial-shift data supplies the exact split seam. -/
theorem step247UniformTouchedSplitKRData_of_touchedMonomialShiftKRData
    (hMono : Step247UniformTouchedMonomialShiftKRData) :
    Step247UniformTouchedSplitKRData := by
  intro M n hn hn2 htb hns
  exact touchedSplitKRData_of_touchedMonomialShiftKRData
    M n hn2 htb hns (hMono M n hn hn2 htb hns)

/-- Uniform monomial-shift data closes Route B. -/
theorem noBoundedSATDeciderAtPaperScale_of_touchedMonomialShiftKRData_TPhi
    (hMono : Step247UniformTouchedMonomialShiftKRData) :
    NoBoundedSATDeciderAtPaperScale :=
  noBoundedSATDeciderAtPaperScale_of_touchedSplitKRData_TPhi
    (step247UniformTouchedSplitKRData_of_touchedMonomialShiftKRData hMono)

/-! ## Axiom audit anchors -/

#print axioms touchedSplitRow_mem_span_monomialRows_of_vars_subset
#print axioms touchedSplitKRData_of_touchedMonomialShiftKRData
#print axioms step247UniformTouchedSplitKRData_of_touchedMonomialShiftKRData
#print axioms noBoundedSATDeciderAtPaperScale_of_touchedMonomialShiftKRData_TPhi

end PallLean.Paper93.DeepMath.PathB
