import PallLean.Paper93.DeepMath.PathB.ZeroProfileCompressedSpanProgress
import PallLean.Paper93.Paper283.RouteBRicherGaugePWindowConcreteCover

/-!
# Zero-profile quotient/type-space compression

This file adds the projected replacement interface for the all-zero
Cook-Levin profile.  The unquotiented local type-space obligation in
`ZeroProfileCompressedSpanProgress` is too strong: singleton shifts already
force dimension at least the ambient variable count.  The interface below
therefore separates two pieces of data:

* a linear projection/quotient map whose kernel contains the singleton-shift
  obstruction;
* a finite local type alphabet for the projected rows, plus an explicitly paid
  residual span for what the projection removes.

No concrete Cook-Levin local typing is claimed here.
-/

namespace PallLean
namespace Paper93
namespace DeepMath
namespace PathB

open MvPolynomial SymmetricPowerBound TuringMachine PaperFaithfulSeparation
open WithinProfileBound MultilinearSPDP SPDP
open scoped BigOperators

attribute [local instance] Classical.dec

/-! ## Singleton obstruction killed by a projection -/

/-- The subspace generated by singleton-shift zero-profile rows.  This is the
checked obstruction that makes the unquotiented zero-profile type-space target
too large at paper scale. -/
noncomputable def zeroProfileSingletonShiftSubspace {n L : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
  Submodule.span ℚ
    (Set.range
      (fun i : Fin n =>
        mlProj (MvPolynomial.X i * Finset.univ.prod factors)))

/-- A projection/quotient map kills the singleton-shift obstruction. -/
def ZeroProfileProjectionKillsSingletonShifts {n L : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ) : Prop :=
  ∀ i : Fin n,
    project (mlProj (MvPolynomial.X i * Finset.univ.prod factors)) = 0

/-- Kernel form of `ZeroProfileProjectionKillsSingletonShifts`. -/
theorem zeroProfileProjectionKillsSingletonShifts_iff_singletonShiftSubspace_le_ker
    {n L : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ) :
    ZeroProfileProjectionKillsSingletonShifts factors project ↔
      zeroProfileSingletonShiftSubspace factors ≤ LinearMap.ker project := by
  constructor
  · intro hkills
    unfold zeroProfileSingletonShiftSubspace
    apply Submodule.span_le.mpr
    intro row hrow
    rcases hrow with ⟨i, rfl⟩
    exact LinearMap.mem_ker.mpr (hkills i)
  · intro hker i
    exact LinearMap.mem_ker.mp
      (hker (Submodule.subset_span (Set.mem_range_self i)))

/-! ## Projected type alphabets -/

/-- A finite local type alphabet for projected zero-profile rows.

The budget is explicit so residual/kernel rows can be paid for separately
before comparing the total with `withinProfileBound`. -/
structure ZeroProfileQuotientTypeAlphabet (n typeBudget : ℕ) where
  type : Type
  [typeFintype : Fintype type]
  localDim : ℕ
  localBasis : type → Finset (MvPolynomial (Fin n) ℚ)
  localBasis_card_le : ∀ τ, (localBasis τ).card ≤ localDim
  symmetricProfileBudget_le :
    Fintype.card type * localDim ≤ typeBudget

/-- The ambient type space represented by one quotient type. -/
noncomputable def zeroProfileQuotientTypeSpace {n typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget)
    (τ : A.type) :
    Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
  Submodule.span ℚ
    (↑(A.localBasis τ) : Set (MvPolynomial (Fin n) ℚ))

/-- Each quotient type space has dimension bounded by `localDim`. -/
theorem zeroProfileQuotientTypeSpace_finrank_le {n typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget)
    (τ : A.type) :
    Module.finrank ℚ ↥(zeroProfileQuotientTypeSpace A τ) ≤
      A.localDim := by
  classical
  unfold zeroProfileQuotientTypeSpace
  exact (finrank_span_finset_le_card (A.localBasis τ)).trans
    (A.localBasis_card_le τ)

/-- Global projected normal-form basis obtained by unioning the per-type
local bases. -/
noncomputable def zeroProfileQuotientTypeGlobalBasis {n typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget) :
    Finset (MvPolynomial (Fin n) ℚ) := by
  classical
  letI : Fintype A.type := A.typeFintype
  exact Finset.univ.biUnion A.localBasis

/-- The global projected normal-form basis fits inside its explicit type
budget. -/
theorem zeroProfileQuotientTypeGlobalBasis_card_le_typeBudget
    {n typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget) :
    (zeroProfileQuotientTypeGlobalBasis A).card ≤ typeBudget := by
  classical
  letI : Fintype A.type := A.typeFintype
  have hcard :
      (Finset.univ.biUnion A.localBasis).card ≤
        (Finset.univ : Finset A.type).card * A.localDim :=
    Finset.card_biUnion_le_card_mul
      (Finset.univ : Finset A.type) A.localBasis A.localDim
      (by
        intro τ _hτ
        exact A.localBasis_card_le τ)
  have htype_card :
      (Finset.univ : Finset A.type).card = Fintype.card A.type :=
    Finset.card_univ
  simpa [zeroProfileQuotientTypeGlobalBasis, htype_card] using
    hcard.trans A.symmetricProfileBudget_le

/-- The compressed projected type span represented by the quotient alphabet. -/
noncomputable def zeroProfileQuotientTypeCompressedSpan {n typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget) :
    Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
  Submodule.span ℚ
    (↑(zeroProfileQuotientTypeGlobalBasis A) :
      Set (MvPolynomial (Fin n) ℚ))

/-- A single quotient type space is contained in the global quotient type
span. -/
theorem zeroProfileQuotientTypeSpace_le_compressedSpan {n typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget)
    (τ : A.type) :
    zeroProfileQuotientTypeSpace A τ ≤
      zeroProfileQuotientTypeCompressedSpan A := by
  classical
  letI : Fintype A.type := A.typeFintype
  unfold zeroProfileQuotientTypeSpace zeroProfileQuotientTypeCompressedSpan
  apply Submodule.span_mono
  intro q hq
  change q ∈ zeroProfileQuotientTypeGlobalBasis A
  unfold zeroProfileQuotientTypeGlobalBasis
  exact Finset.mem_biUnion.mpr ⟨τ, Finset.mem_univ τ, hq⟩

/-- Projected zero-profile shifted rows. -/
noncomputable def zeroProfileProjectedShiftImageSet {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ) :
    Set (MvPolynomial (Fin n) ℚ) :=
  project '' zeroProfileShiftImageSet κ factors

/-- Budgeted common-span form for projected zero-profile shifted rows. -/
def ZeroProfileProjectedCommonSpanWithBudget {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ)
    (budget : ℕ) : Prop :=
  ∃ G : Finset (MvPolynomial (Fin n) ℚ),
    G.card ≤ budget ∧
    zeroProfileProjectedShiftImageSet κ factors project ⊆
      Submodule.span ℚ (↑G : Set (MvPolynomial (Fin n) ℚ))

/-- Generator-to-type map after projection. -/
structure ZeroProfileProjectedGeneratorTypeMap {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ) where
  rowType :
    ∀ (S : List (Fin n)), S.length ≤ κ →
      ∀ shift : MvPolynomial (Fin n) ℚ, shift.vars ⊆ S.toFinset →
        A.type
  projected_row_mem_typeSpace :
    ∀ (S : List (Fin n)) (hS : S.length ≤ κ)
      (shift : MvPolynomial (Fin n) ℚ) (hshift : shift.vars ⊆ S.toFinset),
        project (mlProj (shift * Finset.univ.prod factors)) ∈
          zeroProfileQuotientTypeSpace A (rowType S hS shift hshift)

/-- A projected generator type map puts every projected row in the global
quotient type span. -/
theorem zeroProfileProjectedGeneratorTypeMap_row_mem_compressedSpan
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ)
    (hmap : ZeroProfileProjectedGeneratorTypeMap κ factors A project)
    (S : List (Fin n)) (hS : S.length ≤ κ)
    (shift : MvPolynomial (Fin n) ℚ) (hshift : shift.vars ⊆ S.toFinset) :
    project (mlProj (shift * Finset.univ.prod factors)) ∈
      zeroProfileQuotientTypeCompressedSpan A :=
  (zeroProfileQuotientTypeSpace_le_compressedSpan A
    (hmap.rowType S hS shift hshift))
    (hmap.projected_row_mem_typeSpace S hS shift hshift)

/-- Projected shifted rows are contained in the quotient type span. -/
theorem zeroProfileProjectedShiftImageSet_subset_quotientTypeCompressedSpan
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ)
    (hmap : ZeroProfileProjectedGeneratorTypeMap κ factors A project) :
    zeroProfileProjectedShiftImageSet κ factors project ⊆
      zeroProfileQuotientTypeCompressedSpan A := by
  intro q hq
  rcases hq with ⟨row, hrow, rfl⟩
  simp only [zeroProfileShiftImageSet, Set.mem_iUnion,
    Set.mem_singleton_iff] at hrow
  rcases hrow with ⟨S, hS, shift, hshift, row_eq⟩
  rw [row_eq]
  exact zeroProfileProjectedGeneratorTypeMap_row_mem_compressedSpan
    κ factors A project hmap S hS shift hshift

/-- A projected local type map gives a budgeted common span for the projected
zero-profile rows. -/
theorem zeroProfileProjectedCommonSpanWithBudget_of_projectedTypeMap
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ)
    (hmap : ZeroProfileProjectedGeneratorTypeMap κ factors A project) :
    ZeroProfileProjectedCommonSpanWithBudget κ factors project typeBudget := by
  classical
  refine ⟨zeroProfileQuotientTypeGlobalBasis A,
    zeroProfileQuotientTypeGlobalBasis_card_le_typeBudget A, ?_⟩
  simpa [zeroProfileQuotientTypeCompressedSpan] using
    zeroProfileProjectedShiftImageSet_subset_quotientTypeCompressedSpan
      κ factors A project hmap

/-- Full projected/quotient zero-profile type-space certificate.  The
projection is required to be idempotent and to kill singleton shifts; row
factorization is required only after projection. -/
structure ZeroProfileQuotientTypeSpaceCertificate {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (typeBudget : ℕ) where
  project : MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ
  project_idempotent : project.comp project = project
  killsSingleton : ZeroProfileProjectionKillsSingletonShifts factors project
  alphabet : ZeroProfileQuotientTypeAlphabet n typeBudget
  typeMap :
    ZeroProfileProjectedGeneratorTypeMap κ factors alphabet project

/-- The certificate's kernel contains the singleton-shift obstruction. -/
theorem zeroProfileQuotientTypeSpaceCertificate_singletonShiftSubspace_le_ker
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {typeBudget : ℕ}
    (cert :
      ZeroProfileQuotientTypeSpaceCertificate κ factors typeBudget) :
    zeroProfileSingletonShiftSubspace factors ≤ LinearMap.ker cert.project :=
  (zeroProfileProjectionKillsSingletonShifts_iff_singletonShiftSubspace_le_ker
    factors cert.project).mp cert.killsSingleton

/-- The certificate gives the projected common-span obligation. -/
theorem zeroProfileProjectedCommonSpanWithBudget_of_quotientTypeSpaceCertificate
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {typeBudget : ℕ}
    (cert :
      ZeroProfileQuotientTypeSpaceCertificate κ factors typeBudget) :
    ZeroProfileProjectedCommonSpanWithBudget
      κ factors cert.project typeBudget :=
  zeroProfileProjectedCommonSpanWithBudget_of_projectedTypeMap
    κ factors cert.alphabet cert.project cert.typeMap

/-! ## Separately paid projection residual -/

/-- A paid residual span for the rows removed by the projection.  This is the
honest way to turn a projected quotient certificate back into an unprojected
common-span statement. -/
def ZeroProfileProjectionResidualClosureWithBudget {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ)
    (residualBudget : ℕ) : Prop :=
  ∃ R : Finset (MvPolynomial (Fin n) ℚ),
    R.card ≤ residualBudget ∧
    ∀ q ∈ zeroProfileShiftImageSet κ factors,
      q - project q ∈
        Submodule.span ℚ (↑R : Set (MvPolynomial (Fin n) ℚ))

/-- Projected common span plus a paid residual span gives an unprojected
common span with the summed budget. -/
theorem zeroProfileCompressedSpanCommonSpanWithBudget_of_projectedCommonSpan_residualClosure
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ)
    {projectedBudget residualBudget budget : ℕ}
    (hprojected :
      ZeroProfileProjectedCommonSpanWithBudget
        κ factors project projectedBudget)
    (hresidual :
      ZeroProfileProjectionResidualClosureWithBudget
        κ factors project residualBudget)
    (hbudget : projectedBudget + residualBudget ≤ budget) :
    ZeroProfileCompressedSpanCommonSpanWithBudget κ factors budget := by
  classical
  rcases hprojected with ⟨G, hG_card, hG_span⟩
  rcases hresidual with ⟨R, hR_card, hR_span⟩
  refine ⟨G ∪ R, ?_, ?_⟩
  · calc
      (G ∪ R).card ≤ G.card + R.card := Finset.card_union_le G R
      _ ≤ projectedBudget + residualBudget :=
          Nat.add_le_add hG_card hR_card
      _ ≤ budget := hbudget
  · intro q hq
    have hprojected_mem :
        project q ∈
          Submodule.span ℚ
            (↑G : Set (MvPolynomial (Fin n) ℚ)) := by
      exact hG_span ⟨q, hq, rfl⟩
    have hresidual_mem :
        q - project q ∈
          Submodule.span ℚ
            (↑R : Set (MvPolynomial (Fin n) ℚ)) :=
      hR_span q hq
    have hG_subset :
        (↑G : Set (MvPolynomial (Fin n) ℚ)) ⊆
          (↑(G ∪ R) : Set (MvPolynomial (Fin n) ℚ)) := by
      intro x hx
      exact Finset.mem_union.mpr (Or.inl hx)
    have hR_subset :
        (↑R : Set (MvPolynomial (Fin n) ℚ)) ⊆
          (↑(G ∪ R) : Set (MvPolynomial (Fin n) ℚ)) := by
      intro x hx
      exact Finset.mem_union.mpr (Or.inr hx)
    have hprojected_union :
        project q ∈
          Submodule.span ℚ
            (↑(G ∪ R) : Set (MvPolynomial (Fin n) ℚ)) :=
      (Submodule.span_mono hG_subset) hprojected_mem
    have hresidual_union :
        q - project q ∈
          Submodule.span ℚ
            (↑(G ∪ R) : Set (MvPolynomial (Fin n) ℚ)) :=
      (Submodule.span_mono hR_subset) hresidual_mem
    have hsum :
        project q + (q - project q) ∈
          Submodule.span ℚ
            (↑(G ∪ R) : Set (MvPolynomial (Fin n) ℚ)) :=
      Submodule.add_mem _ hprojected_union hresidual_union
    simpa [sub_eq_add_neg, add_assoc, add_comm, add_left_comm] using hsum

/-- A quotient/type-space certificate plus a paid residual span gives an
unprojected common span. -/
theorem zeroProfileCompressedSpanCommonSpanWithBudget_of_quotientTypeSpaceCertificate_residualClosure
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {typeBudget residualBudget budget : ℕ}
    (cert :
      ZeroProfileQuotientTypeSpaceCertificate κ factors typeBudget)
    (hresidual :
      ZeroProfileProjectionResidualClosureWithBudget
        κ factors cert.project residualBudget)
    (hbudget : typeBudget + residualBudget ≤ budget) :
    ZeroProfileCompressedSpanCommonSpanWithBudget κ factors budget :=
  zeroProfileCompressedSpanCommonSpanWithBudget_of_projectedCommonSpan_residualClosure
    κ factors cert.project
    (zeroProfileProjectedCommonSpanWithBudget_of_quotientTypeSpaceCertificate
      κ factors cert)
    hresidual hbudget

/-! ## Cook-Levin wrappers -/

/-- Cook-Levin quotient/projected zero-profile type-space obligation with an
explicit projected type budget. -/
def CookLevinZeroProfileQuotientTypeNormalFormObligation
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (typeBudget : ℕ) : Prop :=
  Nonempty
    (ZeroProfileQuotientTypeSpaceCertificate (Nat.log 2 n)
      (fun i => (cookLevinFactorList M n hn htb hns).get i)
      typeBudget)

/-- Cook-Levin projected zero-profile common-span obligation.  It remembers
that the chosen map is an idempotent projection and that its kernel contains
the singleton-shift obstruction. -/
def CookLevinZeroProfileProjectedCommonSpanObligation
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (typeBudget : ℕ) : Prop :=
  ∃ project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ,
    project.comp project = project ∧
      ZeroProfileProjectionKillsSingletonShifts
        (fun i => (cookLevinFactorList M n hn htb hns).get i)
        project ∧
      ZeroProfileProjectedCommonSpanWithBudget (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn htb hns).get i)
        project typeBudget

/-- Cook-Levin residual closure for a chosen quotient projection. -/
def CookLevinZeroProfileProjectionResidualClosureWithBudget
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ)
    (residualBudget : ℕ) : Prop :=
  ZeroProfileProjectionResidualClosureWithBudget (Nat.log 2 n)
    (fun i => (cookLevinFactorList M n hn htb hns).get i)
    project residualBudget

/-- A Cook-Levin quotient type certificate closes the projected zero-profile
common-span obligation. -/
theorem cookLevinZeroProfileProjectedCommonSpanWithBudget_of_quotientTypeCertificate
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    {typeBudget : ℕ}
    (cert :
      ZeroProfileQuotientTypeSpaceCertificate (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn htb hns).get i)
        typeBudget) :
    ZeroProfileProjectedCommonSpanWithBudget (Nat.log 2 n)
      (fun i => (cookLevinFactorList M n hn htb hns).get i)
      cert.project typeBudget :=
  zeroProfileProjectedCommonSpanWithBudget_of_quotientTypeSpaceCertificate
    (Nat.log 2 n)
    (fun i => (cookLevinFactorList M n hn htb hns).get i)
    cert

/-- The existential quotient/type-space obligation closes the named projected
zero-profile common-span obligation. -/
theorem cookLevinZeroProfileProjectedCommonSpanObligation_of_quotientTypeNormalFormObligation
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    {typeBudget : ℕ}
    (hquot :
      CookLevinZeroProfileQuotientTypeNormalFormObligation
        M n hn htb hns typeBudget) :
    CookLevinZeroProfileProjectedCommonSpanObligation
      M n hn htb hns typeBudget := by
  rcases hquot with ⟨cert⟩
  exact
    ⟨cert.project, cert.project_idempotent, cert.killsSingleton,
      cookLevinZeroProfileProjectedCommonSpanWithBudget_of_quotientTypeCertificate
        M n hn htb hns cert⟩

/-- Cook-Levin non-scalar zero-profile closure from a quotient type
certificate plus an explicitly paid residual span. -/
theorem cookLevinZeroProfileNonScalarClosureWithBudget_of_quotientTypeCertificate_residualClosure
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    {typeBudget residualBudget budget : ℕ}
    (cert :
      ZeroProfileQuotientTypeSpaceCertificate (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn htb hns).get i)
        typeBudget)
    (hresidual :
      CookLevinZeroProfileProjectionResidualClosureWithBudget
        M n hn htb hns cert.project residualBudget)
    (hbudget : typeBudget + residualBudget ≤ budget) :
    CookLevinZeroProfileNonScalarClosureWithBudget
      M n hn htb hns budget := by
  simpa [CookLevinZeroProfileNonScalarClosureWithBudget,
    CookLevinZeroProfileProjectionResidualClosureWithBudget,
    ZeroProfileCompressedSpanCommonSpanWithBudget] using
    (zeroProfileCompressedSpanCommonSpanWithBudget_of_quotientTypeSpaceCertificate_residualClosure
      (Nat.log 2 n)
      (fun i => (cookLevinFactorList M n hn htb hns).get i)
      cert hresidual hbudget)

/-- If the projected type budget plus the separately paid residual budget fits
inside the profile budget, the existing zero-profile common-span bridge
closes. -/
theorem cookLevinZeroHistogramShiftCommonSpan_of_quotientTypeCertificate_residualClosure
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    {typeBudget residualBudget : ℕ}
    (cert :
      ZeroProfileQuotientTypeSpaceCertificate (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn htb hns).get i)
        typeBudget)
    (hresidual :
      CookLevinZeroProfileProjectionResidualClosureWithBudget
        M n hn htb hns cert.project residualBudget)
    (hbudget :
      typeBudget + residualBudget ≤ withinProfileBound (Nat.log 2 n)) :
    CookLevinZeroHistogramShiftCommonSpan M n hn htb hns :=
  cookLevinZeroHistogramShiftCommonSpan_of_nonScalarClosureWithBudget
    M n hn htb hns
    (cookLevinZeroProfileNonScalarClosureWithBudget_of_quotientTypeCertificate_residualClosure
      M n hn htb hns
      (budget := typeBudget + residualBudget)
      cert hresidual le_rfl)
    hbudget

/-! ## Axiom audit anchors -/

#print axioms zeroProfileProjectionKillsSingletonShifts_iff_singletonShiftSubspace_le_ker
#print axioms zeroProfileQuotientTypeSpace_finrank_le
#print axioms zeroProfileQuotientTypeGlobalBasis_card_le_typeBudget
#print axioms zeroProfileQuotientTypeSpace_le_compressedSpan
#print axioms zeroProfileProjectedShiftImageSet_subset_quotientTypeCompressedSpan
#print axioms zeroProfileProjectedCommonSpanWithBudget_of_projectedTypeMap
#print axioms zeroProfileQuotientTypeSpaceCertificate_singletonShiftSubspace_le_ker
#print axioms zeroProfileProjectedCommonSpanWithBudget_of_quotientTypeSpaceCertificate
#print axioms zeroProfileCompressedSpanCommonSpanWithBudget_of_projectedCommonSpan_residualClosure
#print axioms zeroProfileCompressedSpanCommonSpanWithBudget_of_quotientTypeSpaceCertificate_residualClosure
#print axioms cookLevinZeroProfileProjectedCommonSpanWithBudget_of_quotientTypeCertificate
#print axioms cookLevinZeroProfileProjectedCommonSpanObligation_of_quotientTypeNormalFormObligation
#print axioms cookLevinZeroProfileNonScalarClosureWithBudget_of_quotientTypeCertificate_residualClosure
#print axioms cookLevinZeroHistogramShiftCommonSpan_of_quotientTypeCertificate_residualClosure

end PathB
end DeepMath
end Paper93
end PallLean

namespace PallLean.Paper93.Paper283

open TuringMachine
open SymmetricPowerBound
open WithinProfileBound
open PallLean.Paper93.DeepMath.PathB

attribute [local instance] Classical.dec

/-- P-window wrapper from live-profile cases plus the projected/quotient
zero-profile replacement.  The zero-profile side is supplied by a quotient
type certificate and a separately paid residual span. -/
noncomputable def routeBRicherGauge_unprojectedPWindowFiniteSpanCover_of_liveProfileCases_zeroQuotientTypeCertificate
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (hn4 : n >= 4)
    {typeBudget residualBudget : Nat}
    (cert :
      ZeroProfileQuotientTypeSpaceCertificate (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn2 htb hns).get i)
        typeBudget)
    (hresidual :
      CookLevinZeroProfileProjectionResidualClosureWithBudget
        M n hn2 htb hns cert.project residualBudget)
    (hbudget :
      typeBudget + residualBudget <= withinProfileBound (Nat.log 2 n))
    (hlive :
      CookLevinAllBoundedProfileCommonSpanLiveProfileCases
        M n hn2 htb hns) :
    RouteBRicherGaugeUnprojectedPWindowFiniteSpanCover M n hn2 htb hns :=
  routeBRicherGauge_unprojectedPWindowFiniteSpanCover_of_liveProfileCases
    M n hn2 htb hns hn4
    (cookLevinZeroHistogramShiftCommonSpan_of_quotientTypeCertificate_residualClosure
      M n hn2 htb hns cert hresidual hbudget)
    hlive

/-- Active-profile P-window wrapper from the projected/quotient zero-profile
replacement. -/
noncomputable def routeBRicherGauge_unprojectedPWindowFiniteSpanCover_of_activeTypeCaseBlockers_zeroQuotientTypeCertificate
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (hn4 : n >= 4)
    {typeBudget residualBudget : Nat}
    (cert :
      ZeroProfileQuotientTypeSpaceCertificate (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn2 htb hns).get i)
        typeBudget)
    (hresidual :
      CookLevinZeroProfileProjectionResidualClosureWithBudget
        M n hn2 htb hns cert.project residualBudget)
    (hbudget :
      typeBudget + residualBudget <= withinProfileBound (Nat.log 2 n))
    (hactive :
      CookLevinActiveProfileTypeCaseBlockers M n hn2 htb hns) :
    RouteBRicherGaugeUnprojectedPWindowFiniteSpanCover M n hn2 htb hns :=
  routeBRicherGauge_unprojectedPWindowFiniteSpanCover_of_activeTypeCaseBlockers_and_zeroProfileCommonSpan
    M n hn2 htb hns hn4
    (cookLevinZeroHistogramShiftCommonSpan_of_quotientTypeCertificate_residualClosure
      M n hn2 htb hns cert hresidual hbudget)
    hactive

/-! ## Axiom audit anchors -/

#print axioms routeBRicherGauge_unprojectedPWindowFiniteSpanCover_of_liveProfileCases_zeroQuotientTypeCertificate
#print axioms routeBRicherGauge_unprojectedPWindowFiniteSpanCover_of_activeTypeCaseBlockers_zeroQuotientTypeCertificate

end PallLean.Paper93.Paper283
