import PallLean.Paper93.DeepMath.PathB.ZeroProfileNonScalarClosure
import Mathlib.LinearAlgebra.Basis.VectorSpace
import Mathlib.LinearAlgebra.Projection

/-!
# Zero-profile compressed-span frontier

This file separates the actual zero-profile common-span problem from the
currently too-large support-cardinality enumeration.

The support basis already proves finite-dimensionality of the shifted
base-product span.  The remaining paper-faithful target is therefore exactly
the dimension bound on that compressed span, not the cardinality of the
monomial support enumeration.
-/

namespace PallLean
namespace Paper93
namespace DeepMath
namespace PathB

open MvPolynomial SymmetricPowerBound TuringMachine PaperFaithfulSeparation
open WithinProfileBound MultilinearSPDP SPDP
open scoped BigOperators

attribute [local instance] Classical.dec

/-- The actual compressed span of the all-zero profile shifted base-product
rows. -/
noncomputable def zeroProfileCompressedShiftSpan {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
  Submodule.span ℚ (zeroProfileShiftImageSet κ factors)

/-- Budgeted common-span form for the compressed zero-profile shifted image. -/
def ZeroProfileCompressedSpanCommonSpanWithBudget {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (budget : ℕ) : Prop :=
  ∃ G : Finset (MvPolynomial (Fin n) ℚ),
    G.card ≤ budget ∧
    zeroProfileShiftImageSet κ factors ⊆
      Submodule.span ℚ (↑G : Set (MvPolynomial (Fin n) ℚ))

/-- Exact finrank condition for the compressed zero-profile shifted-image
span.  The finite-dimensionality clause is included for generic use; for the
actual support-basis construction it is proved below. -/
def ZeroProfileCompressedSpanFinrankCondition {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (budget : ℕ) : Prop :=
  Module.Finite ℚ ↥(zeroProfileCompressedShiftSpan κ factors) ∧
    Module.finrank ℚ ↥(zeroProfileCompressedShiftSpan κ factors) ≤ budget

/-- The support-basis containment proves finite-dimensionality of the exact
compressed shifted-image span. -/
theorem zeroProfileCompressedShiftSpan_finite {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    Module.Finite ℚ ↥(zeroProfileCompressedShiftSpan κ factors) := by
  classical
  have hle :
      zeroProfileCompressedShiftSpan κ factors ≤
        Submodule.span ℚ
          (↑(zeroProfileShiftSupportBasis κ factors) :
            Set (MvPolynomial (Fin n) ℚ)) :=
    zeroProfileShiftImageSpan_le_supportBasis_span κ factors
  haveI hfinite_support :
      Module.Finite ℚ
        ↥(Submodule.span ℚ
          (↑(zeroProfileShiftSupportBasis κ factors) :
            Set (MvPolynomial (Fin n) ℚ))) :=
    Module.Finite.span_of_finite ℚ
      (Finset.finite_toSet (zeroProfileShiftSupportBasis κ factors))
  exact Module.Finite.of_injective (Submodule.inclusion hle)
    (Submodule.inclusion_injective hle)

/-- The exact compressed shifted-image span has dimension no larger than the
existing support-basis cardinality.  This records precisely where the old
support-card route loses information. -/
theorem zeroProfileCompressedShiftSpan_finrank_le_supportBasis_card {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    Module.finrank ℚ ↥(zeroProfileCompressedShiftSpan κ factors) ≤
      (zeroProfileShiftSupportBasis κ factors).card := by
  classical
  have hle :
      zeroProfileCompressedShiftSpan κ factors ≤
        Submodule.span ℚ
          (↑(zeroProfileShiftSupportBasis κ factors) :
            Set (MvPolynomial (Fin n) ℚ)) :=
    zeroProfileShiftImageSpan_le_supportBasis_span κ factors
  haveI hfinite_compressed :
      Module.Finite ℚ ↥(zeroProfileCompressedShiftSpan κ factors) :=
    zeroProfileCompressedShiftSpan_finite κ factors
  haveI hfinite_support :
      Module.Finite ℚ
        ↥(Submodule.span ℚ
          (↑(zeroProfileShiftSupportBasis κ factors) :
            Set (MvPolynomial (Fin n) ℚ))) :=
    Module.Finite.span_of_finite ℚ
      (Finset.finite_toSet (zeroProfileShiftSupportBasis κ factors))
  calc
    Module.finrank ℚ ↥(zeroProfileCompressedShiftSpan κ factors)
        ≤ Module.finrank ℚ
            ↥(Submodule.span ℚ
              (↑(zeroProfileShiftSupportBasis κ factors) :
                Set (MvPolynomial (Fin n) ℚ))) :=
          Submodule.finrank_mono hle
    _ ≤ (zeroProfileShiftSupportBasis κ factors).card :=
          finrank_span_finset_le_card (zeroProfileShiftSupportBasis κ factors)

/-! ## Monomial-shift compression -/

/-- Projected zero-profile rows generated by multilinear shift-support
monomials on a fixed variable set.  This keeps the base product intact and
therefore avoids the larger `T ∪ baseVars` monomial expansion. -/
noncomputable def zeroProfileShiftMonomialImagesOn {n : ℕ}
    (V : Finset (Fin n))
    (p : MvPolynomial (Fin n) ℚ) :
    Finset (MvPolynomial (Fin n) ℚ) :=
  V.powerset.image
    (fun T => mlProj (T.prod (fun i => MvPolynomial.X i) * p))

/-- Finite projected rows generated by admissible multilinear shift-support
monomials.  The counted object is just the family of shift supports
`T.card ≤ κ`, not the full support basis of all monomials on
`T ∪ baseVars`. -/
noncomputable def zeroProfileShiftMonomialImageBasis {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    Finset (MvPolynomial (Fin n) ℚ) :=
  (zeroProfileShiftSupportSetFamily n κ).image
    (fun T => mlProj (T.prod (fun i => MvPolynomial.X i) *
      Finset.univ.prod factors))

/-- The monomial-shift image basis is counted by admissible shift supports. -/
theorem zeroProfileShiftMonomialImageBasis_card_le_supportSetCount {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    (zeroProfileShiftMonomialImageBasis κ factors).card ≤
      zeroProfileShiftSupportSetCount n κ := by
  classical
  unfold zeroProfileShiftMonomialImageBasis zeroProfileShiftSupportSetCount
  exact Finset.card_image_le

/-- A non-multilinear monomial shift contributes nothing after the final
multilinear projection, even after multiplication by an arbitrary base
polynomial. -/
theorem mlProj_monomial_mul_eq_zero_of_not_multilinear {n : ℕ}
    (α : Fin n →₀ ℕ)
    (c : ℚ)
    (p : MvPolynomial (Fin n) ℚ)
    (hα : ¬ Finsupp.IsMultilinear α) :
    mlProj (MvPolynomial.monomial α c * p) = 0 := by
  classical
  ext γ
  rw [WithinProfileBound.coeff_mlProj]
  by_cases hγ : Finsupp.IsMultilinear γ
  · rw [if_pos hγ, MvPolynomial.coeff_mul]
    apply Finset.sum_eq_zero
    rintro ⟨β, δ⟩ hβδ
    simp only [Finset.mem_antidiagonal] at hβδ
    rw [MvPolynomial.coeff_monomial]
    by_cases hαβ : α = β
    · subst β
      exfalso
      apply hα
      intro i
      have hγi := hγ i
      rw [← hβδ] at hγi
      simp only [Finsupp.coe_add, Pi.add_apply] at hγi
      omega
    · rw [if_neg hαβ]
      simp
  · rw [if_neg hγ]
    simp

/-- Every shifted base-product row with `shift.vars ⊆ V` lies in the span of
the projected rows obtained from multilinear monomial shifts supported on
`V`. -/
theorem mlProj_mul_mem_span_shiftMonomialImagesOn_of_vars_subset {n : ℕ}
    (V : Finset (Fin n))
    (shift p : MvPolynomial (Fin n) ℚ)
    (hshift : shift.vars ⊆ V) :
    mlProj (shift * p) ∈
      Submodule.span ℚ
        (↑(zeroProfileShiftMonomialImagesOn V p) :
          Set (MvPolynomial (Fin n) ℚ)) := by
  classical
  rw [show shift =
      ∑ α ∈ shift.support, MvPolynomial.monomial α
        (MvPolynomial.coeff α shift) from shift.as_sum, Finset.sum_mul]
  change (mlProjLinearMap (Fin n) ℚ)
      (∑ α ∈ shift.support,
        MvPolynomial.monomial α (MvPolynomial.coeff α shift) * p) ∈
      Submodule.span ℚ
        (↑(zeroProfileShiftMonomialImagesOn V p) :
          Set (MvPolynomial (Fin n) ℚ))
  rw [map_sum]
  apply Submodule.sum_mem
  intro α hαmem
  by_cases hαml : Finsupp.IsMultilinear α
  · have hα_support_subset : α.support ⊆ V := by
      intro i hi
      apply hshift
      exact (MvPolynomial.mem_vars i).mpr ⟨α, hαmem, hi⟩
    have hmon_one :
        MvPolynomial.monomial α (1 : ℚ) =
          α.support.prod (fun i => MvPolynomial.X i) := by
      rw [← MvPolynomial.prod_X_pow_eq_monomial]
      apply Finset.prod_congr rfl
      intro i hi
      have hne : α i ≠ 0 := Finsupp.mem_support_iff.mp hi
      have hi_le := hαml i
      have hi_eq : α i = 1 := by omega
      rw [hi_eq, pow_one]
    have hmon :
        MvPolynomial.monomial α (MvPolynomial.coeff α shift) =
          MvPolynomial.coeff α shift •
            α.support.prod (fun i => MvPolynomial.X i) := by
      rw [← hmon_one, MvPolynomial.smul_monomial, smul_eq_mul, mul_one]
    have himage :
        mlProj (α.support.prod (fun i => MvPolynomial.X i) * p) ∈
          Submodule.span ℚ
            (↑(zeroProfileShiftMonomialImagesOn V p) :
              Set (MvPolynomial (Fin n) ℚ)) := by
      apply Submodule.subset_span
      change mlProj (α.support.prod (fun i => MvPolynomial.X i) * p) ∈
        zeroProfileShiftMonomialImagesOn V p
      unfold zeroProfileShiftMonomialImagesOn
      exact Finset.mem_image.mpr
        ⟨α.support, Finset.mem_powerset.mpr hα_support_subset, rfl⟩
    rw [hmon, smul_mul_assoc]
    change mlProj
        (MvPolynomial.coeff α shift •
          (α.support.prod (fun i => MvPolynomial.X i) * p)) ∈
        Submodule.span ℚ
          (↑(zeroProfileShiftMonomialImagesOn V p) :
            Set (MvPolynomial (Fin n) ℚ))
    rw [mlProj_smul]
    exact Submodule.smul_mem _ _ himage
  · change mlProj
        (MvPolynomial.monomial α (MvPolynomial.coeff α shift) * p) ∈
        Submodule.span ℚ
          (↑(zeroProfileShiftMonomialImagesOn V p) :
            Set (MvPolynomial (Fin n) ℚ))
    rw [mlProj_monomial_mul_eq_zero_of_not_multilinear
      α (MvPolynomial.coeff α shift) p hαml]
    exact Submodule.zero_mem _

/-- The exact zero-profile shifted image is spanned by projected base-product
rows indexed only by admissible multilinear shift supports. -/
theorem zeroProfileShiftImageSet_subset_monomialImageBasis_span {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    zeroProfileShiftImageSet κ factors ⊆
      Submodule.span ℚ
        (↑(zeroProfileShiftMonomialImageBasis κ factors) :
          Set (MvPolynomial (Fin n) ℚ)) := by
  classical
  intro q hq
  simp only [zeroProfileShiftImageSet, Set.mem_iUnion,
    Set.mem_singleton_iff] at hq
  rcases hq with ⟨S, hS, shift, hshift, hq_eq⟩
  rw [hq_eq]
  have hS_card : S.toFinset.card ≤ κ :=
    (List.toFinset_card_le S).trans hS
  have hlocal :
      mlProj (shift * Finset.univ.prod factors) ∈
        Submodule.span ℚ
          (↑(zeroProfileShiftMonomialImagesOn S.toFinset
              (Finset.univ.prod factors)) :
            Set (MvPolynomial (Fin n) ℚ)) :=
    mlProj_mul_mem_span_shiftMonomialImagesOn_of_vars_subset
      S.toFinset shift (Finset.univ.prod factors) hshift
  have hlocal_subset :
      (↑(zeroProfileShiftMonomialImagesOn S.toFinset
          (Finset.univ.prod factors)) :
        Set (MvPolynomial (Fin n) ℚ)) ⊆
      (↑(zeroProfileShiftMonomialImageBasis κ factors) :
        Set (MvPolynomial (Fin n) ℚ)) := by
    intro q hq
    change q ∈ zeroProfileShiftMonomialImageBasis κ factors
    change q ∈ zeroProfileShiftMonomialImagesOn S.toFinset
      (Finset.univ.prod factors) at hq
    unfold zeroProfileShiftMonomialImagesOn at hq
    rcases Finset.mem_image.mp hq with ⟨T, hT, rfl⟩
    unfold zeroProfileShiftMonomialImageBasis
    refine Finset.mem_image.mpr ⟨T, ?_, rfl⟩
    have hT_subset : T ⊆ S.toFinset := Finset.mem_powerset.mp hT
    exact Finset.mem_filter.mpr
      ⟨Finset.mem_powerset.mpr (Finset.subset_univ T),
        (Finset.card_le_card hT_subset).trans hS_card⟩
  exact (Submodule.span_mono hlocal_subset) hlocal

/-- Every monomial-shift basis row is an actual zero-profile shifted row. -/
theorem zeroProfileShiftMonomialImageBasis_subset_shiftImageSet {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    (↑(zeroProfileShiftMonomialImageBasis κ factors) :
      Set (MvPolynomial (Fin n) ℚ)) ⊆
      zeroProfileShiftImageSet κ factors := by
  classical
  intro q hq
  change q ∈ zeroProfileShiftMonomialImageBasis κ factors at hq
  unfold zeroProfileShiftMonomialImageBasis at hq
  rcases Finset.mem_image.mp hq with ⟨T, hT, rfl⟩
  have hT_card : T.card ≤ κ := (Finset.mem_filter.mp hT).2
  have hvars :
      (T.prod (fun i => (MvPolynomial.X i :
        MvPolynomial (Fin n) ℚ))).vars ⊆ T := by
    intro x hx
    have hx_union := MvPolynomial.vars_prod
      (fun i => (MvPolynomial.X i : MvPolynomial (Fin n) ℚ)) hx
    simpa [MvPolynomial.vars_X] using hx_union
  simp only [zeroProfileShiftImageSet, Set.mem_iUnion,
    Set.mem_singleton_iff]
  refine ⟨T.toList, ?_, T.prod (fun i => MvPolynomial.X i), ?_, rfl⟩
  · rw [Finset.length_toList]
    exact hT_card
  · simpa [Finset.toList_toFinset] using hvars

/-- Span-level form of the monomial-shift compression. -/
theorem zeroProfileShiftImageSpan_le_monomialImageBasis_span {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    zeroProfileCompressedShiftSpan κ factors ≤
      Submodule.span ℚ
        (↑(zeroProfileShiftMonomialImageBasis κ factors) :
          Set (MvPolynomial (Fin n) ℚ)) := by
  exact Submodule.span_le.mpr
    (zeroProfileShiftImageSet_subset_monomialImageBasis_span κ factors)

/-- Exact span identity: the zero-profile compressed shifted-image span is the
span of the projected base-product rows indexed by admissible multilinear
shift supports. -/
theorem zeroProfileShiftImageSpan_eq_monomialImageBasis_span {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    zeroProfileCompressedShiftSpan κ factors =
      Submodule.span ℚ
        (↑(zeroProfileShiftMonomialImageBasis κ factors) :
          Set (MvPolynomial (Fin n) ℚ)) := by
  apply le_antisymm
  · exact zeroProfileShiftImageSpan_le_monomialImageBasis_span κ factors
  · exact Submodule.span_mono
      (zeroProfileShiftMonomialImageBasis_subset_shiftImageSet κ factors)

/-- The compressed zero-profile shifted span has finrank bounded by the
number of admissible shift supports.  This is the sharper counted object left
by monomial-shift compression. -/
theorem zeroProfileCompressedShiftSpan_finrank_le_shiftSupportSetCount
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    Module.finrank ℚ ↥(zeroProfileCompressedShiftSpan κ factors) ≤
      zeroProfileShiftSupportSetCount n κ := by
  classical
  have hle :
      zeroProfileCompressedShiftSpan κ factors ≤
        Submodule.span ℚ
          (↑(zeroProfileShiftMonomialImageBasis κ factors) :
            Set (MvPolynomial (Fin n) ℚ)) :=
    zeroProfileShiftImageSpan_le_monomialImageBasis_span κ factors
  haveI hfinite_compressed :
      Module.Finite ℚ ↥(zeroProfileCompressedShiftSpan κ factors) :=
    zeroProfileCompressedShiftSpan_finite κ factors
  haveI hfinite_monomial :
      Module.Finite ℚ
        ↥(Submodule.span ℚ
          (↑(zeroProfileShiftMonomialImageBasis κ factors) :
            Set (MvPolynomial (Fin n) ℚ))) :=
    Module.Finite.span_of_finite ℚ
      (Finset.finite_toSet (zeroProfileShiftMonomialImageBasis κ factors))
  calc
    Module.finrank ℚ ↥(zeroProfileCompressedShiftSpan κ factors)
        ≤ Module.finrank ℚ
            ↥(Submodule.span ℚ
              (↑(zeroProfileShiftMonomialImageBasis κ factors) :
                Set (MvPolynomial (Fin n) ℚ))) :=
          Submodule.finrank_mono hle
    _ ≤ (zeroProfileShiftMonomialImageBasis κ factors).card :=
          finrank_span_finset_le_card
            (zeroProfileShiftMonomialImageBasis κ factors)
    _ ≤ zeroProfileShiftSupportSetCount n κ :=
          zeroProfileShiftMonomialImageBasis_card_le_supportSetCount κ factors

/-- The smaller combinatorial side condition isolated by monomial-shift
compression: the admissible shift-support count itself is within the
profile budget. -/
def ZeroProfileShiftSupportCountSideCondition (n κ : ℕ) : Prop :=
  zeroProfileShiftSupportSetCount n κ ≤ withinProfileBound κ

/-- Any shift-support count budget must already pay for the singleton shift
supports, hence for the ambient variable count. -/
theorem ambient_le_withinProfileBound_of_zeroProfileShiftSupportCountSideCondition
    (n κ : ℕ)
    (hκ : 1 ≤ κ)
    (hcount : ZeroProfileShiftSupportCountSideCondition n κ) :
    n ≤ withinProfileBound κ :=
  (zeroProfileShiftSupportSetCount_ge_ambient_of_one_le n κ hκ).trans hcount

/-- Therefore the shift-support count side condition is impossible whenever the
within-profile budget is smaller than the ambient variable count. -/
theorem not_zeroProfileShiftSupportCountSideCondition_of_withinProfileBound_lt_ambient
    (n κ : ℕ)
    (hκ : 1 ≤ κ)
    (hlt : withinProfileBound κ < n) :
    ¬ ZeroProfileShiftSupportCountSideCondition n κ := by
  intro hcount
  exact (not_le_of_gt hlt)
    (ambient_le_withinProfileBound_of_zeroProfileShiftSupportCountSideCondition
      n κ hκ hcount)

/-- The shift-support count side condition proves the exact compressed-span
finrank condition. -/
theorem zeroProfileCompressedSpanFinrankCondition_of_shiftSupportCountSideCondition
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (hcount : ZeroProfileShiftSupportCountSideCondition n κ) :
    ZeroProfileCompressedSpanFinrankCondition κ factors
      (withinProfileBound κ) := by
  refine ⟨zeroProfileCompressedShiftSpan_finite κ factors, ?_⟩
  exact (zeroProfileCompressedShiftSpan_finrank_le_shiftSupportSetCount
    κ factors).trans hcount

/-! ## Compression certificates -/

/-- A concrete ambient compression separates the zero-profile compressed span
when its kernel has zero intersection with that span.  This is the
paper-faithful linear-algebra target: exhibit a small family of linear
observables that is injective on the actual compressed shifted-image span. -/
def ZeroProfileCompressedSpanKernelSeparated {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {ι : Type}
    (compress :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] (ι → ℚ)) : Prop :=
  ∀ x : ↥(zeroProfileCompressedShiftSpan κ factors), compress x = 0 → x = 0

/-- Kernel-separation is exactly disjointness of the compressed span from the
ambient compression kernel. -/
theorem zeroProfileCompressedSpanKernelSeparated_iff_disjoint_ker {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {ι : Type}
    (compress :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] (ι → ℚ)) :
    ZeroProfileCompressedSpanKernelSeparated κ factors compress ↔
      Disjoint (zeroProfileCompressedShiftSpan κ factors)
        (LinearMap.ker compress) := by
  classical
  constructor
  · intro hsep
    rw [disjoint_iff, Submodule.eq_bot_iff]
    intro p hp
    have hp_zero :
        (⟨p, hp.1⟩ :
          ↥(zeroProfileCompressedShiftSpan κ factors)) = 0 :=
      hsep ⟨p, hp.1⟩ (by
        simpa [LinearMap.mem_ker] using hp.2)
    exact congrArg
      (fun x : ↥(zeroProfileCompressedShiftSpan κ factors) =>
        (x : MvPolynomial (Fin n) ℚ)) hp_zero
  · intro hdisj x hx
    apply Subtype.ext
    have hbot :
        zeroProfileCompressedShiftSpan κ factors ⊓ LinearMap.ker compress =
          ⊥ := disjoint_iff.mp hdisj
    have hxinf :
        (x : MvPolynomial (Fin n) ℚ) ∈
          zeroProfileCompressedShiftSpan κ factors ⊓ LinearMap.ker compress := by
      exact ⟨x.property, by simpa [LinearMap.mem_ker] using hx⟩
    exact (Submodule.eq_bot_iff _).mp hbot (x : MvPolynomial (Fin n) ℚ) hxinf

/-- If a compression with at most `budget` coordinates separates the exact
compressed span, then the sharp compressed-span finrank condition follows.
This avoids using the cardinality of the explicit support enumeration as the
target. -/
theorem zeroProfileCompressedSpanFinrankCondition_of_kernelSeparated
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (budget : ℕ)
    {ι : Type} [Fintype ι]
    (compress :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] (ι → ℚ))
    (hcard : Fintype.card ι ≤ budget)
    (hsep : ZeroProfileCompressedSpanKernelSeparated κ factors compress) :
    ZeroProfileCompressedSpanFinrankCondition κ factors budget := by
  classical
  let U : Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
    zeroProfileCompressedShiftSpan κ factors
  have hfinite : Module.Finite ℚ ↥U :=
    zeroProfileCompressedShiftSpan_finite κ factors
  letI : Module.Finite ℚ ↥U := hfinite
  have hinj : Function.Injective (compress.domRestrict U) := by
    intro x y hxy
    apply sub_eq_zero.mp
    apply hsep
    have hzero : (compress.domRestrict U) (x - y) = 0 := by
      rw [map_sub, hxy, sub_self]
    simpa [LinearMap.domRestrict_apply] using hzero
  refine ⟨hfinite, ?_⟩
  calc
    Module.finrank ℚ ↥(zeroProfileCompressedShiftSpan κ factors)
        = Module.finrank ℚ ↥U := rfl
    _ ≤ Module.finrank ℚ (ι → ℚ) :=
          LinearMap.finrank_le_finrank_of_injective
            (f := compress.domRestrict U) hinj
    _ = Fintype.card ι := Module.finrank_fintype_fun_eq_card ℚ
    _ ≤ budget := hcard

/-- Disjoint-kernel form of the compression certificate. -/
theorem zeroProfileCompressedSpanFinrankCondition_of_disjoint_ker
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (budget : ℕ)
    {ι : Type} [Fintype ι]
    (compress :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] (ι → ℚ))
    (hcard : Fintype.card ι ≤ budget)
    (hdisj :
      Disjoint (zeroProfileCompressedShiftSpan κ factors)
        (LinearMap.ker compress)) :
    ZeroProfileCompressedSpanFinrankCondition κ factors budget :=
  zeroProfileCompressedSpanFinrankCondition_of_kernelSeparated
    κ factors budget compress hcard
    ((zeroProfileCompressedSpanKernelSeparated_iff_disjoint_ker
      κ factors compress).mpr hdisj)

/-- The remaining compressed-span obligation as a small ambient linear
compression: find at most `budget` linear coordinates whose common kernel is
disjoint from the exact compressed shifted-image span. -/
def ZeroProfileCompressedSpanKernelDisjointCompressionObligation {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (budget : ℕ) : Prop :=
  ∃ ι : Type, ∃ _ : Fintype ι,
    Fintype.card ι ≤ budget ∧
      ∃ compress : MvPolynomial (Fin n) ℚ →ₗ[ℚ] (ι → ℚ),
        Disjoint (zeroProfileCompressedShiftSpan κ factors)
          (LinearMap.ker compress)

/-- The small ambient compression obligation is sufficient for the exact
compressed-span finrank condition. -/
theorem zeroProfileCompressedSpanFinrankCondition_of_kernelDisjointCompressionObligation
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (budget : ℕ)
    (hcompress :
      ZeroProfileCompressedSpanKernelDisjointCompressionObligation
        κ factors budget) :
    ZeroProfileCompressedSpanFinrankCondition κ factors budget := by
  rcases hcompress with ⟨ι, hι, hcard, compress, hdisj⟩
  letI : Fintype ι := hι
  exact zeroProfileCompressedSpanFinrankCondition_of_disjoint_ker
    κ factors budget compress hcard hdisj

/-- Ambient coordinate compression obtained by projecting onto the exact
compressed span along a chosen complement, then reading off the finite-basis
coordinates of that span. -/
noncomputable def zeroProfileCompressedSpanFinBasisCoordinateCompression
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    [Module.Finite ℚ ↥(zeroProfileCompressedShiftSpan κ factors)] :
    MvPolynomial (Fin n) ℚ →ₗ[ℚ]
      (Fin (Module.finrank ℚ
        ↥(zeroProfileCompressedShiftSpan κ factors)) → ℚ) :=
  let U : Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
    zeroProfileCompressedShiftSpan κ factors
  let C : Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
    Classical.choose U.exists_isCompl
  let hC : IsCompl U C := Classical.choose_spec U.exists_isCompl
  let projToU :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] ↥U :=
    (Submodule.IsCompl.projection hC).codRestrict U
      (fun p => Submodule.IsCompl.projection_apply_mem hC p)
  let b : Module.Basis (Fin (Module.finrank ℚ ↥U)) ℚ ↥U :=
    Module.finBasis ℚ ↥U
  b.equivFun.toLinearMap.comp projToU

/-- The chosen-complement finite-basis coordinate compression is injective on
the exact compressed span. -/
theorem zeroProfileCompressedSpanFinBasisCoordinateCompression_kernelSeparated
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    [Module.Finite ℚ ↥(zeroProfileCompressedShiftSpan κ factors)] :
    ZeroProfileCompressedSpanKernelSeparated κ factors
      (zeroProfileCompressedSpanFinBasisCoordinateCompression κ factors) := by
  classical
  let U : Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
    zeroProfileCompressedShiftSpan κ factors
  let C : Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
    Classical.choose U.exists_isCompl
  let hC : IsCompl U C := Classical.choose_spec U.exists_isCompl
  let projToU :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] ↥U :=
    (Submodule.IsCompl.projection hC).codRestrict U
      (fun p => Submodule.IsCompl.projection_apply_mem hC p)
  let b : Module.Basis (Fin (Module.finrank ℚ ↥U)) ℚ ↥U :=
    Module.finBasis ℚ ↥U
  intro x hx
  have hprojx : projToU x = x := by
    apply Subtype.ext
    simp [projToU, Submodule.IsCompl.projection_apply_left hC x]
  have hcoords : b.equivFun x = 0 := by
    simpa [zeroProfileCompressedSpanFinBasisCoordinateCompression,
      U, C, hC, projToU, b, hprojx, LinearMap.comp_apply] using hx
  have hcoords_zero : b.equivFun x = b.equivFun 0 := by
    simpa using hcoords
  exact b.equivFun.injective hcoords_zero

/-- The exact finrank condition produces an actual ambient compression whose
kernel is disjoint from the compressed span.  This closes the ambient-extension
gap left by the intrinsic coordinate equivalence. -/
theorem zeroProfileCompressedSpanKernelDisjointCompressionObligation_of_finrankCondition
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (budget : ℕ)
    (hfinrank :
      ZeroProfileCompressedSpanFinrankCondition κ factors budget) :
    ZeroProfileCompressedSpanKernelDisjointCompressionObligation
      κ factors budget := by
  classical
  rcases hfinrank with ⟨hfinite, hdim⟩
  let U : Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
    zeroProfileCompressedShiftSpan κ factors
  letI : Module.Finite ℚ ↥U := hfinite
  refine ⟨Fin (Module.finrank ℚ ↥U), inferInstance, ?_, ?_⟩
  · simpa [U] using hdim
  · refine ⟨zeroProfileCompressedSpanFinBasisCoordinateCompression
        κ factors, ?_⟩
    exact (zeroProfileCompressedSpanKernelSeparated_iff_disjoint_ker
      κ factors
      (zeroProfileCompressedSpanFinBasisCoordinateCompression
        κ factors)).mp
      (zeroProfileCompressedSpanFinBasisCoordinateCompression_kernelSeparated
        κ factors)

/-- Ambient kernel-disjoint compression is equivalent to the exact finrank
condition.  The reverse direction is constructive up to the chosen complement:
project to the compressed span, then take finite-basis coordinates. -/
theorem zeroProfileCompressedSpanKernelDisjointCompressionObligation_iff_finrankCondition
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (budget : ℕ) :
    ZeroProfileCompressedSpanKernelDisjointCompressionObligation
        κ factors budget ↔
      ZeroProfileCompressedSpanFinrankCondition κ factors budget :=
  ⟨zeroProfileCompressedSpanFinrankCondition_of_kernelDisjointCompressionObligation
      κ factors budget,
    zeroProfileCompressedSpanKernelDisjointCompressionObligation_of_finrankCondition
      κ factors budget⟩

/-- Intrinsic coordinate-compression version of the exact finrank condition.
This removes the ambient-extension issue and records the pure linear-algebra
equivalence: the compressed span has finrank at most `budget` iff it injects
into a coordinate space with at most `budget` coordinates. -/
def ZeroProfileCompressedSpanIntrinsicCompressionObligation {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (budget : ℕ) : Prop :=
  ∃ ι : Type, ∃ _ : Fintype ι,
    Fintype.card ι ≤ budget ∧
      ∃ compress :
        ↥(zeroProfileCompressedShiftSpan κ factors) →ₗ[ℚ] (ι → ℚ),
        Function.Injective compress

/-- Exact intrinsic compression equivalence for the zero-profile compressed
span. -/
theorem zeroProfileCompressedSpanIntrinsicCompressionObligation_iff_finrankCondition
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (budget : ℕ) :
    ZeroProfileCompressedSpanIntrinsicCompressionObligation κ factors budget ↔
      ZeroProfileCompressedSpanFinrankCondition κ factors budget := by
  classical
  constructor
  · rintro ⟨ι, hι, hcard, compress, hinj⟩
    letI : Fintype ι := hι
    have hfinite :
        Module.Finite ℚ ↥(zeroProfileCompressedShiftSpan κ factors) :=
      zeroProfileCompressedShiftSpan_finite κ factors
    letI :
        Module.Finite ℚ ↥(zeroProfileCompressedShiftSpan κ factors) :=
      hfinite
    refine ⟨hfinite, ?_⟩
    calc
      Module.finrank ℚ ↥(zeroProfileCompressedShiftSpan κ factors)
          ≤ Module.finrank ℚ (ι → ℚ) :=
            LinearMap.finrank_le_finrank_of_injective
              (f := compress) hinj
      _ = Fintype.card ι := Module.finrank_fintype_fun_eq_card ℚ
      _ ≤ budget := hcard
  · rintro ⟨hfinite, hfinrank⟩
    let U : Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
      zeroProfileCompressedShiftSpan κ factors
    letI : Module.Finite ℚ ↥U := hfinite
    refine ⟨Fin (Module.finrank ℚ ↥U), inferInstance, ?_, ?_⟩
    · simpa using hfinrank
    · let b : Module.Basis (Fin (Module.finrank ℚ ↥U)) ℚ ↥U :=
        Module.finBasis ℚ ↥U
      exact ⟨b.equivFun.toLinearMap, b.equivFun.injective⟩

/-- Generic exact equivalence: a finite common-span witness of size `budget`
exists if and only if the compressed shifted-image span is finite-dimensional
with finrank at most `budget`. -/
theorem zeroProfileCompressedSpanCommonSpanWithBudget_iff_finrankCondition
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (budget : ℕ) :
    ZeroProfileCompressedSpanCommonSpanWithBudget κ factors budget ↔
      ZeroProfileCompressedSpanFinrankCondition κ factors budget := by
  classical
  constructor
  · rintro ⟨G, hG_card, hG_span⟩
    have hle :
        zeroProfileCompressedShiftSpan κ factors ≤
          Submodule.span ℚ (↑G : Set (MvPolynomial (Fin n) ℚ)) :=
      Submodule.span_le.mpr hG_span
    haveI hfinite_G :
        Module.Finite ℚ
          ↥(Submodule.span ℚ
            (↑G : Set (MvPolynomial (Fin n) ℚ))) :=
      Module.Finite.span_of_finite ℚ (Finset.finite_toSet G)
    have hfinite_compressed :
        Module.Finite ℚ ↥(zeroProfileCompressedShiftSpan κ factors) :=
      Module.Finite.of_injective (Submodule.inclusion hle)
        (Submodule.inclusion_injective hle)
    letI : Module.Finite ℚ ↥(zeroProfileCompressedShiftSpan κ factors) :=
      hfinite_compressed
    refine ⟨hfinite_compressed, ?_⟩
    calc
      Module.finrank ℚ ↥(zeroProfileCompressedShiftSpan κ factors)
          ≤ Module.finrank ℚ
              ↥(Submodule.span ℚ
                (↑G : Set (MvPolynomial (Fin n) ℚ))) :=
            Submodule.finrank_mono hle
      _ ≤ G.card := finrank_span_finset_le_card G
      _ ≤ budget := hG_card
  · rintro ⟨hfinite_compressed, hfinrank⟩
    let U : Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
      zeroProfileCompressedShiftSpan κ factors
    haveI : Module.Finite ℚ ↥U := hfinite_compressed
    rcases finite_submodule_le_span_finset_card_le_finrank U with
      ⟨G, hU_span, hG_card⟩
    refine ⟨G, hG_card.trans hfinrank, ?_⟩
    intro p hp
    exact hU_span (Submodule.subset_span hp)

/-- Cook-Levin instance of the exact compressed-span finrank condition. -/
def CookLevinZeroProfileCompressedSpanFinrankCondition
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) : Prop :=
  ZeroProfileCompressedSpanFinrankCondition (Nat.log 2 n)
    (fun i => (cookLevinFactorList M n hn htb hns).get i)
    (withinProfileBound (Nat.log 2 n))

/-- The actual Cook-Levin zero-profile compressed span is finite-dimensional;
only its sharp dimension bound remains open. -/
theorem cookLevinZeroProfileCompressedShiftSpan_finite
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    Module.Finite ℚ
      ↥(zeroProfileCompressedShiftSpan (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn htb hns).get i)) :=
  zeroProfileCompressedShiftSpan_finite (Nat.log 2 n)
    (fun i => (cookLevinFactorList M n hn htb hns).get i)

/-- Cook-Levin compressed-span finrank bound by the admissible shift-support
count isolated by monomial-shift compression. -/
theorem cookLevinZeroProfileCompressedShiftSpan_finrank_le_shiftSupportSetCount
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    Module.finrank ℚ
      ↥(zeroProfileCompressedShiftSpan (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn htb hns).get i)) ≤
      zeroProfileShiftSupportSetCount n (Nat.log 2 n) :=
  zeroProfileCompressedShiftSpan_finrank_le_shiftSupportSetCount
    (Nat.log 2 n)
    (fun i => (cookLevinFactorList M n hn htb hns).get i)

/-- Cook-Levin instance of the smaller counting side condition left by
monomial-shift compression. -/
def CookLevinZeroProfileShiftSupportCountSideCondition (n : ℕ) : Prop :=
  ZeroProfileShiftSupportCountSideCondition n (Nat.log 2 n)

/-- Cook-Levin specialization of the singleton-support necessary condition for
the shift-support count route. -/
theorem ambient_le_withinProfileBound_of_CookLevinZeroProfileShiftSupportCountSideCondition
    (n : ℕ)
    (hn : n ≥ 2)
    (hcount : CookLevinZeroProfileShiftSupportCountSideCondition n) :
    n ≤ withinProfileBound (Nat.log 2 n) := by
  have hlog_pos : 0 < Nat.log 2 n := Nat.log_pos (by omega) hn
  exact
    ambient_le_withinProfileBound_of_zeroProfileShiftSupportCountSideCondition
      n (Nat.log 2 n) (Nat.succ_le_of_lt hlog_pos) hcount

/-- The current Cook-Levin shift-support count target cannot hold in ambient
sizes where `withinProfileBound (Nat.log 2 n) < n`.  This rules out closing the
zero-profile frontier by the raw shift-support count in those regimes. -/
theorem not_CookLevinZeroProfileShiftSupportCountSideCondition_of_withinProfileBound_lt_ambient
    (n : ℕ)
    (hn : n ≥ 2)
    (hlt : withinProfileBound (Nat.log 2 n) < n) :
    ¬ CookLevinZeroProfileShiftSupportCountSideCondition n := by
  intro hcount
  exact (not_le_of_gt hlt)
    (ambient_le_withinProfileBound_of_CookLevinZeroProfileShiftSupportCountSideCondition
      n hn hcount)

/-- At the paper-scale endpoint, the within-profile budget is already smaller
than the ambient variable count. -/
theorem withinProfileBound_log_two_pow_804_lt_ambient :
    withinProfileBound (Nat.log 2 ((2 : ℕ) ^ 804)) < (2 : ℕ) ^ 804 := by
  rw [Nat.log_pow (by norm_num : 1 < 2) 804]
  unfold withinProfileBound
  set_option exponentiation.threshold 1000 in
  calc
    (804 + 1) ^ 8 < ((2 : ℕ) ^ 10) ^ 8 := by
      exact Nat.pow_lt_pow_left (by norm_num : 804 + 1 < (2 : ℕ) ^ 10)
        (by norm_num : 8 ≠ 0)
    _ = (2 : ℕ) ^ (10 * 8) := by
      rw [Nat.pow_mul]
    _ ≤ (2 : ℕ) ^ 804 := by
      exact Nat.pow_le_pow_right (by omega : (1 : ℕ) ≤ 2)
        (by omega : 10 * 8 ≤ 804)

/-- Concrete no-go: the raw Cook-Levin shift-support count target is false at
the paper-scale endpoint `n = 2^804`. -/
theorem not_CookLevinZeroProfileShiftSupportCountSideCondition_two_pow_804 :
    ¬ CookLevinZeroProfileShiftSupportCountSideCondition ((2 : ℕ) ^ 804) := by
  apply
    not_CookLevinZeroProfileShiftSupportCountSideCondition_of_withinProfileBound_lt_ambient
  · set_option exponentiation.threshold 1000 in
    calc
      (2 : ℕ) = 2 ^ 1 := (pow_one 2).symm
      _ ≤ 2 ^ 804 := Nat.pow_le_pow_right (by omega : (1 : ℕ) ≤ 2)
        (by omega : 1 ≤ 804)
  · exact withinProfileBound_log_two_pow_804_lt_ambient

/-- The Cook-Levin shift-support count side condition proves the sharp
compressed-span finrank condition. -/
theorem cookLevinZeroProfileCompressedSpanFinrankCondition_of_shiftSupportCountSideCondition
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (hcount : CookLevinZeroProfileShiftSupportCountSideCondition n) :
    CookLevinZeroProfileCompressedSpanFinrankCondition M n hn htb hns := by
  simpa [CookLevinZeroProfileCompressedSpanFinrankCondition,
    CookLevinZeroProfileShiftSupportCountSideCondition] using
    zeroProfileCompressedSpanFinrankCondition_of_shiftSupportCountSideCondition
      (Nat.log 2 n)
      (fun i => (cookLevinFactorList M n hn htb hns).get i)
      hcount

/-- Exact Cook-Levin frontier: the theorem-level common-span blocker is
equivalent to the sharp finrank bound for the compressed shifted-image span. -/
theorem cookLevinZeroHistogramShiftCommonSpan_iff_compressedSpanFinrankCondition
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    CookLevinZeroHistogramShiftCommonSpan M n hn htb hns ↔
      CookLevinZeroProfileCompressedSpanFinrankCondition M n hn htb hns := by
  simpa [CookLevinZeroHistogramShiftCommonSpan,
    CookLevinZeroProfileCompressedSpanFinrankCondition,
    ZeroProfileCompressedSpanCommonSpanWithBudget] using
    (zeroProfileCompressedSpanCommonSpanWithBudget_iff_finrankCondition
      (Nat.log 2 n)
      (fun i => (cookLevinFactorList M n hn htb hns).get i)
      (withinProfileBound (Nat.log 2 n)))

/-- The sharp compressed-span finrank condition closes the existing
zero-profile common-span blocker. -/
theorem cookLevinZeroHistogramShiftCommonSpan_of_compressedSpanFinrankCondition
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (hcompressed :
      CookLevinZeroProfileCompressedSpanFinrankCondition M n hn htb hns) :
    CookLevinZeroHistogramShiftCommonSpan M n hn htb hns :=
  (cookLevinZeroHistogramShiftCommonSpan_iff_compressedSpanFinrankCondition
    M n hn htb hns).mpr hcompressed

/-- The smaller shift-support count side condition closes the Cook-Levin
zero-profile common-span blocker. -/
theorem cookLevinZeroHistogramShiftCommonSpan_of_shiftSupportCountSideCondition
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (hcount : CookLevinZeroProfileShiftSupportCountSideCondition n) :
    CookLevinZeroHistogramShiftCommonSpan M n hn htb hns :=
  cookLevinZeroHistogramShiftCommonSpan_of_compressedSpanFinrankCondition
    M n hn htb hns
    (cookLevinZeroProfileCompressedSpanFinrankCondition_of_shiftSupportCountSideCondition
      M n hn htb hns hcount)

/-- The old support-card sum side condition factors through the sharper
compressed-span finrank condition.  This is a comparison theorem, not a proof
that the support-card sum is the right frontier. -/
theorem cookLevinZeroProfileCompressedSpanFinrankCondition_of_supportCardSumSideCondition
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (hside :
      CookLevinZeroProfileSupportCardSumSideCondition M n hn htb hns) :
    CookLevinZeroProfileCompressedSpanFinrankCondition M n hn htb hns :=
  (cookLevinZeroHistogramShiftCommonSpan_iff_compressedSpanFinrankCondition
    M n hn htb hns).mp
    (cookLevinZeroHistogramShiftCommonSpan_of_supportCardSumSideCondition
      M n hn htb hns hside)

/-- Cook-Levin version of the small ambient compression obligation for the
actual zero-profile compressed shifted-image span. -/
def CookLevinZeroProfileCompressedSpanKernelDisjointCompressionObligation
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) : Prop :=
  ZeroProfileCompressedSpanKernelDisjointCompressionObligation (Nat.log 2 n)
    (fun i => (cookLevinFactorList M n hn htb hns).get i)
    (withinProfileBound (Nat.log 2 n))

/-- A small kernel-disjoint ambient compression proves the Cook-Levin
zero-profile compressed-span finrank condition. -/
theorem cookLevinZeroProfileCompressedSpanFinrankCondition_of_kernelDisjointCompressionObligation
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (hcompress :
      CookLevinZeroProfileCompressedSpanKernelDisjointCompressionObligation
        M n hn htb hns) :
    CookLevinZeroProfileCompressedSpanFinrankCondition M n hn htb hns :=
  zeroProfileCompressedSpanFinrankCondition_of_kernelDisjointCompressionObligation
    (Nat.log 2 n)
    (fun i => (cookLevinFactorList M n hn htb hns).get i)
    (withinProfileBound (Nat.log 2 n))
    hcompress

/-- A Cook-Levin compressed-span finrank proof now gives the actual ambient
kernel-disjoint compression requested by the zero-profile frontier. -/
theorem cookLevinZeroProfileCompressedSpanKernelDisjointCompressionObligation_of_compressedSpanFinrankCondition
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (hcompressed :
      CookLevinZeroProfileCompressedSpanFinrankCondition M n hn htb hns) :
    CookLevinZeroProfileCompressedSpanKernelDisjointCompressionObligation
      M n hn htb hns :=
  zeroProfileCompressedSpanKernelDisjointCompressionObligation_of_finrankCondition
    (Nat.log 2 n)
    (fun i => (cookLevinFactorList M n hn htb hns).get i)
    (withinProfileBound (Nat.log 2 n))
    hcompressed

/-- Cook-Levin target equivalence: the small ambient kernel-disjoint
compression obligation is exactly the sharp compressed-span finrank condition. -/
theorem cookLevinZeroProfileCompressedSpanKernelDisjointCompressionObligation_iff_compressedSpanFinrankCondition
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    CookLevinZeroProfileCompressedSpanKernelDisjointCompressionObligation
        M n hn htb hns ↔
      CookLevinZeroProfileCompressedSpanFinrankCondition M n hn htb hns := by
  simpa [CookLevinZeroProfileCompressedSpanKernelDisjointCompressionObligation,
    CookLevinZeroProfileCompressedSpanFinrankCondition] using
    (zeroProfileCompressedSpanKernelDisjointCompressionObligation_iff_finrankCondition
      (Nat.log 2 n)
      (fun i => (cookLevinFactorList M n hn htb hns).get i)
      (withinProfileBound (Nat.log 2 n)))

/-! ## Singleton-shift lower bound -/

/-- Coefficient probe for singleton shifted rows: the coefficient of `X j` in
`mlProj (X i * p)` is diagonal, with diagonal entry the constant coefficient
of `p`. -/
theorem coeff_singleton_mlProj_X_mul {n : ℕ}
    (p : MvPolynomial (Fin n) ℚ)
    (i j : Fin n) :
    MvPolynomial.coeff (Finsupp.single j 1)
        (mlProj (MvPolynomial.X i * p)) =
      if i = j then
        MvPolynomial.coeff (0 : Fin n →₀ ℕ) p
      else 0 := by
  classical
  have hmono :
      Finsupp.IsMultilinear (Finsupp.single j 1 : Fin n →₀ ℕ) := by
    intro k
    by_cases hk : k = j
    · subst k
      simp
    · simp [hk]
  rw [coeff_mlProj_of_isMultilinear_mono _ _ hmono]
  rw [MvPolynomial.coeff_X_mul']
  by_cases hij : i = j
  · subst j
    simp
  · have hnot_mem :
        i ∉ (Finsupp.single j 1 : Fin n →₀ ℕ).support := by
      simp [Finsupp.mem_support_iff, hij]
    rw [if_neg hnot_mem]
    simp [hij]

/-- Singleton shifted rows are linearly independent whenever the base
polynomial has nonzero constant coefficient. -/
theorem linearIndependent_singletonShiftRows_of_constCoeff_ne_zero {n : ℕ}
    (p : MvPolynomial (Fin n) ℚ)
    (hp0 : MvPolynomial.coeff (0 : Fin n →₀ ℕ) p ≠ 0) :
    LinearIndependent ℚ
      (fun i : Fin n => mlProj (MvPolynomial.X i * p)) := by
  classical
  rw [linearIndependent_iff']
  intro s w hw i hi
  have hcoeff :
      MvPolynomial.coeff (Finsupp.single i 1)
          (∑ j ∈ s, w j • mlProj (MvPolynomial.X j * p)) = 0 := by
    rw [hw]
    simp
  simp only [coeff_sum, coeff_smul, smul_eq_mul] at hcoeff
  have hsum :
      ∑ j ∈ s,
          w j *
            MvPolynomial.coeff (Finsupp.single i 1)
              (mlProj (MvPolynomial.X j * p)) =
        w i * MvPolynomial.coeff (0 : Fin n →₀ ℕ) p := by
    rw [Finset.sum_eq_single i]
    · rw [coeff_singleton_mlProj_X_mul p i i]
      simp
    · intro j _ hj_ne
      rw [coeff_singleton_mlProj_X_mul p j i]
      simp [hj_ne]
    · intro hnot
      exact False.elim (hnot hi)
  rw [hsum] at hcoeff
  rcases mul_eq_zero.mp hcoeff with hwi | hp
  · exact hwi
  · exact False.elim (hp0 hp)

/-- The singleton shifted row belongs to the exact zero-profile compressed
shift span as soon as one shift variable is allowed. -/
theorem singletonShiftRow_mem_zeroProfileCompressedShiftSpan {n L κ : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (i : Fin n)
    (hκ : 1 ≤ κ) :
    mlProj (MvPolynomial.X i * Finset.univ.prod factors) ∈
      zeroProfileCompressedShiftSpan κ factors := by
  classical
  apply Submodule.subset_span
  simp only [zeroProfileShiftImageSet, Set.mem_iUnion,
    Set.mem_singleton_iff]
  exact ⟨[i], by simpa using hκ, MvPolynomial.X i, by simp, rfl⟩

/-- True compressed-span lower bound: nonzero constant coefficient forces the
`n` singleton-shift rows into the compressed span as a linearly independent
family. -/
theorem ambient_le_zeroProfileCompressedShiftSpan_finrank_of_constCoeff_ne_zero
    {n L κ : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (hκ : 1 ≤ κ)
    (hp0 :
      MvPolynomial.coeff (0 : Fin n →₀ ℕ)
        (Finset.univ.prod factors) ≠ 0) :
    n ≤ Module.finrank ℚ
      ↥(zeroProfileCompressedShiftSpan κ factors) := by
  classical
  let U : Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
    zeroProfileCompressedShiftSpan κ factors
  have hfinite : Module.Finite ℚ ↥U :=
    zeroProfileCompressedShiftSpan_finite κ factors
  letI : Module.Finite ℚ ↥U := hfinite
  let rows : Fin n → ↥U := fun i =>
    ⟨mlProj (MvPolynomial.X i * Finset.univ.prod factors),
      singletonShiftRow_mem_zeroProfileCompressedShiftSpan factors i hκ⟩
  have hli_rows : LinearIndependent ℚ rows := by
    apply LinearIndependent.of_comp U.subtype
    simpa [rows, U, Function.comp_def] using
      (linearIndependent_singletonShiftRows_of_constCoeff_ne_zero
        (Finset.univ.prod factors) hp0)
  simpa [rows, U] using hli_rows.fintype_card_le_finrank

/-- If the proposed budget is smaller than the ambient variable count, the
exact compressed-span finrank condition is impossible under the same nonzero
constant-coefficient hypothesis. -/
theorem not_zeroProfileCompressedSpanFinrankCondition_of_constCoeff_ne_zero_of_budget_lt_ambient
    {n L κ budget : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (hκ : 1 ≤ κ)
    (hp0 :
      MvPolynomial.coeff (0 : Fin n →₀ ℕ)
        (Finset.univ.prod factors) ≠ 0)
    (hbudget : budget < n) :
    ¬ ZeroProfileCompressedSpanFinrankCondition κ factors budget := by
  rintro ⟨_hfinite, hfinrank⟩
  exact (not_le_of_gt hbudget)
    ((ambient_le_zeroProfileCompressedShiftSpan_finrank_of_constCoeff_ne_zero
      factors hκ hp0).trans hfinrank)

/-- Within-profile specialization of the true compressed-span obstruction. -/
theorem not_zeroProfileCompressedSpanFinrankCondition_withinProfileBound_of_constCoeff_ne_zero
    {n L κ : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (hκ : 1 ≤ κ)
    (hp0 :
      MvPolynomial.coeff (0 : Fin n →₀ ℕ)
        (Finset.univ.prod factors) ≠ 0)
    (hlt : withinProfileBound κ < n) :
    ¬ ZeroProfileCompressedSpanFinrankCondition κ factors
      (withinProfileBound κ) :=
  not_zeroProfileCompressedSpanFinrankCondition_of_constCoeff_ne_zero_of_budget_lt_ambient
    factors hκ hp0 hlt

/-- Cook-Levin true compressed-span no-go in every regime where the
within-profile budget is smaller than the ambient variable count. -/
theorem not_cookLevinZeroProfileCompressedSpanFinrankCondition_of_withinProfileBound_lt_ambient
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (hlt : withinProfileBound (Nat.log 2 n) < n) :
    ¬ CookLevinZeroProfileCompressedSpanFinrankCondition M n hn htb hns := by
  have hlog_pos : 0 < Nat.log 2 n := Nat.log_pos (by omega) hn
  have hlog : 1 ≤ Nat.log 2 n := Nat.succ_le_of_lt hlog_pos
  have hp0 :
      MvPolynomial.coeff (0 : Fin n →₀ ℕ)
        (Finset.univ.prod
          (fun i => (cookLevinFactorList M n hn htb hns).get i)) ≠
        0 := by
    have hcoeff :
        MvPolynomial.coeff (0 : Fin n →₀ ℕ)
          (Finset.univ.prod
            (fun i => (cookLevinFactorList M n hn htb hns).get i)) =
          (1 : ℚ) := by
      simpa [cookLevinZeroProfileBaseProduct] using
        cookLevinZeroProfileBaseProduct_coeff_zero M n hn htb hns
    rw [hcoeff]
    norm_num
  simpa [CookLevinZeroProfileCompressedSpanFinrankCondition] using
    (not_zeroProfileCompressedSpanFinrankCondition_withinProfileBound_of_constCoeff_ne_zero
      (fun i => (cookLevinFactorList M n hn htb hns).get i)
      hlog hp0 hlt)

/-- Paper-scale true no-go: at `n = 2^804`, the actual Cook-Levin compressed
span already has finrank larger than the within-profile budget. -/
theorem not_cookLevinZeroProfileCompressedSpanFinrankCondition_two_pow_804
    (M : DTM)
    (hn : (2 : ℕ) ^ 804 ≥ 2)
    (htb : M.timeBound ≤ 4)
    (hns : M.numStates ≤ (2 : ℕ) ^ 804) :
    ¬ CookLevinZeroProfileCompressedSpanFinrankCondition M
      ((2 : ℕ) ^ 804) hn htb hns :=
  not_cookLevinZeroProfileCompressedSpanFinrankCondition_of_withinProfileBound_lt_ambient
    M ((2 : ℕ) ^ 804) hn htb hns
    withinProfileBound_log_two_pow_804_lt_ambient

/-- Generic scalar version of a one-dimensional zero-profile compressed span:
all shifted base-product rows are scalar multiples of one ambient anchor. -/
def ZeroProfileCompressedSpanScalarClosure {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) : Prop :=
  ∃ anchor : MvPolynomial (Fin n) ℚ,
    ∀ (S : List (Fin n)), S.length ≤ κ →
      ∀ shift : MvPolynomial (Fin n) ℚ, shift.vars ⊆ S.toFinset →
        ∃ c : ℚ, c • anchor =
          mlProj (shift * Finset.univ.prod factors)

/-- A budget-one common-span witness localizes to a scalar closure witness.
This is the generic version of the Cook-Levin singleton-template reduction. -/
theorem zeroProfileCompressedSpanScalarClosure_of_commonSpanWithBudget_one
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (hcommon :
      ZeroProfileCompressedSpanCommonSpanWithBudget κ factors 1) :
    ZeroProfileCompressedSpanScalarClosure κ factors := by
  classical
  rcases hcommon with ⟨G, hG_card, hG_span⟩
  by_cases hG_empty : G = ∅
  · refine ⟨0, ?_⟩
    intro S hS shift hshift
    have hp :
        mlProj (shift * Finset.univ.prod factors) ∈
          zeroProfileShiftImageSet κ factors := by
      simp only [zeroProfileShiftImageSet, Set.mem_iUnion,
        Set.mem_singleton_iff]
      exact ⟨S, hS, shift, hshift, rfl⟩
    have hmem :
        mlProj (shift * Finset.univ.prod factors) ∈
          Submodule.span ℚ
            ({(0 : MvPolynomial (Fin n) ℚ)} :
              Set (MvPolynomial (Fin n) ℚ)) := by
      exact (Submodule.span_mono (by
        intro q hq
        simp [hG_empty] at hq)) (hG_span hp)
    rcases Submodule.mem_span_singleton.mp hmem with ⟨c, hc⟩
    exact ⟨c, hc⟩
  · have hG_card_eq_one : G.card = 1 := by
      apply Nat.le_antisymm hG_card
      exact Nat.succ_le_of_lt
        (Finset.card_pos.mpr
          (by simpa [Finset.nonempty_iff_ne_empty] using hG_empty))
    rcases Finset.card_eq_one.mp hG_card_eq_one with ⟨anchor, hG_eq⟩
    refine ⟨anchor, ?_⟩
    intro S hS shift hshift
    have hp :
        mlProj (shift * Finset.univ.prod factors) ∈
          zeroProfileShiftImageSet κ factors := by
      simp only [zeroProfileShiftImageSet, Set.mem_iUnion,
        Set.mem_singleton_iff]
      exact ⟨S, hS, shift, hshift, rfl⟩
    have hmem :
        mlProj (shift * Finset.univ.prod factors) ∈
          Submodule.span ℚ
            ({anchor} : Set (MvPolynomial (Fin n) ℚ)) := by
      simpa [hG_eq] using hG_span hp
    rcases Submodule.mem_span_singleton.mp hmem with ⟨c, hc⟩
    exact ⟨c, hc⟩

/-- A budget-one finrank condition localizes to scalar closure. -/
theorem zeroProfileCompressedSpanScalarClosure_of_finrankCondition_budget_one
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (hfinrank :
      ZeroProfileCompressedSpanFinrankCondition κ factors 1) :
    ZeroProfileCompressedSpanScalarClosure κ factors :=
  zeroProfileCompressedSpanScalarClosure_of_commonSpanWithBudget_one
    κ factors
    ((zeroProfileCompressedSpanCommonSpanWithBudget_iff_finrankCondition
      κ factors 1).mpr hfinrank)

/-- Localized budget-one obstruction: any zero-profile base product with
nonzero constant coefficient forces compressed-span dimension at least two
as soon as one shift variable is allowed. -/
theorem not_zeroProfileCompressedSpanFinrankCondition_budget_one_of_constCoeff_ne_zero
    {n L κ : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (i : Fin n)
    (hκ : 1 ≤ κ)
    (hp0 :
      MvPolynomial.coeff (0 : Fin n →₀ ℕ)
        (Finset.univ.prod factors) ≠ 0) :
    ¬ ZeroProfileCompressedSpanFinrankCondition κ factors 1 := by
  intro hfinrank
  exact zeroProfileScalarClosure_obstruction_of_constCoeff_ne_zero
    (p := Finset.univ.prod factors) i hκ hp0
    (zeroProfileCompressedSpanScalarClosure_of_finrankCondition_budget_one
      κ factors hfinrank)

/-- Localized lower-bound form of the generic budget-one obstruction. -/
theorem two_le_zeroProfileCompressedShiftSpan_finrank_of_constCoeff_ne_zero
    {n L κ : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (i : Fin n)
    (hκ : 1 ≤ κ)
    (hp0 :
      MvPolynomial.coeff (0 : Fin n →₀ ℕ)
        (Finset.univ.prod factors) ≠ 0) :
    2 ≤ Module.finrank ℚ
      ↥(zeroProfileCompressedShiftSpan κ factors) := by
  by_contra hnot
  have hle_one :
      Module.finrank ℚ
        ↥(zeroProfileCompressedShiftSpan κ factors) ≤ 1 := by
    omega
  exact not_zeroProfileCompressedSpanFinrankCondition_budget_one_of_constCoeff_ne_zero
    factors i hκ hp0
    ⟨zeroProfileCompressedShiftSpan_finite κ factors, hle_one⟩

/-- The actual Cook-Levin zero-profile compressed span cannot satisfy a
one-dimensional compressed-span bound.  This is a checked lower-bound/no-go:
the sharp compressed-span target is not the old singleton template target. -/
theorem not_cookLevinZeroProfileCompressedSpanFinrankCondition_budget_one
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    ¬ ZeroProfileCompressedSpanFinrankCondition (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn htb hns).get i) 1 := by
  have hlog_pos : 0 < Nat.log 2 n := Nat.log_pos (by omega) hn
  have hlog : 1 ≤ Nat.log 2 n := Nat.succ_le_of_lt hlog_pos
  apply
    not_zeroProfileCompressedSpanFinrankCondition_budget_one_of_constCoeff_ne_zero
      (fun i => (cookLevinFactorList M n hn htb hns).get i)
      ⟨0, by omega⟩ hlog
  intro hzero
  have hcoeff :
      MvPolynomial.coeff (0 : Fin n →₀ ℕ)
        (Finset.univ.prod
          (fun i => (cookLevinFactorList M n hn htb hns).get i)) =
        (1 : ℚ) := by
    simpa [cookLevinZeroProfileBaseProduct] using
      cookLevinZeroProfileBaseProduct_coeff_zero M n hn htb hns
  rw [hzero] at hcoeff
  norm_num at hcoeff

/-- Equivalent lower-bound form: the actual Cook-Levin zero-profile compressed
span has finrank at least two. -/
theorem cookLevinZeroProfileCompressedShiftSpan_two_le_finrank
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    2 ≤ Module.finrank ℚ
      ↥(zeroProfileCompressedShiftSpan (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn htb hns).get i)) := by
  have hlog_pos : 0 < Nat.log 2 n := Nat.log_pos (by omega) hn
  have hlog : 1 ≤ Nat.log 2 n := Nat.succ_le_of_lt hlog_pos
  apply two_le_zeroProfileCompressedShiftSpan_finrank_of_constCoeff_ne_zero
    (fun i => (cookLevinFactorList M n hn htb hns).get i)
    ⟨0, by omega⟩ hlog
  intro hzero
  have hcoeff :
      MvPolynomial.coeff (0 : Fin n →₀ ℕ)
        (Finset.univ.prod
          (fun i => (cookLevinFactorList M n hn htb hns).get i)) =
        (1 : ℚ) := by
    simpa [cookLevinZeroProfileBaseProduct] using
      cookLevinZeroProfileBaseProduct_coeff_zero M n hn htb hns
  rw [hzero] at hcoeff
  norm_num at hcoeff

/-! ## Axiom audit anchors -/

#print axioms zeroProfileCompressedShiftSpan_finite
#print axioms zeroProfileCompressedShiftSpan_finrank_le_supportBasis_card
#print axioms zeroProfileShiftMonomialImageBasis_card_le_supportSetCount
#print axioms mlProj_monomial_mul_eq_zero_of_not_multilinear
#print axioms mlProj_mul_mem_span_shiftMonomialImagesOn_of_vars_subset
#print axioms zeroProfileShiftImageSet_subset_monomialImageBasis_span
#print axioms zeroProfileShiftMonomialImageBasis_subset_shiftImageSet
#print axioms zeroProfileShiftImageSpan_eq_monomialImageBasis_span
#print axioms zeroProfileCompressedShiftSpan_finrank_le_shiftSupportSetCount
#print axioms ambient_le_withinProfileBound_of_zeroProfileShiftSupportCountSideCondition
#print axioms not_zeroProfileShiftSupportCountSideCondition_of_withinProfileBound_lt_ambient
#print axioms zeroProfileCompressedSpanFinrankCondition_of_shiftSupportCountSideCondition
#print axioms zeroProfileCompressedSpanKernelSeparated_iff_disjoint_ker
#print axioms zeroProfileCompressedSpanFinrankCondition_of_kernelSeparated
#print axioms zeroProfileCompressedSpanFinrankCondition_of_disjoint_ker
#print axioms zeroProfileCompressedSpanFinrankCondition_of_kernelDisjointCompressionObligation
#print axioms zeroProfileCompressedSpanFinBasisCoordinateCompression_kernelSeparated
#print axioms zeroProfileCompressedSpanKernelDisjointCompressionObligation_of_finrankCondition
#print axioms zeroProfileCompressedSpanKernelDisjointCompressionObligation_iff_finrankCondition
#print axioms zeroProfileCompressedSpanIntrinsicCompressionObligation_iff_finrankCondition
#print axioms zeroProfileCompressedSpanCommonSpanWithBudget_iff_finrankCondition
#print axioms cookLevinZeroProfileCompressedShiftSpan_finrank_le_shiftSupportSetCount
#print axioms ambient_le_withinProfileBound_of_CookLevinZeroProfileShiftSupportCountSideCondition
#print axioms not_CookLevinZeroProfileShiftSupportCountSideCondition_of_withinProfileBound_lt_ambient
#print axioms withinProfileBound_log_two_pow_804_lt_ambient
#print axioms not_CookLevinZeroProfileShiftSupportCountSideCondition_two_pow_804
#print axioms cookLevinZeroProfileCompressedSpanFinrankCondition_of_shiftSupportCountSideCondition
#print axioms cookLevinZeroHistogramShiftCommonSpan_iff_compressedSpanFinrankCondition
#print axioms cookLevinZeroHistogramShiftCommonSpan_of_compressedSpanFinrankCondition
#print axioms cookLevinZeroHistogramShiftCommonSpan_of_shiftSupportCountSideCondition
#print axioms cookLevinZeroProfileCompressedSpanFinrankCondition_of_supportCardSumSideCondition
#print axioms cookLevinZeroProfileCompressedSpanFinrankCondition_of_kernelDisjointCompressionObligation
#print axioms cookLevinZeroProfileCompressedSpanKernelDisjointCompressionObligation_of_compressedSpanFinrankCondition
#print axioms cookLevinZeroProfileCompressedSpanKernelDisjointCompressionObligation_iff_compressedSpanFinrankCondition
#print axioms coeff_singleton_mlProj_X_mul
#print axioms linearIndependent_singletonShiftRows_of_constCoeff_ne_zero
#print axioms singletonShiftRow_mem_zeroProfileCompressedShiftSpan
#print axioms ambient_le_zeroProfileCompressedShiftSpan_finrank_of_constCoeff_ne_zero
#print axioms not_zeroProfileCompressedSpanFinrankCondition_of_constCoeff_ne_zero_of_budget_lt_ambient
#print axioms not_zeroProfileCompressedSpanFinrankCondition_withinProfileBound_of_constCoeff_ne_zero
#print axioms not_cookLevinZeroProfileCompressedSpanFinrankCondition_of_withinProfileBound_lt_ambient
#print axioms not_cookLevinZeroProfileCompressedSpanFinrankCondition_two_pow_804
#print axioms zeroProfileCompressedSpanScalarClosure_of_commonSpanWithBudget_one
#print axioms zeroProfileCompressedSpanScalarClosure_of_finrankCondition_budget_one
#print axioms not_zeroProfileCompressedSpanFinrankCondition_budget_one_of_constCoeff_ne_zero
#print axioms two_le_zeroProfileCompressedShiftSpan_finrank_of_constCoeff_ne_zero
#print axioms not_cookLevinZeroProfileCompressedSpanFinrankCondition_budget_one
#print axioms cookLevinZeroProfileCompressedShiftSpan_two_le_finrank

end PathB
end DeepMath
end Paper93
end PallLean
