import PallLean.Paper93.DeepMath.PathB.ZeroProfileScalarClosure
import PallLean.Paper93.DeepMath.PathB.KeepFOBPsideTemplateCollapseBridge

set_option exponentiation.threshold 1000

/-!
# Zero-profile gauge quotient adapter

`ZeroProfileScalarClosure` proves that the actual zero-profile shifted family
cannot collapse to one scalar line in the original polynomial space: the
constant shift and a variable shift have incompatible constant/linear
coefficients.

This file records the quotient adapter that removes exactly that obstruction.
We quotient by the span of the relations

  `mlProj (shift * baseProduct) - mlProj baseProduct`

for all admissible zero-profile shifts.  In the quotient every shifted
zero-profile generator is equal to one anchor class.  The construction is a
rank/spanning adapter only: it does not prove NP identity-minor preservation,
and it only feeds the existing keepFOB P-side route after an explicit lift back
to the original template-collapse statement is supplied.
-/

namespace PallLean
namespace Paper93
namespace DeepMath
namespace PathB

open MvPolynomial SymmetricPowerBound TuringMachine PaperFaithfulSeparation
open WithinProfileBound MultilinearSPDP SPDP
open scoped BigOperators

attribute [local instance] Classical.dec

private theorem ge_four_of_ge_two_pow_804_for_zeroProfileGaugeQuotient
    {n : Nat} (hn : n ≥ 2 ^ 804) : n ≥ 4 := by
  have hfour : (4 : Nat) ≤ 2 ^ 804 := by
    calc
      (4 : Nat) = 2 ^ 2 := by norm_num
      _ ≤ 2 ^ 804 := Nat.pow_le_pow_right (by omega) (by omega)
  exact le_trans hfour hn

/-- The zero-profile anchor before quotienting: the projected unshifted base
product. -/
noncomputable def zeroProfileGaugeAnchorImage {n L : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    MvPolynomial (Fin n) ℚ :=
  mlProj (Finset.univ.prod factors)

/-- Relations identifying every admissible shifted zero-profile base-product
image with the unshifted anchor image. -/
noncomputable def zeroProfileGaugeRelationSet {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    Set (MvPolynomial (Fin n) ℚ) :=
  {r | ∃ p,
    p ∈ zeroProfileShiftImageSet κ factors ∧
      r = p - zeroProfileGaugeAnchorImage factors}

/-- The submodule generated by the zero-profile gauge relations. -/
noncomputable def zeroProfileGaugeRelationSpan {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
  Submodule.span ℚ (zeroProfileGaugeRelationSet κ factors)

/-- Quotient polynomial space in which all admissible zero-profile shifted
base products have the same class. -/
abbrev ZeroProfileGaugeQuotient {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) : Type :=
  MvPolynomial (Fin n) ℚ ⧸ zeroProfileGaugeRelationSpan κ factors

/-- The quotient map for the zero-profile gauge adapter. -/
noncomputable def zeroProfileGaugeQuotientMap {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    MvPolynomial (Fin n) ℚ →ₗ[ℚ] ZeroProfileGaugeQuotient κ factors :=
  (zeroProfileGaugeRelationSpan κ factors).mkQ

/-- The anchor class in the quotient. -/
noncomputable def zeroProfileGaugeQuotientAnchor {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    ZeroProfileGaugeQuotient κ factors :=
  zeroProfileGaugeQuotientMap κ factors
    (zeroProfileGaugeAnchorImage factors)

/-- A shifted base-product generator is a member of the zero-profile shifted
image set. -/
theorem zeroProfileShiftImageSet_shiftedBase_mem {n L κ : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (S : List (Fin n)) (hS : S.length ≤ κ)
    (shift : MvPolynomial (Fin n) ℚ)
    (hshift : shift.vars ⊆ S.toFinset) :
    mlProj (shift * Finset.univ.prod factors) ∈
      zeroProfileShiftImageSet κ factors := by
  simp only [zeroProfileShiftImageSet, Set.mem_iUnion, Set.mem_singleton_iff]
  exact ⟨S, hS, shift, hshift, rfl⟩

/-- Every shifted-image relation lies in the relation span. -/
theorem zeroProfileGaugeRelation_mem_of_shiftImage {n L κ : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {p : MvPolynomial (Fin n) ℚ}
    (hp : p ∈ zeroProfileShiftImageSet κ factors) :
    p - zeroProfileGaugeAnchorImage factors ∈
      zeroProfileGaugeRelationSpan κ factors := by
  exact Submodule.subset_span ⟨p, hp, rfl⟩

/-- The quotient map sends every admissible shifted image to the anchor class. -/
theorem zeroProfileGaugeQuotientMap_eq_anchor_of_shiftImage {n L κ : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {p : MvPolynomial (Fin n) ℚ}
    (hp : p ∈ zeroProfileShiftImageSet κ factors) :
    zeroProfileGaugeQuotientMap κ factors p =
      zeroProfileGaugeQuotientAnchor κ factors := by
  unfold zeroProfileGaugeQuotientMap zeroProfileGaugeQuotientAnchor
  change Submodule.Quotient.mk p =
    Submodule.Quotient.mk (zeroProfileGaugeAnchorImage factors)
  exact (Submodule.Quotient.eq
    (zeroProfileGaugeRelationSpan κ factors)).mpr
      (zeroProfileGaugeRelation_mem_of_shiftImage factors hp)

/-- Shifted-base form of the quotient collapse. -/
theorem zeroProfileGaugeQuotientMap_shiftedBase_eq_anchor {n L κ : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (S : List (Fin n)) (hS : S.length ≤ κ)
    (shift : MvPolynomial (Fin n) ℚ)
    (hshift : shift.vars ⊆ S.toFinset) :
    zeroProfileGaugeQuotientMap κ factors
        (mlProj (shift * Finset.univ.prod factors)) =
      zeroProfileGaugeQuotientAnchor κ factors :=
  zeroProfileGaugeQuotientMap_eq_anchor_of_shiftImage factors
    (zeroProfileShiftImageSet_shiftedBase_mem factors S hS shift hshift)

/-- The constant shift collapses to the quotient anchor. -/
theorem zeroProfileGaugeQuotientMap_one_shift_eq_anchor {n L κ : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    zeroProfileGaugeQuotientMap κ factors
        (mlProj ((1 : MvPolynomial (Fin n) ℚ) *
          Finset.univ.prod factors)) =
      zeroProfileGaugeQuotientAnchor κ factors := by
  simpa using
    zeroProfileGaugeQuotientMap_shiftedBase_eq_anchor
      (κ := κ) factors [] (by simp)
      (1 : MvPolynomial (Fin n) ℚ) (by simp)

/-- Every variable shift collapses to the quotient anchor once `κ ≥ 1`. -/
theorem zeroProfileGaugeQuotientMap_X_shift_eq_anchor {n L κ : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (hκ : 1 ≤ κ) (i : Fin n) :
    zeroProfileGaugeQuotientMap κ factors
        (mlProj (MvPolynomial.X i * Finset.univ.prod factors)) =
      zeroProfileGaugeQuotientAnchor κ factors := by
  simpa using
    zeroProfileGaugeQuotientMap_shiftedBase_eq_anchor
      (κ := κ) factors [i] (by simpa using hκ)
      (MvPolynomial.X i) (by simp)

/-- In the quotient, the obstruction witnesses `shift = 1` and `shift = X i`
are literally the same class. -/
theorem zeroProfileGaugeQuotientMap_one_shift_eq_X_shift {n L κ : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (hκ : 1 ≤ κ) (i : Fin n) :
    zeroProfileGaugeQuotientMap κ factors
        (mlProj ((1 : MvPolynomial (Fin n) ℚ) *
          Finset.univ.prod factors)) =
      zeroProfileGaugeQuotientMap κ factors
        (mlProj (MvPolynomial.X i * Finset.univ.prod factors)) := by
  calc
    zeroProfileGaugeQuotientMap κ factors
        (mlProj ((1 : MvPolynomial (Fin n) ℚ) *
          Finset.univ.prod factors))
        = zeroProfileGaugeQuotientAnchor κ factors :=
            zeroProfileGaugeQuotientMap_one_shift_eq_anchor factors
    _ = zeroProfileGaugeQuotientMap κ factors
        (mlProj (MvPolynomial.X i * Finset.univ.prod factors)) :=
            (zeroProfileGaugeQuotientMap_X_shift_eq_anchor
              factors hκ i).symm

/-- Quotient scalar-collapse interface: the shifted zero-profile image family
is scalar-generated by one quotient anchor. -/
def ZeroProfileGaugeQuotientScalarObligation {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) : Prop :=
  ∃ anchor : ZeroProfileGaugeQuotient κ factors,
    ∀ (S : List (Fin n)), S.length ≤ κ →
      ∀ shift : MvPolynomial (Fin n) ℚ, shift.vars ⊆ S.toFinset →
        ∃ c : ℚ,
          c • anchor =
            zeroProfileGaugeQuotientMap κ factors
              (mlProj (shift * Finset.univ.prod factors))

/-- The quotient scalar-collapse interface is satisfied by construction. -/
theorem zeroProfileGaugeQuotientScalarObligation {n L κ : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    ZeroProfileGaugeQuotientScalarObligation κ factors := by
  refine ⟨zeroProfileGaugeQuotientAnchor κ factors, ?_⟩
  intro S hS shift hshift
  refine ⟨1, ?_⟩
  simpa using
    (zeroProfileGaugeQuotientMap_shiftedBase_eq_anchor
      (κ := κ) factors S hS shift hshift).symm

/-- The quotient image span of the zero-profile shifted family. -/
noncomputable def zeroProfileGaugeQuotientImageSpan {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    Submodule ℚ (ZeroProfileGaugeQuotient κ factors) :=
  Submodule.span ℚ
    (zeroProfileGaugeQuotientMap κ factors ''
      zeroProfileShiftImageSet κ factors)

/-- The quotient image span is contained in the line generated by the quotient
anchor. -/
theorem zeroProfileGaugeQuotientImageSpan_le_anchorSpan {n L κ : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    zeroProfileGaugeQuotientImageSpan κ factors ≤
      (ℚ ∙ zeroProfileGaugeQuotientAnchor κ factors :
        Submodule ℚ (ZeroProfileGaugeQuotient κ factors)) := by
  rw [zeroProfileGaugeQuotientImageSpan, Submodule.span_le]
  intro q hq
  rcases hq with ⟨p, hp, rfl⟩
  rw [zeroProfileGaugeQuotientMap_eq_anchor_of_shiftImage factors hp]
  exact Submodule.subset_span (by simp)

/-- A one-vector span has finrank at most one. -/
theorem finrank_span_singleton_le_one
    {V : Type} [AddCommGroup V] [Module ℚ V] (v : V) :
    Module.finrank ℚ (ℚ ∙ v : Submodule ℚ V) ≤ 1 := by
  by_cases hv : v = 0
  · subst v
    have hbot : (ℚ ∙ (0 : V) : Submodule ℚ V) = ⊥ := by
      rw [Submodule.span_singleton_eq_bot]
    rw [hbot, finrank_bot]
    omega
  · rw [finrank_span_singleton hv]

/-- Rank side: the quotient image of the zero-profile shifted family has
finrank at most one. -/
theorem zeroProfileGaugeQuotientImageSpan_finrank_le_one {n L κ : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    Module.finrank ℚ (zeroProfileGaugeQuotientImageSpan κ factors) ≤ 1 := by
  exact
    (Submodule.finrank_mono
      (zeroProfileGaugeQuotientImageSpan_le_anchorSpan
        (κ := κ) factors)).trans
      (finrank_span_singleton_le_one
        (zeroProfileGaugeQuotientAnchor κ factors))

/-- Template-spanning interface in the quotient target. -/
def ZeroProfileGaugeQuotientTemplateShiftCollapse {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) : Prop :=
  ∃ G : Finset (ZeroProfileGaugeQuotient κ factors),
    G.card ≤ profileTemplateBound zeroProfileHistogram ∧
      (zeroProfileGaugeQuotientMap κ factors ''
        zeroProfileShiftImageSet κ factors) ⊆
          Submodule.span ℚ
            (↑G : Set (ZeroProfileGaugeQuotient κ factors))

/-- Spanning side: one quotient template spans the whole shifted family. -/
theorem zeroProfileGaugeQuotientTemplateShiftCollapse {n L κ : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    ZeroProfileGaugeQuotientTemplateShiftCollapse κ factors := by
  refine
    ⟨{zeroProfileGaugeQuotientAnchor κ factors}, ?_, ?_⟩
  · simp [profileTemplateBound_zeroProfileHistogram]
  · intro q hq
    rcases hq with ⟨p, hp, rfl⟩
    rw [zeroProfileGaugeQuotientMap_eq_anchor_of_shiftImage factors hp]
    exact Submodule.subset_span (by simp)

/-! ## Cook-Levin specialization -/

/-- Cook-Levin quotient scalar-collapse obligation for the zero-profile
shifted base product. -/
def CookLevinZeroProfileGaugeQuotientScalarObligation
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) : Prop :=
  ZeroProfileGaugeQuotientScalarObligation (Nat.log 2 n)
    (fun i => (cookLevinFactorList M n hn htb hns).get i)

/-- Cook-Levin quotient template-collapse obligation for the zero-profile
shifted base product. -/
def CookLevinZeroProfileGaugeQuotientTemplateShiftCollapse
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) : Prop :=
  ZeroProfileGaugeQuotientTemplateShiftCollapse (Nat.log 2 n)
    (fun i => (cookLevinFactorList M n hn htb hns).get i)

/-- The Cook-Levin zero-profile quotient scalar-collapse interface is
satisfied. -/
theorem cookLevinZeroProfileGaugeQuotientScalarObligation
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    CookLevinZeroProfileGaugeQuotientScalarObligation M n hn htb hns :=
  zeroProfileGaugeQuotientScalarObligation
    (κ := Nat.log 2 n)
    (fun i => (cookLevinFactorList M n hn htb hns).get i)

/-- The Cook-Levin zero-profile quotient template-collapse interface is
satisfied by the singleton quotient anchor. -/
theorem cookLevinZeroProfileGaugeQuotientTemplateShiftCollapse
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    CookLevinZeroProfileGaugeQuotientTemplateShiftCollapse M n hn htb hns :=
  zeroProfileGaugeQuotientTemplateShiftCollapse
    (κ := Nat.log 2 n)
    (fun i => (cookLevinFactorList M n hn htb hns).get i)

/-- In the Cook-Levin quotient, the two obstruction witnesses from
`ZeroProfileScalarClosure` become equal. -/
theorem cookLevinZeroProfileGaugeQuotient_one_shift_eq_X_shift
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (i : Fin n) :
    zeroProfileGaugeQuotientMap (Nat.log 2 n)
        (fun j => (cookLevinFactorList M n hn htb hns).get j)
        (mlProj ((1 : MvPolynomial (Fin n) ℚ) *
          cookLevinZeroProfileBaseProduct M n hn htb hns)) =
      zeroProfileGaugeQuotientMap (Nat.log 2 n)
        (fun j => (cookLevinFactorList M n hn htb hns).get j)
        (mlProj (MvPolynomial.X i *
          cookLevinZeroProfileBaseProduct M n hn htb hns)) := by
  have hlog_pos : 0 < Nat.log 2 n := Nat.log_pos (by omega) hn
  have hlog : 1 ≤ Nat.log 2 n := Nat.succ_le_of_lt hlog_pos
  simpa [cookLevinZeroProfileBaseProduct] using
    zeroProfileGaugeQuotientMap_one_shift_eq_X_shift
      (κ := Nat.log 2 n)
      (fun j => (cookLevinFactorList M n hn htb hns).get j) hlog i

/-- The original scalar line is false, but the quotient scalar interface is
true.  This is the formal obstruction-removal statement; it is not a lift back
to the original polynomial space. -/
theorem cookLevinZeroProfile_originalScalar_false_and_quotientScalar_true
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    ¬ CookLevinZeroProfileTemplateScalarObligation M n hn htb hns ∧
      CookLevinZeroProfileGaugeQuotientScalarObligation M n hn htb hns :=
  ⟨not_CookLevinZeroProfileTemplateScalarObligation M n hn htb hns,
    cookLevinZeroProfileGaugeQuotientScalarObligation M n hn htb hns⟩

/-- Exact remaining lift needed to use the quotient adapter in the existing
original-space zero-profile template-collapse theorem. -/
def CookLevinZeroProfileGaugeQuotientLiftToTemplateCollapse
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) : Prop :=
  CookLevinZeroProfileGaugeQuotientTemplateShiftCollapse M n hn htb hns →
    CookLevinZeroHistogramTemplateShiftCollapse M n hn htb hns

/-- If the quotient singleton collapse lifts back to the original polynomial
space, active admissible profile cases give bounded-profile template
collapse. -/
theorem cookLevinProfileTemplateCollapseLemmaBoundedProfile_of_activeCases_zeroGaugeQuotientLift
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (hn4 : n ≥ 4)
    (hlift :
      CookLevinZeroProfileGaugeQuotientLiftToTemplateCollapse
        M n hn htb hns)
    (hcases :
      CookLevinProfileTemplateCollapseActiveAdmissibleProfileCases
        M n hn htb hns) :
    CookLevinProfileTemplateCollapseLemmaBoundedProfile M n hn htb hns :=
  cookLevinProfileTemplateCollapseLemmaBoundedProfile_of_activeAdmissibleProfileCases
    M n hn htb hns hn4
    (hlift
      (cookLevinZeroProfileGaugeQuotientTemplateShiftCollapse
        M n hn htb hns))
    hcases

/-- keepFOB P-side path preserved: the concrete keepFOB rich-projection target
follows from active cases plus the exact quotient-to-original lift.  The
keepFOB NP field is the already-proved one from the keepFOB assembly; this
theorem does not prove any new NP preservation for the quotient adapter. -/
theorem cookLevinRichProjectionTarget_of_keepFOB_activeCases_zeroGaugeQuotientLift
    (M : DTM) (n : Nat) (hn : n ≥ 2 ^ 804) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (hlift :
      CookLevinZeroProfileGaugeQuotientLiftToTemplateCollapse
        M n hn2 htb hns)
    (hcases :
      CookLevinProfileTemplateCollapseActiveAdmissibleProfileCases
        M n hn2 htb hns) :
    CookLevinRichProjectionTarget M n hn hn2 htb hns :=
  cookLevinRichProjectionTarget_of_keepFOB_boundedProfileTemplateCollapse
    M n hn hn2 htb hns
    (cookLevinProfileTemplateCollapseLemmaBoundedProfile_of_activeCases_zeroGaugeQuotientLift
      M n hn2 htb hns
      (ge_four_of_ge_two_pow_804_for_zeroProfileGaugeQuotient hn)
      hlift hcases)

/-! ## Axiom audit anchors -/

#print axioms zeroProfileGaugeQuotientMap_one_shift_eq_X_shift
#print axioms zeroProfileGaugeQuotientScalarObligation
#print axioms zeroProfileGaugeQuotientImageSpan_finrank_le_one
#print axioms zeroProfileGaugeQuotientTemplateShiftCollapse
#print axioms cookLevinZeroProfileGaugeQuotient_one_shift_eq_X_shift
#print axioms cookLevinZeroProfile_originalScalar_false_and_quotientScalar_true
#print axioms cookLevinProfileTemplateCollapseLemmaBoundedProfile_of_activeCases_zeroGaugeQuotientLift
#print axioms cookLevinRichProjectionTarget_of_keepFOB_activeCases_zeroGaugeQuotientLift

end PathB
end DeepMath
end Paper93
end PallLean
