import PallLean.Paper93.DeepMath.PathB.ZeroProfileCompressedSpanProgress
import PallLean.Paper93.Paper283.RouteBRicherGaugePWindowConcreteCover

/-!
# Zero-profile quotient/type-space compression

This file adds the projected replacement interface for the all-zero
Cook-Levin profile.  The unquotiented local type-space obligation in
`ZeroProfileCompressedSpanProgress` is too strong: singleton shifts already
force dimension at least the ambient variable count.  The interface below
therefore separates two pieces of data:

* a linear projection/quotient map whose kernel contains the singleton-shift
  obstruction;
* a finite local type alphabet for the projected rows, plus an explicitly paid
  residual span for what the projection removes.

No concrete Cook-Levin local typing is claimed here.
-/

namespace PallLean
namespace Paper93
namespace DeepMath
namespace PathB

open MvPolynomial SymmetricPowerBound TuringMachine PaperFaithfulSeparation
open WithinProfileBound MultilinearSPDP SPDP
open scoped BigOperators

attribute [local instance] Classical.dec

/-! ## Singleton obstruction killed by a projection -/

/-- The subspace generated by singleton-shift zero-profile rows.  This is the
checked obstruction that makes the unquotiented zero-profile type-space target
too large at paper scale. -/
noncomputable def zeroProfileSingletonShiftSubspace {n L : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
  Submodule.span ℚ
    (Set.range
      (fun i : Fin n =>
        mlProj (MvPolynomial.X i * Finset.univ.prod factors)))

/-- The finite singleton-shift basis used to pay the quotient residual. -/
noncomputable def zeroProfileSingletonShiftBasis {n L : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    Finset (MvPolynomial (Fin n) ℚ) :=
  Finset.univ.image
    (fun i : Fin n =>
      mlProj (MvPolynomial.X i * Finset.univ.prod factors))

/-- The finite singleton-shift basis spans the singleton-shift subspace. -/
theorem zeroProfileSingletonShiftSubspace_eq_span_singletonShiftBasis
    {n L : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    zeroProfileSingletonShiftSubspace factors =
      Submodule.span ℚ
        (↑(zeroProfileSingletonShiftBasis factors) :
          Set (MvPolynomial (Fin n) ℚ)) := by
  classical
  have hset :
      Set.range
          (fun i : Fin n =>
            mlProj (MvPolynomial.X i * Finset.univ.prod factors)) =
        (↑(zeroProfileSingletonShiftBasis factors) :
          Set (MvPolynomial (Fin n) ℚ)) := by
    ext q
    constructor
    · rintro ⟨i, rfl⟩
      change
        mlProj (MvPolynomial.X i * Finset.univ.prod factors) ∈
          Finset.univ.image
            (fun i : Fin n =>
              mlProj (MvPolynomial.X i * Finset.univ.prod factors))
      exact Finset.mem_image.mpr ⟨i, Finset.mem_univ i, rfl⟩
    · intro hq
      change q ∈
        Finset.univ.image
          (fun i : Fin n =>
            mlProj (MvPolynomial.X i * Finset.univ.prod factors)) at hq
      rcases Finset.mem_image.mp hq with ⟨i, _hi, rfl⟩
      exact ⟨i, rfl⟩
  unfold zeroProfileSingletonShiftSubspace
  rw [hset]

/-- Paying all singleton-shift residual rows costs at most the ambient
variable count. -/
theorem zeroProfileSingletonShiftBasis_card_le_ambient
    {n L : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    (zeroProfileSingletonShiftBasis factors).card ≤ n := by
  classical
  calc
    (zeroProfileSingletonShiftBasis factors).card
        ≤ (Finset.univ : Finset (Fin n)).card := by
          unfold zeroProfileSingletonShiftBasis
          exact Finset.card_image_le
    _ = n := Fintype.card_fin n

/-- A projection/quotient map kills the singleton-shift obstruction. -/
def ZeroProfileProjectionKillsSingletonShifts {n L : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ) : Prop :=
  ∀ i : Fin n,
    project (mlProj (MvPolynomial.X i * Finset.univ.prod factors)) = 0

/-- Kernel form of `ZeroProfileProjectionKillsSingletonShifts`. -/
theorem zeroProfileProjectionKillsSingletonShifts_iff_singletonShiftSubspace_le_ker
    {n L : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ) :
    ZeroProfileProjectionKillsSingletonShifts factors project ↔
      zeroProfileSingletonShiftSubspace factors ≤ LinearMap.ker project := by
  constructor
  · intro hkills
    unfold zeroProfileSingletonShiftSubspace
    apply Submodule.span_le.mpr
    intro row hrow
    rcases hrow with ⟨i, rfl⟩
    exact LinearMap.mem_ker.mpr (hkills i)
  · intro hker i
    exact LinearMap.mem_ker.mp
      (hker (Submodule.subset_span (Set.mem_range_self i)))

/-! ## Canonical quotient by singleton-shift directions -/

/-- A chosen complement to the singleton-shift subspace.  The corresponding
projection below is the quotient representative that removes singleton
directions and leaves the complement. -/
noncomputable def zeroProfileSingletonShiftComplement {n L : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
  Classical.choose (zeroProfileSingletonShiftSubspace factors).exists_isCompl

/-- The chosen singleton-shift complement is complementary to the singleton
subspace. -/
theorem zeroProfileSingletonShiftSubspace_isCompl_complement
    {n L : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    IsCompl (zeroProfileSingletonShiftSubspace factors)
      (zeroProfileSingletonShiftComplement factors) :=
  Classical.choose_spec (zeroProfileSingletonShiftSubspace factors).exists_isCompl

/-- Projection to the chosen complement along the singleton-shift subspace. -/
noncomputable def zeroProfileQuotientBySingletonShiftProjection {n L : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ :=
  Submodule.IsCompl.projection
    (zeroProfileSingletonShiftSubspace_isCompl_complement factors).symm

/-- The chosen singleton quotient projection is idempotent. -/
theorem zeroProfileQuotientBySingletonShiftProjection_idempotent
    {n L : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    (zeroProfileQuotientBySingletonShiftProjection factors).comp
        (zeroProfileQuotientBySingletonShiftProjection factors) =
      zeroProfileQuotientBySingletonShiftProjection factors := by
  simpa [zeroProfileQuotientBySingletonShiftProjection,
    IsIdempotentElem] using
    (Submodule.IsCompl.projection_isIdempotentElem
      (zeroProfileSingletonShiftSubspace_isCompl_complement factors).symm)

/-- The chosen singleton quotient projection kills the singleton-shift
subspace. -/
theorem zeroProfileQuotientBySingletonShiftProjection_singletonShiftSubspace_le_ker
    {n L : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    zeroProfileSingletonShiftSubspace factors ≤
      LinearMap.ker (zeroProfileQuotientBySingletonShiftProjection factors) := by
  intro q hq
  exact LinearMap.mem_ker.mpr (by
    simpa [zeroProfileQuotientBySingletonShiftProjection] using
      ((Submodule.IsCompl.projection_apply_eq_zero_iff
        (zeroProfileSingletonShiftSubspace_isCompl_complement
          factors).symm).mpr hq))

/-- The chosen singleton quotient projection kills every singleton-shift row. -/
theorem zeroProfileQuotientBySingletonShiftProjection_killsSingletonShifts
    {n L : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    ZeroProfileProjectionKillsSingletonShifts factors
      (zeroProfileQuotientBySingletonShiftProjection factors) := by
  exact
    (zeroProfileProjectionKillsSingletonShifts_iff_singletonShiftSubspace_le_ker
      factors (zeroProfileQuotientBySingletonShiftProjection factors)).mpr
      (zeroProfileQuotientBySingletonShiftProjection_singletonShiftSubspace_le_ker
        factors)

/-- The residual of the chosen singleton quotient projection always lies in
the singleton-shift subspace. -/
theorem zeroProfileQuotientBySingletonShiftProjection_residual_mem_singletonShiftSubspace
    {n L : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (q : MvPolynomial (Fin n) ℚ) :
    q - zeroProfileQuotientBySingletonShiftProjection factors q ∈
      zeroProfileSingletonShiftSubspace factors := by
  classical
  let h :
      IsCompl (zeroProfileSingletonShiftSubspace factors)
        (zeroProfileSingletonShiftComplement factors) :=
    zeroProfileSingletonShiftSubspace_isCompl_complement factors
  have hres :
      Submodule.IsCompl.projection h q =
        q - zeroProfileQuotientBySingletonShiftProjection factors q := by
    simpa [h, zeroProfileQuotientBySingletonShiftProjection] using
      (Submodule.IsCompl.projection_eq_self_sub_projection h.symm q)
  rw [← hres]
  exact Submodule.IsCompl.projection_apply_mem h q

/-! ## Projected type alphabets -/

/-- A finite local type alphabet for projected zero-profile rows.

The budget is explicit so residual/kernel rows can be paid for separately
before comparing the total with `withinProfileBound`. -/
structure ZeroProfileQuotientTypeAlphabet (n typeBudget : ℕ) where
  type : Type
  [typeFintype : Fintype type]
  localDim : ℕ
  localBasis : type → Finset (MvPolynomial (Fin n) ℚ)
  localBasis_card_le : ∀ τ, (localBasis τ).card ≤ localDim
  symmetricProfileBudget_le :
    Fintype.card type * localDim ≤ typeBudget

/-- The ambient type space represented by one quotient type. -/
noncomputable def zeroProfileQuotientTypeSpace {n typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget)
    (τ : A.type) :
    Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
  Submodule.span ℚ
    (↑(A.localBasis τ) : Set (MvPolynomial (Fin n) ℚ))

/-- Each quotient type space has dimension bounded by `localDim`. -/
theorem zeroProfileQuotientTypeSpace_finrank_le {n typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget)
    (τ : A.type) :
    Module.finrank ℚ ↥(zeroProfileQuotientTypeSpace A τ) ≤
      A.localDim := by
  classical
  unfold zeroProfileQuotientTypeSpace
  exact (finrank_span_finset_le_card (A.localBasis τ)).trans
    (A.localBasis_card_le τ)

/-- Global projected normal-form basis obtained by unioning the per-type
local bases. -/
noncomputable def zeroProfileQuotientTypeGlobalBasis {n typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget) :
    Finset (MvPolynomial (Fin n) ℚ) := by
  classical
  letI : Fintype A.type := A.typeFintype
  exact Finset.univ.biUnion A.localBasis

/-- The global projected normal-form basis fits inside its explicit type
budget. -/
theorem zeroProfileQuotientTypeGlobalBasis_card_le_typeBudget
    {n typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget) :
    (zeroProfileQuotientTypeGlobalBasis A).card ≤ typeBudget := by
  classical
  letI : Fintype A.type := A.typeFintype
  have hcard :
      (Finset.univ.biUnion A.localBasis).card ≤
        (Finset.univ : Finset A.type).card * A.localDim :=
    Finset.card_biUnion_le_card_mul
      (Finset.univ : Finset A.type) A.localBasis A.localDim
      (by
        intro τ _hτ
        exact A.localBasis_card_le τ)
  have htype_card :
      (Finset.univ : Finset A.type).card = Fintype.card A.type :=
    Finset.card_univ
  simpa [zeroProfileQuotientTypeGlobalBasis, htype_card] using
    hcard.trans A.symmetricProfileBudget_le

/-- The compressed projected type span represented by the quotient alphabet. -/
noncomputable def zeroProfileQuotientTypeCompressedSpan {n typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget) :
    Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
  Submodule.span ℚ
    (↑(zeroProfileQuotientTypeGlobalBasis A) :
      Set (MvPolynomial (Fin n) ℚ))

/-- A single quotient type space is contained in the global quotient type
span. -/
theorem zeroProfileQuotientTypeSpace_le_compressedSpan {n typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget)
    (τ : A.type) :
    zeroProfileQuotientTypeSpace A τ ≤
      zeroProfileQuotientTypeCompressedSpan A := by
  classical
  letI : Fintype A.type := A.typeFintype
  unfold zeroProfileQuotientTypeSpace zeroProfileQuotientTypeCompressedSpan
  apply Submodule.span_mono
  intro q hq
  change q ∈ zeroProfileQuotientTypeGlobalBasis A
  unfold zeroProfileQuotientTypeGlobalBasis
  exact Finset.mem_biUnion.mpr ⟨τ, Finset.mem_univ τ, hq⟩

/-- Projected zero-profile shifted rows. -/
noncomputable def zeroProfileProjectedShiftImageSet {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ) :
    Set (MvPolynomial (Fin n) ℚ) :=
  project '' zeroProfileShiftImageSet κ factors

/-- The exact projected quotient span of the zero-profile shifted rows. -/
noncomputable def zeroProfileProjectedShiftSpan {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ) :
    Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
  (zeroProfileCompressedShiftSpan κ factors).map project

/-- Projecting the exact compressed zero-profile span is the same as spanning
the projected row image.  This is the factor-through statement used by the
singleton-quotient classifier below. -/
theorem zeroProfileProjectedShiftSpan_eq_span_projectedShiftImageSet
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ) :
    zeroProfileProjectedShiftSpan κ factors project =
      Submodule.span ℚ
        (zeroProfileProjectedShiftImageSet κ factors project) := by
  rw [zeroProfileProjectedShiftSpan, zeroProfileCompressedShiftSpan,
    zeroProfileProjectedShiftImageSet, Submodule.map_span]

/-- The exact projected shifted span remains finite-dimensional. -/
theorem zeroProfileProjectedShiftSpan_finite
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ) :
    Module.Finite ℚ ↥(zeroProfileProjectedShiftSpan κ factors project) := by
  classical
  unfold zeroProfileProjectedShiftSpan
  haveI :
      Module.Finite ℚ ↥(zeroProfileCompressedShiftSpan κ factors) :=
    zeroProfileCompressedShiftSpan_finite κ factors
  infer_instance

/-- Budgeted common-span form for projected zero-profile shifted rows. -/
def ZeroProfileProjectedCommonSpanWithBudget {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ)
    (budget : ℕ) : Prop :=
  ∃ G : Finset (MvPolynomial (Fin n) ℚ),
    G.card ≤ budget ∧
    zeroProfileProjectedShiftImageSet κ factors project ⊆
      Submodule.span ℚ (↑G : Set (MvPolynomial (Fin n) ℚ))

/-- Generator-to-type map after projection. -/
structure ZeroProfileProjectedGeneratorTypeMap {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ) where
  rowType :
    ∀ (S : List (Fin n)), S.length ≤ κ →
      ∀ shift : MvPolynomial (Fin n) ℚ, shift.vars ⊆ S.toFinset →
        A.type
  projected_row_mem_typeSpace :
    ∀ (S : List (Fin n)) (hS : S.length ≤ κ)
      (shift : MvPolynomial (Fin n) ℚ) (hshift : shift.vars ⊆ S.toFinset),
        project (mlProj (shift * Finset.univ.prod factors)) ∈
          zeroProfileQuotientTypeSpace A (rowType S hS shift hshift)

/-- A projected generator type map puts every projected row in the global
quotient type span. -/
theorem zeroProfileProjectedGeneratorTypeMap_row_mem_compressedSpan
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ)
    (hmap : ZeroProfileProjectedGeneratorTypeMap κ factors A project)
    (S : List (Fin n)) (hS : S.length ≤ κ)
    (shift : MvPolynomial (Fin n) ℚ) (hshift : shift.vars ⊆ S.toFinset) :
    project (mlProj (shift * Finset.univ.prod factors)) ∈
      zeroProfileQuotientTypeCompressedSpan A :=
  (zeroProfileQuotientTypeSpace_le_compressedSpan A
    (hmap.rowType S hS shift hshift))
    (hmap.projected_row_mem_typeSpace S hS shift hshift)

/-- Projected shifted rows are contained in the quotient type span. -/
theorem zeroProfileProjectedShiftImageSet_subset_quotientTypeCompressedSpan
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ)
    (hmap : ZeroProfileProjectedGeneratorTypeMap κ factors A project) :
    zeroProfileProjectedShiftImageSet κ factors project ⊆
      zeroProfileQuotientTypeCompressedSpan A := by
  intro q hq
  rcases hq with ⟨row, hrow, rfl⟩
  simp only [zeroProfileShiftImageSet, Set.mem_iUnion,
    Set.mem_singleton_iff] at hrow
  rcases hrow with ⟨S, hS, shift, hshift, row_eq⟩
  rw [row_eq]
  exact zeroProfileProjectedGeneratorTypeMap_row_mem_compressedSpan
    κ factors A project hmap S hS shift hshift

/-- A projected local type map gives a budgeted common span for the projected
zero-profile rows. -/
theorem zeroProfileProjectedCommonSpanWithBudget_of_projectedTypeMap
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ)
    (hmap : ZeroProfileProjectedGeneratorTypeMap κ factors A project) :
    ZeroProfileProjectedCommonSpanWithBudget κ factors project typeBudget := by
  classical
  refine ⟨zeroProfileQuotientTypeGlobalBasis A,
    zeroProfileQuotientTypeGlobalBasis_card_le_typeBudget A, ?_⟩
  simpa [zeroProfileQuotientTypeCompressedSpan] using
    zeroProfileProjectedShiftImageSet_subset_quotientTypeCompressedSpan
      κ factors A project hmap

/-- A budgeted projected common span bounds the exact projected shifted-span
finrank.  This is the local compression direction used to discharge projected
singleton quotient budgets without invoking shifted-support enumeration. -/
theorem zeroProfileProjectedShiftSpan_finrank_le_of_commonSpanWithBudget_quotient
    {n L κ budget : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ)
    (hspan :
      ZeroProfileProjectedCommonSpanWithBudget κ factors project budget) :
    Module.finrank ℚ ↥(zeroProfileProjectedShiftSpan κ factors project) ≤
      budget := by
  classical
  rcases hspan with ⟨G, hG_card, hG_span⟩
  have hle :
      zeroProfileProjectedShiftSpan κ factors project ≤
        Submodule.span ℚ
          (↑G : Set (MvPolynomial (Fin n) ℚ)) := by
    rw [zeroProfileProjectedShiftSpan_eq_span_projectedShiftImageSet]
    exact Submodule.span_le.mpr hG_span
  haveI hprojFinite :
      Module.Finite ℚ ↥(zeroProfileProjectedShiftSpan κ factors project) :=
    zeroProfileProjectedShiftSpan_finite κ factors project
  haveI hspanFinite :
      Module.Finite ℚ
        ↥(Submodule.span ℚ
          (↑G : Set (MvPolynomial (Fin n) ℚ))) :=
    Module.Finite.span_of_finite ℚ (Finset.finite_toSet G)
  exact
    (Submodule.finrank_mono hle).trans
      ((finrank_span_finset_le_card G).trans hG_card)

/-! ## Exact projected-span classifier -/

/-- A finite spanning basis for the exact projected zero-profile shifted span,
chosen with cardinality bounded by its finrank. -/
noncomputable def zeroProfileProjectedShiftSpanBasis
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ) :
    Finset (MvPolynomial (Fin n) ℚ) := by
  classical
  let U := zeroProfileProjectedShiftSpan κ factors project
  haveI : Module.Finite ℚ ↥U :=
    zeroProfileProjectedShiftSpan_finite κ factors project
  exact Classical.choose
    (finite_submodule_le_span_finset_card_le_finrank U)

/-- The chosen projected-span basis spans the whole projected zero-profile
shifted span. -/
theorem zeroProfileProjectedShiftSpan_le_basis_span
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ) :
    zeroProfileProjectedShiftSpan κ factors project ≤
      Submodule.span ℚ
        (↑(zeroProfileProjectedShiftSpanBasis κ factors project) :
          Set (MvPolynomial (Fin n) ℚ)) := by
  classical
  let U := zeroProfileProjectedShiftSpan κ factors project
  haveI : Module.Finite ℚ ↥U :=
    zeroProfileProjectedShiftSpan_finite κ factors project
  simpa [zeroProfileProjectedShiftSpanBasis, U] using
    (Classical.choose_spec
      (finite_submodule_le_span_finset_card_le_finrank U)).1

/-- The chosen projected-span basis has cardinality bounded by the exact
projected zero-profile shifted-span finrank. -/
theorem zeroProfileProjectedShiftSpanBasis_card_le_finrank
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ) :
    (zeroProfileProjectedShiftSpanBasis κ factors project).card ≤
      Module.finrank ℚ
        ↥(zeroProfileProjectedShiftSpan κ factors project) := by
  classical
  let U := zeroProfileProjectedShiftSpan κ factors project
  haveI : Module.Finite ℚ ↥U :=
    zeroProfileProjectedShiftSpan_finite κ factors project
  simpa [zeroProfileProjectedShiftSpanBasis, U] using
    (Classical.choose_spec
      (finite_submodule_le_span_finset_card_le_finrank U)).2

/-- The exact projected zero-profile shifted-span finrank is a complete
projected common-span budget. -/
theorem zeroProfileProjectedCommonSpanWithBudget_of_projectedShiftSpan_finrank
    {n L κ budget : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ)
    (hbudget :
      Module.finrank ℚ
          ↥(zeroProfileProjectedShiftSpan κ factors project) ≤
        budget) :
    ZeroProfileProjectedCommonSpanWithBudget κ factors project budget := by
  classical
  refine
    ⟨zeroProfileProjectedShiftSpanBasis κ factors project,
      (zeroProfileProjectedShiftSpanBasis_card_le_finrank
        κ factors project).trans hbudget, ?_⟩
  intro q hq
  exact
    zeroProfileProjectedShiftSpan_le_basis_span κ factors project
      (by
        rw [zeroProfileProjectedShiftSpan_eq_span_projectedShiftImageSet]
        exact Submodule.subset_span hq)

/-! ## Exact singleton-quotient projected classifier -/

/-- The corrected quotient type budget: the actual finrank of the projected
zero-profile shifted span after killing singleton shifts. -/
noncomputable def zeroProfileSingletonQuotientProjectedTypeBudget
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) : ℕ :=
  Module.finrank ℚ
    ↥(zeroProfileProjectedShiftSpan κ factors
      (zeroProfileQuotientBySingletonShiftProjection factors))

/-- A finite spanning basis for the exact projected singleton-quotient span,
chosen with cardinality bounded by its finrank. -/
noncomputable def zeroProfileSingletonQuotientProjectedBasis
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    Finset (MvPolynomial (Fin n) ℚ) := by
  classical
  let project := zeroProfileQuotientBySingletonShiftProjection factors
  let U := zeroProfileProjectedShiftSpan κ factors project
  haveI : Module.Finite ℚ ↥U :=
    zeroProfileProjectedShiftSpan_finite κ factors project
  exact Classical.choose
    (finite_submodule_le_span_finset_card_le_finrank U)

/-- The chosen projected singleton-quotient basis spans the whole projected
quotient image. -/
theorem zeroProfileSingletonQuotientProjectedSpan_le_basis_span
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    zeroProfileProjectedShiftSpan κ factors
        (zeroProfileQuotientBySingletonShiftProjection factors) ≤
      Submodule.span ℚ
        (↑(zeroProfileSingletonQuotientProjectedBasis κ factors) :
          Set (MvPolynomial (Fin n) ℚ)) := by
  classical
  let project := zeroProfileQuotientBySingletonShiftProjection factors
  let U := zeroProfileProjectedShiftSpan κ factors project
  haveI : Module.Finite ℚ ↥U :=
    zeroProfileProjectedShiftSpan_finite κ factors project
  simpa [zeroProfileSingletonQuotientProjectedBasis, U, project] using
    (Classical.choose_spec
      (finite_submodule_le_span_finset_card_le_finrank U)).1

/-- The chosen projected singleton-quotient basis has cardinality bounded by
the exact projected quotient finrank. -/
theorem zeroProfileSingletonQuotientProjectedBasis_card_le_typeBudget
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    (zeroProfileSingletonQuotientProjectedBasis κ factors).card ≤
      zeroProfileSingletonQuotientProjectedTypeBudget κ factors := by
  classical
  let project := zeroProfileQuotientBySingletonShiftProjection factors
  let U := zeroProfileProjectedShiftSpan κ factors project
  haveI : Module.Finite ℚ ↥U :=
    zeroProfileProjectedShiftSpan_finite κ factors project
  simpa [zeroProfileSingletonQuotientProjectedBasis,
    zeroProfileSingletonQuotientProjectedTypeBudget, U, project] using
    (Classical.choose_spec
      (finite_submodule_le_span_finset_card_le_finrank U)).2

/-- The one-type quotient alphabet whose local space is the exact projected
singleton-quotient span. -/
noncomputable def zeroProfileSingletonQuotientProjectedTypeAlphabet
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    ZeroProfileQuotientTypeAlphabet n
      (zeroProfileSingletonQuotientProjectedTypeBudget κ factors) where
  type := PUnit
  typeFintype := inferInstance
  localDim := zeroProfileSingletonQuotientProjectedTypeBudget κ factors
  localBasis := fun _ =>
    zeroProfileSingletonQuotientProjectedBasis κ factors
  localBasis_card_le := fun _ =>
    zeroProfileSingletonQuotientProjectedBasis_card_le_typeBudget κ factors
  symmetricProfileBudget_le := by
    simp

/-- Every projected generator row for the singleton quotient factors through
the exact projected quotient span. -/
theorem zeroProfileSingletonQuotient_projectedRow_mem_projectedShiftSpan
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (S : List (Fin n)) (hS : S.length ≤ κ)
    (shift : MvPolynomial (Fin n) ℚ) (hshift : shift.vars ⊆ S.toFinset) :
    zeroProfileQuotientBySingletonShiftProjection factors
        (mlProj (shift * Finset.univ.prod factors)) ∈
      zeroProfileProjectedShiftSpan κ factors
        (zeroProfileQuotientBySingletonShiftProjection factors) := by
  classical
  have hrow :
      mlProj (shift * Finset.univ.prod factors) ∈
        zeroProfileShiftImageSet κ factors := by
    simp only [zeroProfileShiftImageSet, Set.mem_iUnion,
      Set.mem_singleton_iff]
    exact ⟨S, hS, shift, hshift, rfl⟩
  exact Submodule.mem_map_of_mem (Submodule.subset_span hrow)

/-- Actual projected quotient type-map for the chosen singleton quotient.  It
uses the exact projected quotient span as the local type space, with budget
equal to that span's finrank. -/
noncomputable def zeroProfileSingletonQuotientProjectedGeneratorTypeMap
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    ZeroProfileProjectedGeneratorTypeMap κ factors
      (zeroProfileSingletonQuotientProjectedTypeAlphabet κ factors)
      (zeroProfileQuotientBySingletonShiftProjection factors) where
  rowType := fun _ _ _ _ => PUnit.unit
  projected_row_mem_typeSpace := by
    intro S hS shift hshift
    have hrow :=
      zeroProfileSingletonQuotient_projectedRow_mem_projectedShiftSpan
        κ factors S hS shift hshift
    exact
      zeroProfileSingletonQuotientProjectedSpan_le_basis_span
        κ factors hrow

/-- The concrete singleton-quotient classifier gives the projected common-span
budget with no assumed row map. -/
theorem zeroProfileProjectedCommonSpanWithBudget_singletonQuotient_projectedFinrank
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    ZeroProfileProjectedCommonSpanWithBudget κ factors
      (zeroProfileQuotientBySingletonShiftProjection factors)
      (zeroProfileSingletonQuotientProjectedTypeBudget κ factors) :=
  zeroProfileProjectedCommonSpanWithBudget_of_projectedTypeMap
    κ factors
    (zeroProfileSingletonQuotientProjectedTypeAlphabet κ factors)
    (zeroProfileQuotientBySingletonShiftProjection factors)
    (zeroProfileSingletonQuotientProjectedGeneratorTypeMap κ factors)

/-- The singleton quotient alphabet, re-budgeted at any larger type budget.

This is the concrete projected type-map instantiation of the exact singleton
quotient span: the local basis remains the chosen projected-span basis, while
the ambient type budget is any `typeBudget` above the exact finrank. -/
noncomputable def zeroProfileSingletonQuotientProjectedTypeAlphabet_of_budget
    {n L κ typeBudget : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (hbudget :
      zeroProfileSingletonQuotientProjectedTypeBudget κ factors ≤
        typeBudget) :
    ZeroProfileQuotientTypeAlphabet n typeBudget where
  type := PUnit
  typeFintype := inferInstance
  localDim := zeroProfileSingletonQuotientProjectedTypeBudget κ factors
  localBasis := fun _ =>
    zeroProfileSingletonQuotientProjectedBasis κ factors
  localBasis_card_le := fun _ =>
    zeroProfileSingletonQuotientProjectedBasis_card_le_typeBudget κ factors
  symmetricProfileBudget_le := by
    simpa using hbudget

/-- The budget-relaxed singleton quotient alphabet carries the same concrete
projected generator type map as the exact-finrank alphabet. -/
noncomputable def zeroProfileSingletonQuotientProjectedGeneratorTypeMap_of_budget
    {n L κ typeBudget : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (hbudget :
      zeroProfileSingletonQuotientProjectedTypeBudget κ factors ≤
        typeBudget) :
    ZeroProfileProjectedGeneratorTypeMap κ factors
      (zeroProfileSingletonQuotientProjectedTypeAlphabet_of_budget
        factors hbudget)
      (zeroProfileQuotientBySingletonShiftProjection factors) where
  rowType := fun _ _ _ _ => PUnit.unit
  projected_row_mem_typeSpace := by
    intro S hS shift hshift
    have hrow :=
      zeroProfileSingletonQuotient_projectedRow_mem_projectedShiftSpan
        κ factors S hS shift hshift
    simpa [zeroProfileSingletonQuotientProjectedTypeAlphabet_of_budget]
      using zeroProfileSingletonQuotientProjectedSpan_le_basis_span
        κ factors hrow

/-- Any projected common-span certificate for the singleton quotient bounds
the exact singleton-quotient projected type budget. -/
theorem zeroProfileSingletonQuotientProjectedTypeBudget_le_of_projectedCommonSpan
    {n L κ budget : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (hspan :
      ZeroProfileProjectedCommonSpanWithBudget κ factors
        (zeroProfileQuotientBySingletonShiftProjection factors) budget) :
    zeroProfileSingletonQuotientProjectedTypeBudget κ factors ≤ budget := by
  simpa [zeroProfileSingletonQuotientProjectedTypeBudget] using
    zeroProfileProjectedShiftSpan_finrank_le_of_commonSpanWithBudget_quotient
      (κ := κ) factors
      (zeroProfileQuotientBySingletonShiftProjection factors) hspan

/-- For the concrete singleton quotient, a budgeted projected common span is
equivalent to the exact projected quotient finrank fitting in that budget. -/
theorem zeroProfileSingletonQuotient_projectedCommonSpanWithBudget_iff_projectedTypeBudget_le
    {n L κ budget : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    ZeroProfileProjectedCommonSpanWithBudget κ factors
        (zeroProfileQuotientBySingletonShiftProjection factors) budget ↔
      zeroProfileSingletonQuotientProjectedTypeBudget κ factors ≤
        budget := by
  constructor
  · intro hspan
    exact
      zeroProfileSingletonQuotientProjectedTypeBudget_le_of_projectedCommonSpan
        factors hspan
  · intro hbudget
    simpa [zeroProfileSingletonQuotientProjectedTypeBudget] using
      zeroProfileProjectedCommonSpanWithBudget_of_projectedShiftSpan_finrank
        (κ := κ)
        factors
        (zeroProfileQuotientBySingletonShiftProjection factors)
        hbudget

/-- A projected common-span certificate for the singleton quotient discharges
the exact projected type-budget gate once its own budget fits the profile
bound. -/
theorem zeroProfileSingletonQuotientProjectedTypeBudget_le_withinProfileBound_of_projectedCommonSpan
    {n L κ budget : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (hspan :
      ZeroProfileProjectedCommonSpanWithBudget κ factors
        (zeroProfileQuotientBySingletonShiftProjection factors) budget)
    (hbudget : budget ≤ withinProfileBound κ) :
    zeroProfileSingletonQuotientProjectedTypeBudget κ factors ≤
      withinProfileBound κ :=
  (zeroProfileSingletonQuotientProjectedTypeBudget_le_of_projectedCommonSpan
    factors hspan).trans hbudget

/-- A quotient type map for the singleton quotient bounds the exact projected
singleton quotient finrank by its type budget. -/
theorem zeroProfileSingletonQuotientProjectedTypeBudget_le_of_projectedTypeMap
    {n L κ typeBudget : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget)
    (hmap :
      ZeroProfileProjectedGeneratorTypeMap κ factors A
        (zeroProfileQuotientBySingletonShiftProjection factors)) :
    zeroProfileSingletonQuotientProjectedTypeBudget κ factors ≤ typeBudget :=
  zeroProfileSingletonQuotientProjectedTypeBudget_le_of_projectedCommonSpan
    factors
    (zeroProfileProjectedCommonSpanWithBudget_of_projectedTypeMap
      κ factors A (zeroProfileQuotientBySingletonShiftProjection factors)
      hmap)

/-- For the concrete singleton quotient, having some projected type map at a
given type budget is equivalent to the exact projected quotient finrank fitting
inside that type budget. -/
theorem zeroProfileSingletonQuotient_projectedTypeMap_iff_projectedTypeBudget_le
    {n L κ typeBudget : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    (∃ A : ZeroProfileQuotientTypeAlphabet n typeBudget,
        Nonempty
          (ZeroProfileProjectedGeneratorTypeMap κ factors A
            (zeroProfileQuotientBySingletonShiftProjection factors))) ↔
      zeroProfileSingletonQuotientProjectedTypeBudget κ factors ≤
        typeBudget := by
  constructor
  · rintro ⟨A, ⟨hmap⟩⟩
    exact
      zeroProfileSingletonQuotientProjectedTypeBudget_le_of_projectedTypeMap
        factors A hmap
  · intro hbudget
    exact
      ⟨zeroProfileSingletonQuotientProjectedTypeAlphabet_of_budget
          factors hbudget,
        ⟨zeroProfileSingletonQuotientProjectedGeneratorTypeMap_of_budget
          factors hbudget⟩⟩

/-- A quotient type map for the singleton quotient closes the exact projected
type-budget gate when its type budget fits the profile bound. -/
theorem zeroProfileSingletonQuotientProjectedTypeBudget_le_withinProfileBound_of_projectedTypeMap
    {n L κ typeBudget : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget)
    (hmap :
      ZeroProfileProjectedGeneratorTypeMap κ factors A
        (zeroProfileQuotientBySingletonShiftProjection factors))
    (hbudget : typeBudget ≤ withinProfileBound κ) :
    zeroProfileSingletonQuotientProjectedTypeBudget κ factors ≤
      withinProfileBound κ :=
  (zeroProfileSingletonQuotientProjectedTypeBudget_le_of_projectedTypeMap
    factors A hmap).trans hbudget

/-- The corrected singleton-quotient budget can only hold if the ambient
singleton residual itself fits inside the profile bound. -/
theorem ambient_le_withinProfileBound_of_singletonQuotient_projectedFinrank_budget
    {n L κ : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (hbudget :
      zeroProfileSingletonQuotientProjectedTypeBudget κ factors + n ≤
        withinProfileBound κ) :
    n ≤ withinProfileBound κ :=
  (Nat.le_add_left n
    (zeroProfileSingletonQuotientProjectedTypeBudget κ factors)).trans
    hbudget

/-- No-go form for the corrected singleton-quotient classifier budget: if the
within-profile budget is below the ambient singleton residual `n`, then the
projected-finrank classifier plus singleton residual cannot fit. -/
theorem not_singletonQuotient_projectedFinrank_budget_of_withinProfileBound_lt_ambient
    {n L κ : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (hlt : withinProfileBound κ < n) :
    ¬ zeroProfileSingletonQuotientProjectedTypeBudget κ factors + n ≤
        withinProfileBound κ := by
  intro hbudget
  exact (not_le_of_gt hlt)
    (ambient_le_withinProfileBound_of_singletonQuotient_projectedFinrank_budget
      factors hbudget)

/-- Full projected/quotient zero-profile type-space certificate.  The
projection is required to be idempotent and to kill singleton shifts; row
factorization is required only after projection. -/
structure ZeroProfileQuotientTypeSpaceCertificate {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (typeBudget : ℕ) where
  project : MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ
  project_idempotent : project.comp project = project
  killsSingleton : ZeroProfileProjectionKillsSingletonShifts factors project
  alphabet : ZeroProfileQuotientTypeAlphabet n typeBudget
  typeMap :
    ZeroProfileProjectedGeneratorTypeMap κ factors alphabet project

/-- The certificate's kernel contains the singleton-shift obstruction. -/
theorem zeroProfileQuotientTypeSpaceCertificate_singletonShiftSubspace_le_ker
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {typeBudget : ℕ}
    (cert :
      ZeroProfileQuotientTypeSpaceCertificate κ factors typeBudget) :
    zeroProfileSingletonShiftSubspace factors ≤ LinearMap.ker cert.project :=
  (zeroProfileProjectionKillsSingletonShifts_iff_singletonShiftSubspace_le_ker
    factors cert.project).mp cert.killsSingleton

/-- The certificate gives the projected common-span obligation. -/
theorem zeroProfileProjectedCommonSpanWithBudget_of_quotientTypeSpaceCertificate
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {typeBudget : ℕ}
    (cert :
      ZeroProfileQuotientTypeSpaceCertificate κ factors typeBudget) :
    ZeroProfileProjectedCommonSpanWithBudget
      κ factors cert.project typeBudget :=
  zeroProfileProjectedCommonSpanWithBudget_of_projectedTypeMap
    κ factors cert.alphabet cert.project cert.typeMap

/-- Full concrete certificate for the chosen singleton quotient, with the
projected type budget set to the exact projected quotient finrank. -/
noncomputable def zeroProfileSingletonQuotientTypeSpaceCertificate_projectedFinrank
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    ZeroProfileQuotientTypeSpaceCertificate κ factors
      (zeroProfileSingletonQuotientProjectedTypeBudget κ factors) where
  project := zeroProfileQuotientBySingletonShiftProjection factors
  project_idempotent :=
    zeroProfileQuotientBySingletonShiftProjection_idempotent factors
  killsSingleton :=
    zeroProfileQuotientBySingletonShiftProjection_killsSingletonShifts factors
  alphabet :=
    zeroProfileSingletonQuotientProjectedTypeAlphabet κ factors
  typeMap :=
    zeroProfileSingletonQuotientProjectedGeneratorTypeMap κ factors

/-! ## Separately paid projection residual -/

/-- A paid residual span for the rows removed by the projection.  This is the
honest way to turn a projected quotient certificate back into an unprojected
common-span statement. -/
def ZeroProfileProjectionResidualClosureWithBudget {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ)
    (residualBudget : ℕ) : Prop :=
  ∃ R : Finset (MvPolynomial (Fin n) ℚ),
    R.card ≤ residualBudget ∧
    ∀ q ∈ zeroProfileShiftImageSet κ factors,
      q - project q ∈
        Submodule.span ℚ (↑R : Set (MvPolynomial (Fin n) ℚ))

/-- If every projection residual lands in the singleton-shift subspace, then
the residual is paid by the finite singleton-shift basis with ambient budget
`n`. -/
theorem zeroProfileProjectionResidualClosureWithBudget_ambient_of_residual_mem_singletonShiftSubspace
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ)
    (hresidual :
      ∀ q ∈ zeroProfileShiftImageSet κ factors,
        q - project q ∈ zeroProfileSingletonShiftSubspace factors) :
    ZeroProfileProjectionResidualClosureWithBudget
      κ factors project n := by
  classical
  refine ⟨zeroProfileSingletonShiftBasis factors,
    zeroProfileSingletonShiftBasis_card_le_ambient factors, ?_⟩
  intro q hq
  simpa [zeroProfileSingletonShiftSubspace_eq_span_singletonShiftBasis] using
    hresidual q hq

/-- The chosen quotient by singleton shifts has residual closure with ambient
budget `n`: every removed component lies in the singleton-shift subspace. -/
theorem zeroProfileQuotientBySingletonShiftProjection_residualClosureWithBudget_ambient
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ) :
    ZeroProfileProjectionResidualClosureWithBudget κ factors
      (zeroProfileQuotientBySingletonShiftProjection factors) n :=
  zeroProfileProjectionResidualClosureWithBudget_ambient_of_residual_mem_singletonShiftSubspace
    κ factors (zeroProfileQuotientBySingletonShiftProjection factors)
    (fun q _hq =>
      zeroProfileQuotientBySingletonShiftProjection_residual_mem_singletonShiftSubspace
        factors q)

/-- Projected common span plus a paid residual span gives an unprojected
common span with the summed budget. -/
theorem zeroProfileCompressedSpanCommonSpanWithBudget_of_projectedCommonSpan_residualClosure
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ)
    {projectedBudget residualBudget budget : ℕ}
    (hprojected :
      ZeroProfileProjectedCommonSpanWithBudget
        κ factors project projectedBudget)
    (hresidual :
      ZeroProfileProjectionResidualClosureWithBudget
        κ factors project residualBudget)
    (hbudget : projectedBudget + residualBudget ≤ budget) :
    ZeroProfileCompressedSpanCommonSpanWithBudget κ factors budget := by
  classical
  rcases hprojected with ⟨G, hG_card, hG_span⟩
  rcases hresidual with ⟨R, hR_card, hR_span⟩
  refine ⟨G ∪ R, ?_, ?_⟩
  · calc
      (G ∪ R).card ≤ G.card + R.card := Finset.card_union_le G R
      _ ≤ projectedBudget + residualBudget :=
          Nat.add_le_add hG_card hR_card
      _ ≤ budget := hbudget
  · intro q hq
    have hprojected_mem :
        project q ∈
          Submodule.span ℚ
            (↑G : Set (MvPolynomial (Fin n) ℚ)) := by
      exact hG_span ⟨q, hq, rfl⟩
    have hresidual_mem :
        q - project q ∈
          Submodule.span ℚ
            (↑R : Set (MvPolynomial (Fin n) ℚ)) :=
      hR_span q hq
    have hG_subset :
        (↑G : Set (MvPolynomial (Fin n) ℚ)) ⊆
          (↑(G ∪ R) : Set (MvPolynomial (Fin n) ℚ)) := by
      intro x hx
      exact Finset.mem_union.mpr (Or.inl hx)
    have hR_subset :
        (↑R : Set (MvPolynomial (Fin n) ℚ)) ⊆
          (↑(G ∪ R) : Set (MvPolynomial (Fin n) ℚ)) := by
      intro x hx
      exact Finset.mem_union.mpr (Or.inr hx)
    have hprojected_union :
        project q ∈
          Submodule.span ℚ
            (↑(G ∪ R) : Set (MvPolynomial (Fin n) ℚ)) :=
      (Submodule.span_mono hG_subset) hprojected_mem
    have hresidual_union :
        q - project q ∈
          Submodule.span ℚ
            (↑(G ∪ R) : Set (MvPolynomial (Fin n) ℚ)) :=
      (Submodule.span_mono hR_subset) hresidual_mem
    have hsum :
        project q + (q - project q) ∈
          Submodule.span ℚ
            (↑(G ∪ R) : Set (MvPolynomial (Fin n) ℚ)) :=
      Submodule.add_mem _ hprojected_union hresidual_union
    simpa [sub_eq_add_neg, add_assoc, add_comm, add_left_comm] using hsum

/-- A quotient/type-space certificate plus a paid residual span gives an
unprojected common span. -/
theorem zeroProfileCompressedSpanCommonSpanWithBudget_of_quotientTypeSpaceCertificate_residualClosure
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {typeBudget residualBudget budget : ℕ}
    (cert :
      ZeroProfileQuotientTypeSpaceCertificate κ factors typeBudget)
    (hresidual :
      ZeroProfileProjectionResidualClosureWithBudget
        κ factors cert.project residualBudget)
    (hbudget : typeBudget + residualBudget ≤ budget) :
    ZeroProfileCompressedSpanCommonSpanWithBudget κ factors budget :=
  zeroProfileCompressedSpanCommonSpanWithBudget_of_projectedCommonSpan_residualClosure
    κ factors cert.project
    (zeroProfileProjectedCommonSpanWithBudget_of_quotientTypeSpaceCertificate
      κ factors cert)
    hresidual hbudget

/-- Projected common span for the chosen singleton quotient closes the
unprojected common-span target after paying exactly the ambient singleton
residual budget. -/
theorem zeroProfileCompressedSpanCommonSpanWithBudget_of_projectedCommonSpan_singletonQuotient
    {n L : ℕ}
    (κ : ℕ)
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    {projectedBudget budget : ℕ}
    (hprojected :
      ZeroProfileProjectedCommonSpanWithBudget κ factors
        (zeroProfileQuotientBySingletonShiftProjection factors)
        projectedBudget)
    (hbudget : projectedBudget + n ≤ budget) :
    ZeroProfileCompressedSpanCommonSpanWithBudget κ factors budget :=
  zeroProfileCompressedSpanCommonSpanWithBudget_of_projectedCommonSpan_residualClosure
    κ factors (zeroProfileQuotientBySingletonShiftProjection factors)
    hprojected
    (zeroProfileQuotientBySingletonShiftProjection_residualClosureWithBudget_ambient
      κ factors)
    hbudget

/-- The concrete singleton-quotient classifier closes the unprojected
zero-profile span exactly when the projected finrank plus the unavoidable
singleton residual budget fits. -/
theorem zeroProfileCompressedSpanCommonSpanWithBudget_of_singletonQuotient_projectedFinrank
    {n L κ budget : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (hbudget :
      zeroProfileSingletonQuotientProjectedTypeBudget κ factors + n ≤
        budget) :
    ZeroProfileCompressedSpanCommonSpanWithBudget κ factors budget :=
  zeroProfileCompressedSpanCommonSpanWithBudget_of_projectedCommonSpan_singletonQuotient
    κ factors
    (zeroProfileProjectedCommonSpanWithBudget_singletonQuotient_projectedFinrank
      κ factors)
    hbudget

/-- A projected quotient type map for the chosen singleton quotient closes the
unprojected common-span target after adding the ambient singleton residual
budget.  This is the positive classifier gate left by the singleton
obstruction: classify only modulo singleton shifts, then pay those shifts
separately. -/
theorem zeroProfileCompressedSpanCommonSpanWithBudget_of_singletonQuotientTypeMap
    {n L κ typeBudget budget : ℕ}
    (factors : Fin L → MvPolynomial (Fin n) ℚ)
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget)
    (hmap :
      ZeroProfileProjectedGeneratorTypeMap κ factors A
        (zeroProfileQuotientBySingletonShiftProjection factors))
    (hbudget : typeBudget + n ≤ budget) :
    ZeroProfileCompressedSpanCommonSpanWithBudget κ factors budget :=
  zeroProfileCompressedSpanCommonSpanWithBudget_of_projectedCommonSpan_singletonQuotient
    κ factors
    (zeroProfileProjectedCommonSpanWithBudget_of_projectedTypeMap
      κ factors A (zeroProfileQuotientBySingletonShiftProjection factors)
      hmap)
    hbudget

/-! ## Cook-Levin wrappers -/

/-- Cook-Levin quotient/projected zero-profile type-space obligation with an
explicit projected type budget. -/
def CookLevinZeroProfileQuotientTypeNormalFormObligation
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (typeBudget : ℕ) : Prop :=
  Nonempty
    (ZeroProfileQuotientTypeSpaceCertificate (Nat.log 2 n)
      (fun i => (cookLevinFactorList M n hn htb hns).get i)
      typeBudget)

/-- Cook-Levin projected zero-profile common-span obligation.  It remembers
that the chosen map is an idempotent projection and that its kernel contains
the singleton-shift obstruction. -/
def CookLevinZeroProfileProjectedCommonSpanObligation
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (typeBudget : ℕ) : Prop :=
  ∃ project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ,
    project.comp project = project ∧
      ZeroProfileProjectionKillsSingletonShifts
        (fun i => (cookLevinFactorList M n hn htb hns).get i)
        project ∧
      ZeroProfileProjectedCommonSpanWithBudget (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn htb hns).get i)
        project typeBudget

/-- Cook-Levin residual closure for a chosen quotient projection. -/
def CookLevinZeroProfileProjectionResidualClosureWithBudget
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (project :
      MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ)
    (residualBudget : ℕ) : Prop :=
  ZeroProfileProjectionResidualClosureWithBudget (Nat.log 2 n)
    (fun i => (cookLevinFactorList M n hn htb hns).get i)
    project residualBudget

/-- Cook-Levin residual closure for the chosen singleton quotient projection:
the removed singleton component is paid with ambient budget `n`. -/
theorem cookLevinZeroProfileSingletonQuotientResidualClosureWithBudget_ambient
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    CookLevinZeroProfileProjectionResidualClosureWithBudget
      M n hn htb hns
      (zeroProfileQuotientBySingletonShiftProjection
        (fun i => (cookLevinFactorList M n hn htb hns).get i))
      n := by
  simpa [CookLevinZeroProfileProjectionResidualClosureWithBudget] using
    zeroProfileQuotientBySingletonShiftProjection_residualClosureWithBudget_ambient
      (Nat.log 2 n)
      (fun i => (cookLevinFactorList M n hn htb hns).get i)

/-- A Cook-Levin quotient type certificate closes the projected zero-profile
common-span obligation. -/
theorem cookLevinZeroProfileProjectedCommonSpanWithBudget_of_quotientTypeCertificate
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    {typeBudget : ℕ}
    (cert :
      ZeroProfileQuotientTypeSpaceCertificate (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn htb hns).get i)
        typeBudget) :
    ZeroProfileProjectedCommonSpanWithBudget (Nat.log 2 n)
      (fun i => (cookLevinFactorList M n hn htb hns).get i)
      cert.project typeBudget :=
  zeroProfileProjectedCommonSpanWithBudget_of_quotientTypeSpaceCertificate
    (Nat.log 2 n)
    (fun i => (cookLevinFactorList M n hn htb hns).get i)
    cert

/-- The existential quotient/type-space obligation closes the named projected
zero-profile common-span obligation. -/
theorem cookLevinZeroProfileProjectedCommonSpanObligation_of_quotientTypeNormalFormObligation
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    {typeBudget : ℕ}
    (hquot :
      CookLevinZeroProfileQuotientTypeNormalFormObligation
        M n hn htb hns typeBudget) :
    CookLevinZeroProfileProjectedCommonSpanObligation
      M n hn htb hns typeBudget := by
  rcases hquot with ⟨cert⟩
  exact
    ⟨cert.project, cert.project_idempotent, cert.killsSingleton,
      cookLevinZeroProfileProjectedCommonSpanWithBudget_of_quotientTypeCertificate
        M n hn htb hns cert⟩

/-- Cook-Levin non-scalar zero-profile closure from a quotient type
certificate plus an explicitly paid residual span. -/
theorem cookLevinZeroProfileNonScalarClosureWithBudget_of_quotientTypeCertificate_residualClosure
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    {typeBudget residualBudget budget : ℕ}
    (cert :
      ZeroProfileQuotientTypeSpaceCertificate (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn htb hns).get i)
        typeBudget)
    (hresidual :
      CookLevinZeroProfileProjectionResidualClosureWithBudget
        M n hn htb hns cert.project residualBudget)
    (hbudget : typeBudget + residualBudget ≤ budget) :
    CookLevinZeroProfileNonScalarClosureWithBudget
      M n hn htb hns budget := by
  simpa [CookLevinZeroProfileNonScalarClosureWithBudget,
    CookLevinZeroProfileProjectionResidualClosureWithBudget,
    ZeroProfileCompressedSpanCommonSpanWithBudget] using
    (zeroProfileCompressedSpanCommonSpanWithBudget_of_quotientTypeSpaceCertificate_residualClosure
      (Nat.log 2 n)
      (fun i => (cookLevinFactorList M n hn htb hns).get i)
      cert hresidual hbudget)

/-- If the projected type budget plus the separately paid residual budget fits
inside the profile budget, the existing zero-profile common-span bridge
closes. -/
theorem cookLevinZeroHistogramShiftCommonSpan_of_quotientTypeCertificate_residualClosure
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    {typeBudget residualBudget : ℕ}
    (cert :
      ZeroProfileQuotientTypeSpaceCertificate (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn htb hns).get i)
        typeBudget)
    (hresidual :
      CookLevinZeroProfileProjectionResidualClosureWithBudget
        M n hn htb hns cert.project residualBudget)
    (hbudget :
      typeBudget + residualBudget ≤ withinProfileBound (Nat.log 2 n)) :
    CookLevinZeroHistogramShiftCommonSpan M n hn htb hns :=
  cookLevinZeroHistogramShiftCommonSpan_of_nonScalarClosureWithBudget
    M n hn htb hns
    (cookLevinZeroProfileNonScalarClosureWithBudget_of_quotientTypeCertificate_residualClosure
      M n hn htb hns
      (budget := typeBudget + residualBudget)
      cert hresidual le_rfl)
    hbudget

/-- Cook-Levin classifier-facing singleton quotient gate: a quotient type map
for the chosen singleton projection closes zero-profile once the projected
budget plus the ambient singleton residual budget fits in `withinProfileBound`.
-/
theorem cookLevinZeroHistogramShiftCommonSpan_of_singletonQuotientTypeMap
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    {typeBudget : ℕ}
    (A : ZeroProfileQuotientTypeAlphabet n typeBudget)
    (hmap :
      ZeroProfileProjectedGeneratorTypeMap (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn htb hns).get i) A
        (zeroProfileQuotientBySingletonShiftProjection
          (fun i => (cookLevinFactorList M n hn htb hns).get i)))
    (hbudget :
      typeBudget + n ≤ withinProfileBound (Nat.log 2 n)) :
    CookLevinZeroHistogramShiftCommonSpan M n hn htb hns := by
  have hcommon :
      ZeroProfileCompressedSpanCommonSpanWithBudget (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn htb hns).get i)
        (withinProfileBound (Nat.log 2 n)) :=
    zeroProfileCompressedSpanCommonSpanWithBudget_of_singletonQuotientTypeMap
      (κ := Nat.log 2 n)
      (factors := fun i => (cookLevinFactorList M n hn htb hns).get i)
      A hmap hbudget
  simpa [CookLevinZeroHistogramShiftCommonSpan,
    ZeroProfileCompressedSpanCommonSpanWithBudget] using hcommon

/-- The actual singleton-quotient projected-finrank classifier instantiates the
Cook-Levin quotient/type normal-form obligation. -/
theorem cookLevinZeroProfileQuotientTypeNormalFormObligation_singletonQuotient_projectedFinrank
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) :
    CookLevinZeroProfileQuotientTypeNormalFormObligation
      M n hn htb hns
      (zeroProfileSingletonQuotientProjectedTypeBudget (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn htb hns).get i)) :=
  ⟨zeroProfileSingletonQuotientTypeSpaceCertificate_projectedFinrank
    (Nat.log 2 n)
    (fun i => (cookLevinFactorList M n hn htb hns).get i)⟩

/-- Cook-Levin zero-profile gate with the corrected singleton quotient
classifier: the remaining arithmetic is exactly projected quotient finrank
plus the unavoidable ambient singleton residual budget `n`. -/
theorem cookLevinZeroHistogramShiftCommonSpan_of_singletonQuotient_projectedFinrankBudget
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (hbudget :
      zeroProfileSingletonQuotientProjectedTypeBudget (Nat.log 2 n)
          (fun i => (cookLevinFactorList M n hn htb hns).get i) + n ≤
        withinProfileBound (Nat.log 2 n)) :
    CookLevinZeroHistogramShiftCommonSpan M n hn htb hns := by
  have hcommon :
      ZeroProfileCompressedSpanCommonSpanWithBudget (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn htb hns).get i)
        (withinProfileBound (Nat.log 2 n)) :=
    zeroProfileCompressedSpanCommonSpanWithBudget_of_singletonQuotient_projectedFinrank
      (κ := Nat.log 2 n)
      (factors := fun i => (cookLevinFactorList M n hn htb hns).get i)
      hbudget
  simpa [CookLevinZeroHistogramShiftCommonSpan,
    ZeroProfileCompressedSpanCommonSpanWithBudget] using hcommon

/-- Cook-Levin no-go for the corrected singleton-quotient classifier budget:
when `withinProfileBound (Nat.log 2 n) < n`, even the exact projected quotient
finrank budget cannot be added to the mandatory singleton residual `n` and
fit inside the within-profile bound. -/
theorem not_cookLevin_singletonQuotient_projectedFinrankBudget_of_withinProfileBound_lt_ambient
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (hlt : withinProfileBound (Nat.log 2 n) < n) :
    ¬ zeroProfileSingletonQuotientProjectedTypeBudget (Nat.log 2 n)
          (fun i => (cookLevinFactorList M n hn htb hns).get i) + n ≤
        withinProfileBound (Nat.log 2 n) :=
  not_singletonQuotient_projectedFinrank_budget_of_withinProfileBound_lt_ambient
    (fun i => (cookLevinFactorList M n hn htb hns).get i) hlt

/-! ## Axiom audit anchors -/

#print axioms zeroProfileSingletonShiftSubspace_eq_span_singletonShiftBasis
#print axioms zeroProfileSingletonShiftBasis_card_le_ambient
#print axioms zeroProfileQuotientBySingletonShiftProjection_idempotent
#print axioms zeroProfileQuotientBySingletonShiftProjection_singletonShiftSubspace_le_ker
#print axioms zeroProfileQuotientBySingletonShiftProjection_killsSingletonShifts
#print axioms zeroProfileQuotientBySingletonShiftProjection_residual_mem_singletonShiftSubspace
#print axioms zeroProfileProjectionKillsSingletonShifts_iff_singletonShiftSubspace_le_ker
#print axioms zeroProfileQuotientTypeSpace_finrank_le
#print axioms zeroProfileQuotientTypeGlobalBasis_card_le_typeBudget
#print axioms zeroProfileQuotientTypeSpace_le_compressedSpan
#print axioms zeroProfileProjectedShiftSpan_eq_span_projectedShiftImageSet
#print axioms zeroProfileProjectedShiftSpan_finite
#print axioms zeroProfileProjectedShiftImageSet_subset_quotientTypeCompressedSpan
#print axioms zeroProfileProjectedCommonSpanWithBudget_of_projectedTypeMap
#print axioms zeroProfileProjectedShiftSpan_finrank_le_of_commonSpanWithBudget_quotient
#print axioms zeroProfileProjectedShiftSpanBasis
#print axioms zeroProfileProjectedShiftSpan_le_basis_span
#print axioms zeroProfileProjectedShiftSpanBasis_card_le_finrank
#print axioms zeroProfileProjectedCommonSpanWithBudget_of_projectedShiftSpan_finrank
#print axioms zeroProfileSingletonQuotientProjectedSpan_le_basis_span
#print axioms zeroProfileSingletonQuotientProjectedBasis_card_le_typeBudget
#print axioms zeroProfileSingletonQuotient_projectedRow_mem_projectedShiftSpan
#print axioms zeroProfileSingletonQuotientProjectedGeneratorTypeMap
#print axioms zeroProfileProjectedCommonSpanWithBudget_singletonQuotient_projectedFinrank
#print axioms zeroProfileSingletonQuotientProjectedTypeAlphabet_of_budget
#print axioms zeroProfileSingletonQuotientProjectedGeneratorTypeMap_of_budget
#print axioms zeroProfileSingletonQuotientProjectedTypeBudget_le_of_projectedCommonSpan
#print axioms zeroProfileSingletonQuotient_projectedCommonSpanWithBudget_iff_projectedTypeBudget_le
#print axioms zeroProfileSingletonQuotientProjectedTypeBudget_le_withinProfileBound_of_projectedCommonSpan
#print axioms zeroProfileSingletonQuotientProjectedTypeBudget_le_of_projectedTypeMap
#print axioms zeroProfileSingletonQuotient_projectedTypeMap_iff_projectedTypeBudget_le
#print axioms zeroProfileSingletonQuotientProjectedTypeBudget_le_withinProfileBound_of_projectedTypeMap
#print axioms ambient_le_withinProfileBound_of_singletonQuotient_projectedFinrank_budget
#print axioms not_singletonQuotient_projectedFinrank_budget_of_withinProfileBound_lt_ambient
#print axioms zeroProfileSingletonQuotientTypeSpaceCertificate_projectedFinrank
#print axioms zeroProfileQuotientTypeSpaceCertificate_singletonShiftSubspace_le_ker
#print axioms zeroProfileProjectedCommonSpanWithBudget_of_quotientTypeSpaceCertificate
#print axioms zeroProfileProjectionResidualClosureWithBudget_ambient_of_residual_mem_singletonShiftSubspace
#print axioms zeroProfileQuotientBySingletonShiftProjection_residualClosureWithBudget_ambient
#print axioms zeroProfileCompressedSpanCommonSpanWithBudget_of_projectedCommonSpan_residualClosure
#print axioms zeroProfileCompressedSpanCommonSpanWithBudget_of_quotientTypeSpaceCertificate_residualClosure
#print axioms zeroProfileCompressedSpanCommonSpanWithBudget_of_projectedCommonSpan_singletonQuotient
#print axioms zeroProfileCompressedSpanCommonSpanWithBudget_of_singletonQuotient_projectedFinrank
#print axioms zeroProfileCompressedSpanCommonSpanWithBudget_of_singletonQuotientTypeMap
#print axioms cookLevinZeroProfileSingletonQuotientResidualClosureWithBudget_ambient
#print axioms cookLevinZeroProfileProjectedCommonSpanWithBudget_of_quotientTypeCertificate
#print axioms cookLevinZeroProfileProjectedCommonSpanObligation_of_quotientTypeNormalFormObligation
#print axioms cookLevinZeroProfileNonScalarClosureWithBudget_of_quotientTypeCertificate_residualClosure
#print axioms cookLevinZeroHistogramShiftCommonSpan_of_quotientTypeCertificate_residualClosure
#print axioms cookLevinZeroHistogramShiftCommonSpan_of_singletonQuotientTypeMap
#print axioms cookLevinZeroProfileQuotientTypeNormalFormObligation_singletonQuotient_projectedFinrank
#print axioms cookLevinZeroHistogramShiftCommonSpan_of_singletonQuotient_projectedFinrankBudget
#print axioms not_cookLevin_singletonQuotient_projectedFinrankBudget_of_withinProfileBound_lt_ambient

end PathB
end DeepMath
end Paper93
end PallLean

namespace PallLean.Paper93.Paper283

open TuringMachine
open SymmetricPowerBound
open WithinProfileBound
open PallLean.Paper93.DeepMath.PathB

attribute [local instance] Classical.dec

/-- P-window wrapper from live-profile cases plus the projected/quotient
zero-profile replacement.  The zero-profile side is supplied by a quotient
type certificate and a separately paid residual span. -/
noncomputable def routeBRicherGauge_unprojectedPWindowFiniteSpanCover_of_liveProfileCases_zeroQuotientTypeCertificate
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (hn4 : n >= 4)
    {typeBudget residualBudget : Nat}
    (cert :
      ZeroProfileQuotientTypeSpaceCertificate (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn2 htb hns).get i)
        typeBudget)
    (hresidual :
      CookLevinZeroProfileProjectionResidualClosureWithBudget
        M n hn2 htb hns cert.project residualBudget)
    (hbudget :
      typeBudget + residualBudget <= withinProfileBound (Nat.log 2 n))
    (hlive :
      CookLevinAllBoundedProfileCommonSpanLiveProfileCases
        M n hn2 htb hns) :
    RouteBRicherGaugeUnprojectedPWindowFiniteSpanCover M n hn2 htb hns :=
  routeBRicherGauge_unprojectedPWindowFiniteSpanCover_of_liveProfileCases
    M n hn2 htb hns hn4
    (cookLevinZeroHistogramShiftCommonSpan_of_quotientTypeCertificate_residualClosure
      M n hn2 htb hns cert hresidual hbudget)
    hlive

/-- Active-profile P-window wrapper from the projected/quotient zero-profile
replacement. -/
noncomputable def routeBRicherGauge_unprojectedPWindowFiniteSpanCover_of_activeTypeCaseBlockers_zeroQuotientTypeCertificate
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (hn4 : n >= 4)
    {typeBudget residualBudget : Nat}
    (cert :
      ZeroProfileQuotientTypeSpaceCertificate (Nat.log 2 n)
        (fun i => (cookLevinFactorList M n hn2 htb hns).get i)
        typeBudget)
    (hresidual :
      CookLevinZeroProfileProjectionResidualClosureWithBudget
        M n hn2 htb hns cert.project residualBudget)
    (hbudget :
      typeBudget + residualBudget <= withinProfileBound (Nat.log 2 n))
    (hactive :
      CookLevinActiveProfileTypeCaseBlockers M n hn2 htb hns) :
    RouteBRicherGaugeUnprojectedPWindowFiniteSpanCover M n hn2 htb hns :=
  routeBRicherGauge_unprojectedPWindowFiniteSpanCover_of_activeTypeCaseBlockers_and_zeroProfileCommonSpan
    M n hn2 htb hns hn4
    (cookLevinZeroHistogramShiftCommonSpan_of_quotientTypeCertificate_residualClosure
      M n hn2 htb hns cert hresidual hbudget)
    hactive

/-! ## Axiom audit anchors -/

#print axioms routeBRicherGauge_unprojectedPWindowFiniteSpanCover_of_liveProfileCases_zeroQuotientTypeCertificate
#print axioms routeBRicherGauge_unprojectedPWindowFiniteSpanCover_of_activeTypeCaseBlockers_zeroQuotientTypeCertificate

end PallLean.Paper93.Paper283
