/-
  PallLean/Paper93/Closure/ShiftClosure.lean

  Agent I3 (of 10, parallel) — Shift closure: finite-dimensional
  envelope of `s · W` over all polynomial shifts `s` with
  `s.totalDegree ≤ ℓ`.

  ## Scope

  Agent I1 supplied the pointwise shift-multiplication primitive
  (`Paper93/Closure/ShiftMultiplication.lean`):

      `mulByPoly (m : MvPolynomial (Fin n) ℚ) : End ℚ _` is the
      `ℚ`-linear endomorphism of `MvPolynomial (Fin n) ℚ` given by
      right-multiplication by `m`. For a finite-dimensional
      submodule `W`, the image `W.map (mulByPoly m)` is again
      finite-dimensional with `finrank` bounded by `finrank W`.

  This file (I3) assembles those per-shift images over the full
  family of shift polynomials of bounded total degree:

      `shiftClosure W ℓ  :=
          ⨆ s : { s // s.totalDegree ≤ ℓ }, W.map (mulByPoly s.1)`

  is the ambient submodule containing `s · f` for every `f ∈ W`
  and every shift polynomial `s` with `totalDegree s ≤ ℓ`.

  The two deliverables are:

    * **`shiftClosure_finite`** — `shiftClosure W ℓ` is
      finite-dimensional over `ℚ`.

    * **`finrank_shiftClosure_le`** — the crude bound

          `finrank ℚ (shiftClosure W ℓ)
            ≤ (card of monomial exponents of total degree ≤ ℓ)
              * finrank ℚ W`.

      Since the cardinal of `{ α : Fin n →₀ ℕ // α.sum _ ≤ ℓ }`
      is bounded by `(ℓ+1)^n` (each variable has degree at most
      `ℓ`), this specialises to the shape

          `finrank ℚ (shiftClosure W ℓ) ≤ (ℓ+1)^n * finrank ℚ W`.

  The argument proceeds via an auxiliary `monomialShiftClosure`
  indexed only by monomial exponents, which has the same span
  (any `s` with `totalDegree s ≤ ℓ` expands into its monomial
  support), and whose finite-dimensional structure is immediate
  from `Submodule.finite_iSup` plus finiteness of the monomial
  index type.

  ## Kernel-only

    * No `sorry`.
    * No bespoke `axiom`.
    * All content routes through Mathlib primitives
      (`Submodule.map`, `LinearMap.mulRight`, `iSup`, and the
      `finrank_iSup_fin_le` helper from `SPDPDefs`).

  Expected `#print axioms` output: `[propext, Classical.choice,
  Quot.sound]`.
-/
import PallLean.Paper93.Closure.ShiftMultiplication
import PallLean.SPDPDefs

namespace PallLean
namespace Paper93
namespace Closure

open MvPolynomial
open scoped BigOperators

variable {n : ℕ}

/-! ## 1. The monomial index type

We parametrise shifts by their monomial exponents. The type of
"monomial exponents of total degree ≤ ℓ" is finite. This is the
combinatorial skeleton of the degree-ℓ shift family. -/

/-- Monomial exponents of total degree at most `ℓ` in `Fin n` variables. -/
def MonoIdx (n ℓ : ℕ) : Type :=
  { α : Fin n →₀ ℕ // (α.sum fun _ e => e) ≤ ℓ }

/-- `MonoIdx n ℓ` is finite: each such exponent has `α i ≤ ℓ` for all
`i`, hence is a subtype of the finite bounded-degree family. -/
instance MonoIdx.finite (n ℓ : ℕ) : Finite (MonoIdx n ℓ) := by
  classical
  -- The set `{ f : Fin n →₀ ℕ | f.sum (fun _ e => e) ≤ ℓ }` is finite:
  -- any such `f` has `f i ≤ ℓ` for every `i`, reducing to the standard
  -- bounded-degree finiteness used in Mathlib's `restrictTotalDegree`
  -- finiteness proof.
  have hbd : Finite { f : Fin n →₀ ℕ | ∀ a, f a ≤ ℓ } :=
    ((Set.Finite.pi' fun _ ↦ Set.finite_le_nat _).preimage
        DFunLike.coe_injective.injOn).to_subtype
  have hSubset :
      {s : Fin n →₀ ℕ | s.sum (fun _ e ↦ e) ≤ ℓ}
        ⊆ {f : Fin n →₀ ℕ | ∀ a, f a ≤ ℓ} := by
    intro s hs i
    rcases eq_or_ne (s i) 0 with h | h
    · rw [h]; exact Nat.zero_le _
    · have hi : i ∈ s.support := Finsupp.mem_support_iff.mpr h
      have hle : s i ≤ s.sum (fun _ e ↦ e) :=
        Finset.single_le_sum (fun _ _ ↦ Nat.zero_le _) hi
      exact hle.trans hs
  have : Finite { f : Fin n →₀ ℕ | f.sum (fun _ e ↦ e) ≤ ℓ } := by
    rw [Set.finite_coe_iff] at hbd ⊢
    exact hbd.subset hSubset
  -- `MonoIdx n ℓ` is defeq to the subtype over the above set.
  exact this

noncomputable instance MonoIdx.fintype (n ℓ : ℕ) : Fintype (MonoIdx n ℓ) :=
  Fintype.ofFinite _

/-! ## 2. Monomial-indexed shift closure

The auxiliary "monomial-only" shift closure. Its finite-dim structure
is immediate from `Submodule.finite_iSup`. -/

/-- Monomial-indexed shift closure: the submodule generated by
`(monomial α 1) · W` over all monomial exponents `α` of total
degree ≤ `ℓ`. -/
noncomputable def monomialShiftClosure
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ)) (ℓ : ℕ) :
    Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
  ⨆ α : MonoIdx n ℓ, W.map (mulByPoly (n := n) (monomial α.1 (1 : ℚ)))

/-- `monomialShiftClosure` is finite-dimensional: it is a finite
supremum of finite-dimensional submodules (each `W.map _` is finite
by `mulByPoly_map_finite`). -/
instance monomialShiftClosure_finite
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ)) [Module.Finite ℚ W] (ℓ : ℕ) :
    Module.Finite ℚ (monomialShiftClosure W ℓ) := by
  unfold monomialShiftClosure
  -- Each summand is finite by the I1 instance, and `MonoIdx n ℓ` is finite.
  haveI : ∀ α : MonoIdx n ℓ,
      Module.Finite ℚ (W.map (mulByPoly (n := n) (monomial α.1 (1 : ℚ)))) :=
    fun α => mulByPoly_map_finite W (monomial α.1 (1 : ℚ))
  infer_instance

/-- Finrank bound for `monomialShiftClosure`: the sum of per-summand
finranks, each of which is at most `finrank W`. -/
theorem finrank_monomialShiftClosure_le
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ)) [Module.Finite ℚ W] (ℓ : ℕ) :
    Module.finrank ℚ (monomialShiftClosure W ℓ)
      ≤ Fintype.card (MonoIdx n ℓ) * Module.finrank ℚ W := by
  classical
  -- Step 1: translate the subtype-indexed `⨆` into a `Fin`-indexed one
  -- via `Fintype.equivFin`, so we can apply `SPDP.finrank_iSup_fin_le`.
  set m : ℕ := Fintype.card (MonoIdx n ℓ) with hm
  let e : MonoIdx n ℓ ≃ Fin m := Fintype.equivFin (MonoIdx n ℓ)
  -- Reindex the submodule family through `e`.
  let U : Fin m → Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
    fun i => W.map (mulByPoly (n := n) (monomial (e.symm i).1 (1 : ℚ)))
  haveI hUfin : ∀ i, Module.Finite ℚ ↥(U i) := by
    intro i
    exact mulByPoly_map_finite W (monomial (e.symm i).1 (1 : ℚ))
  -- The two iSup's are equal.
  have hreindex :
      monomialShiftClosure W ℓ
        = (⨆ i : Fin m, U i : Submodule ℚ (MvPolynomial (Fin n) ℚ)) := by
    unfold monomialShiftClosure
    apply le_antisymm
    · refine iSup_le (fun α => ?_)
      have hα : α = e.symm (e α) := (e.symm_apply_apply α).symm
      have hstep :
          W.map (mulByPoly (n := n) (monomial α.1 (1 : ℚ))) = U (e α) := by
        show W.map (mulByPoly (n := n) (monomial α.1 (1 : ℚ)))
          = W.map (mulByPoly (n := n) (monomial (e.symm (e α)).1 (1 : ℚ)))
        rw [← hα]
      rw [hstep]
      exact le_iSup (fun i : Fin m => U i) (e α)
    · refine iSup_le (fun i => ?_)
      show U i ≤ ⨆ α : MonoIdx n ℓ,
          W.map (mulByPoly (n := n) (monomial α.1 (1 : ℚ)))
      exact le_iSup
        (fun α : MonoIdx n ℓ =>
          W.map (mulByPoly (n := n) (monomial α.1 (1 : ℚ))))
        (e.symm i)
  -- Step 2: sum of finranks ≤ m * finrank W.
  have hsum :
      (∑ i : Fin m, Module.finrank ℚ ↥(U i))
        ≤ m * Module.finrank ℚ ↥W := by
    have hpt : ∀ i : Fin m,
        Module.finrank ℚ ↥(U i) ≤ Module.finrank ℚ ↥W := by
      intro i
      exact mulByPoly_map_finrank_le W (monomial (e.symm i).1 (1 : ℚ))
    calc
      (∑ i : Fin m, Module.finrank ℚ ↥(U i))
          ≤ ∑ _ : Fin m, Module.finrank ℚ ↥W :=
            Finset.sum_le_sum (fun i _ => hpt i)
      _ = m * Module.finrank ℚ ↥W := by
            rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin,
                smul_eq_mul]
  -- Step 3: combine via `finrank_iSup_fin_le`.
  have hfin_bound :
      Module.finrank ℚ ↥(⨆ i : Fin m, U i)
        ≤ ∑ i : Fin m, Module.finrank ℚ ↥(U i) :=
    SPDP.finrank_iSup_fin_le (F := ℚ) m U
  calc
    Module.finrank ℚ (monomialShiftClosure W ℓ)
        = Module.finrank ℚ ↥(⨆ i : Fin m, U i) := by rw [hreindex]
    _ ≤ ∑ i : Fin m, Module.finrank ℚ ↥(U i) := hfin_bound
    _ ≤ m * Module.finrank ℚ W := hsum

/-! ## 3. Full shift closure

The primary object of this file: `shiftClosure W ℓ` is the ambient
submodule containing `s · f` for every `f ∈ W` and every shift
polynomial `s` with `totalDegree s ≤ ℓ`. -/

/-- **Shift closure** of `W` at degree `ℓ`. Submodule generated by
`s · f` for every shift polynomial `s` of total degree ≤ `ℓ` and
every `f ∈ W`.

Implementationally this is the supremum of `W.map (mulByPoly s)`
over all shift polynomials `s` with `totalDegree s ≤ ℓ`. -/
noncomputable def shiftClosure
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ)) (ℓ : ℕ) :
    Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
  ⨆ s : { s : MvPolynomial (Fin n) ℚ // s.totalDegree ≤ ℓ },
      W.map (mulByPoly (n := n) s.1)

/-! ## 4. Equality with the monomial-indexed version

Every shift polynomial of total degree ≤ ℓ is a ℚ-linear combination
of monomials of total degree ≤ ℓ, so the two iSup's span the same
submodule. -/

/-- The monomial-indexed shift closure is contained in the full
shift closure (every monomial of total degree ≤ ℓ is itself a
shift of total degree ≤ ℓ). -/
theorem monomialShiftClosure_le_shiftClosure
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ)) (ℓ : ℕ) :
    monomialShiftClosure W ℓ ≤ shiftClosure W ℓ := by
  classical
  refine iSup_le (fun α => ?_)
  -- `(monomial α.1 1)` has total degree ≤ ℓ (in fact `= α.sum _`).
  have hdeg : (monomial α.1 (1 : ℚ) : MvPolynomial (Fin n) ℚ).totalDegree ≤ ℓ := by
    have h1 : (monomial α.1 (1 : ℚ) : MvPolynomial (Fin n) ℚ).totalDegree
            = α.1.sum (fun _ e => e) := by
      have honeZero : (1 : ℚ) ≠ 0 := one_ne_zero
      exact totalDegree_monomial α.1 honeZero
    rw [h1]; exact α.2
  -- Package as subtype and conclude.
  have : W.map (mulByPoly (n := n) (monomial α.1 (1 : ℚ)))
          ≤ shiftClosure W ℓ := by
    refine le_iSup
      (fun s : { s : MvPolynomial (Fin n) ℚ // s.totalDegree ≤ ℓ } =>
        W.map (mulByPoly (n := n) s.1))
      (⟨monomial α.1 (1 : ℚ), hdeg⟩ : _)
  exact this

/-- The full shift closure is contained in the monomial-indexed one.
This is the nontrivial direction, handled by expanding any shift
polynomial into its monomial support. -/
theorem shiftClosure_le_monomialShiftClosure
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ)) (ℓ : ℕ) :
    shiftClosure W ℓ ≤ monomialShiftClosure W ℓ := by
  classical
  -- Fix a shift `s` with `totalDegree s ≤ ℓ`. Show
  -- `W.map (mulByPoly s) ≤ monomialShiftClosure W ℓ`.
  refine iSup_le (fun s => ?_)
  -- Any element of `W.map (mulByPoly s)` is `f * s` for some `f ∈ W`.
  intro q hq
  rcases hq with ⟨f, hfW, hfq⟩
  -- `f * s = ∑ β ∈ s.support, (monomial β 1) * f * coeff β s`.
  -- (We use `s.as_sum` to expand `s`.)
  -- Reduce to: `f * s ∈ monomialShiftClosure W ℓ`.
  -- The `mulByPoly s f = f * s` (note: `mulByPoly` is right-multiplication
  -- by construction in `ShiftMultiplication.lean`).
  have hfq' : q = f * s.1 := by
    have := hfq
    -- `mulByPoly_apply : mulByPoly m p = p * m`
    rw [show ((mulByPoly (n := n) s.1) f) = f * s.1 from rfl] at this
    exact this.symm
  subst hfq'
  clear hfq
  -- Expand `s.1` via `as_sum`.
  have hsdeg := s.2
  -- `s.1 = ∑ β ∈ s.1.support, monomial β (coeff β s.1)`.
  rw [show f * s.1 = f * ∑ β ∈ s.1.support, monomial β (coeff β s.1) from by
        rw [← MvPolynomial.as_sum s.1]]
  -- Distribute multiplication over the finite sum.
  rw [Finset.mul_sum]
  -- Each summand `f * monomial β (coeff β s.1) = coeff β s.1 • (f * monomial β 1)`
  -- lies in `monomialShiftClosure W ℓ`, since `β ∈ s.1.support` implies
  -- `β.sum _ ≤ totalDegree s.1 ≤ ℓ`, so `⟨β, _⟩ : MonoIdx n ℓ`.
  refine Submodule.sum_mem _ (fun β hβ => ?_)
  -- Get the degree bound: `β.sum _ ≤ ℓ`.
  have hβdeg : (β.sum fun _ e => e) ≤ ℓ :=
    le_trans (le_totalDegree hβ) hsdeg
  set idx : MonoIdx n ℓ := ⟨β, hβdeg⟩
  -- Rewrite the summand as a scalar multiple of a mapped element:
  --   `coeff β s.1 • (f * monomial β 1) = f * (coeff β s.1 • monomial β 1)`
  --   `                                = f * monomial β (coeff β s.1 • 1)`
  --   `                                = f * monomial β (coeff β s.1)`.
  have hmon :
      (coeff β s.1) • (f * (monomial β (1 : ℚ) : MvPolynomial (Fin n) ℚ))
        = f * (monomial β (coeff β s.1) : MvPolynomial (Fin n) ℚ) := by
    rw [show (coeff β s.1) • (f * monomial β (1 : ℚ))
            = f * (coeff β s.1) • (monomial β (1 : ℚ) : MvPolynomial (Fin n) ℚ)
              from (Algebra.mul_smul_comm _ f (monomial β (1 : ℚ))).symm,
        smul_monomial, smul_eq_mul, mul_one]
  rw [← hmon]
  -- `f * monomial β 1 = (mulByPoly (monomial β 1)) f ∈ W.map (mulByPoly _)`.
  have hfmap :
      f * (monomial β (1 : ℚ) : MvPolynomial (Fin n) ℚ)
        ∈ W.map (mulByPoly (n := n) (monomial β (1 : ℚ))) := by
    refine ⟨f, hfW, ?_⟩
    -- `mulByPoly m f = f * m` by definition.
    rfl
  -- That submodule is a summand of `monomialShiftClosure W ℓ`.
  have hsubmap :
      W.map (mulByPoly (n := n) (monomial idx.1 (1 : ℚ)))
        ≤ monomialShiftClosure W ℓ := by
    refine le_iSup
      (fun α : MonoIdx n ℓ =>
        W.map (mulByPoly (n := n) (monomial α.1 (1 : ℚ)))) idx
  -- The smul closes.
  exact (monomialShiftClosure W ℓ).smul_mem (coeff β s.1) (hsubmap hfmap)

/-- **Shift closure coincides with its monomial-indexed model.** -/
theorem shiftClosure_eq_monomialShiftClosure
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ)) (ℓ : ℕ) :
    shiftClosure W ℓ = monomialShiftClosure W ℓ :=
  le_antisymm
    (shiftClosure_le_monomialShiftClosure W ℓ)
    (monomialShiftClosure_le_shiftClosure W ℓ)

/-! ## 5. Main deliverables

Finite-dimensionality and a dimension bound for `shiftClosure`. -/

/-- **Main finite-dim instance.** `shiftClosure W ℓ` is
finite-dimensional over `ℚ`. -/
instance shiftClosure_finite
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ)) [Module.Finite ℚ W] (ℓ : ℕ) :
    Module.Finite ℚ (shiftClosure W ℓ) := by
  rw [shiftClosure_eq_monomialShiftClosure]
  infer_instance

/-- **Main dimension bound.** The finrank of the shift closure
is bounded by `(card of monomials of total degree ≤ ℓ) * finrank W`.

In particular, since `Fintype.card (MonoIdx n ℓ) ≤ (ℓ+1)^n` (each
coordinate of a bounded-total-degree exponent is at most `ℓ`), we
have

    `finrank ℚ (shiftClosure W ℓ) ≤ (ℓ+1)^n * finrank ℚ W`.

The coarser `(ℓ+1)^n` bound is derived in `finrank_shiftClosure_pow_bound`
below. -/
theorem finrank_shiftClosure_le
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ)) [Module.Finite ℚ W] (ℓ : ℕ) :
    Module.finrank ℚ (shiftClosure W ℓ)
      ≤ Fintype.card (MonoIdx n ℓ) * Module.finrank ℚ W := by
  rw [shiftClosure_eq_monomialShiftClosure]
  exact finrank_monomialShiftClosure_le W ℓ

/-- The monomial-index type has cardinality at most `(ℓ+1)^n`:
every bounded-total-degree exponent has each coordinate in
`{0, 1, …, ℓ}`, giving an injection into `Fin n → Fin (ℓ+1)`. -/
theorem card_MonoIdx_le (n ℓ : ℕ) :
    Fintype.card (MonoIdx n ℓ) ≤ (ℓ + 1) ^ n := by
  classical
  -- Build the injection `MonoIdx n ℓ ↪ (Fin n → Fin (ℓ+1))`.
  let φ : MonoIdx n ℓ → (Fin n → Fin (ℓ + 1)) := fun α i =>
    ⟨α.1 i, by
      -- `α i ≤ α.sum _ ≤ ℓ < ℓ+1`.
      rcases eq_or_ne (α.1 i) 0 with h | h
      · rw [h]; exact Nat.succ_pos _
      · have hi : i ∈ α.1.support := Finsupp.mem_support_iff.mpr h
        have h1 : α.1 i ≤ α.1.sum (fun _ e => e) :=
          Finset.single_le_sum (fun _ _ => Nat.zero_le _) hi
        exact Nat.lt_succ_of_le (h1.trans α.2)⟩
  have hφ : Function.Injective φ := by
    intro a b hab
    apply Subtype.ext
    ext i
    have hi : φ a i = φ b i := congrFun hab i
    -- Values of `Fin (ℓ+1)` agree as `Nat`s iff they agree as `Fin`s.
    have : (φ a i).val = (φ b i).val := congrArg Fin.val hi
    exact this
  calc
    Fintype.card (MonoIdx n ℓ)
        ≤ Fintype.card (Fin n → Fin (ℓ + 1)) := Fintype.card_le_of_injective φ hφ
    _ = (ℓ + 1) ^ n := by
          simp [Fintype.card_fin]

/-- **Coarse `(ℓ+1)^n` dimension bound.** Combining the main bound
with `card_MonoIdx_le` yields the advertised shape
`dim (shiftClosure W ℓ) ≤ dim W × (ℓ+1)^n`. -/
theorem finrank_shiftClosure_pow_bound
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ)) [Module.Finite ℚ W] (ℓ : ℕ) :
    Module.finrank ℚ (shiftClosure W ℓ)
      ≤ (ℓ + 1) ^ n * Module.finrank ℚ W := by
  calc
    Module.finrank ℚ (shiftClosure W ℓ)
        ≤ Fintype.card (MonoIdx n ℓ) * Module.finrank ℚ W :=
          finrank_shiftClosure_le W ℓ
    _ ≤ (ℓ + 1) ^ n * Module.finrank ℚ W :=
          Nat.mul_le_mul_right _ (card_MonoIdx_le n ℓ)

/-! ## 6. Pointwise membership lemma

Convenience: if `f ∈ W` and `s.totalDegree ≤ ℓ`, then `s · f`
(equivalently `f · s`) lies in `shiftClosure W ℓ`. -/

/-- **Pointwise membership.** For `f ∈ W` and any shift polynomial
`s` with `totalDegree s ≤ ℓ`, the product `f * s` lies in
`shiftClosure W ℓ`.

(Because `MvPolynomial` is commutative, this is equivalent to
`s * f ∈ shiftClosure W ℓ`.) -/
theorem mul_mem_shiftClosure
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ)) (ℓ : ℕ)
    {f s : MvPolynomial (Fin n) ℚ}
    (hf : f ∈ W) (hs : s.totalDegree ≤ ℓ) :
    f * s ∈ shiftClosure W ℓ := by
  -- `f * s = (mulByPoly s) f ∈ W.map (mulByPoly s) ≤ shiftClosure W ℓ`.
  have hmem : (mulByPoly (n := n) s) f
      ∈ W.map (mulByPoly (n := n) s) :=
    Submodule.mem_map_of_mem hf
  have hle : W.map (mulByPoly (n := n) s) ≤ shiftClosure W ℓ := by
    refine le_iSup
      (fun t : { s : MvPolynomial (Fin n) ℚ // s.totalDegree ≤ ℓ } =>
        W.map (mulByPoly (n := n) t.1))
      (⟨s, hs⟩ : _)
  -- Unfold `mulByPoly s f = f * s`.
  have happ : (mulByPoly (n := n) s) f = f * s := rfl
  rw [happ] at hmem
  exact hle hmem

/-- Symmetric form: `s * f ∈ shiftClosure W ℓ`. -/
theorem shift_mul_mem_shiftClosure
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ)) (ℓ : ℕ)
    {f s : MvPolynomial (Fin n) ℚ}
    (hf : f ∈ W) (hs : s.totalDegree ≤ ℓ) :
    s * f ∈ shiftClosure W ℓ := by
  rw [mul_comm]
  exact mul_mem_shiftClosure W ℓ hf hs

end Closure
end Paper93
end PallLean
