import PallLean.Paper93.DeepMath.PathB.ConcreteWFactorMembership

/-!
# Augmented concrete `W` H3 reduction

The fixed-row concrete H3 target

`fun tau => concreteW n hn4 (Fin.castLEEmb hn4) tau`

requires canonical-row transport for booleanity and adjacency factors.  This
file records the corrected row-insensitive target: `augmentedW` is generated by
all row-indexed concrete spaces `concreteW n hn4 σ tau`.  The existing direct
branch shape witnesses then close H3 without
`CookLevinConcreteWCanonicalRowTransport`.
-/

namespace PallLean.Paper93.DeepMath.PathB

open MvPolynomial
open TuringMachine
open SymmetricPowerBound
open WithinProfileBound
open PallLean.Paper93
open PallLean.Paper93.Spanning
open PallLean.Paper93.Wiring

attribute [local instance] Classical.dec

/-- Row-insensitive concrete per-type space.

For a fixed type `tau`, this is the linear span of all polynomials that belong
to at least one row-embedded concrete space `concreteW n hn4 σ tau`. -/
noncomputable def augmentedW
    (n : ℕ) (hn4 : n ≥ 4) (tau : ConstraintType) :
    Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
  Submodule.span ℚ
    {p : MvPolynomial (Fin n) ℚ |
      ∃ σ : Fin 4 ↪ Fin n, p ∈ concreteW n hn4 σ tau}

/-- Every concrete row embeds into the augmented row-insensitive space. -/
theorem concreteW_le_augmentedW
    (n : ℕ) (hn4 : n ≥ 4) (σ : Fin 4 ↪ Fin n)
    (tau : ConstraintType) :
    concreteW n hn4 σ tau ≤ augmentedW n hn4 tau := by
  intro p hp
  exact Submodule.subset_span ⟨σ, hp⟩

/-- Existential row membership is exactly enough to close H3 for
`augmentedW`, with no canonical-row transport. -/
theorem CookLevinFactorMemPerType_augmentedW_of_existsRowMembership
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) (hn4 : n ≥ 4)
    (hExists :
      CookLevinConcreteWExistsRowMembership M n hn htb hns hn4) :
    CookLevinFactorMemPerType M n hn htb hns (augmentedW n hn4) := by
  intro i
  obtain ⟨σ, hσ⟩ := hExists i
  exact concreteW_le_augmentedW n hn4 σ
    (cookLevinConstraintType M n hn htb hns i) hσ

/-- Direct branch shape witnesses close H3 for `augmentedW`.

This is the corrected H3 target: the direct branch witnesses may choose their
own row embedding, and `augmentedW` absorbs that row choice globally. -/
theorem CookLevinFactorMemPerType_augmentedW_of_directBranchShapeWitnesses
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) (hn4 : n ≥ 4)
    (hShape :
      CookLevinDirectBranchShapeWitnesses M n hn htb hns hn4) :
    CookLevinFactorMemPerType M n hn htb hns (augmentedW n hn4) :=
  CookLevinFactorMemPerType_augmentedW_of_existsRowMembership
    M n hn htb hns hn4
    (CookLevinConcreteWExistsRowMembership_of_directBranchShapeWitnesses
      M n hn htb hns hn4 hShape)

/-- The previous fixed canonical-row H3 target also maps into `augmentedW`;
this is a sanity reduction, not the route used by the direct branch theorem. -/
theorem CookLevinFactorMemPerType_augmentedW_of_canonicalConcreteW
    (M : DTM) (n : ℕ) (hn : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n) (hn4 : n ≥ 4)
    (hFactor :
      CookLevinFactorMemPerType M n hn htb hns
        (fun tau => concreteW n hn4 (Fin.castLEEmb hn4) tau)) :
    CookLevinFactorMemPerType M n hn htb hns (augmentedW n hn4) := by
  intro i
  exact concreteW_le_augmentedW n hn4 (Fin.castLEEmb hn4)
    (cookLevinConstraintType M n hn htb hns i) (hFactor i)

/-! ## Checked reductions and axiom anchors -/

#check concreteW_le_augmentedW
#check CookLevinFactorMemPerType_augmentedW_of_existsRowMembership
#check CookLevinFactorMemPerType_augmentedW_of_directBranchShapeWitnesses
#check CookLevinFactorMemPerType_augmentedW_of_canonicalConcreteW

#print axioms concreteW_le_augmentedW
#print axioms CookLevinFactorMemPerType_augmentedW_of_existsRowMembership
#print axioms CookLevinFactorMemPerType_augmentedW_of_directBranchShapeWitnesses
#print axioms CookLevinFactorMemPerType_augmentedW_of_canonicalConcreteW

end PallLean.Paper93.DeepMath.PathB
