import PallLean.IterDerivHelpers
import PallLean.Paper93.Paper283.BridgeAGeneralizedNonzeroWitness

/-!
# Upper-containment helpers for the Bridge A square-helper candidate

This file is intentionally disjoint from
`BridgeAGeneralizedNonzeroWitness.lean`.  It records the row span intended for
the exact square-helper candidate and proves the main mixed/incomplete
vanishing mechanism: if every row is missing at least one helper derivative,
then every shifted strict generator is killed by `mlProj`.
-/

namespace PallLean.Paper93.Paper283

open MvPolynomial
open MultilinearSPDP
open SPDP

namespace BridgeAGeneralizedNonzeroWitness

attribute [local instance] Classical.dec

/-- The intended multilinear row monomial left after differentiating once in
each helper belonging to row `r`. -/
noncomputable def squareHelperRowMonomial (kappa gadgetN : Nat)
    (r : Fin (rowCount kappa gadgetN)) :
    MvPolynomial (Fin (squareHelperVarCount kappa gadgetN)) Rat :=
  X (squarePayloadIndex kappa gadgetN r) *
    ∏ j : Fin kappa, X (squareHelperIndex kappa gadgetN r j)

/-- The row span generated by the intended square-helper row monomials. -/
noncomputable def squareHelperRowSpan (kappa gadgetN : Nat) :
    Submodule Rat (MvPolynomial (Fin (squareHelperVarCount kappa gadgetN)) Rat) :=
  Submodule.span Rat
    (Set.range (squareHelperRowMonomial kappa gadgetN))

/-- The row term with one helper-square factor removed. -/
noncomputable def squareHelperRowRemainder (kappa gadgetN : Nat)
    (r : Fin (rowCount kappa gadgetN)) (j : Fin kappa) :
    MvPolynomial (Fin (squareHelperVarCount kappa gadgetN)) Rat :=
  X (squarePayloadIndex kappa gadgetN r) *
    (Finset.univ.erase j).prod
      (fun j' : Fin kappa =>
        X (squareHelperIndex kappa gadgetN r j') *
          X (squareHelperIndex kappa gadgetN r j'))

/-- Split a row term into a chosen helper square times the remaining factors. -/
theorem squareHelperRowTerm_eq_helperSq_mul_remainder
    (kappa gadgetN : Nat) (r : Fin (rowCount kappa gadgetN)) (j : Fin kappa) :
    squareHelperRowTerm kappa gadgetN r =
      (X (squareHelperIndex kappa gadgetN r j) *
        X (squareHelperIndex kappa gadgetN r j)) *
        squareHelperRowRemainder kappa gadgetN r j := by
  classical
  unfold squareHelperRowTerm squareHelperRowRemainder
  rw [← Finset.mul_prod_erase (Finset.univ : Finset (Fin kappa))
    (fun j' : Fin kappa =>
      X (squareHelperIndex kappa gadgetN r j') *
        X (squareHelperIndex kappa gadgetN r j')) (Finset.mem_univ j)]
  ring

/-- A variable different from `v` does not differentiate the square `X_v^2`. -/
theorem pderiv_helperSq_of_ne {n : Nat} {v i : Fin n} (hiv : i ≠ v) :
    pderiv i ((X v * X v : MvPolynomial (Fin n) Rat)) = 0 := by
  rw [pderiv_mul, MvPolynomial.pderiv_X_of_ne hiv.symm]
  simp

/-- If the helper `j` is absent from the derivative list, its square factors
out of the row-term iterated derivative. -/
theorem iterDerivList_squareHelperRowTerm_eq_helperSq_mul_of_helper_not_mem
    (kappa gadgetN : Nat) (S : List (Fin (squareHelperVarCount kappa gadgetN)))
    (r : Fin (rowCount kappa gadgetN)) (j : Fin kappa)
    (hjS : squareHelperIndex kappa gadgetN r j ∉ S) :
    iterDerivList S (squareHelperRowTerm kappa gadgetN r) =
      (X (squareHelperIndex kappa gadgetN r j) *
        X (squareHelperIndex kappa gadgetN r j)) *
        iterDerivList S (squareHelperRowRemainder kappa gadgetN r j) := by
  rw [squareHelperRowTerm_eq_helperSq_mul_remainder]
  apply IterDerivHelpers.iterDerivList_mul_left_const
  intro i hi
  exact pderiv_helperSq_of_ne (by
    intro h
    exact hjS (by simpa [h] using hi))

/-- `mlProj` kills any polynomial with a fixed square factor. -/
theorem mlProj_helperSq_mul_eq_zero {n : Nat} (v : Fin n)
    (q : MvPolynomial (Fin n) Rat) :
    mlProj ((X v * X v : MvPolynomial (Fin n) Rat) * q) = 0 := by
  classical
  induction q using MvPolynomial.induction_on' with
  | monomial s a =>
      rw [MvPolynomial.X, MvPolynomial.monomial_mul, MvPolynomial.monomial_mul,
        one_mul, one_mul, mlProj_monomial]
      have hnot :
          ¬ Finsupp.IsMultilinear
            (Finsupp.single v 1 + Finsupp.single v 1 + s : Fin n →₀ Nat) := by
        intro hml
        have hv := hml v
        simp at hv
        omega
      rw [if_neg hnot]
  | add p q hp hq =>
      rw [mul_add, mlProj_add, hp, hq, add_zero]

/-- Row-level mixed/incomplete vanishing: if a row is missing one helper from
the derivative list, then the shifted row contribution is killed by `mlProj`. -/
theorem mlProj_shift_iterDerivList_squareHelperRowTerm_eq_zero_of_helper_not_mem
    (kappa gadgetN : Nat)
    (S : List (Fin (squareHelperVarCount kappa gadgetN)))
    (m : MvPolynomial (Fin (squareHelperVarCount kappa gadgetN)) Rat)
    (r : Fin (rowCount kappa gadgetN)) (j : Fin kappa)
    (hjS : squareHelperIndex kappa gadgetN r j ∉ S) :
    mlProj (m * iterDerivList S (squareHelperRowTerm kappa gadgetN r)) = 0 := by
  rw [iterDerivList_squareHelperRowTerm_eq_helperSq_mul_of_helper_not_mem
    kappa gadgetN S r j hjS]
  rw [show
      m *
          ((X (squareHelperIndex kappa gadgetN r j) *
              X (squareHelperIndex kappa gadgetN r j)) *
            iterDerivList S (squareHelperRowRemainder kappa gadgetN r j)) =
        (X (squareHelperIndex kappa gadgetN r j) *
            X (squareHelperIndex kappa gadgetN r j)) *
          (m * iterDerivList S (squareHelperRowRemainder kappa gadgetN r j)) by
    ring]
  exact mlProj_helperSq_mul_eq_zero (squareHelperIndex kappa gadgetN r j)
    (m * iterDerivList S (squareHelperRowRemainder kappa gadgetN r j))

/-- Iterated derivatives distribute over a finite sum. -/
theorem iterDerivList_finset_sum {n : Nat} {ι : Type*}
    (S : List (Fin n)) (s : Finset ι)
    (f : ι -> MvPolynomial (Fin n) Rat) :
    iterDerivList S (s.sum f) = s.sum (fun i => iterDerivList S (f i)) := by
  induction S generalizing f with
  | nil =>
      simp [IterDerivHelpers.iterDerivList_nil]
  | cons i rest ih =>
      rw [IterDerivHelpers.iterDerivList_cons]
      rw [show pderiv i (s.sum f) = s.sum (fun a => pderiv i (f a)) by
        exact map_sum (pderiv i) f s]
      rw [ih]
      simp [IterDerivHelpers.iterDerivList_cons]

/-- `mlProj` distributes over a finite sum. -/
theorem mlProj_finset_sum {n : Nat} {ι : Type*}
    (s : Finset ι) (f : ι -> MvPolynomial (Fin n) Rat) :
    mlProj (s.sum f) = s.sum (fun i => mlProj (f i)) := by
  change (mlProjHom Rat) (s.sum f) = s.sum (fun i => (mlProjHom Rat) (f i))
  exact map_sum (mlProjHom Rat) f s

/-- Global mixed/incomplete vanishing for the square-helper candidate: if every
row has at least one helper absent from `S`, then every shifted generator for
`squareHelperQ` vanishes after multilinear projection. -/
theorem mlProj_shift_iterDerivList_squareHelperQ_eq_zero_of_forall_missing_helper
    (kappa gadgetN : Nat)
    (S : List (Fin (squareHelperVarCount kappa gadgetN)))
    (m : MvPolynomial (Fin (squareHelperVarCount kappa gadgetN)) Rat)
    (hmissing :
      ∀ r : Fin (rowCount kappa gadgetN),
        ∃ j : Fin kappa, squareHelperIndex kappa gadgetN r j ∉ S) :
    mlProj (m * iterDerivList S (squareHelperQ kappa gadgetN)) = 0 := by
  classical
  unfold squareHelperQ
  rw [iterDerivList_finset_sum]
  rw [Finset.mul_sum]
  rw [mlProj_finset_sum]
  apply Finset.sum_eq_zero
  intro r _hr
  rcases hmissing r with ⟨j, hjS⟩
  exact mlProj_shift_iterDerivList_squareHelperRowTerm_eq_zero_of_helper_not_mem
    kappa gadgetN S m r j hjS

/-- The same mixed/incomplete generators lie in the intended row span, by
vanishing. -/
theorem mlProj_shift_iterDerivList_squareHelperQ_mem_rowSpan_of_forall_missing_helper
    (kappa gadgetN : Nat)
    (S : List (Fin (squareHelperVarCount kappa gadgetN)))
    (m : MvPolynomial (Fin (squareHelperVarCount kappa gadgetN)) Rat)
    (hmissing :
      ∀ r : Fin (rowCount kappa gadgetN),
        ∃ j : Fin kappa, squareHelperIndex kappa gadgetN r j ∉ S) :
    mlProj (m * iterDerivList S (squareHelperQ kappa gadgetN)) ∈
      squareHelperRowSpan kappa gadgetN := by
  rw [mlProj_shift_iterDerivList_squareHelperQ_eq_zero_of_forall_missing_helper
    kappa gadgetN S m hmissing]
  exact Submodule.zero_mem _

/-! ## Axiom audit anchors -/

#print axioms mlProj_helperSq_mul_eq_zero
#print axioms mlProj_shift_iterDerivList_squareHelperQ_eq_zero_of_forall_missing_helper
#print axioms mlProj_shift_iterDerivList_squareHelperQ_mem_rowSpan_of_forall_missing_helper

end BridgeAGeneralizedNonzeroWitness

end PallLean.Paper93.Paper283
