import PallLean.MlProjFar
import PallLean.IterDerivHelpers
import PallLean.Paper93.Paper283.BridgeACompilerLocalPolynomial

/-!
# Bridge A diagonal quadratic family

This file extends the one-variable nonzero Bridge A local-polynomial witness
to arbitrary local width at the `kappa = 1` pocket:

`Q_N = sum_i X_i^2`

has exact blocked multilinear SPDP rank `N` at `(kappa, ell) = (1, 1)`.
Thus it realizes the normalized target `kappa * gadgetN` for `kappa = 1`
and arbitrary `gadgetN`.
-/

namespace PallLean.Paper93.Paper283

open MvPolynomial
open MultilinearSPDP
open SPDP

namespace BridgeADiagonalQuadraticFamily

attribute [local instance] Classical.dec

/-- The one-block local partition used by the diagonal-quadratic family. -/
noncomputable def oneBlockPartition (N : Nat) : BlockPartition N where
  numBlocks := 1
  assign := fun _ => 0

/-- The diagonal quadratic family `sum_i X_i^2`. -/
noncomputable def diagonalQuadratic (N : Nat) : MvPolynomial (Fin N) Rat :=
  Finset.univ.sum (fun i : Fin N => X i * X i)

/-- The coordinate-linear span generated by the variables `X_i`. -/
noncomputable def coordinateSpan (N : Nat) :
    Submodule Rat (MvPolynomial (Fin N) Rat) :=
  Submodule.span Rat (Set.range (fun i : Fin N => (X i : MvPolynomial (Fin N) Rat)))

/-- Singleton derivative rows are block-admissible for the one-block partition. -/
theorem singleton_admissible {N : Nat} (i : Fin N) :
    isBlockAdmissible (oneBlockPartition N) [i] := by
  constructor
  · simp
  · intro b
    fin_cases b
    simp [oneBlockPartition]

/-- Variables of `mlProj p` are already variables of `p`. -/
theorem vars_mlProj_subset_local {N : Nat} (p : MvPolynomial (Fin N) Rat) :
    (mlProj p).vars ⊆ p.vars := by
  intro v hv
  rw [MvPolynomial.mem_vars] at hv ⊢
  rcases hv with ⟨α, hα, hvα⟩
  exact ⟨α, mlProj_support_subset p hα, hvα⟩

/-- The coordinate variables are linearly independent in the polynomial ring. -/
theorem linearIndependent_X (N : Nat) :
    LinearIndependent Rat
      (fun i : Fin N => (X i : MvPolynomial (Fin N) Rat)) := by
  classical
  simpa [MvPolynomial.X] using
    (Finsupp.linearIndependent_single_one Rat (Fin N →₀ Nat)).comp
      (fun i : Fin N => Finsupp.single i 1)
      (by
        intro i j hij
        have h := congrArg (fun α : Fin N →₀ Nat => α i) hij
        by_cases hji : j = i
        · exact hji.symm
        · have hij' : i ≠ j := by
            intro hij_eq
            exact hji hij_eq.symm
          simp [Finsupp.single_eq_of_ne hij'] at h)

/-- The coordinate span has exact dimension `N`. -/
theorem finrank_coordinateSpan (N : Nat) :
    Module.finrank Rat (coordinateSpan N) = N := by
  unfold coordinateSpan
  have hli := linearIndependent_X N
  simpa [Fintype.card_fin] using
    (finrank_span_eq_card hli)

/-- Differentiating the diagonal quadratic in coordinate `i` gives `2 X_i`. -/
theorem pderiv_diagonalQuadratic {N : Nat} (i : Fin N) :
    pderiv i (diagonalQuadratic N) = (2 : Rat) • X i := by
  classical
  unfold diagonalQuadratic
  rw [show pderiv i (Finset.univ.sum
        (fun j : Fin N => X j * X j : Fin N -> MvPolynomial (Fin N) Rat)) =
      Finset.univ.sum (fun j : Fin N => pderiv i (X j * X j)) by
        exact map_sum (pderiv i) _ _]
  rw [Finset.sum_eq_single_of_mem i (Finset.mem_univ i)]
  · rw [pderiv_mul, MvPolynomial.pderiv_X_self]
    simp only [one_mul, mul_one]
    rw [two_smul]
  · intro j _hj hji
    rw [pderiv_mul, MvPolynomial.pderiv_X_of_ne hji]
    simp

/-- Any length-one derivative list over the diagonal quadratic is the
corresponding singleton derivative row. -/
theorem iterDerivList_diagonalQuadratic_of_length_one {N : Nat}
    (S : List (Fin N)) (hlen : S.length = 1) :
    ∃ i : Fin N, S = [i] ∧
      iterDerivList S (diagonalQuadratic N) = (2 : Rat) • X i := by
  cases S with
  | nil =>
      simp at hlen
  | cons a rest =>
      have hrest_len : rest.length = 0 := by
        have hlen' : Nat.succ rest.length = Nat.succ 0 := by
          simpa using hlen
        exact Nat.succ.inj hlen'
      have hrest : rest = [] := List.length_eq_zero_iff.mp hrest_len
      subst hrest
      exact ⟨a, rfl, by
        rw [IterDerivHelpers.iterDerivList_single, pderiv_diagonalQuadratic]⟩

/-- `mlProj` fixes every coordinate variable. -/
theorem mlProj_X {N : Nat} (i : Fin N) :
    mlProj (X i : MvPolynomial (Fin N) Rat) = X i := by
  change mlProj (MvPolynomial.monomial (Finsupp.single i 1) (1 : Rat)) =
    MvPolynomial.monomial (Finsupp.single i 1) (1 : Rat)
  have hml : Finsupp.IsMultilinear (Finsupp.single i 1) := by
    intro j
    by_cases hji : j = i
    · subst hji
      simp
    · simp [Finsupp.single_eq_of_ne hji]
  rw [mlProj_monomial, if_pos hml]

/-- Each coordinate variable belongs to the diagonal-quadratic SPDP subspace. -/
theorem X_mem_diagonalQuadratic_subspace {N : Nat} (i : Fin N) :
    X i ∈ mlBlockedSpdpSubspace (oneBlockPartition N) 1 1 (diagonalQuadratic N) := by
  have hrow :
      (2 : Rat) • X i ∈
        mlBlockedSpdpSubspace (oneBlockPartition N) 1 1 (diagonalQuadratic N) := by
    have hgen :=
      mlProj_deriv_mem (oneBlockPartition N) 1 1 (diagonalQuadratic N)
        [i] (by simp) (singleton_admissible i)
    have hgen' :
        mlProj (iterDerivList [i] (diagonalQuadratic N)) ∈
          mlBlockedSpdpSubspace (oneBlockPartition N) 1 1 (diagonalQuadratic N) := by
      simpa [one_mul] using hgen
    rw [IterDerivHelpers.iterDerivList_single, pderiv_diagonalQuadratic,
      mlProj_smul, mlProj_X] at hgen'
    exact hgen'
  have hscale :
      ((1 / 2 : Rat) • ((2 : Rat) • (X i : MvPolynomial (Fin N) Rat))) =
        (X i : MvPolynomial (Fin N) Rat) := by
    rw [smul_smul]
    norm_num
  rw [← hscale]
  exact Submodule.smul_mem _ (1 / 2 : Rat) hrow

/-- The coordinate span is contained in the diagonal-quadratic SPDP subspace. -/
theorem coordinateSpan_le_subspace (N : Nat) :
    coordinateSpan N ≤
      mlBlockedSpdpSubspace (oneBlockPartition N) 1 1 (diagonalQuadratic N) := by
  unfold coordinateSpan
  apply Submodule.span_le.mpr
  rintro p ⟨i, rfl⟩
  exact X_mem_diagonalQuadratic_subspace i

/-- The multilinear monomial basis on `{i}` is contained in `span {1, X_i}`. -/
theorem singleton_mlMonomialBasis_le_span_one_X {N : Nat} (i : Fin N) :
    Submodule.span Rat
        (↑(MlProjFar.mlMonomialBasis ({i} : Finset (Fin N))) :
          Set (MvPolynomial (Fin N) Rat)) ≤
      Submodule.span Rat
        ({(1 : MvPolynomial (Fin N) Rat), X i} :
          Set (MvPolynomial (Fin N) Rat)) := by
  apply Submodule.span_mono
  intro p hp
  simp only [MlProjFar.mlMonomialBasis, Finset.coe_image, Set.mem_image] at hp
  rcases hp with ⟨T, hT, rfl⟩
  have hT' : T ∈ ({i} : Finset (Fin N)).powerset := by
    exact hT
  by_cases hi : i ∈ T
  · have hT_eq : T = {i} := by
      ext j
      constructor
      · intro hj
        exact Finset.mem_powerset.mp hT' hj
      · intro hj
        simpa [Finset.mem_singleton.mp hj] using hi
    rw [hT_eq]
    simp
  · have hT_eq : T = ∅ := by
      ext j
      constructor
      · intro hj
        have hji : j = i := Finset.mem_singleton.mp
          (Finset.mem_powerset.mp hT' hj)
        exact (hi (by simpa [hji] using hj)).elim
      · intro hj
        simp at hj
    rw [hT_eq]
    simp

/-- Inside `span {1, X_i}`, zero constant coefficient forces membership in
`span {X_i}`. -/
theorem mem_span_X_of_mem_span_one_X_of_constantCoeff_zero {N : Nat} {i : Fin N}
    {q : MvPolynomial (Fin N) Rat}
    (hspan :
      q ∈ Submodule.span Rat
        ({(1 : MvPolynomial (Fin N) Rat), X i} :
          Set (MvPolynomial (Fin N) Rat)))
    (hconst : MvPolynomial.constantCoeff q = 0) :
    q ∈ (Rat ∙ (X i : MvPolynomial (Fin N) Rat) :
      Submodule Rat (MvPolynomial (Fin N) Rat)) := by
  rw [Submodule.mem_span_pair] at hspan
  rcases hspan with ⟨a, b, hq⟩
  have ha : a = 0 := by
    have hc := congrArg MvPolynomial.constantCoeff hq
    rw [hconst] at hc
    simpa [MvPolynomial.constantCoeff_eq] using hc
  rw [← hq, ha, zero_smul, zero_add]
  exact Submodule.smul_mem _ b (Submodule.mem_span_singleton_self _)

/-- Multiplying by a coordinate variable forces zero constant coefficient,
and `mlProj` preserves the constant coefficient. -/
theorem constantCoeff_mlProj_mul_X_zero {N : Nat} (i : Fin N)
    (m : MvPolynomial (Fin N) Rat) :
    MvPolynomial.constantCoeff (mlProj (m * ((2 : Rat) • X i))) = 0 := by
  change coeff (0 : Fin N →₀ Nat) (mlProj (m * ((2 : Rat) • X i))) = 0
  rw [coeff_mlProj_of_isMultilinear_mono _ 0 (by intro j; simp)]
  rw [show ((2 : Rat) • X i : MvPolynomial (Fin N) Rat) =
      MvPolynomial.C (2 : Rat) * X i by simp [MvPolynomial.smul_eq_C_mul]]
  rw [MvPolynomial.coeff_mul]
  apply Finset.sum_eq_zero
  intro a ha
  rcases a with ⟨a, b⟩
  rw [Finset.mem_antidiagonal] at ha
  have hbi : b i = 0 := by
    have hsum := congrArg (fun α : Fin N →₀ Nat => α i) ha
    have hsum' : a i + b i = 0 := by simpa using hsum
    omega
  have hbcoeff : coeff b (MvPolynomial.C (2 : Rat) * X i) = 0 := by
    rw [MvPolynomial.coeff_C_mul, MvPolynomial.coeff_X']
    by_cases hb : Finsupp.single i 1 = b
    · have hb_i := congrArg (fun α : Fin N →₀ Nat => α i) hb
      simp [hbi] at hb_i
    · simp [hb]
  rw [hbcoeff, mul_zero]

/-- A shifted singleton derivative generator lies in the coordinate span. -/
theorem generator_mem_coordinateSpan {N : Nat}
    (S : List (Fin N)) (m : MvPolynomial (Fin N) Rat)
    (hlen : S.length = 1) (hvars : m.vars ⊆ S.toFinset) :
    mlProj (m * iterDerivList S (diagonalQuadratic N)) ∈ coordinateSpan N := by
  rcases iterDerivList_diagonalQuadratic_of_length_one S hlen with
    ⟨i, hS, hderiv⟩
  subst hS
  rw [hderiv]
  have hspan_single :
      mlProj (m * ((2 : Rat) • X i)) ∈
        Submodule.span Rat
          (↑(MlProjFar.mlMonomialBasis ({i} : Finset (Fin N))) :
            Set (MvPolynomial (Fin N) Rat)) := by
    apply MlProjFar.mlProj_in_span_of_vars_subset
    · intro α hα
      change α ∈
        (Finsupp.filter (fun α => Finsupp.IsMultilinear α)
          (m * ((2 : Rat) • X i))).support at hα
      rw [Finsupp.support_filter] at hα
      exact (Finset.mem_filter.mp hα).2
    · intro x hx
      have hx_prod : x ∈ (m * ((2 : Rat) • X i)).vars :=
        vars_mlProj_subset_local _ hx
      have hx_split := MvPolynomial.vars_mul m (((2 : Rat) • X i)) hx_prod
      rcases Finset.mem_union.mp hx_split with hxm | hxX
      · have hmi : x ∈ ({i} : Finset (Fin N)) := by
          apply hvars at hxm
          simpa using hxm
        simpa using hmi
      · have hxX' : x ∈ (X i : MvPolynomial (Fin N) Rat).vars := by
          have hx_cmul := MvPolynomial.vars_mul (MvPolynomial.C (2 : Rat))
            (X i : MvPolynomial (Fin N) Rat) (by
              simpa [MvPolynomial.smul_eq_C_mul] using hxX)
          rcases Finset.mem_union.mp hx_cmul with hxC | hxXi
          · simp [MvPolynomial.vars_C] at hxC
          · exact hxXi
        simpa [MvPolynomial.vars_X] using hxX'
  have hspan_one_X :
      mlProj (m * ((2 : Rat) • X i)) ∈
        Submodule.span Rat
          ({(1 : MvPolynomial (Fin N) Rat), X i} :
            Set (MvPolynomial (Fin N) Rat)) :=
    singleton_mlMonomialBasis_le_span_one_X i hspan_single
  have hspan_X :
      mlProj (m * ((2 : Rat) • X i)) ∈
        (Rat ∙ (X i : MvPolynomial (Fin N) Rat) :
          Submodule Rat (MvPolynomial (Fin N) Rat)) :=
    mem_span_X_of_mem_span_one_X_of_constantCoeff_zero hspan_one_X
      (by
        simpa [MvPolynomial.constantCoeff_eq] using
          constantCoeff_mlProj_mul_X_zero i m)
  exact Submodule.span_mono
    (by
      intro p hp
      rw [Set.mem_range]
      exact ⟨i, by simpa using hp.symm⟩) hspan_X

/-- The diagonal-quadratic SPDP subspace is contained in the coordinate span. -/
theorem subspace_le_coordinateSpan (N : Nat) :
    mlBlockedSpdpSubspace (oneBlockPartition N) 1 1 (diagonalQuadratic N) ≤
      coordinateSpan N := by
  unfold mlBlockedSpdpSubspace
  apply Submodule.span_le.mpr
  rintro q ⟨S, m, hlen, _hdeg, hvars, _hadm, hq⟩
  rw [hq]
  exact generator_mem_coordinateSpan S m hlen hvars

/-- Exact rank of the diagonal-quadratic family at `(kappa, ell) = (1, 1)`. -/
theorem diagonalQuadratic_rank_eq (N : Nat) :
    mlBlockedSpdpRank (oneBlockPartition N) 1 1 (diagonalQuadratic N) = N := by
  haveI : Module.Finite Rat (coordinateSpan N) := by
    unfold coordinateSpan
    exact Module.Finite.span_of_finite Rat (Set.finite_range _)
  unfold mlBlockedSpdpRank
  apply le_antisymm
  · calc
      Module.finrank Rat
          (mlBlockedSpdpSubspace (oneBlockPartition N) 1 1 (diagonalQuadratic N))
          ≤ Module.finrank Rat (coordinateSpan N) :=
            Submodule.finrank_mono (subspace_le_coordinateSpan N)
      _ = N := finrank_coordinateSpan N
  · calc
      N = Module.finrank Rat (coordinateSpan N) := (finrank_coordinateSpan N).symm
      _ ≤ Module.finrank Rat
          (mlBlockedSpdpSubspace (oneBlockPartition N) 1 1 (diagonalQuadratic N)) :=
            Submodule.finrank_mono (coordinateSpan_le_subspace N)

/-- The arbitrary-width normalized local-polynomial package for the `kappa = 1`
Bridge A pocket. -/
noncomputable def diagonalQuadratic_normalizedLocalPolynomial
    {N d : Nat} (alpha beta alpha0 : Real) (gadgetN : Nat)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N) (Phi : Fin N -> Real) (v : Fin N) :
    BridgeAPerVertexLocalPolynomialNormalized
      alpha beta alpha0 1 gadgetN G chi Phi v where
  spdpVars := gadgetN
  partition := oneBlockPartition gadgetN
  Qv := diagonalQuadratic gadgetN
  rank_eq_normalized := by
    simpa using diagonalQuadratic_rank_eq gadgetN

/-- Family-level arbitrary-width normalized local-polynomial package for the
`kappa = 1` Bridge A pocket.  Every vertex uses the same concrete local
polynomial `sum_i X_i^2` on `gadgetN` local variables. -/
noncomputable def diagonalQuadratic_normalizedLocalPolynomialFamily
    {N d : Nat} (alpha beta alpha0 : Real) (gadgetN : Nat)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N) (Phi : Fin N -> Real) :
    BridgeACompilerLocalPolynomialFamilyNormalized
      alpha beta alpha0 1 gadgetN G chi Phi where
  spdpVars := fun _ => gadgetN
  partition := fun _ => oneBlockPartition gadgetN
  Qv := fun _ => diagonalQuadratic gadgetN
  rank_eq_normalized := by
    intro _v
    simpa using diagonalQuadratic_rank_eq gadgetN

/-! ## Axiom audit anchors -/

#print axioms pderiv_diagonalQuadratic
#print axioms linearIndependent_X
#print axioms diagonalQuadratic_rank_eq
#print axioms diagonalQuadratic_normalizedLocalPolynomial
#print axioms diagonalQuadratic_normalizedLocalPolynomialFamily

end BridgeADiagonalQuadraticFamily

end PallLean.Paper93.Paper283
