import PallLean.Paper93.Paper283.RouteBStationaryIndependentAssembly
import PallLean.Paper93.Paper283.RouteBRicherGaugeReducedCertificate

/-!
# Stationary-derived source witnesses and richer finite-row gauges

This module connects a stationary-derived Route B source witness to the
existing richer finite-row gauge machinery.  The finite-row gauge is generated
by the embedded stationary source row itself, so the fixed-embed field is a
checked finite-span projection fact.  The extraction identity and the
transport-side gauge obligations are not manufactured here; they remain
explicit certificate fields.
-/

namespace PallLean.Paper93.Paper283

open MultilinearSPDP
open PaperFaithfulCompilation
open PaperFaithfulSeparation
open TuringMachine
open PallLean.Paper93.DeepMath.PathB

/-- The one-row richer-gauge row family generated by a stationary-derived
source witness. -/
noncomputable def routeBStationaryDerivedSourceWitnessRows {N d : Nat}
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (alpha beta lam : Real)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N)
    (extractor :
      RouteBStationaryCoupledSheetExtractor M n hn2 htb hns
        alpha beta lam G chi)
    (source :
      RouteBStationaryDerivedSourceWitness M n hn2 htb hns
        alpha beta lam G chi extractor) :
    Fin 1 -> SATDeciderGaugeSpace M n hn2 htb hns :=
  fun _ =>
    CoupledSheetPoly.embed (flatCookLevinUVSplit M n hn2 htb hns) source.Q

/-- The richer finite-row candidate gauge generated by a stationary-derived
source witness. -/
noncomputable abbrev routeBStationaryDerivedSourceWitnessGauge {N d : Nat}
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (alpha beta lam : Real)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N)
    (extractor :
      RouteBStationaryCoupledSheetExtractor M n hn2 htb hns
        alpha beta lam G chi)
    (source :
      RouteBStationaryDerivedSourceWitness M n hn2 htb hns
        alpha beta lam G chi extractor) :
    PallLean.Paper93.NFrame.CandidateGauge
      (RouteBCookLevinDim M n hn2 htb hns) :=
  routeBRicherFiniteRowsCandidateGauge M n hn2 htb hns
    (routeBStationaryDerivedSourceWitnessRows
      M n hn2 htb hns alpha beta lam G chi extractor source)

/-- The unique row of the stationary-derived richer gauge is the embedded
stationary source sheet. -/
theorem routeBStationaryDerivedSourceWitnessRows_eq_embed {N d : Nat}
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (alpha beta lam : Real)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N)
    (extractor :
      RouteBStationaryCoupledSheetExtractor M n hn2 htb hns
        alpha beta lam G chi)
    (source :
      RouteBStationaryDerivedSourceWitness M n hn2 htb hns
        alpha beta lam G chi extractor)
    (i : Fin 1) :
    routeBStationaryDerivedSourceWitnessRows
        M n hn2 htb hns alpha beta lam G chi extractor source i =
      CoupledSheetPoly.embed (flatCookLevinUVSplit M n hn2 htb hns)
        source.Q := by
  rfl

/-- The stationary-derived one-row richer gauge is admissible for the current
NFrame API. -/
theorem routeBStationaryDerivedSourceWitnessGauge_admissible {N d : Nat}
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (alpha beta lam : Real)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N)
    (extractor :
      RouteBStationaryCoupledSheetExtractor M n hn2 htb hns
        alpha beta lam G chi)
    (source :
      RouteBStationaryDerivedSourceWitness M n hn2 htb hns
        alpha beta lam G chi extractor) :
    PallLean.Paper93.NFrame.AdmissibleGauge
      (routeBStationaryDerivedSourceWitnessGauge
        M n hn2 htb hns alpha beta lam G chi extractor source) :=
  routeBRicherFiniteRowsCandidateGauge_admissible M n hn2 htb hns
    (routeBStationaryDerivedSourceWitnessRows
      M n hn2 htb hns alpha beta lam G chi extractor source)

/-- The stationary-derived one-row richer gauge fixes the embedded stationary
source sheet. -/
theorem routeBStationaryDerivedSourceWitnessGauge_fixed_embed {N d : Nat}
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (alpha beta lam : Real)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N)
    (extractor :
      RouteBStationaryCoupledSheetExtractor M n hn2 htb hns
        alpha beta lam G chi)
    (source :
      RouteBStationaryDerivedSourceWitness M n hn2 htb hns
        alpha beta lam G chi extractor) :
    routeBNFrameCandidateAsSATGauge M n hn2 htb hns
        (routeBStationaryDerivedSourceWitnessGauge
          M n hn2 htb hns alpha beta lam G chi extractor source)
        (CoupledSheetPoly.embed (flatCookLevinUVSplit M n hn2 htb hns)
          source.Q) =
      CoupledSheetPoly.embed (flatCookLevinUVSplit M n hn2 htb hns)
        source.Q := by
  simpa [routeBStationaryDerivedSourceWitnessGauge,
    routeBStationaryDerivedSourceWitnessRows] using
    routeBRicherFiniteRowsCandidateGauge_fixes_row
      M n hn2 htb hns
      (routeBStationaryDerivedSourceWitnessRows
        M n hn2 htb hns alpha beta lam G chi extractor source)
      (0 : Fin 1)

/-- Exact remaining NP-side compatibility field for the stationary-derived
one-row richer gauge.  The fixed-embed part is proved by
`routeBStationaryDerivedSourceWitnessGauge_fixed_embed`; the extraction
identity is the remaining gauge-specific fact. -/
structure RouteBStationaryDerivedGaugeNPCompatibility {N d : Nat}
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (alpha beta lam : Real)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N)
    (extractor :
      RouteBStationaryCoupledSheetExtractor M n hn2 htb hns
        alpha beta lam G chi) : Type where
  source :
    RouteBStationaryDerivedSourceWitness M n hn2 htb hns
      alpha beta lam G chi extractor
  extracts_compiled :
    routeBNFrameCandidateAsSATGauge M n hn2 htb hns
        (routeBStationaryDerivedSourceWitnessGauge
          M n hn2 htb hns alpha beta lam G chi extractor source)
        (compiledPoly (cook_levin_compilation M n hn2 htb hns)) =
      routeBNFrameCandidateAsSATGauge M n hn2 htb hns
        (routeBStationaryDerivedSourceWitnessGauge
          M n hn2 htb hns alpha beta lam G chi extractor source)
        (CoupledSheetPoly.embed
          (flatCookLevinUVSplit M n hn2 htb hns) source.Q)

/-- The NP compatibility certificate forgets to the existing stationary-derived
fixed-embed certificate package. -/
noncomputable def routeBStationaryDerivedNPFixedEmbedCertificate_of_gaugeNPCompatibility
    {N d : Nat}
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (alpha beta lam : Real)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N)
    (extractor :
      RouteBStationaryCoupledSheetExtractor M n hn2 htb hns
        alpha beta lam G chi)
    (cert :
      RouteBStationaryDerivedGaugeNPCompatibility M n hn2 htb hns
        alpha beta lam G chi extractor) :
    RouteBStationaryDerivedNPFixedEmbedCertificate M n hn2 htb hns
      alpha beta lam G chi extractor
      (routeBStationaryDerivedSourceWitnessGauge
        M n hn2 htb hns alpha beta lam G chi extractor cert.source) where
  source := cert.source
  fixed_embed :=
    routeBStationaryDerivedSourceWitnessGauge_fixed_embed
      M n hn2 htb hns alpha beta lam G chi extractor cert.source
  extracts_compiled := cert.extracts_compiled

/-- The NP compatibility certificate gives the projected NP identity-minor
field for the stationary-derived richer gauge. -/
theorem routeBSATProjectedNPIdentityMinorLowerBound_of_stationaryDerivedGaugeNPCompatibility
    {N d : Nat}
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (alpha beta lam : Real)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N)
    (extractor :
      RouteBStationaryCoupledSheetExtractor M n hn2 htb hns
        alpha beta lam G chi)
    (cert :
      RouteBStationaryDerivedGaugeNPCompatibility M n hn2 htb hns
        alpha beta lam G chi extractor) :
    RouteBSATProjectedNPIdentityMinorLowerBound M n hn2 htb hns
      (routeBNFrameCandidateAsSATGauge M n hn2 htb hns
        (routeBStationaryDerivedSourceWitnessGauge
          M n hn2 htb hns alpha beta lam G chi extractor cert.source)) :=
  routeBSATProjectedNPIdentityMinorLowerBound_of_stationaryDerived
    M n hn2 htb hns alpha beta lam G chi extractor
    (routeBStationaryDerivedSourceWitnessGauge
      M n hn2 htb hns alpha beta lam G chi extractor cert.source)
    (routeBStationaryDerivedNPFixedEmbedCertificate_of_gaugeNPCompatibility
      M n hn2 htb hns alpha beta lam G chi extractor cert)

/-- Exact remaining transport-side fields for the stationary-derived one-row
richer gauge.  The NP lower-bound component is supplied by
`RouteBStationaryDerivedGaugeNPCompatibility`; SPDP containment and the
unprojected P-window cover remain the genuine gauge compatibility inputs. -/
structure RouteBStationaryDerivedGaugeTransportCompatibility {N d : Nat}
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (alpha beta lam : Real)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N)
    (extractor :
      RouteBStationaryCoupledSheetExtractor M n hn2 htb hns
        alpha beta lam G chi) : Type where
  np :
    RouteBStationaryDerivedGaugeNPCompatibility M n hn2 htb hns
      alpha beta lam G chi extractor
  spdp_containment :
    RouteBRicherGaugeSPDPSubspaceContainment M n hn2 htb hns
      (routeBStationaryDerivedSourceWitnessGauge
        M n hn2 htb hns alpha beta lam G chi extractor np.source)
  p_window_cover :
    RouteBRicherGaugeUnprojectedPWindowFiniteSpanCover M n hn2 htb hns

/-- The transport compatibility certificate reaches the primitive Route B
functorial transport package. -/
theorem routeBFunctorialTransportCertificate_of_stationaryDerivedGaugeCompatibility
    {N d : Nat}
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (alpha beta lam : Real)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N)
    (extractor :
      RouteBStationaryCoupledSheetExtractor M n hn2 htb hns
        alpha beta lam G chi)
    (cert :
      RouteBStationaryDerivedGaugeTransportCompatibility M n hn2 htb hns
        alpha beta lam G chi extractor) :
    RouteBFunctorialTransportCertificate M n hn2 htb hns
      (routeBStationaryDerivedSourceWitnessGauge
        M n hn2 htb hns alpha beta lam G chi extractor cert.np.source) :=
  routeBRicherFiniteRowsCandidateGauge_transportCertificate_of_stationaryDerived
    M n hn2 htb hns alpha beta lam G chi extractor
    (routeBStationaryDerivedSourceWitnessRows
      M n hn2 htb hns alpha beta lam G chi extractor cert.np.source)
    cert.spdp_containment cert.p_window_cover cert.np.source (0 : Fin 1)
    (routeBStationaryDerivedSourceWitnessRows_eq_embed
      M n hn2 htb hns alpha beta lam G chi extractor cert.np.source
      (0 : Fin 1))
    cert.np.extracts_compiled

/-- Specialized NP compatibility surface for the monomial-product stationary
source constructor.  It exposes only the extraction identity left after the
one-row richer gauge proves fixed-embed. -/
structure RouteBStationaryMonomialGaugeNPCompatibility {N d : Nat}
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (alpha beta lam : Real)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N)
    (extractor :
      RouteBStationaryCoupledSheetExtractor M n hn2 htb hns
        alpha beta lam G chi) : Type where
  monomial_source :
    RouteBStationaryMonomialProductCertificate M n hn2 htb hns
      alpha beta lam G chi extractor
  extracts_compiled :
    let source :=
      routeBStationaryDerivedSourceWitness_of_monomialProduct
        M n hn2 htb hns alpha beta lam G chi extractor monomial_source
    routeBNFrameCandidateAsSATGauge M n hn2 htb hns
        (routeBStationaryDerivedSourceWitnessGauge
          M n hn2 htb hns alpha beta lam G chi extractor source)
        (compiledPoly (cook_levin_compilation M n hn2 htb hns)) =
      routeBNFrameCandidateAsSATGauge M n hn2 htb hns
        (routeBStationaryDerivedSourceWitnessGauge
          M n hn2 htb hns alpha beta lam G chi extractor source)
        (CoupledSheetPoly.embed
          (flatCookLevinUVSplit M n hn2 htb hns) source.Q)

/-- A monomial-product stationary compatibility certificate is an instance of
the generic stationary-derived NP compatibility surface. -/
noncomputable def routeBStationaryDerivedGaugeNPCompatibility_of_monomial
    {N d : Nat}
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (alpha beta lam : Real)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N)
    (extractor :
      RouteBStationaryCoupledSheetExtractor M n hn2 htb hns
        alpha beta lam G chi)
    (cert :
      RouteBStationaryMonomialGaugeNPCompatibility M n hn2 htb hns
        alpha beta lam G chi extractor) :
    RouteBStationaryDerivedGaugeNPCompatibility M n hn2 htb hns
      alpha beta lam G chi extractor where
  source :=
    routeBStationaryDerivedSourceWitness_of_monomialProduct
      M n hn2 htb hns alpha beta lam G chi extractor cert.monomial_source
  extracts_compiled := cert.extracts_compiled

/-! ## Axiom audit anchors -/

#print axioms routeBStationaryDerivedSourceWitnessRows_eq_embed
#print axioms routeBStationaryDerivedSourceWitnessGauge_admissible
#print axioms routeBStationaryDerivedSourceWitnessGauge_fixed_embed
#print axioms routeBStationaryDerivedNPFixedEmbedCertificate_of_gaugeNPCompatibility
#print axioms routeBSATProjectedNPIdentityMinorLowerBound_of_stationaryDerivedGaugeNPCompatibility
#print axioms routeBFunctorialTransportCertificate_of_stationaryDerivedGaugeCompatibility
#print axioms routeBStationaryDerivedGaugeNPCompatibility_of_monomial

end PallLean.Paper93.Paper283
