import PallLean.Paper93.Paper283.RouteBRicherGaugeSPDPStableCandidateProfileTail

/-!
# Head subspace cover for the Route B SPDP-stable candidate

This file isolates the finite head-cover part of the Route B profile-window
candidate.  The selected tail is a basis for the finite supremum of all strict
blocked-SPDP head subspaces inside the canonical log window.
-/

namespace PallLean.Paper93.Paper283

open scoped BigOperators
open MultilinearSPDP
open PaperFaithfulCompilation
open PaperFaithfulSeparation
open TuringMachine
open PallLean.Paper93.DeepMath.PathB

attribute [local instance] Classical.dec

/-- The finite ambient subspace generated by all strict blocked-SPDP subspaces
of the compiled head row whose `(kappa, ell)` profile lies in the canonical
log window. -/
noncomputable abbrev routeBRicherSPDPStableCandidateLogWindowHeadSpan
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n) :
    Submodule Rat (SATDeciderGaugeSpace M n hn2 htb hns) :=
  ⨆ kappa : Fin (Nat.log 2 n + 1),
    ⨆ ell : Fin (Nat.log 2 n + 1),
      mlBlockedSpdpSubspace
        (cook_levin_compilation M n hn2 htb hns).partition
        kappa.1 ell.1
        (compiledPoly (cook_levin_compilation M n hn2 htb hns))

/-- The finite log-window head span contains each strict head SPDP subspace in
the window. -/
theorem routeBRicherSPDPStableCandidateLogWindowHeadSpan_contains
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (spdpKappa ell : Nat)
    (hKappa : spdpKappa <= Nat.log 2 n)
    (hEll : ell <= Nat.log 2 n) :
    mlBlockedSpdpSubspace
        (cook_levin_compilation M n hn2 htb hns).partition
        spdpKappa ell
        (compiledPoly (cook_levin_compilation M n hn2 htb hns)) <=
      routeBRicherSPDPStableCandidateLogWindowHeadSpan M n hn2 htb hns := by
  let kappaFin : Fin (Nat.log 2 n + 1) :=
    ⟨spdpKappa, Nat.lt_succ_of_le hKappa⟩
  let ellFin : Fin (Nat.log 2 n + 1) :=
    ⟨ell, Nat.lt_succ_of_le hEll⟩
  simpa [routeBRicherSPDPStableCandidateLogWindowHeadSpan, kappaFin, ellFin]
    using
      (le_iSup_of_le kappaFin
        (le_iSup_of_le ellFin
          (le_rfl :
            mlBlockedSpdpSubspace
              (cook_levin_compilation M n hn2 htb hns).partition
              kappaFin.1 ellFin.1
              (compiledPoly (cook_levin_compilation M n hn2 htb hns)) <=
            mlBlockedSpdpSubspace
              (cook_levin_compilation M n hn2 htb hns).partition
              kappaFin.1 ellFin.1
              (compiledPoly (cook_levin_compilation M n hn2 htb hns)))))

/-- Basis tail for the finite log-window head span. -/
noncomputable def routeBRicherSPDPStableCandidateLogWindowHeadTail
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n) :
    Fin
      (Module.finrank Rat
        (routeBRicherSPDPStableCandidateLogWindowHeadSpan
          M n hn2 htb hns)) ->
      SATDeciderGaugeSpace M n hn2 htb hns :=
  let U := routeBRicherSPDPStableCandidateLogWindowHeadSpan M n hn2 htb hns
  let b : Module.Basis (Fin (Module.finrank Rat U)) Rat U :=
    Module.finBasis Rat U
  fun i => (b i : SATDeciderGaugeSpace M n hn2 htb hns)

/-- The finite basis tail spans the log-window head span. -/
theorem routeBRicherSPDPStableCandidateLogWindowHeadSpan_le_tailSpan
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n) :
    routeBRicherSPDPStableCandidateLogWindowHeadSpan M n hn2 htb hns <=
      finiteRowsSubmodule
        (routeBRicherSPDPStableCandidateLogWindowHeadTail
          M n hn2 htb hns) := by
  let U := routeBRicherSPDPStableCandidateLogWindowHeadSpan M n hn2 htb hns
  let b : Module.Basis (Fin (Module.finrank Rat U)) Rat U :=
    Module.finBasis Rat U
  intro x hx
  change x ∈ Submodule.span Rat
    (Set.range
      (fun i : Fin (Module.finrank Rat U) =>
        ((b i : U) : SATDeciderGaugeSpace M n hn2 htb hns)))
  have hmemU : (⟨x, hx⟩ : U) ∈ Submodule.span Rat (Set.range b) :=
    Module.Basis.mem_span b ⟨x, hx⟩
  have hmemMap :
      U.subtype (⟨x, hx⟩ : U) ∈
        Submodule.map U.subtype (Submodule.span Rat (Set.range b)) :=
    ⟨⟨x, hx⟩, hmemU, rfl⟩
  have hmap :
      Submodule.map U.subtype (Submodule.span Rat (Set.range b)) =
        Submodule.span Rat
          ((fun y : U => (y : SATDeciderGaugeSpace M n hn2 htb hns)) ''
            Set.range b) := by
    rw [Submodule.map_span]
    rfl
  rw [hmap] at hmemMap
  refine Submodule.span_mono ?_ hmemMap
  intro y hy
  rcases hy with ⟨z, ⟨i, rfl⟩, rfl⟩
  exact ⟨i, rfl⟩

/-- The finite basis tail spans the log-window head span even after the
concrete NP head row is prepended. -/
theorem routeBRicherSPDPStableCandidateLogWindowHeadSpan_le_candidateRowsSpan
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n) :
    routeBRicherSPDPStableCandidateLogWindowHeadSpan M n hn2 htb hns <=
      finiteRowsSubmodule
        (routeBRicherSPDPStableCandidateRows M n hn2 htb hns
          (routeBRicherSPDPStableCandidateLogWindowHeadTail
            M n hn2 htb hns)) := by
  refine le_trans
    (routeBRicherSPDPStableCandidateLogWindowHeadSpan_le_tailSpan
      M n hn2 htb hns) ?_
  simpa [routeBRicherSPDPStableCandidateRows] using
    (finiteRowsSubmodule_le_concreteNPPrependedRows_tail
      M n hn2 htb hns
      (routeBRicherSPDPStableCandidateLogWindowHeadTail
        M n hn2 htb hns))

/-- Any common finite row span containing every log-window head subspace gives
the head-subspace-cover predicate.  This is the thin interface for downstream
profile/common-span constructions. -/
theorem routeBRicherSPDPStableCandidate_logWindowHeadSPDPSubspaceCovered_of_commonSubspace
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (hcommon :
      forall (spdpKappa ell : Nat),
        spdpKappa <= Nat.log 2 n ->
        ell <= Nat.log 2 n ->
        mlBlockedSpdpSubspace
            (cook_levin_compilation M n hn2 htb hns).partition
            spdpKappa ell
            (compiledPoly (cook_levin_compilation M n hn2 htb hns)) <=
          finiteRowsSubmodule
            (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail)) :
    RouteBRicherSPDPStableCandidateLogWindowHeadSPDPSubspaceCovered
      M n hn2 htb hns tail := by
  intro spdpKappa ell hKappa hEll
  exact hcommon spdpKappa ell hKappa hEll

/-- The basis tail for the finite log-window head span proves the Route B
SPDP-stable candidate's head-subspace-cover target. -/
theorem routeBRicherSPDPStableCandidate_logWindowHeadSPDPSubspaceCovered_for_headSpanTail
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n) :
    RouteBRicherSPDPStableCandidateLogWindowHeadSPDPSubspaceCovered
      M n hn2 htb hns
      (routeBRicherSPDPStableCandidateLogWindowHeadTail
        M n hn2 htb hns) := by
  apply
    routeBRicherSPDPStableCandidate_logWindowHeadSPDPSubspaceCovered_of_commonSubspace
  intro spdpKappa ell hKappa hEll
  exact le_trans
    (routeBRicherSPDPStableCandidateLogWindowHeadSpan_contains
      M n hn2 htb hns spdpKappa ell hKappa hEll)
    (routeBRicherSPDPStableCandidateLogWindowHeadSpan_le_candidateRowsSpan
      M n hn2 htb hns)

/-- Row-level log-window head coverage follows immediately for the basis tail. -/
theorem routeBRicherSPDPStableCandidate_logWindowHeadMlCovering_for_headSpanTail
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n) :
    RouteBRicherSPDPStableCandidateLogWindowHeadMlCovering
      M n hn2 htb hns
      (routeBRicherSPDPStableCandidateLogWindowHeadTail
        M n hn2 htb hns) :=
  routeBRicherSPDPStableCandidate_logWindowHeadMlCovering_of_headSPDPSubspaceCovered
    M n hn2 htb hns
    (routeBRicherSPDPStableCandidateLogWindowHeadTail
      M n hn2 htb hns)
    (routeBRicherSPDPStableCandidate_logWindowHeadSPDPSubspaceCovered_for_headSpanTail
      M n hn2 htb hns)

/-! ## Axiom audit anchors -/

#print axioms routeBRicherSPDPStableCandidateLogWindowHeadSpan_contains
#print axioms routeBRicherSPDPStableCandidateLogWindowHeadSpan_le_tailSpan
#print axioms routeBRicherSPDPStableCandidateLogWindowHeadSpan_le_candidateRowsSpan
#print axioms routeBRicherSPDPStableCandidate_logWindowHeadSPDPSubspaceCovered_of_commonSubspace
#print axioms routeBRicherSPDPStableCandidate_logWindowHeadSPDPSubspaceCovered_for_headSpanTail
#print axioms routeBRicherSPDPStableCandidate_logWindowHeadMlCovering_for_headSpanTail

end PallLean.Paper93.Paper283
