import PallLean.Paper93.Paper283.RouteBRicherGaugePrependedCorrectedMapPreimage

/-!
# Concrete multilinear tail rows for the Route B richer gauge

The one-row concrete NP witness is not SPDP-row closed by itself: the scalar
closure target is false.  This module supplies a concrete finite richer tail
that closes the finite-row part honestly: all multilinear monomials in the
Cook-Levin ambient variable set.

This is intentionally a broad finite tail.  It discharges the selected-row
closure package because every Route B SPDP generator row is an `mlProj` output,
and hence lies in the span of the multilinear monomial basis.  The separate
map-preimage/P-window obligations remain explicit.
-/

namespace PallLean.Paper93.Paper283

open scoped BigOperators
open MultilinearSPDP
open PaperFaithfulCompilation
open PaperFaithfulSeparation
open TuringMachine
open SymmetricPowerBound
open WithinProfileBound
open PallLean.Paper93.DeepMath.PathB

attribute [local instance] Classical.dec

/-- The concrete multilinear monomial tail basis in the Route B Cook-Levin
ambient row space. -/
noncomputable def routeBRicherMultilinearTailBasis
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n) :
    Finset (SATDeciderGaugeSpace M n hn2 htb hns) :=
  MlProjFar.mlMonomialBasis
    (Finset.univ : Finset (Fin (RouteBCookLevinDim M n hn2 htb hns)))

/-- Number of concrete multilinear monomial tail rows. -/
noncomputable abbrev routeBRicherMultilinearTailRowCount
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n) : Nat :=
  (routeBRicherMultilinearTailBasis M n hn2 htb hns).card

/-- The broad multilinear tail has the expected coarse exponential row-count
bound in the Cook-Levin ambient dimension. -/
theorem routeBRicherMultilinearTailRowCount_le_two_pow_dim
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n) :
    routeBRicherMultilinearTailRowCount M n hn2 htb hns <=
      2 ^ RouteBCookLevinDim M n hn2 htb hns := by
  simpa [routeBRicherMultilinearTailRowCount,
    routeBRicherMultilinearTailBasis] using
    MlProjFar.mlMonomialBasis_card
      (Finset.univ :
        Finset (Fin (RouteBCookLevinDim M n hn2 htb hns)))

/-- A usable row-budget side condition for the concrete multilinear tail. -/
theorem routeBRicherConcreteNPPrependedMultilinearRows_rowCount_le_of_two_pow_dim
    {N : Nat}
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (hNrows :
      2 ^ RouteBCookLevinDim M n hn2 htb hns + 1 <= N) :
    routeBRicherMultilinearTailRowCount M n hn2 htb hns + 1 <= N :=
  (Nat.add_le_add_right
    (routeBRicherMultilinearTailRowCount_le_two_pow_dim
      M n hn2 htb hns) 1).trans hNrows

/-- Concrete richer tail rows: an enumeration of all multilinear monomials in
the Cook-Levin ambient row space. -/
noncomputable def routeBRicherMultilinearTailRows
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n) :
    Fin (routeBRicherMultilinearTailRowCount M n hn2 htb hns) ->
      SATDeciderGaugeSpace M n hn2 htb hns :=
  fun i =>
    ((Finset.equivFin
      (routeBRicherMultilinearTailBasis M n hn2 htb hns)).symm i).1

/-- The concrete prepended row family: the Cook-Levin NP witness followed by
the multilinear monomial tail. -/
noncomputable abbrev routeBRicherConcreteNPPrependedMultilinearRows
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n) :
    Fin (routeBRicherMultilinearTailRowCount M n hn2 htb hns + 1) ->
      SATDeciderGaugeSpace M n hn2 htb hns :=
  routeBRicherConcreteNPPrependedRows M n hn2 htb hns
    (routeBRicherMultilinearTailRows M n hn2 htb hns)

/-- The finite-row candidate gauge generated by the concrete NP row plus the
multilinear monomial tail. -/
noncomputable abbrev routeBRicherConcreteNPPrependedMultilinearGauge
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n) :
    PallLean.Paper93.NFrame.CandidateGauge
      (RouteBCookLevinDim M n hn2 htb hns) :=
  routeBRicherFiniteRowsCandidateGauge M n hn2 htb hns
    (routeBRicherConcreteNPPrependedMultilinearRows M n hn2 htb hns)

/-- Every tail-basis row is in the finite span of the enumerated tail rows. -/
theorem routeBRicherMultilinearTailRows_mem_span_of_mem_basis
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {p : SATDeciderGaugeSpace M n hn2 htb hns}
    (hp : p ∈ routeBRicherMultilinearTailBasis M n hn2 htb hns) :
    p ∈ finiteRowsSubmodule
      (routeBRicherMultilinearTailRows M n hn2 htb hns) := by
  apply Submodule.subset_span
  refine
    ⟨(Finset.equivFin
        (routeBRicherMultilinearTailBasis M n hn2 htb hns)) ⟨p, hp⟩, ?_⟩
  simp [routeBRicherMultilinearTailRows]

/-- Every `mlProj` output lies in the span of the multilinear monomial tail. -/
theorem routeBRicherMultilinearTailRows_mlProj_mem
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (p : SATDeciderGaugeSpace M n hn2 htb hns) :
    mlProj p ∈ finiteRowsSubmodule
      (routeBRicherMultilinearTailRows M n hn2 htb hns) := by
  have hle :
      Submodule.span ℚ
          (↑(routeBRicherMultilinearTailBasis M n hn2 htb hns) :
            Set (SATDeciderGaugeSpace M n hn2 htb hns)) ≤
        finiteRowsSubmodule
          (routeBRicherMultilinearTailRows M n hn2 htb hns) := by
    apply Submodule.span_le.mpr
    intro q hq
    exact
      routeBRicherMultilinearTailRows_mem_span_of_mem_basis
        M n hn2 htb hns hq
  exact hle (WithinProfileBound.mlProj_mem_span_mlMonomialBasis p)

/-- The tail span is contained in the span after the concrete NP row is
prepended. -/
theorem finiteRowsSubmodule_le_concreteNPPrependedRows_tail
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    finiteRowsSubmodule tail ≤
      finiteRowsSubmodule
        (routeBRicherConcreteNPPrependedRows M n hn2 htb hns tail) := by
  apply Submodule.span_le.mpr
  rintro p ⟨i, rfl⟩
  apply Submodule.subset_span
  exact ⟨Fin.succ i, rfl⟩

/-- Every `mlProj` output lies in the span after prepending the concrete NP
row to the multilinear tail. -/
theorem routeBRicherConcreteNPPrependedMultilinearRows_mlProj_mem
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (p : SATDeciderGaugeSpace M n hn2 htb hns) :
    mlProj p ∈ finiteRowsSubmodule
      (routeBRicherConcreteNPPrependedMultilinearRows M n hn2 htb hns) := by
  exact
    finiteRowsSubmodule_le_concreteNPPrependedRows_tail
      M n hn2 htb hns
      (routeBRicherMultilinearTailRows M n hn2 htb hns)
      (routeBRicherMultilinearTailRows_mlProj_mem M n hn2 htb hns p)

/-- The concrete NP row plus multilinear monomial tail satisfies the explicit
head/tail SPDP row-closure package. -/
theorem routeBRicherConcreteNPPrependedMultilinearRows_spdpRowClosurePackage
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n) :
    RouteBRicherConcreteNPPrependedRowsSPDPRowClosurePackage
      M n hn2 htb hns
      (routeBRicherMultilinearTailRows M n hn2 htb hns) where
  concrete_row_closure := by
    intro _spdpKappa _ell S shift _hSlen _hshiftDegree _hshiftVars _hadm
    exact
      routeBRicherConcreteNPPrependedMultilinearRows_mlProj_mem
        M n hn2 htb hns
        (shift *
          SPDP.iterDerivList S
            (routeBRicherConcreteNPWitnessRows M n hn2 htb hns 0))
  tail_row_closure := by
    intro _spdpKappa _ell S shift _hSlen _hshiftDegree _hshiftVars _hadm i
    exact
      routeBRicherConcreteNPPrependedMultilinearRows_mlProj_mem
        M n hn2 htb hns
        (shift *
          SPDP.iterDerivList S
            (routeBRicherMultilinearTailRows M n hn2 htb hns i))

/-- The concrete NP row plus multilinear monomial tail satisfies the
finite-row SPDP closure half. -/
theorem routeBRicherConcreteNPPrependedMultilinearRows_spdpClosure
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n) :
    RouteBRicherGaugeFiniteRowsSPDPClosure M n hn2 htb hns
      (routeBRicherConcreteNPPrependedMultilinearRows M n hn2 htb hns) :=
  routeBRicherConcreteNPPrependedRows_spdpClosure_of_rowClosurePackage
    M n hn2 htb hns
    (routeBRicherMultilinearTailRows M n hn2 htb hns)
    (routeBRicherConcreteNPPrependedMultilinearRows_spdpRowClosurePackage
      M n hn2 htb hns)

/-- With the separate unprojected-preimage side supplied, the concrete NP row
plus multilinear monomial tail gives the finite-row map-preimage surface. -/
theorem routeBRicherConcreteNPPrependedMultilinearRows_spdpMapPreimage_of_unprojectedPreimage
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (preimage :
      RouteBRicherGaugeFiniteRowsSPDPUnprojectedPreimage M n hn2 htb hns
        (routeBRicherConcreteNPPrependedMultilinearRows M n hn2 htb hns)) :
    RouteBRicherGaugeFiniteRowsSPDPMapPreimage M n hn2 htb hns
      (routeBRicherConcreteNPPrependedMultilinearRows M n hn2 htb hns) :=
  routeBRicherConcreteNPPrependedRows_spdpMapPreimage_of_rowClosurePackage_unprojectedPreimage
    M n hn2 htb hns
    (routeBRicherMultilinearTailRows M n hn2 htb hns)
    (routeBRicherConcreteNPPrependedMultilinearRows_spdpRowClosurePackage
      M n hn2 htb hns)
    preimage

/-- For the concrete multilinear-tail gauge, the map-preimage SPDP target is
equivalent to the Route B SPDP image-containment field itself.

This is the corrected surface for the remaining projection work: the broad
multilinear tail closes finite-row closure, while the SPDP content is exactly
image containment for the selected finite-rank projection. -/
theorem routeBRicherConcreteNPPrependedMultilinearRows_spdpMapPreimage_iff_spdpSubspaceContainment
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n) :
    RouteBRicherGaugeFiniteRowsSPDPMapPreimage M n hn2 htb hns
        (routeBRicherConcreteNPPrependedMultilinearRows M n hn2 htb hns) ↔
      RouteBRicherGaugeSPDPSubspaceContainment M n hn2 htb hns
        (routeBRicherConcreteNPPrependedMultilinearGauge M n hn2 htb hns) := by
  simpa [routeBRicherConcreteNPPrependedMultilinearGauge] using
    routeBRicherGaugeFiniteRowsSPDPMapPreimage_iff_spdpSubspaceContainment
      M n hn2 htb hns
      (routeBRicherConcreteNPPrependedMultilinearRows M n hn2 htb hns)

/-- Concrete-tail Route B certificate from the map-preimage SPDP side and the
corrected active-blocker/non-scalar P-window cover.

Unlike the older unprojected-preimage wrapper, this consumes the weaker
`RouteBRicherGaugeFiniteRowsSPDPMapPreimage` field directly, which is the
actual image-containment witness needed by the finite-row assembly. -/
theorem routeBPerInstanceCertificate_of_prependedConcreteNP_multilinearTail_mapPreimage_activeBlockersZeroNonScalarCover_deltaEqRateKappa
    {N d : Nat}
    (M : DTM) (n : Nat) (hn : n >= 2 ^ 804) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (hn4 : n >= 4)
    (alpha beta alpha0 : Real) (kappa gadgetN : Nat)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N) (Phi : Fin N -> Real)
    {eta theta : Real}
    (hN : 1 <= N)
    (hrowCount :
      routeBRicherMultilinearTailRowCount M n hn2 htb hns + 1 <= N)
    (heta : 0 < eta) (htheta : 0 < theta)
    (halpha : 0 < alpha) (halpha0 : 0 < alpha0)
    (hkappa : 0 < kappa) (hgadgetN : 2 <= gadgetN)
    (hbound :
      cookLevinZeroProfileNonScalarCardBound M n hn2 htb hns <=
        withinProfileBound (Nat.log 2 n))
    (hactive :
      CookLevinActiveProfileTypeCaseBlockers M n hn2 htb hns)
    (preimage :
      RouteBRicherGaugeFiniteRowsSPDPMapPreimage M n hn2 htb hns
        (routeBRicherConcreteNPPrependedMultilinearRows M n hn2 htb hns)) :
    RouteBPerInstanceCertificate M n hn2 htb hns :=
  routeBPerInstanceCertificate_of_prependedConcreteNP_finiteRowsSPDPMapPreimage_activeBlockersZeroNonScalarCover_deltaEqRateKappa
    (N := N) (d := d)
    M n hn hn2 htb hns hn4
    alpha beta alpha0 kappa gadgetN G chi Phi
    (routeBRicherMultilinearTailRows M n hn2 htb hns)
    hN hrowCount heta htheta halpha halpha0 hkappa hgadgetN
    hbound hactive preimage

/-- Concrete-tail Route B certificate from the map-preimage SPDP side, with
P-window inputs reduced to the primitive per-type spanning package and the
zero-profile support-card finite-sum side condition. -/
theorem routeBPerInstanceCertificate_of_prependedConcreteNP_multilinearTail_mapPreimage_perTypeSpanning_zeroSupportCardSum_deltaEqRateKappa
    {N d : Nat}
    (M : DTM) (n : Nat) (hn : n >= 2 ^ 804) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (hn4 : n >= 4)
    (alpha beta alpha0 : Real) (kappa gadgetN : Nat)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N) (Phi : Fin N -> Real)
    {eta theta : Real}
    (hN : 1 <= N)
    (hrowCount :
      routeBRicherMultilinearTailRowCount M n hn2 htb hns + 1 <= N)
    (heta : 0 < eta) (htheta : 0 < theta)
    (halpha : 0 < alpha) (halpha0 : 0 < alpha0)
    (hkappa : 0 < kappa) (hgadgetN : 2 <= gadgetN)
    (W : ConstraintType -> Submodule Rat (MvPolynomial (Fin n) Rat))
    (hW_fin : forall tau, Module.Finite Rat (W tau))
    (hW_dim : forall tau, Module.finrank Rat (W tau) <= 3)
    (hSpan :
      PallLean.Paper93.Spanning.CookLevinPerTypeSpanning
        M n hn2 htb hns W)
    (hzero :
      CookLevinZeroProfileSupportCardSumSideCondition M n hn2 htb hns)
    (preimage :
      RouteBRicherGaugeFiniteRowsSPDPMapPreimage M n hn2 htb hns
        (routeBRicherConcreteNPPrependedMultilinearRows M n hn2 htb hns)) :
    RouteBPerInstanceCertificate M n hn2 htb hns :=
  routeBPerInstanceCertificate_of_prependedConcreteNP_finiteRowsSPDPMapPreimage_perTypeSpanning_zeroSupportCardSum_deltaEqRateKappa
    (N := N) (d := d)
    M n hn hn2 htb hns hn4
    alpha beta alpha0 kappa gadgetN G chi Phi
    (routeBRicherMultilinearTailRows M n hn2 htb hns)
    hN hrowCount heta htheta halpha halpha0 hkappa hgadgetN
    W hW_fin hW_dim hSpan hzero preimage

/-- Concrete-tail Route B certificate with the SPDP side stated directly as
Route B image containment and the P-side reduced to the primitive per-type
spanning plus zero-profile support-card inputs. -/
theorem routeBPerInstanceCertificate_of_prependedConcreteNP_multilinearTail_spdpContainment_perTypeSpanning_zeroSupportCardSum_deltaEqRateKappa
    {N d : Nat}
    (M : DTM) (n : Nat) (hn : n >= 2 ^ 804) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (hn4 : n >= 4)
    (alpha beta alpha0 : Real) (kappa gadgetN : Nat)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N) (Phi : Fin N -> Real)
    {eta theta : Real}
    (hN : 1 <= N)
    (hrowCount :
      routeBRicherMultilinearTailRowCount M n hn2 htb hns + 1 <= N)
    (heta : 0 < eta) (htheta : 0 < theta)
    (halpha : 0 < alpha) (halpha0 : 0 < alpha0)
    (hkappa : 0 < kappa) (hgadgetN : 2 <= gadgetN)
    (W : ConstraintType -> Submodule Rat (MvPolynomial (Fin n) Rat))
    (hW_fin : forall tau, Module.Finite Rat (W tau))
    (hW_dim : forall tau, Module.finrank Rat (W tau) <= 3)
    (hSpan :
      PallLean.Paper93.Spanning.CookLevinPerTypeSpanning
        M n hn2 htb hns W)
    (hzero :
      CookLevinZeroProfileSupportCardSumSideCondition M n hn2 htb hns)
    (contain :
      RouteBRicherGaugeSPDPSubspaceContainment M n hn2 htb hns
        (routeBRicherConcreteNPPrependedMultilinearGauge M n hn2 htb hns)) :
    RouteBPerInstanceCertificate M n hn2 htb hns :=
  routeBPerInstanceCertificate_of_prependedConcreteNP_multilinearTail_mapPreimage_perTypeSpanning_zeroSupportCardSum_deltaEqRateKappa
    (N := N) (d := d)
    M n hn hn2 htb hns hn4
    alpha beta alpha0 kappa gadgetN G chi Phi
    hN hrowCount heta htheta halpha halpha0 hkappa hgadgetN
    W hW_fin hW_dim hSpan hzero
    ((routeBRicherConcreteNPPrependedMultilinearRows_spdpMapPreimage_iff_spdpSubspaceContainment
      M n hn2 htb hns).mpr contain)

/-- Concrete-tail Route B certificate from the unprojected-preimage side and
an endpoint/charged P-window bridge. -/
theorem routeBPerInstanceCertificate_of_prependedConcreteNP_multilinearTail_unprojectedPreimage_endpointChargedBridge_deltaEqRateKappa
    {N d : Nat}
    (M : DTM) (n : Nat) (hn : n >= 2 ^ 804) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (hn4 : n >= 4) (charge : ProfileCharge n)
    (alpha beta alpha0 : Real) (kappa gadgetN : Nat)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N) (Phi : Fin N -> Real)
    {eta theta : Real}
    (hN : 1 <= N)
    (hrowCount :
      routeBRicherMultilinearTailRowCount M n hn2 htb hns + 1 <= N)
    (heta : 0 < eta) (htheta : 0 < theta)
    (halpha : 0 < alpha) (halpha0 : 0 < alpha0)
    (hkappa : 0 < kappa) (hgadgetN : 2 <= gadgetN)
    (unprojectedPreimage :
      RouteBRicherGaugeFiniteRowsSPDPUnprojectedPreimage M n hn2 htb hns
        (routeBRicherConcreteNPPrependedMultilinearRows M n hn2 htb hns))
    (bridge :
      RouteBRicherGaugeEndpointChargedPWindowBridge
        M n hn2 htb hns hn4 charge) :
    RouteBPerInstanceCertificate M n hn2 htb hns :=
  routeBPerInstanceCertificate_of_prependedConcreteNP_rowClosurePackage_unprojectedPreimage_endpointChargedBridge_deltaEqRateKappa
    (N := N) (d := d)
    M n hn hn2 htb hns hn4 charge
    alpha beta alpha0 kappa gadgetN G chi Phi
    (routeBRicherMultilinearTailRows M n hn2 htb hns)
    hN hrowCount heta htheta halpha halpha0 hkappa hgadgetN
    (routeBRicherConcreteNPPrependedMultilinearRows_spdpRowClosurePackage
      M n hn2 htb hns)
    unprojectedPreimage bridge

/-- Concrete-tail Route B certificate from the unprojected-preimage side and
the active-blocker/non-scalar P-window cover. -/
theorem routeBPerInstanceCertificate_of_prependedConcreteNP_multilinearTail_unprojectedPreimage_activeBlockersZeroNonScalarCover_deltaEqRateKappa
    {N d : Nat}
    (M : DTM) (n : Nat) (hn : n >= 2 ^ 804) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (hn4 : n >= 4)
    (alpha beta alpha0 : Real) (kappa gadgetN : Nat)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N) (Phi : Fin N -> Real)
    {eta theta : Real}
    (hN : 1 <= N)
    (hrowCount :
      routeBRicherMultilinearTailRowCount M n hn2 htb hns + 1 <= N)
    (heta : 0 < eta) (htheta : 0 < theta)
    (halpha : 0 < alpha) (halpha0 : 0 < alpha0)
    (hkappa : 0 < kappa) (hgadgetN : 2 <= gadgetN)
    (hbound :
      cookLevinZeroProfileNonScalarCardBound M n hn2 htb hns <=
        withinProfileBound (Nat.log 2 n))
    (hactive :
      CookLevinActiveProfileTypeCaseBlockers M n hn2 htb hns)
    (unprojectedPreimage :
      RouteBRicherGaugeFiniteRowsSPDPUnprojectedPreimage M n hn2 htb hns
        (routeBRicherConcreteNPPrependedMultilinearRows M n hn2 htb hns)) :
    RouteBPerInstanceCertificate M n hn2 htb hns :=
  routeBPerInstanceCertificate_of_prependedConcreteNP_rowClosurePackage_unprojectedPreimage_activeBlockersZeroNonScalarCover_deltaEqRateKappa
    (N := N) (d := d)
    M n hn hn2 htb hns hn4
    alpha beta alpha0 kappa gadgetN G chi Phi
    (routeBRicherMultilinearTailRows M n hn2 htb hns)
    hN hrowCount heta htheta halpha halpha0 hkappa hgadgetN
    hbound hactive
    (routeBRicherConcreteNPPrependedMultilinearRows_spdpRowClosurePackage
      M n hn2 htb hns)
    unprojectedPreimage

/-! ## Axiom audit anchors -/

#print axioms routeBRicherMultilinearTailRows_mem_span_of_mem_basis
#print axioms routeBRicherMultilinearTailRowCount_le_two_pow_dim
#print axioms routeBRicherConcreteNPPrependedMultilinearRows_rowCount_le_of_two_pow_dim
#print axioms routeBRicherMultilinearTailRows_mlProj_mem
#print axioms finiteRowsSubmodule_le_concreteNPPrependedRows_tail
#print axioms routeBRicherConcreteNPPrependedMultilinearRows_mlProj_mem
#print axioms routeBRicherConcreteNPPrependedMultilinearRows_spdpRowClosurePackage
#print axioms routeBRicherConcreteNPPrependedMultilinearRows_spdpClosure
#print axioms routeBRicherConcreteNPPrependedMultilinearRows_spdpMapPreimage_of_unprojectedPreimage
#print axioms routeBRicherConcreteNPPrependedMultilinearRows_spdpMapPreimage_iff_spdpSubspaceContainment
#print axioms routeBPerInstanceCertificate_of_prependedConcreteNP_multilinearTail_mapPreimage_activeBlockersZeroNonScalarCover_deltaEqRateKappa
#print axioms routeBPerInstanceCertificate_of_prependedConcreteNP_multilinearTail_mapPreimage_perTypeSpanning_zeroSupportCardSum_deltaEqRateKappa
#print axioms routeBPerInstanceCertificate_of_prependedConcreteNP_multilinearTail_spdpContainment_perTypeSpanning_zeroSupportCardSum_deltaEqRateKappa
#print axioms routeBPerInstanceCertificate_of_prependedConcreteNP_multilinearTail_unprojectedPreimage_endpointChargedBridge_deltaEqRateKappa
#print axioms routeBPerInstanceCertificate_of_prependedConcreteNP_multilinearTail_unprojectedPreimage_activeBlockersZeroNonScalarCover_deltaEqRateKappa

end PallLean.Paper93.Paper283
