import PallLean.Paper93.Paper283.RouteBRicherGaugeConcreteMapPreimage

/-!
# Smaller concrete-NP prepended SPDP-stable finite-row candidate

The broad concrete multilinear-tail gauge closes finite-row SPDP row closure by
including every multilinear monomial.  This module records the smaller Route B
candidate surface: keep the concrete Cook--Levin NP row as row `0`, and add only
a finite tail whose selected rows are closed under the SPDP generator-row
operators.  The remaining compatibility is the exact residual-invisibility
condition needed by the finite-row projection/complement argument.

No new axiom is introduced here.  The final mathematical obligations are named
as `RouteBRicherSPDPStableCandidateSelectedRowClosure` and
`RouteBRicherSPDPStableCandidateResidualInvisible`.
-/

namespace PallLean.Paper93.Paper283

open scoped BigOperators
open MultilinearSPDP
open PaperFaithfulCompilation
open PaperFaithfulSeparation
open TuringMachine
open PallLean.Paper93.DeepMath.BridgeB
open PallLean.Paper93.DeepMath.GadgetRank
open PallLean.Paper93.DeepMath.PathB

attribute [local instance] Classical.dec

/-- Candidate rows for the smaller SPDP-stable richer gauge: row `0` is the
concrete Cook--Levin NP witness, followed by a finite tail chosen to close the
selected SPDP generator rows. -/
noncomputable abbrev routeBRicherSPDPStableCandidateRows
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    Fin (m + 1) -> SATDeciderGaugeSpace M n hn2 htb hns :=
  routeBRicherConcreteNPPrependedRows M n hn2 htb hns tail

/-- The finite-row candidate gauge generated by the concrete NP witness and
the selected SPDP-stable tail. -/
noncomputable abbrev routeBRicherSPDPStableCandidateGauge
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    PallLean.Paper93.NFrame.CandidateGauge
      (RouteBCookLevinDim M n hn2 htb hns) :=
  routeBRicherFiniteRowsCandidateGauge M n hn2 htb hns
    (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail)

/-- SAT-side projection map associated to the smaller SPDP-stable finite-row
candidate. -/
noncomputable abbrev routeBRicherSPDPStableCandidateProjection
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    SATDeciderGaugeSpace M n hn2 htb hns →ₗ[Rat]
      SATDeciderGaugeSpace M n hn2 htb hns :=
  routeBNFrameCandidateAsSATGauge M n hn2 htb hns
    (routeBRicherSPDPStableCandidateGauge M n hn2 htb hns tail)

/-- The arbitrary complement selected by the finite-row projection for the
smaller SPDP-stable candidate.  The current residual obstruction is exactly
invariance of this complement under all admissible SPDP generator maps. -/
noncomputable abbrev routeBRicherSPDPStableCandidateProjectionComplement
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    Submodule Rat (SATDeciderGaugeSpace M n hn2 htb hns) :=
  finiteSubmoduleProjectionComplement
    (finiteRowsSubmodule
      (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail))

/-- Exact selected-row closure obligation for the smaller candidate.

This says precisely that SPDP generator rows of the concrete head row and of
each selected tail row land in the span of the prepended finite rows. -/
abbrev RouteBRicherSPDPStableCandidateSelectedRowClosure
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) : Prop :=
  RouteBRicherConcreteNPPrependedRowsSPDPRowClosurePackage
    M n hn2 htb hns tail

/-- Exact residual-invisibility obligation for the smaller candidate.

After decomposing `p` into its selected finite-row projection plus residual,
every SPDP generator row built from the residual must be killed by the selected
projection.  This is weaker than the multilinear-tail residual-zero condition:
only the projection of the residual generator is required to vanish. -/
def RouteBRicherSPDPStableCandidateResidualInvisible
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) : Prop :=
  forall (spdpKappa ell : Nat)
    (p : SATDeciderGaugeSpace M n hn2 htb hns)
    (S : List (Fin (RouteBCookLevinDim M n hn2 htb hns)))
    (shift : SATDeciderGaugeSpace M n hn2 htb hns),
    S.length = spdpKappa ->
    shift.totalDegree <= ell ->
    shift.vars <= S.toFinset ->
    SPDP.isBlockAdmissible
      (cook_levin_compilation M n hn2 htb hns).partition S ->
    routeBRicherSPDPStableCandidateProjection M n hn2 htb hns tail
      (routeBSPDPGeneratorRow M n hn2 htb hns
        (p - routeBRicherSPDPStableCandidateProjection
          M n hn2 htb hns tail p)
        S shift) = 0

/-- Kernel form of residual invisibility.

Every vector killed by the selected finite-row projection must have all of
its SPDP generator rows killed after applying that same projection. -/
def RouteBRicherSPDPStableCandidateKernelGeneratorInvisible
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) : Prop :=
  forall (spdpKappa ell : Nat)
    (p : SATDeciderGaugeSpace M n hn2 htb hns)
    (S : List (Fin (RouteBCookLevinDim M n hn2 htb hns)))
    (shift : SATDeciderGaugeSpace M n hn2 htb hns),
    S.length = spdpKappa ->
    shift.totalDegree <= ell ->
    shift.vars <= S.toFinset ->
    SPDP.isBlockAdmissible
      (cook_levin_compilation M n hn2 htb hns).partition S ->
    routeBRicherSPDPStableCandidateProjection M n hn2 htb hns tail p = 0 ->
    routeBRicherSPDPStableCandidateProjection M n hn2 htb hns tail
      (routeBSPDPGeneratorRow M n hn2 htb hns p S shift) = 0

/-- Stronger kernel form: every vector killed by the selected finite-row
projection has all SPDP generator rows equal to zero before projection. -/
def RouteBRicherSPDPStableCandidateKernelGeneratorZero
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) : Prop :=
  forall (spdpKappa ell : Nat)
    (p : SATDeciderGaugeSpace M n hn2 htb hns)
    (S : List (Fin (RouteBCookLevinDim M n hn2 htb hns)))
    (shift : SATDeciderGaugeSpace M n hn2 htb hns),
    S.length = spdpKappa ->
    shift.totalDegree <= ell ->
    shift.vars <= S.toFinset ->
    SPDP.isBlockAdmissible
      (cook_levin_compilation M n hn2 htb hns).partition S ->
    routeBRicherSPDPStableCandidateProjection M n hn2 htb hns tail p = 0 ->
    routeBSPDPGeneratorRow M n hn2 htb hns p S shift = 0

/-- Complement-invariance form of kernel invisibility.

The finite-row projection chooses an arbitrary complement to the selected row
span.  This predicate asks that the chosen complement itself be invariant under
each admissible Route B SPDP generator operator. -/
def RouteBRicherSPDPStableCandidateChosenComplementInvariant
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) : Prop :=
  forall (spdpKappa ell : Nat)
    (p : SATDeciderGaugeSpace M n hn2 htb hns)
    (S : List (Fin (RouteBCookLevinDim M n hn2 htb hns)))
    (shift : SATDeciderGaugeSpace M n hn2 htb hns),
    S.length = spdpKappa ->
    shift.totalDegree <= ell ->
    shift.vars <= S.toFinset ->
    SPDP.isBlockAdmissible
      (cook_levin_compilation M n hn2 htb hns).partition S ->
    p ∈ routeBRicherSPDPStableCandidateProjectionComplement
      M n hn2 htb hns tail ->
    routeBSPDPGeneratorRow M n hn2 htb hns p S shift ∈
      routeBRicherSPDPStableCandidateProjectionComplement
        M n hn2 htb hns tail

/-- Combined SPDP-stability obligations for the smaller concrete-NP prepended
candidate. -/
structure RouteBRicherSPDPStableCandidateObligations
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    Prop where
  selected_row_closure :
    RouteBRicherSPDPStableCandidateSelectedRowClosure
      M n hn2 htb hns tail
  residual_invisible :
    RouteBRicherSPDPStableCandidateResidualInvisible
      M n hn2 htb hns tail

/-- The smaller candidate still has the concrete NP source as row `0`. -/
theorem routeBRicherSPDPStableCandidateRows_zero_eq_embed
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail 0 =
      CoupledSheetPoly.embed (flatCookLevinUVSplit M n hn2 htb hns)
        (routeBRicherConcreteNPWitnessQ M n hn2 htb hns) :=
  routeBRicherConcreteNPPrependedRows_zero_eq_embed M n hn2 htb hns tail

/-- The smaller candidate fixes its concrete NP head row. -/
theorem routeBRicherSPDPStableCandidateGauge_fixes_concreteNPRow
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    (routeBRicherSPDPStableCandidateGauge M n hn2 htb hns tail).projection
        (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail 0) =
      routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail 0 := by
  exact
    routeBRicherFiniteRowsCandidateGauge_fixes_row M n hn2 htb hns
      (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail) 0

/-- The concrete NP extraction equality is retained by the smaller candidate. -/
theorem routeBRicherSPDPStableCandidate_extracts_compiled
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    routeBRicherSPDPStableCandidateProjection M n hn2 htb hns tail
        (compiledPoly (cook_levin_compilation M n hn2 htb hns)) =
      routeBRicherSPDPStableCandidateProjection M n hn2 htb hns tail
        (CoupledSheetPoly.embed
          (flatCookLevinUVSplit M n hn2 htb hns)
          (routeBRicherConcreteNPWitnessQ M n hn2 htb hns)) := by
  simpa [routeBRicherSPDPStableCandidateProjection,
    routeBRicherSPDPStableCandidateGauge,
    routeBRicherSPDPStableCandidateRows] using
    routeBRicherConcreteNP_extracts_compiled_for_rows
      M n hn2 htb hns
      (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail)

/-- Selected-row closure gives the standard finite-row row-closure field. -/
theorem routeBRicherSPDPStableCandidate_rowClosure
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (hclosure :
      RouteBRicherSPDPStableCandidateSelectedRowClosure
        M n hn2 htb hns tail) :
    RouteBRicherGaugeFiniteRowsSPDPRowClosure M n hn2 htb hns
      (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail) :=
  routeBRicherConcreteNPPrependedRows_spdpRowClosure_of_package
    M n hn2 htb hns tail hclosure

/-- Selected-row closure gives coefficient-level finite-row SPDP closure. -/
theorem routeBRicherSPDPStableCandidate_spdpClosure
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (hclosure :
      RouteBRicherSPDPStableCandidateSelectedRowClosure
        M n hn2 htb hns tail) :
    RouteBRicherGaugeFiniteRowsSPDPClosure M n hn2 htb hns
      (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail) :=
  routeBRicherConcreteNPPrependedRows_spdpClosure_of_rowClosurePackage
    M n hn2 htb hns tail hclosure

/-- Residual invisibility is equivalent to its projection-kernel form.

This restates the remaining SPDP containment obstruction without mentioning
the residual decomposition: it is enough, and necessary, to prove projected
SPDP-generator invisibility on the kernel of the selected-row projection. -/
theorem routeBRicherSPDPStableCandidate_residualInvisible_iff_kernelGeneratorInvisible
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    RouteBRicherSPDPStableCandidateResidualInvisible
        M n hn2 htb hns tail ↔
      RouteBRicherSPDPStableCandidateKernelGeneratorInvisible
        M n hn2 htb hns tail := by
  constructor
  · intro hinvisible spdpKappa ell p S shift hSlen hshiftDegree hshiftVars
      hadm hker
    have hrow :=
      hinvisible spdpKappa ell p S shift hSlen hshiftDegree hshiftVars hadm
    simpa [hker] using hrow
  · intro hkernel spdpKappa ell p S shift hSlen hshiftDegree hshiftVars hadm
    let Pi :=
      routeBRicherSPDPStableCandidateProjection M n hn2 htb hns tail
    have hPiPi : Pi (Pi p) = Pi p := by
      have hidem :=
        (routeBRicherSPDPStableCandidateGauge
          M n hn2 htb hns tail).is_idempotent
      have happ := congrArg (fun L => L p) hidem
      simpa [Pi, routeBRicherSPDPStableCandidateProjection,
        LinearMap.comp_apply] using happ
    have hresKer : Pi (p - Pi p) = 0 := by
      simp [Pi, map_sub, hPiPi]
    exact
      hkernel spdpKappa ell (p - Pi p) S shift
        hSlen hshiftDegree hshiftVars hadm hresKer

/-- The stronger zero-before-projection kernel condition is sufficient for
the projected kernel-invisibility condition. -/
theorem routeBRicherSPDPStableCandidate_kernelGeneratorInvisible_of_kernelGeneratorZero
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (hzero :
      RouteBRicherSPDPStableCandidateKernelGeneratorZero
        M n hn2 htb hns tail) :
    RouteBRicherSPDPStableCandidateKernelGeneratorInvisible
      M n hn2 htb hns tail := by
  intro spdpKappa ell p S shift hSlen hshiftDegree hshiftVars hadm hker
  have hrow :=
    hzero spdpKappa ell p S shift hSlen hshiftDegree hshiftVars hadm hker
  rw [hrow]
  simp

/-- The stronger zero-before-projection kernel condition is sufficient for
residual invisibility. -/
theorem routeBRicherSPDPStableCandidate_residualInvisible_of_kernelGeneratorZero
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (hzero :
      RouteBRicherSPDPStableCandidateKernelGeneratorZero
        M n hn2 htb hns tail) :
    RouteBRicherSPDPStableCandidateResidualInvisible
      M n hn2 htb hns tail :=
  (routeBRicherSPDPStableCandidate_residualInvisible_iff_kernelGeneratorInvisible
    M n hn2 htb hns tail).mpr
    (routeBRicherSPDPStableCandidate_kernelGeneratorInvisible_of_kernelGeneratorZero
      M n hn2 htb hns tail hzero)

/-- Invariance of the finite projection's chosen complement implies projected
kernel-generator invisibility. -/
theorem routeBRicherSPDPStableCandidate_kernelGeneratorInvisible_of_chosenComplementInvariant
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (hinvariant :
      RouteBRicherSPDPStableCandidateChosenComplementInvariant
        M n hn2 htb hns tail) :
    RouteBRicherSPDPStableCandidateKernelGeneratorInvisible
      M n hn2 htb hns tail := by
  intro spdpKappa ell p S shift hSlen hshiftDegree hshiftVars hadm hker
  let rows := routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail
  have hpComplement :
      p ∈ finiteSubmoduleProjectionComplement (finiteRowsSubmodule rows) := by
    have hkerRows :
        (routeBRicherFiniteRowsCandidateGauge M n hn2 htb hns rows).projection p = 0 := by
      simpa [routeBRicherSPDPStableCandidateProjection,
        routeBRicherSPDPStableCandidateGauge, rows]
        using hker
    exact
      (routeBRicherFiniteRowsCandidateGauge_projection_apply_eq_zero_iff
        M n hn2 htb hns rows p).mp hkerRows
  have hrowComplement :
      routeBSPDPGeneratorRow M n hn2 htb hns p S shift ∈
        finiteSubmoduleProjectionComplement (finiteRowsSubmodule rows) := by
    simpa [routeBRicherSPDPStableCandidateProjectionComplement, rows] using
      hinvariant spdpKappa ell p S shift
        hSlen hshiftDegree hshiftVars hadm hpComplement
  have hrowZero :
      (routeBRicherFiniteRowsCandidateGauge M n hn2 htb hns rows).projection
          (routeBSPDPGeneratorRow M n hn2 htb hns p S shift) = 0 :=
    (routeBRicherFiniteRowsCandidateGauge_projection_apply_eq_zero_iff
      M n hn2 htb hns rows
      (routeBSPDPGeneratorRow M n hn2 htb hns p S shift)).mpr hrowComplement
  simpa [routeBRicherSPDPStableCandidateProjection,
    routeBRicherSPDPStableCandidateGauge, rows]
    using hrowZero

/-- Invariance of the chosen complement is sufficient for residual
invisibility. -/
theorem routeBRicherSPDPStableCandidate_residualInvisible_of_chosenComplementInvariant
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (hinvariant :
      RouteBRicherSPDPStableCandidateChosenComplementInvariant
        M n hn2 htb hns tail) :
    RouteBRicherSPDPStableCandidateResidualInvisible
      M n hn2 htb hns tail :=
  (routeBRicherSPDPStableCandidate_residualInvisible_iff_kernelGeneratorInvisible
    M n hn2 htb hns tail).mpr
    (routeBRicherSPDPStableCandidate_kernelGeneratorInvisible_of_chosenComplementInvariant
      M n hn2 htb hns tail hinvariant)

/-- No-go criterion: a single projection-kernel vector whose SPDP generator
row remains visible after the selected-row projection refutes residual
invisibility. -/
theorem routeBRicherSPDPStableCandidate_residualInvisible_noGo_of_kernelGeneratorVisible
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (hbad :
      exists (spdpKappa ell : Nat)
        (p : SATDeciderGaugeSpace M n hn2 htb hns)
        (S : List (Fin (RouteBCookLevinDim M n hn2 htb hns)))
        (shift : SATDeciderGaugeSpace M n hn2 htb hns),
        S.length = spdpKappa ∧
          shift.totalDegree <= ell ∧
          shift.vars <= S.toFinset ∧
          SPDP.isBlockAdmissible
            (cook_levin_compilation M n hn2 htb hns).partition S ∧
          routeBRicherSPDPStableCandidateProjection
            M n hn2 htb hns tail p = 0 ∧
          routeBRicherSPDPStableCandidateProjection M n hn2 htb hns tail
            (routeBSPDPGeneratorRow M n hn2 htb hns p S shift) ≠ 0) :
    ¬ RouteBRicherSPDPStableCandidateResidualInvisible
        M n hn2 htb hns tail := by
  rintro hinvisible
  rcases hbad with
    ⟨spdpKappa, ell, p, S, shift, hSlen, hshiftDegree, hshiftVars,
      hadm, hker, hvisible⟩
  have hkernel :=
    (routeBRicherSPDPStableCandidate_residualInvisible_iff_kernelGeneratorInvisible
      M n hn2 htb hns tail).mp hinvisible
  exact hvisible
    (hkernel spdpKappa ell p S shift
      hSlen hshiftDegree hshiftVars hadm hker)

/-- Residual invisibility is exactly the kernel/complement compatibility
expected by the existing finite-row commutation bridge. -/
theorem routeBRicherSPDPStableCandidate_kernelCompatibility_of_residualInvisible
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (hinvisible :
      RouteBRicherSPDPStableCandidateResidualInvisible
        M n hn2 htb hns tail) :
    RouteBRicherGaugeFiniteRowsSPDPKernelCompatibility M n hn2 htb hns
      (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail) := by
  intro spdpKappa ell p S shift hSlen hshiftDegree hshiftVars hadm
  exact
    hinvisible spdpKappa ell p S shift
      hSlen hshiftDegree hshiftVars hadm

/-- The finite-row kernel/complement compatibility bridge is also sufficient
for the smaller-candidate residual-invisibility obligation. -/
theorem routeBRicherSPDPStableCandidate_residualInvisible_of_kernelCompatibility
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (hker :
      RouteBRicherGaugeFiniteRowsSPDPKernelCompatibility M n hn2 htb hns
        (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail)) :
    RouteBRicherSPDPStableCandidateResidualInvisible
      M n hn2 htb hns tail := by
  intro spdpKappa ell p S shift hSlen hshiftDegree hshiftVars hadm
  exact
    hker spdpKappa ell p S shift
      hSlen hshiftDegree hshiftVars hadm

/-- Exact bridge form of the residual obstruction: the smaller candidate's
residual-invisibility obligation is precisely finite-row SPDP kernel
compatibility for its prepended head/tail rows. -/
theorem routeBRicherSPDPStableCandidate_residualInvisible_iff_kernelCompatibility
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    RouteBRicherSPDPStableCandidateResidualInvisible
        M n hn2 htb hns tail ↔
      RouteBRicherGaugeFiniteRowsSPDPKernelCompatibility M n hn2 htb hns
        (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail) := by
  constructor
  · exact
      routeBRicherSPDPStableCandidate_kernelCompatibility_of_residualInvisible
        M n hn2 htb hns tail
  · exact
      routeBRicherSPDPStableCandidate_residualInvisible_of_kernelCompatibility
        M n hn2 htb hns tail

/-- The two named obligations prove generator commutation for the smaller
finite-row candidate. -/
theorem routeBRicherSPDPStableCandidate_generatorCommutation
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (obligations :
      RouteBRicherSPDPStableCandidateObligations
        M n hn2 htb hns tail) :
    RouteBRicherGaugeGeneratorCommutation M n hn2 htb hns
      (routeBRicherSPDPStableCandidateGauge M n hn2 htb hns tail) := by
  simpa [routeBRicherSPDPStableCandidateGauge,
    routeBRicherSPDPStableCandidateRows] using
    routeBRicherGaugeGeneratorCommutation_of_spdpClosure_kernelCompatibility
      M n hn2 htb hns
      (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail)
      (routeBRicherSPDPStableCandidate_spdpClosure
        M n hn2 htb hns tail obligations.selected_row_closure)
      (routeBRicherSPDPStableCandidate_kernelCompatibility_of_residualInvisible
        M n hn2 htb hns tail obligations.residual_invisible)

/-- The two named obligations prove the finite-row SPDP map-preimage field. -/
theorem routeBRicherSPDPStableCandidate_spdpMapPreimage
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (obligations :
      RouteBRicherSPDPStableCandidateObligations
        M n hn2 htb hns tail) :
    RouteBRicherGaugeFiniteRowsSPDPMapPreimage M n hn2 htb hns
      (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail) := by
  exact
    routeBRicherConcreteNPPrependedRows_spdpMapPreimage_of_spdpClosure_kernelCompatibility
      M n hn2 htb hns tail
      (routeBRicherSPDPStableCandidate_spdpClosure
        M n hn2 htb hns tail obligations.selected_row_closure)
      (routeBRicherSPDPStableCandidate_kernelCompatibility_of_residualInvisible
        M n hn2 htb hns tail obligations.residual_invisible)

/-- The two named obligations prove Route B SPDP subspace containment for the
smaller finite-row candidate. -/
theorem routeBRicherSPDPStableCandidate_spdpSubspaceContainment
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (obligations :
      RouteBRicherSPDPStableCandidateObligations
        M n hn2 htb hns tail) :
    RouteBRicherGaugeSPDPSubspaceContainment M n hn2 htb hns
      (routeBRicherSPDPStableCandidateGauge M n hn2 htb hns tail) := by
  simpa [routeBRicherSPDPStableCandidateGauge,
    routeBRicherSPDPStableCandidateRows] using
    routeBRicherFiniteRowsCandidateGauge_spdpSubspaceContainment_of_mapPreimage
      M n hn2 htb hns
      (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail)
      (routeBRicherSPDPStableCandidate_spdpMapPreimage
        M n hn2 htb hns tail obligations)

/-- The empty-tail one-row candidate cannot be selected-row SPDP closed.  Any
candidate satisfying the named closure obligation must add at least one richer
tail row beyond the concrete NP head. -/
theorem routeBRicherSPDPStableCandidate_tail_nonempty_of_selectedRowClosure
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (hclosure :
      RouteBRicherSPDPStableCandidateSelectedRowClosure
        M n hn2 htb hns tail) :
    0 < m :=
  routeBRicherConcreteNPPrependedRows_tail_nonempty_of_spdpRowClosurePackage
    M n hn2 htb hns tail hclosure

/-- Concrete Route B certificate wrapper for the smaller candidate, using the
checked map-preimage SPDP route and the concreteW row-embedding P-side route.

The remaining non-P-side obligations are exactly
`selected_row_closure` and `residual_invisible`. -/
theorem routeBPerInstanceCertificate_of_spdpStableCandidate_rowEmbeddings_deltaEqRateKappa
    {N d : Nat}
    (M : DTM) (n : Nat) (hn : n >= 2 ^ 804) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (hn4 : n >= 4)
    (alpha beta alpha0 : Real) (kappa gadgetN : Nat)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N) (Phi : Fin N -> Real)
    {eta theta : Real}
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (hN : 1 <= N) (hrowCount : m + 1 <= N)
    (heta : 0 < eta) (htheta : 0 < theta)
    (halpha : 0 < alpha) (halpha0 : 0 < alpha0)
    (hkappa : 0 < kappa) (hgadgetN : 2 <= gadgetN)
    (obligations :
      RouteBRicherSPDPStableCandidateObligations
        M n hn2 htb hns tail)
    (hRowEmbeddings :
      PallLean.Paper93.Direct.CookLevinPerTypeRowEmbeddings_concreteW
        M n hn2 htb hns hn4) :
    RouteBPerInstanceCertificate M n hn2 htb hns :=
  routeBPerInstanceCertificate_of_prependedConcreteNP_finiteRowsSPDPMapPreimage_rowEmbeddings_deltaEqRateKappa
    (N := N) (d := d)
    M n hn hn2 htb hns hn4
    alpha beta alpha0 kappa gadgetN G chi Phi
    tail hN hrowCount heta htheta halpha halpha0 hkappa hgadgetN
    (routeBRicherSPDPStableCandidate_spdpMapPreimage
      M n hn2 htb hns tail obligations)
    hRowEmbeddings

/-! ## Axiom audit anchors -/

#print axioms RouteBRicherSPDPStableCandidateResidualInvisible
#print axioms RouteBRicherSPDPStableCandidateKernelGeneratorInvisible
#print axioms RouteBRicherSPDPStableCandidateKernelGeneratorZero
#print axioms RouteBRicherSPDPStableCandidateChosenComplementInvariant
#print axioms RouteBRicherSPDPStableCandidateObligations
#print axioms routeBRicherSPDPStableCandidateProjectionComplement
#print axioms routeBRicherSPDPStableCandidateRows_zero_eq_embed
#print axioms routeBRicherSPDPStableCandidateGauge_fixes_concreteNPRow
#print axioms routeBRicherSPDPStableCandidate_extracts_compiled
#print axioms routeBRicherSPDPStableCandidate_rowClosure
#print axioms routeBRicherSPDPStableCandidate_spdpClosure
#print axioms routeBRicherSPDPStableCandidate_residualInvisible_iff_kernelGeneratorInvisible
#print axioms routeBRicherSPDPStableCandidate_kernelGeneratorInvisible_of_kernelGeneratorZero
#print axioms routeBRicherSPDPStableCandidate_residualInvisible_of_kernelGeneratorZero
#print axioms routeBRicherSPDPStableCandidate_kernelGeneratorInvisible_of_chosenComplementInvariant
#print axioms routeBRicherSPDPStableCandidate_residualInvisible_of_chosenComplementInvariant
#print axioms routeBRicherSPDPStableCandidate_residualInvisible_noGo_of_kernelGeneratorVisible
#print axioms routeBRicherSPDPStableCandidate_kernelCompatibility_of_residualInvisible
#print axioms routeBRicherSPDPStableCandidate_residualInvisible_of_kernelCompatibility
#print axioms routeBRicherSPDPStableCandidate_residualInvisible_iff_kernelCompatibility
#print axioms routeBRicherSPDPStableCandidate_generatorCommutation
#print axioms routeBRicherSPDPStableCandidate_spdpMapPreimage
#print axioms routeBRicherSPDPStableCandidate_spdpSubspaceContainment
#print axioms routeBRicherSPDPStableCandidate_tail_nonempty_of_selectedRowClosure
#print axioms routeBPerInstanceCertificate_of_spdpStableCandidate_rowEmbeddings_deltaEqRateKappa

end PallLean.Paper93.Paper283
