import PallLean.Paper93.Paper283.RouteBRicherGaugeConcreteMapPreimage

/-!
# Smaller concrete-NP prepended SPDP-stable finite-row candidate

The broad concrete multilinear-tail gauge closes finite-row SPDP row closure by
including every multilinear monomial.  This module records the smaller Route B
candidate surface: keep the concrete Cook--Levin NP row as row `0`, and add only
a finite tail whose selected rows are closed under the SPDP generator-row
operators.  The remaining compatibility is the exact residual-invisibility
condition needed by the finite-row projection/complement argument.

No new axiom is introduced here.  The final mathematical obligations are named
as `RouteBRicherSPDPStableCandidateSelectedRowClosure` and
`RouteBRicherSPDPStableCandidateResidualInvisible`.
-/

namespace PallLean.Paper93.Paper283

open scoped BigOperators
open MultilinearSPDP
open PaperFaithfulCompilation
open PaperFaithfulSeparation
open TuringMachine
open PallLean.Paper93.DeepMath.BridgeB
open PallLean.Paper93.DeepMath.GadgetRank
open PallLean.Paper93.DeepMath.PathB

attribute [local instance] Classical.dec

/-- Candidate rows for the smaller SPDP-stable richer gauge: row `0` is the
concrete Cook--Levin NP witness, followed by a finite tail chosen to close the
selected SPDP generator rows. -/
noncomputable abbrev routeBRicherSPDPStableCandidateRows
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    Fin (m + 1) -> SATDeciderGaugeSpace M n hn2 htb hns :=
  routeBRicherConcreteNPPrependedRows M n hn2 htb hns tail

/-- The finite-row candidate gauge generated by the concrete NP witness and
the selected SPDP-stable tail. -/
noncomputable abbrev routeBRicherSPDPStableCandidateGauge
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    PallLean.Paper93.NFrame.CandidateGauge
      (RouteBCookLevinDim M n hn2 htb hns) :=
  routeBRicherFiniteRowsCandidateGauge M n hn2 htb hns
    (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail)

/-- SAT-side projection map associated to the smaller SPDP-stable finite-row
candidate. -/
noncomputable abbrev routeBRicherSPDPStableCandidateProjection
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    SATDeciderGaugeSpace M n hn2 htb hns →ₗ[Rat]
      SATDeciderGaugeSpace M n hn2 htb hns :=
  routeBNFrameCandidateAsSATGauge M n hn2 htb hns
    (routeBRicherSPDPStableCandidateGauge M n hn2 htb hns tail)

/-- Exact selected-row closure obligation for the smaller candidate.

This says precisely that SPDP generator rows of the concrete head row and of
each selected tail row land in the span of the prepended finite rows. -/
abbrev RouteBRicherSPDPStableCandidateSelectedRowClosure
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) : Prop :=
  RouteBRicherConcreteNPPrependedRowsSPDPRowClosurePackage
    M n hn2 htb hns tail

/-- Exact residual-invisibility obligation for the smaller candidate.

After decomposing `p` into its selected finite-row projection plus residual,
every SPDP generator row built from the residual must be killed by the selected
projection.  This is weaker than the multilinear-tail residual-zero condition:
only the projection of the residual generator is required to vanish. -/
def RouteBRicherSPDPStableCandidateResidualInvisible
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) : Prop :=
  forall (spdpKappa ell : Nat)
    (p : SATDeciderGaugeSpace M n hn2 htb hns)
    (S : List (Fin (RouteBCookLevinDim M n hn2 htb hns)))
    (shift : SATDeciderGaugeSpace M n hn2 htb hns),
    S.length = spdpKappa ->
    shift.totalDegree <= ell ->
    shift.vars <= S.toFinset ->
    SPDP.isBlockAdmissible
      (cook_levin_compilation M n hn2 htb hns).partition S ->
    routeBRicherSPDPStableCandidateProjection M n hn2 htb hns tail
      (routeBSPDPGeneratorRow M n hn2 htb hns
        (p - routeBRicherSPDPStableCandidateProjection
          M n hn2 htb hns tail p)
        S shift) = 0

/-- Combined SPDP-stability obligations for the smaller concrete-NP prepended
candidate. -/
structure RouteBRicherSPDPStableCandidateObligations
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    Prop where
  selected_row_closure :
    RouteBRicherSPDPStableCandidateSelectedRowClosure
      M n hn2 htb hns tail
  residual_invisible :
    RouteBRicherSPDPStableCandidateResidualInvisible
      M n hn2 htb hns tail

/-- The smaller candidate still has the concrete NP source as row `0`. -/
theorem routeBRicherSPDPStableCandidateRows_zero_eq_embed
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail 0 =
      CoupledSheetPoly.embed (flatCookLevinUVSplit M n hn2 htb hns)
        (routeBRicherConcreteNPWitnessQ M n hn2 htb hns) :=
  routeBRicherConcreteNPPrependedRows_zero_eq_embed M n hn2 htb hns tail

/-- The smaller candidate fixes its concrete NP head row. -/
theorem routeBRicherSPDPStableCandidateGauge_fixes_concreteNPRow
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    (routeBRicherSPDPStableCandidateGauge M n hn2 htb hns tail).projection
        (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail 0) =
      routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail 0 := by
  exact
    routeBRicherFiniteRowsCandidateGauge_fixes_row M n hn2 htb hns
      (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail) 0

/-- The concrete NP extraction equality is retained by the smaller candidate. -/
theorem routeBRicherSPDPStableCandidate_extracts_compiled
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    routeBRicherSPDPStableCandidateProjection M n hn2 htb hns tail
        (compiledPoly (cook_levin_compilation M n hn2 htb hns)) =
      routeBRicherSPDPStableCandidateProjection M n hn2 htb hns tail
        (CoupledSheetPoly.embed
          (flatCookLevinUVSplit M n hn2 htb hns)
          (routeBRicherConcreteNPWitnessQ M n hn2 htb hns)) := by
  simpa [routeBRicherSPDPStableCandidateProjection,
    routeBRicherSPDPStableCandidateGauge,
    routeBRicherSPDPStableCandidateRows] using
    routeBRicherConcreteNP_extracts_compiled_for_rows
      M n hn2 htb hns
      (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail)

/-- Selected-row closure gives the standard finite-row row-closure field. -/
theorem routeBRicherSPDPStableCandidate_rowClosure
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (hclosure :
      RouteBRicherSPDPStableCandidateSelectedRowClosure
        M n hn2 htb hns tail) :
    RouteBRicherGaugeFiniteRowsSPDPRowClosure M n hn2 htb hns
      (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail) :=
  routeBRicherConcreteNPPrependedRows_spdpRowClosure_of_package
    M n hn2 htb hns tail hclosure

/-- Selected-row closure gives coefficient-level finite-row SPDP closure. -/
theorem routeBRicherSPDPStableCandidate_spdpClosure
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (hclosure :
      RouteBRicherSPDPStableCandidateSelectedRowClosure
        M n hn2 htb hns tail) :
    RouteBRicherGaugeFiniteRowsSPDPClosure M n hn2 htb hns
      (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail) :=
  routeBRicherConcreteNPPrependedRows_spdpClosure_of_rowClosurePackage
    M n hn2 htb hns tail hclosure

/-- Residual invisibility is exactly the kernel/complement compatibility
expected by the existing finite-row commutation bridge. -/
theorem routeBRicherSPDPStableCandidate_kernelCompatibility_of_residualInvisible
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (hinvisible :
      RouteBRicherSPDPStableCandidateResidualInvisible
        M n hn2 htb hns tail) :
    RouteBRicherGaugeFiniteRowsSPDPKernelCompatibility M n hn2 htb hns
      (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail) := by
  intro spdpKappa ell p S shift hSlen hshiftDegree hshiftVars hadm
  exact
    hinvisible spdpKappa ell p S shift
      hSlen hshiftDegree hshiftVars hadm

/-- The two named obligations prove generator commutation for the smaller
finite-row candidate. -/
theorem routeBRicherSPDPStableCandidate_generatorCommutation
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (obligations :
      RouteBRicherSPDPStableCandidateObligations
        M n hn2 htb hns tail) :
    RouteBRicherGaugeGeneratorCommutation M n hn2 htb hns
      (routeBRicherSPDPStableCandidateGauge M n hn2 htb hns tail) := by
  simpa [routeBRicherSPDPStableCandidateGauge,
    routeBRicherSPDPStableCandidateRows] using
    routeBRicherGaugeGeneratorCommutation_of_spdpClosure_kernelCompatibility
      M n hn2 htb hns
      (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail)
      (routeBRicherSPDPStableCandidate_spdpClosure
        M n hn2 htb hns tail obligations.selected_row_closure)
      (routeBRicherSPDPStableCandidate_kernelCompatibility_of_residualInvisible
        M n hn2 htb hns tail obligations.residual_invisible)

/-- The two named obligations prove the finite-row SPDP map-preimage field. -/
theorem routeBRicherSPDPStableCandidate_spdpMapPreimage
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (obligations :
      RouteBRicherSPDPStableCandidateObligations
        M n hn2 htb hns tail) :
    RouteBRicherGaugeFiniteRowsSPDPMapPreimage M n hn2 htb hns
      (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail) := by
  exact
    routeBRicherConcreteNPPrependedRows_spdpMapPreimage_of_spdpClosure_kernelCompatibility
      M n hn2 htb hns tail
      (routeBRicherSPDPStableCandidate_spdpClosure
        M n hn2 htb hns tail obligations.selected_row_closure)
      (routeBRicherSPDPStableCandidate_kernelCompatibility_of_residualInvisible
        M n hn2 htb hns tail obligations.residual_invisible)

/-- The two named obligations prove Route B SPDP subspace containment for the
smaller finite-row candidate. -/
theorem routeBRicherSPDPStableCandidate_spdpSubspaceContainment
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (obligations :
      RouteBRicherSPDPStableCandidateObligations
        M n hn2 htb hns tail) :
    RouteBRicherGaugeSPDPSubspaceContainment M n hn2 htb hns
      (routeBRicherSPDPStableCandidateGauge M n hn2 htb hns tail) := by
  simpa [routeBRicherSPDPStableCandidateGauge,
    routeBRicherSPDPStableCandidateRows] using
    routeBRicherFiniteRowsCandidateGauge_spdpSubspaceContainment_of_mapPreimage
      M n hn2 htb hns
      (routeBRicherSPDPStableCandidateRows M n hn2 htb hns tail)
      (routeBRicherSPDPStableCandidate_spdpMapPreimage
        M n hn2 htb hns tail obligations)

/-- The empty-tail one-row candidate cannot be selected-row SPDP closed.  Any
candidate satisfying the named closure obligation must add at least one richer
tail row beyond the concrete NP head. -/
theorem routeBRicherSPDPStableCandidate_tail_nonempty_of_selectedRowClosure
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (hclosure :
      RouteBRicherSPDPStableCandidateSelectedRowClosure
        M n hn2 htb hns tail) :
    0 < m :=
  routeBRicherConcreteNPPrependedRows_tail_nonempty_of_spdpRowClosurePackage
    M n hn2 htb hns tail hclosure

/-- Concrete Route B certificate wrapper for the smaller candidate, using the
checked map-preimage SPDP route and the concreteW row-embedding P-side route.

The remaining non-P-side obligations are exactly
`selected_row_closure` and `residual_invisible`. -/
theorem routeBPerInstanceCertificate_of_spdpStableCandidate_rowEmbeddings_deltaEqRateKappa
    {N d : Nat}
    (M : DTM) (n : Nat) (hn : n >= 2 ^ 804) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (hn4 : n >= 4)
    (alpha beta alpha0 : Real) (kappa gadgetN : Nat)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N) (Phi : Fin N -> Real)
    {eta theta : Real}
    {m : Nat}
    (tail : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (hN : 1 <= N) (hrowCount : m + 1 <= N)
    (heta : 0 < eta) (htheta : 0 < theta)
    (halpha : 0 < alpha) (halpha0 : 0 < alpha0)
    (hkappa : 0 < kappa) (hgadgetN : 2 <= gadgetN)
    (obligations :
      RouteBRicherSPDPStableCandidateObligations
        M n hn2 htb hns tail)
    (hRowEmbeddings :
      PallLean.Paper93.Direct.CookLevinPerTypeRowEmbeddings_concreteW
        M n hn2 htb hns hn4) :
    RouteBPerInstanceCertificate M n hn2 htb hns :=
  routeBPerInstanceCertificate_of_prependedConcreteNP_finiteRowsSPDPMapPreimage_rowEmbeddings_deltaEqRateKappa
    (N := N) (d := d)
    M n hn hn2 htb hns hn4
    alpha beta alpha0 kappa gadgetN G chi Phi
    tail hN hrowCount heta htheta halpha halpha0 hkappa hgadgetN
    (routeBRicherSPDPStableCandidate_spdpMapPreimage
      M n hn2 htb hns tail obligations)
    hRowEmbeddings

/-! ## Axiom audit anchors -/

#print axioms RouteBRicherSPDPStableCandidateResidualInvisible
#print axioms RouteBRicherSPDPStableCandidateObligations
#print axioms routeBRicherSPDPStableCandidateRows_zero_eq_embed
#print axioms routeBRicherSPDPStableCandidateGauge_fixes_concreteNPRow
#print axioms routeBRicherSPDPStableCandidate_extracts_compiled
#print axioms routeBRicherSPDPStableCandidate_rowClosure
#print axioms routeBRicherSPDPStableCandidate_spdpClosure
#print axioms routeBRicherSPDPStableCandidate_kernelCompatibility_of_residualInvisible
#print axioms routeBRicherSPDPStableCandidate_generatorCommutation
#print axioms routeBRicherSPDPStableCandidate_spdpMapPreimage
#print axioms routeBRicherSPDPStableCandidate_spdpSubspaceContainment
#print axioms routeBRicherSPDPStableCandidate_tail_nonempty_of_selectedRowClosure
#print axioms routeBPerInstanceCertificate_of_spdpStableCandidate_rowEmbeddings_deltaEqRateKappa

end PallLean.Paper93.Paper283
