import PallLean.Paper93.Paper283.RouteBRicherGaugeReducedCertificate
import PallLean.SymTensorPowerDim

/-!
# Rank budget for finite-row Route B gauges

The finite-span Route B candidate projects onto the span of a finite row
family.  This file records the useful automatic rank bound: the projection
rank is at most the number of selected rows.
-/

namespace PallLean.Paper93.Paper283

open scoped BigOperators
open MultilinearSPDP
open PaperFaithfulCompilation
open PaperFaithfulSeparation
open TuringMachine
open PallLean.Paper93.DeepMath.PathB

/-- The row span generated by `m` rows has finrank at most `m`. -/
theorem finiteRowsSubmodule_finrank_le_card {N m : Nat}
    (rows : Fin m -> MvPolynomial (Fin N) Rat) :
    Module.finrank Rat (finiteRowsSubmodule rows) <= m := by
  simpa [finiteRowsSubmodule, Fintype.card_fin] using
    (PallLean.SymTensorPowerDim.finrank_span_range_le
      (R := Rat) (M := MvPolynomial (Fin N) Rat) rows)

/-- The projection rank of the Route B finite-row candidate is bounded by the
number of selected witness rows. -/
theorem routeBRicherFiniteRowsCandidateGauge_projectionRank_le_rowCount
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    {m : Nat}
    (rows : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns) :
    PallLean.Paper93.Concrete.projectionRank
        (routeBRicherFiniteRowsCandidateGauge M n hn2 htb hns rows) <=
      (m : Real) := by
  rw [routeBRicherFiniteRowsCandidateGauge_projectionRank_eq_spanFinrank]
  exact_mod_cast finiteRowsSubmodule_finrank_le_card rows

/-- Rank compatibility for finite-row candidates from the simpler row-count
budget `m <= rankA`. -/
theorem routeBRicherFiniteRowsCandidateGauge_rankCompatible_of_rowCount_le
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (rankA : Nat)
    {m : Nat}
    (rows : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (hrowRank : m <= rankA) :
    RouteBProjectionRankCompatible M n hn2 htb hns rankA
      (routeBRicherFiniteRowsCandidateGauge M n hn2 htb hns rows) := by
  exact
    (routeBRicherFiniteRowsCandidateGauge_projectionRank_le_rowCount
      M n hn2 htb hns rows).trans (by exact_mod_cast hrowRank)

/-- Version of the finite-row/eigenvalue-floor reduced certificate constructor
using the concrete row-count rank budget `m <= A.rank`. -/
theorem routeBReducedCertificate_of_richerFiniteRows_eigenvalueFloor_rowCount
    {N d : Nat}
    (M : DTM) (n : Nat) (hn2 : n >= 2)
    (htb : M.timeBound <= 4) (hns : M.numStates <= n)
    (alpha beta alpha0 : Real) (kappa gadgetN : Nat)
    (G : PallLean.Paper93.Concrete.RegularGraphFixed N d)
    (chi : TseitinCharge N) (Phi : Fin N -> Real)
    {theta delta rankLogRate lambdaFloor : Real}
    (A : Matrix (Fin N) (Fin N) Real) (hA : A.PosSemidef)
    (S : Finset (Fin N))
    {m : Nat}
    (rows : Fin m -> SATDeciderGaugeSpace M n hn2 htb hns)
    (htheta : 0 < theta)
    (halpha : 0 < alpha) (halpha0 : 0 < alpha0)
    (hgadgetN : 2 <= gadgetN)
    (hrate_nonneg : 0 <= rankLogRate)
    (hdelta_rate : delta <= rankLogRate * (kappa : Real))
    (hlambdaFloor_nonneg : 0 <= lambdaFloor)
    (hfloor : forall i, i ∈ S -> lambdaFloor <= hA.1.eigenvalues i)
    (hbudget :
      rankLogRate *
          ((∑ v ∈ activeSet (N := N) (d := d) alpha beta alpha0 G chi Phi,
            (cookLevinPocketLocalGadgetFamily N alpha kappa gadgetN v).rank) :
            Real) <=
        (S.card : Real) * Real.log (1 + theta * lambdaFloor))
    (hrowRank : m <= A.rank)
    (hcontain :
      RouteBRicherGaugeSPDPSubspaceContainment M n hn2 htb hns
        (routeBRicherFiniteRowsCandidateGauge M n hn2 htb hns rows))
    (cover :
      RouteBRicherGaugeUnprojectedPWindowFiniteSpanCover M n hn2 htb hns)
    (Q : CoupledSheetPoly (flatCookLevinUVSplit M n hn2 htb hns))
    (i : Fin m)
    (hrow :
      rows i =
        CoupledSheetPoly.embed (flatCookLevinUVSplit M n hn2 htb hns) Q)
    (hextract :
      routeBNFrameCandidateAsSATGauge M n hn2 htb hns
          (routeBRicherFiniteRowsCandidateGauge M n hn2 htb hns rows)
          (compiledPoly (cook_levin_compilation M n hn2 htb hns)) =
        routeBNFrameCandidateAsSATGauge M n hn2 htb hns
          (routeBRicherFiniteRowsCandidateGauge M n hn2 htb hns rows)
          (CoupledSheetPoly.embed
            (flatCookLevinUVSplit M n hn2 htb hns) Q))
    (hsource :
      SourceIdentityMinorLowerBound n
        (flatCookLevinUVSplit M n hn2 htb hns)
        (cook_levin_compilation M n hn2 htb hns).partition
        (Nat.log 2 n) (Nat.log 2 n) Q) :
    RouteBReducedCertificate M n hn2 htb hns :=
  routeBReducedCertificate_of_richerFiniteRows_eigenvalueFloor
    M n hn2 htb hns alpha beta alpha0 kappa gadgetN G chi Phi A hA S rows
    htheta halpha halpha0 hgadgetN hrate_nonneg hdelta_rate
    hlambdaFloor_nonneg hfloor hbudget
    (by exact_mod_cast
      le_trans (finiteRowsSubmodule_finrank_le_card rows) hrowRank)
    hcontain cover Q i hrow hextract hsource

/-! ## Axiom audit anchors -/

#print axioms finiteRowsSubmodule_finrank_le_card
#print axioms routeBRicherFiniteRowsCandidateGauge_projectionRank_le_rowCount
#print axioms routeBRicherFiniteRowsCandidateGauge_rankCompatible_of_rowCount_le
#print axioms routeBReducedCertificate_of_richerFiniteRows_eigenvalueFloor_rowCount

end PallLean.Paper93.Paper283
