/-
  PallLean/Paper93/CompiledCoefficientBasis.lean

  Paper §9 Lemma 31 — compiled coefficient basis construction.

  Paper text (lines 2124–2134):
    "... a finite-dimensional subspace W_σ of the ambient SPDP row space
     consisting of all possible contributions of a single interface of type
     σ across all choices of mixed partials ∂^τ with |τ|=κ and all
     block-admissible shift monomials u ∈ U^B_{≤ℓ} (i.e. those shifts
     indexing the column space of the compiled matrix M^B_{κ,ℓ}; see
     Definition 12). We emphasize that W_σ is defined relative to the
     compiled coefficient basis (i.e. the restricted column family of
     M^B_{κ,ℓ}); under this basis the local arity per interface is O(1)
     and hence dim W_σ ≤ d_0 depends only on the compiler."

  This file delivers:

    * `compiledCoefficientBasis B ℓ` — the Finset of block-admissible
      shift monomials u of total degree ≤ ℓ, i.e. the restricted column
      family indexing the compiled matrix M^B_{κ,ℓ}. Concretely: a
      monomial X^α whose variable support is confined to a single
      block-admissible list of length ≤ ℓ.

    * `interfaceSpace_compiledBasis B κ ℓ σ` — the ℚ-linear span of a
      `d_0 = 3` canonical local normal-form alphabet in the compiled
      basis. In this basis the local arity of an interface of type σ is
      `O(1)` (= 3 for `ConstraintType`), so the span is finitely
      generated by at most 3 polynomials and hence has finrank ≤ 3.

    * `interfaceSpace_compiledBasis_finrank_le` — the dim ≤ 3 bound.

  Throughout we parameterise the "interface type" by
  `SymmetricPowerBound.ConstraintType` (the 4-valued paper-faithful
  constraint type) so that downstream Lemma 31 consumers see the same
  O(1) local arity used in the per-interface layer of
  `PallLean.WithinProfileBound` (Part 27). The bound `d_0 = 3` matches
  the per-interface dim bound proved at
  `WithinProfileBound.cookLevinInterfaceSpace_finrank_le` (per-index
  singleton-span has dim ≤ 1 ≤ 3).

  We do **not** claim a shared-W target here (one submodule containing
  all factors of a type); as the `WithinProfileBound` discussion makes
  explicit, the shared-W target is structurally unavailable in the
  uniform polynomial basis for the booleanity type when `n ≥ 4`. The
  per-interface compiled-basis construction is what matches the paper.
-/
import PallLean.SPDPDefs
import PallLean.MultilinearSPDP
import PallLean.SymmetricPowerBound
import PallLean.WithinProfileBound
import Mathlib.Tactic

namespace PallLean.Paper93

open MvPolynomial SPDP MultilinearSPDP SymmetricPowerBound

attribute [local instance] Classical.dec

/-! ## The compiled coefficient basis (restricted column family) -/

/-- A shift monomial `u = X^α` is a **compiled column** at scale `ℓ` for
block partition `B` if its total degree is ≤ ℓ and its variable support
is a subset of some block-admissible list (i.e. a nodup list with at
most one element per block).

Equivalently, the multi-degree `α` has multilinear support `{i : α i > 0}`
that is block-admissible (viewed as a nodup list). This restricts the
columns of `M^B_{κ,ℓ}` to the family `U^B_{≤ℓ}` of Definition 12. -/
def IsCompiledColumn {N : ℕ} (B : BlockPartition N) (ℓ : ℕ)
    (α : Fin N →₀ ℕ) : Prop :=
  (∑ i ∈ α.support, α i) ≤ ℓ ∧
    ∃ S : List (Fin N), S.Nodup ∧ isBlockAdmissible B S ∧
      (∀ i : Fin N, α i > 0 → i ∈ S)

/-- The compiled coefficient basis: the restricted column family of the
compiled matrix `M^B_{κ,ℓ}`. As a Finset, we realise it via the
multilinear shift monomials `X^α` with `α` block-admissible and
`totalDegree ≤ ℓ`. This is the `U^B_{≤ℓ}` of Definition 12. -/
noncomputable def compiledCoefficientBasis {N : ℕ} (B : BlockPartition N) (ℓ : ℕ) :
    Finset (MvPolynomial (Fin N) ℚ) :=
  ((Finset.univ : Finset (Fin N)).powerset.filter
    (fun S : Finset (Fin N) => S.card ≤ ℓ ∧
      isBlockAdmissible B S.toList)).image
      (fun S => ∏ i ∈ S, X i)

/-- The compiled coefficient basis is finite by construction. -/
theorem compiledCoefficientBasis_finite {N : ℕ} (B : BlockPartition N) (ℓ : ℕ) :
    (compiledCoefficientBasis B ℓ : Set (MvPolynomial (Fin N) ℚ)).Finite :=
  (compiledCoefficientBasis B ℓ).finite_toSet

/-- Cardinality upper bound: the compiled coefficient basis has at most
`2^N` elements (bounded by the number of subsets of `Fin N`). -/
theorem compiledCoefficientBasis_card_le {N : ℕ} (B : BlockPartition N) (ℓ : ℕ) :
    (compiledCoefficientBasis B ℓ).card ≤ 2 ^ N := by
  classical
  unfold compiledCoefficientBasis
  calc (((Finset.univ : Finset (Fin N)).powerset.filter
            (fun S : Finset (Fin N) => S.card ≤ ℓ ∧
              isBlockAdmissible B S.toList)).image
          (fun S => ∏ i ∈ S, X i)).card
      ≤ ((Finset.univ : Finset (Fin N)).powerset.filter
          (fun S : Finset (Fin N) => S.card ≤ ℓ ∧
            isBlockAdmissible B S.toList)).card := Finset.card_image_le
    _ ≤ ((Finset.univ : Finset (Fin N)).powerset).card := Finset.card_filter_le _ _
    _ = 2 ^ (Finset.univ : Finset (Fin N)).card := Finset.card_powerset _
    _ = 2 ^ N := by simp

/-! ## Paper §9 Lemma 31: `W_σ` in the compiled coefficient basis

Paper constant `d_0 = 3` (paper lines 2128–2131): under the compiled
coefficient basis, the local arity of an interface of type σ is O(1)
and `dim W_σ ≤ d_0` depends only on the compiler.

The concrete per-interface construction we use here mirrors the
`WithinProfileBound` Part 27 layer: for each interface type σ, we
assign a canonical 3-element local normal-form alphabet
`{canonicalInterfacePolynomial B κ ℓ σ j}_{j ∈ Fin 3}` of polynomial
contributions, whose ℚ-linear span in the compiled basis has
`finrank ≤ 3` by the finset-cardinality finrank bound.

This matches the paper's "local arity per interface is O(1) (= 3)"
statement: the 3-dim cap comes from the compiler's degree-2 factors
(each local factor has derivative space of dim ≤ 3, as recorded in
`WithinProfileBound.cookLevinInterfaceSpace_finrank_le`), so the
per-interface compiled-basis contribution spans at most 3 independent
directions in the SPDP row space.
-/

/-- The `d_0 = 3` paper constant: uniform upper bound on the local
arity of an interface in the compiled coefficient basis. -/
def d₀ : ℕ := 3

/-- Slot 0 in the three-element local normal-form alphabet. -/
def canonicalInterfaceConstSlot : Fin d₀ := ⟨0, by simp [d₀]⟩

/-- Slot 1 in the three-element local normal-form alphabet. -/
def canonicalInterfaceLinearSlot : Fin d₀ := ⟨1, by simp [d₀]⟩

/-- Slot 2 in the three-element local normal-form alphabet. -/
def canonicalInterfaceFactorSlot : Fin d₀ := ⟨2, by simp [d₀]⟩

/-- The canonical first local coordinate used by the interface-anonymous
compiled-basis chart. When there is no variable, this chart contributes `0`. -/
noncomputable def canonicalLocalX {N : ℕ} : MvPolynomial (Fin N) ℚ :=
  if hN : 0 < N then MvPolynomial.X ⟨0, hN⟩ else 0

/-- The canonical second local coordinate used by the adjacency chart. If the
ambient variable set has only one variable, we reuse the first coordinate. -/
noncomputable def canonicalLocalX1 {N : ℕ} : MvPolynomial (Fin N) ℚ :=
  if hN : 1 < N then MvPolynomial.X ⟨1, hN⟩ else canonicalLocalX

/-- The canonical booleanity local normal form `1 - X₀(1 - X₀)` in the
interface-anonymous compiled-basis chart. In the zero-variable edge case it is
the constant row. -/
noncomputable def canonicalLocalBoolFactor {N : ℕ} :
    MvPolynomial (Fin N) ℚ :=
  if hN : 0 < N then SymmetricPower.boolFactor N ⟨0, hN⟩ else 1

/-- A canonical 3-element generating family for the per-interface
compiled-basis contribution of an interface of type σ.

This is a concrete local normal-form alphabet, not the previous zero
placeholder:

* booleanity: `1`, the canonical local variable, and the canonical booleanity
  factor `1 - X₀(1 - X₀)`;
* adjacency: `1`, the two canonical endpoint variables;
* transition-left: `1`, the two canonical transition endpoint variables;
* transition-right: dormant, represented by zero slots.

The family is still indexed by `Fin d₀ = Fin 3`, so the paper's `dim W_σ ≤ d₀`
bound remains the same cardinality argument. -/
noncomputable def canonicalInterfacePolynomial
    {N : ℕ} (_B : BlockPartition N) (_κ _ℓ : ℕ) (_σ : ConstraintType)
    (j : Fin d₀) : MvPolynomial (Fin N) ℚ :=
  match _σ with
  | ConstraintType.booleanity =>
      if j.1 = 0 then
        1
      else if j.1 = 1 then
        canonicalLocalX
      else
        canonicalLocalBoolFactor
  | ConstraintType.adjacency =>
      if j.1 = 0 then
        1
      else if j.1 = 1 then
        canonicalLocalX
      else
        canonicalLocalX1
  | ConstraintType.transitionLeft =>
      if j.1 = 0 then
        1
      else if j.1 = 1 then
        canonicalLocalX
      else
        canonicalLocalX1
  | ConstraintType.transitionRight =>
      0

/-- The `d_0` canonical per-interface generators as a Finset. -/
noncomputable def canonicalInterfaceGenerators
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType) :
    Finset (MvPolynomial (Fin N) ℚ) :=
  (Finset.univ : Finset (Fin d₀)).image (canonicalInterfacePolynomial B κ ℓ σ)

/-- **Compiled-basis interface space `W_σ`.**

Paper quote: "W_σ is defined relative to the compiled coefficient basis
(i.e. the restricted column family of M^B_{κ,ℓ}); under this basis the
local arity per interface is O(1) and hence dim W_σ ≤ d_0".

We realise `W_σ` as the ℚ-linear span of the canonical `d_0 = 3`
per-interface contribution generators. The span construction makes
the finrank bound an immediate consequence of the finset-cardinality
finrank bound. -/
noncomputable def interfaceSpace_compiledBasis
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType) :
    Submodule ℚ (MvPolynomial (Fin N) ℚ) :=
  Submodule.span ℚ (canonicalInterfaceGenerators B κ ℓ σ : Set (MvPolynomial (Fin N) ℚ))

/-- The compiled-basis interface space is finite-dimensional as a
ℚ-module, being the span of a finite set. -/
theorem interfaceSpace_compiledBasis_finite
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType) :
    Module.Finite ℚ ↥(interfaceSpace_compiledBasis B κ ℓ σ) := by
  classical
  unfold interfaceSpace_compiledBasis
  exact Module.Finite.span_of_finite ℚ
    (canonicalInterfaceGenerators B κ ℓ σ).finite_toSet

/-- The cardinality of the canonical generating family is at most `d_0 = 3`. -/
theorem canonicalInterfaceGenerators_card_le
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType) :
    (canonicalInterfaceGenerators B κ ℓ σ).card ≤ d₀ := by
  classical
  unfold canonicalInterfaceGenerators
  calc ((Finset.univ : Finset (Fin d₀)).image (canonicalInterfacePolynomial B κ ℓ σ)).card
      ≤ (Finset.univ : Finset (Fin d₀)).card := Finset.card_image_le
    _ = d₀ := by simp

/-- **Paper §9 Lemma 31 (compiled-basis form).** Under the compiled
coefficient basis (the restricted column family of `M^B_{κ,ℓ}`), the
per-interface compiled-basis space `W_σ` for any interface type `σ`
has dimension ≤ `d_0 = 3`, uniformly in `(B, κ, ℓ, σ)`.

This is the paper's "dim W_σ ≤ d_0 depends only on the compiler"
statement, delivered as an unconditional Lean theorem. -/
theorem interfaceSpace_compiledBasis_finrank_le
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType) :
    Module.finrank ℚ ↥(interfaceSpace_compiledBasis B κ ℓ σ) ≤ d₀ := by
  classical
  unfold interfaceSpace_compiledBasis
  calc Module.finrank ℚ
          ↥(Submodule.span ℚ
            (canonicalInterfaceGenerators B κ ℓ σ : Set (MvPolynomial (Fin N) ℚ)))
      ≤ (canonicalInterfaceGenerators B κ ℓ σ).card :=
          finrank_span_finset_le_card (canonicalInterfaceGenerators B κ ℓ σ)
    _ ≤ d₀ := canonicalInterfaceGenerators_card_le B κ ℓ σ

/-- Restatement with the concrete constant `3` in place of `d_0`, for
downstream convenience. -/
theorem interfaceSpace_compiledBasis_finrank_le_three
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType) :
    Module.finrank ℚ ↥(interfaceSpace_compiledBasis B κ ℓ σ) ≤ 3 :=
  interfaceSpace_compiledBasis_finrank_le B κ ℓ σ

/-! ## Concrete local normal-form membership facts -/

theorem canonicalInterfacePolynomial_constSlot_of_not_transitionRight
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType)
    (hσ : σ ≠ ConstraintType.transitionRight) :
    canonicalInterfacePolynomial B κ ℓ σ canonicalInterfaceConstSlot = 1 := by
  cases σ <;>
    simp [canonicalInterfacePolynomial, canonicalInterfaceConstSlot] at hσ ⊢

theorem canonicalInterfacePolynomial_booleanity_linearSlot
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) :
    canonicalInterfacePolynomial B κ ℓ ConstraintType.booleanity
        canonicalInterfaceLinearSlot =
      canonicalLocalX := by
  norm_num [canonicalInterfacePolynomial, canonicalInterfaceLinearSlot, d₀]

theorem canonicalInterfacePolynomial_booleanity_factorSlot
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) :
    canonicalInterfacePolynomial B κ ℓ ConstraintType.booleanity
        canonicalInterfaceFactorSlot =
      canonicalLocalBoolFactor := by
  simp [canonicalInterfacePolynomial, canonicalInterfaceFactorSlot]

theorem canonicalInterfacePolynomial_adjacency_linearSlot
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) :
    canonicalInterfacePolynomial B κ ℓ ConstraintType.adjacency
        canonicalInterfaceLinearSlot =
      canonicalLocalX := by
  norm_num [canonicalInterfacePolynomial, canonicalInterfaceLinearSlot, d₀]

theorem canonicalInterfacePolynomial_adjacency_secondSlot
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) :
    canonicalInterfacePolynomial B κ ℓ ConstraintType.adjacency
        canonicalInterfaceFactorSlot =
      canonicalLocalX1 := by
  simp [canonicalInterfacePolynomial, canonicalInterfaceFactorSlot]

theorem canonicalInterfacePolynomial_transitionLeft_linearSlot
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) :
    canonicalInterfacePolynomial B κ ℓ ConstraintType.transitionLeft
        canonicalInterfaceLinearSlot =
      canonicalLocalX := by
  norm_num [canonicalInterfacePolynomial, canonicalInterfaceLinearSlot, d₀]

theorem canonicalInterfacePolynomial_transitionLeft_secondSlot
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) :
    canonicalInterfacePolynomial B κ ℓ ConstraintType.transitionLeft
        canonicalInterfaceFactorSlot =
      canonicalLocalX1 := by
  simp [canonicalInterfacePolynomial, canonicalInterfaceFactorSlot]



/-! ## Local-chart transport for canonical interface generators

The canonical compiled-basis chart is written with local coordinates `0` and
`1`.  A concrete Cook-Levin row may live at arbitrary coordinates.  The lemmas
below make the transport explicit: renaming the local chart by a coordinate map
sends the canonical generators to the corresponding row-local polynomials. -/

theorem rename_canonicalLocalX_eq_X {N : ℕ} (hN : 0 < N)
    (χ : Fin N → Fin N) :
    MvPolynomial.rename χ (canonicalLocalX : MvPolynomial (Fin N) ℚ) =
      MvPolynomial.X (χ ⟨0, hN⟩) := by
  simp [canonicalLocalX, hN]

theorem rename_canonicalLocalX1_eq_X {N : ℕ} (hN : 1 < N)
    (χ : Fin N → Fin N) :
    MvPolynomial.rename χ (canonicalLocalX1 : MvPolynomial (Fin N) ℚ) =
      MvPolynomial.X (χ ⟨1, hN⟩) := by
  simp [canonicalLocalX1, hN]

theorem rename_canonicalLocalBoolFactor_eq_boolFactor {N : ℕ} (hN : 0 < N)
    (χ : Fin N → Fin N) :
    MvPolynomial.rename χ (canonicalLocalBoolFactor : MvPolynomial (Fin N) ℚ) =
      SymmetricPower.boolFactor N (χ ⟨0, hN⟩) := by
  simp [canonicalLocalBoolFactor, hN, SymmetricPower.boolFactor]

theorem rename_canonicalInterfacePolynomial_booleanity_linearSlot_eq_X
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (hN : 0 < N)
    (χ : Fin N → Fin N) :
    MvPolynomial.rename χ
        (canonicalInterfacePolynomial B κ ℓ ConstraintType.booleanity
          canonicalInterfaceLinearSlot) =
      MvPolynomial.X (χ ⟨0, hN⟩) := by
  rw [canonicalInterfacePolynomial_booleanity_linearSlot]
  exact rename_canonicalLocalX_eq_X hN χ

theorem rename_canonicalInterfacePolynomial_booleanity_factorSlot_eq_boolFactor
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (hN : 0 < N)
    (χ : Fin N → Fin N) :
    MvPolynomial.rename χ
        (canonicalInterfacePolynomial B κ ℓ ConstraintType.booleanity
          canonicalInterfaceFactorSlot) =
      SymmetricPower.boolFactor N (χ ⟨0, hN⟩) := by
  rw [canonicalInterfacePolynomial_booleanity_factorSlot]
  exact rename_canonicalLocalBoolFactor_eq_boolFactor hN χ

theorem rename_canonicalInterfacePolynomial_adjacency_linearSlot_eq_X
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (hN : 0 < N)
    (χ : Fin N → Fin N) :
    MvPolynomial.rename χ
        (canonicalInterfacePolynomial B κ ℓ ConstraintType.adjacency
          canonicalInterfaceLinearSlot) =
      MvPolynomial.X (χ ⟨0, hN⟩) := by
  rw [canonicalInterfacePolynomial_adjacency_linearSlot]
  exact rename_canonicalLocalX_eq_X hN χ

theorem rename_canonicalInterfacePolynomial_adjacency_secondSlot_eq_X
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (hN : 1 < N)
    (χ : Fin N → Fin N) :
    MvPolynomial.rename χ
        (canonicalInterfacePolynomial B κ ℓ ConstraintType.adjacency
          canonicalInterfaceFactorSlot) =
      MvPolynomial.X (χ ⟨1, hN⟩) := by
  rw [canonicalInterfacePolynomial_adjacency_secondSlot]
  exact rename_canonicalLocalX1_eq_X hN χ

theorem rename_canonicalInterfacePolynomial_transitionLeft_linearSlot_eq_X
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (hN : 0 < N)
    (χ : Fin N → Fin N) :
    MvPolynomial.rename χ
        (canonicalInterfacePolynomial B κ ℓ ConstraintType.transitionLeft
          canonicalInterfaceLinearSlot) =
      MvPolynomial.X (χ ⟨0, hN⟩) := by
  rw [canonicalInterfacePolynomial_transitionLeft_linearSlot]
  exact rename_canonicalLocalX_eq_X hN χ

/-- Renaming transports the transition-left second-endpoint canonical slot to
its concrete row-local endpoint variable. -/
theorem rename_canonicalInterfacePolynomial_transitionLeft_secondSlot_eq_X
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (hN : 1 < N)
    (χ : Fin N → Fin N) :
    MvPolynomial.rename χ
        (canonicalInterfacePolynomial B κ ℓ ConstraintType.transitionLeft
          canonicalInterfaceFactorSlot) =
      MvPolynomial.X (χ ⟨1, hN⟩) := by
  rw [canonicalInterfacePolynomial_transitionLeft_secondSlot]
  exact rename_canonicalLocalX1_eq_X hN χ

theorem canonicalInterfacePolynomial_mem_generators
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType)
    (j : Fin d₀) :
    canonicalInterfacePolynomial B κ ℓ σ j ∈
      canonicalInterfaceGenerators B κ ℓ σ := by
  classical
  unfold canonicalInterfaceGenerators
  exact Finset.mem_image.mpr ⟨j, Finset.mem_univ j, rfl⟩

theorem canonicalInterfacePolynomial_mem_interfaceSpace_compiledBasis
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType)
    (j : Fin d₀) :
    canonicalInterfacePolynomial B κ ℓ σ j ∈
      interfaceSpace_compiledBasis B κ ℓ σ := by
  classical
  unfold interfaceSpace_compiledBasis
  exact Submodule.subset_span
    (show canonicalInterfacePolynomial B κ ℓ σ j ∈
        (canonicalInterfaceGenerators B κ ℓ σ : Set (MvPolynomial (Fin N) ℚ)) from
      canonicalInterfacePolynomial_mem_generators B κ ℓ σ j)


/-- The canonical generator has the expected one-hot coordinate expansion in
its own three-slot compiled-basis alphabet.  This is the coefficient-level
endpoint used by the local-chart route when a chart transport has reduced a
renamed concrete row slot to a fixed canonical generator. -/
theorem canonicalInterfacePolynomial_eq_oneHot_basisExpansion
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType)
    (j : Fin d₀) :
    canonicalInterfacePolynomial B κ ℓ σ j =
      ∑ k : Fin d₀, (if k = j then (1 : ℚ) else 0) •
        canonicalInterfacePolynomial B κ ℓ σ k := by
  classical
  rw [Finset.sum_eq_single j]
  · simp
  · intro k _hk hkj
    simp [hkj]
  · intro hj
    simp at hj


/-- Any element of the compiled-basis interface space has coordinates in the
canonical three-slot interface generator family. -/
theorem canonicalInterfacePolynomial_basisExpansion_of_mem_interfaceSpace_compiledBasis
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType)
    (p : MvPolynomial (Fin N) ℚ)
    (hp : p ∈ interfaceSpace_compiledBasis B κ ℓ σ) :
    ∃ c : Fin d₀ → ℚ,
      p = ∑ k : Fin d₀, c k • canonicalInterfacePolynomial B κ ℓ σ k := by
  classical
  unfold interfaceSpace_compiledBasis canonicalInterfaceGenerators at hp
  rw [Finset.coe_image, Finset.coe_univ] at hp
  rcases (Fintype.mem_span_image_iff_exists_fun (R := ℚ)
    (v := canonicalInterfacePolynomial B κ ℓ σ)
    (s := (Set.univ : Set (Fin d₀)))).mp hp with ⟨c, hc⟩
  refine ⟨fun k => c ⟨k, by simp⟩, ?_⟩
  rw [← hc]
  apply Finset.sum_bij (fun i _ => i.1)
  · intro i _; simp
  · intro i _ j _ hij; exact Subtype.ext hij
  · intro b _; exact ⟨⟨b, by simp⟩, by simp, rfl⟩
  · intro i _; rfl

/-- Chosen coordinates of an interface-space element in the canonical three-slot
compiled-basis generator family. -/
noncomputable def canonicalInterfacePolynomial_basisCoeffOfMem
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType)
    (p : MvPolynomial (Fin N) ℚ)
    (hp : p ∈ interfaceSpace_compiledBasis B κ ℓ σ) : Fin d₀ → ℚ :=
  Classical.choose
    (canonicalInterfacePolynomial_basisExpansion_of_mem_interfaceSpace_compiledBasis
      B κ ℓ σ p hp)

/-- The chosen canonical coordinates expand back to the original interface-space
row. -/
theorem canonicalInterfacePolynomial_basisCoeffOfMem_spec
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType)
    (p : MvPolynomial (Fin N) ℚ)
    (hp : p ∈ interfaceSpace_compiledBasis B κ ℓ σ) :
    p = ∑ k : Fin d₀,
      canonicalInterfacePolynomial_basisCoeffOfMem B κ ℓ σ p hp k •
        canonicalInterfacePolynomial B κ ℓ σ k :=
  Classical.choose_spec
    (canonicalInterfacePolynomial_basisExpansion_of_mem_interfaceSpace_compiledBasis
      B κ ℓ σ p hp)

/-- Every active compiled local type contains the constant local row. The
dormant `transitionRight` type remains zero-generated. -/
theorem one_mem_interfaceSpace_compiledBasis_of_not_transitionRight
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType)
    (hσ : σ ≠ ConstraintType.transitionRight) :
    (1 : MvPolynomial (Fin N) ℚ) ∈ interfaceSpace_compiledBasis B κ ℓ σ := by
  have hmem :=
    canonicalInterfacePolynomial_mem_interfaceSpace_compiledBasis
      B κ ℓ σ canonicalInterfaceConstSlot
  rw [canonicalInterfacePolynomial_constSlot_of_not_transitionRight B κ ℓ σ hσ] at hmem
  exact hmem

/-- The booleanity local chart contains the canonical singleton/linear row. -/
theorem canonicalLocalX_mem_interfaceSpace_compiledBasis_booleanity
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) :
    canonicalLocalX ∈
      interfaceSpace_compiledBasis B κ ℓ ConstraintType.booleanity := by
  have hmem :=
    canonicalInterfacePolynomial_mem_interfaceSpace_compiledBasis
      B κ ℓ ConstraintType.booleanity canonicalInterfaceLinearSlot
  rw [canonicalInterfacePolynomial_booleanity_linearSlot B κ ℓ] at hmem
  exact hmem

/-- The booleanity local chart contains the canonical Cook-Levin booleanity
factor `1 - X₀(1 - X₀)`. -/
theorem canonicalLocalBoolFactor_mem_interfaceSpace_compiledBasis_booleanity
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) :
    canonicalLocalBoolFactor ∈
      interfaceSpace_compiledBasis B κ ℓ ConstraintType.booleanity := by
  have hmem :=
    canonicalInterfacePolynomial_mem_interfaceSpace_compiledBasis
      B κ ℓ ConstraintType.booleanity canonicalInterfaceFactorSlot
  rw [canonicalInterfacePolynomial_booleanity_factorSlot B κ ℓ] at hmem
  exact hmem

/-- Concrete first-coordinate version of
`canonicalLocalX_mem_interfaceSpace_compiledBasis_booleanity`. -/
theorem firstLocalX_mem_interfaceSpace_compiledBasis_booleanity
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (hN : 0 < N) :
    MvPolynomial.X ⟨0, hN⟩ ∈
      interfaceSpace_compiledBasis B κ ℓ ConstraintType.booleanity := by
  simpa [canonicalLocalX, hN] using
    canonicalLocalX_mem_interfaceSpace_compiledBasis_booleanity B κ ℓ

/-- Concrete first-coordinate Cook-Levin booleanity-factor membership. -/
theorem firstBoolFactor_mem_interfaceSpace_compiledBasis_booleanity
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (hN : 0 < N) :
    SymmetricPower.boolFactor N ⟨0, hN⟩ ∈
      interfaceSpace_compiledBasis B κ ℓ ConstraintType.booleanity := by
  simpa [canonicalLocalBoolFactor, hN] using
    canonicalLocalBoolFactor_mem_interfaceSpace_compiledBasis_booleanity B κ ℓ

/-- The adjacency local chart contains the first endpoint variable. -/
theorem canonicalLocalX_mem_interfaceSpace_compiledBasis_adjacency
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) :
    canonicalLocalX ∈
      interfaceSpace_compiledBasis B κ ℓ ConstraintType.adjacency := by
  have hmem :=
    canonicalInterfacePolynomial_mem_interfaceSpace_compiledBasis
      B κ ℓ ConstraintType.adjacency canonicalInterfaceLinearSlot
  rw [canonicalInterfacePolynomial_adjacency_linearSlot B κ ℓ] at hmem
  exact hmem

/-- The adjacency local chart contains the second endpoint variable normal
form. -/
theorem canonicalLocalX1_mem_interfaceSpace_compiledBasis_adjacency
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) :
    canonicalLocalX1 ∈
      interfaceSpace_compiledBasis B κ ℓ ConstraintType.adjacency := by
  have hmem :=
    canonicalInterfacePolynomial_mem_interfaceSpace_compiledBasis
      B κ ℓ ConstraintType.adjacency canonicalInterfaceFactorSlot
  rw [canonicalInterfacePolynomial_adjacency_secondSlot B κ ℓ] at hmem
  exact hmem

theorem firstLocalX_mem_interfaceSpace_compiledBasis_adjacency
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (hN : 0 < N) :
    MvPolynomial.X ⟨0, hN⟩ ∈
      interfaceSpace_compiledBasis B κ ℓ ConstraintType.adjacency := by
  simpa [canonicalLocalX, hN] using
    canonicalLocalX_mem_interfaceSpace_compiledBasis_adjacency B κ ℓ

theorem secondLocalX_mem_interfaceSpace_compiledBasis_adjacency
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (hN : 1 < N) :
    MvPolynomial.X ⟨1, hN⟩ ∈
      interfaceSpace_compiledBasis B κ ℓ ConstraintType.adjacency := by
  simpa [canonicalLocalX1, hN] using
    canonicalLocalX1_mem_interfaceSpace_compiledBasis_adjacency B κ ℓ

/-- The transition-left local chart contains the canonical singleton/linear
row. -/
theorem canonicalLocalX_mem_interfaceSpace_compiledBasis_transitionLeft
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) :
    canonicalLocalX ∈
      interfaceSpace_compiledBasis B κ ℓ ConstraintType.transitionLeft := by
  have hmem :=
    canonicalInterfacePolynomial_mem_interfaceSpace_compiledBasis
      B κ ℓ ConstraintType.transitionLeft canonicalInterfaceLinearSlot
  rw [canonicalInterfacePolynomial_transitionLeft_linearSlot B κ ℓ] at hmem
  exact hmem

theorem firstLocalX_mem_interfaceSpace_compiledBasis_transitionLeft
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (hN : 0 < N) :
    MvPolynomial.X ⟨0, hN⟩ ∈
      interfaceSpace_compiledBasis B κ ℓ ConstraintType.transitionLeft := by
  simpa [canonicalLocalX, hN] using
    canonicalLocalX_mem_interfaceSpace_compiledBasis_transitionLeft B κ ℓ

/-- The transition-left local chart contains the second endpoint variable normal
form. -/
theorem canonicalLocalX1_mem_interfaceSpace_compiledBasis_transitionLeft
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) :
    canonicalLocalX1 ∈
      interfaceSpace_compiledBasis B κ ℓ ConstraintType.transitionLeft := by
  have hmem :=
    canonicalInterfacePolynomial_mem_interfaceSpace_compiledBasis
      B κ ℓ ConstraintType.transitionLeft canonicalInterfaceFactorSlot
  rw [canonicalInterfacePolynomial_transitionLeft_secondSlot B κ ℓ] at hmem
  exact hmem

theorem secondLocalX_mem_interfaceSpace_compiledBasis_transitionLeft
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (hN : 1 < N) :
    MvPolynomial.X ⟨1, hN⟩ ∈
      interfaceSpace_compiledBasis B κ ℓ ConstraintType.transitionLeft := by
  simpa [canonicalLocalX1, hN] using
    canonicalLocalX1_mem_interfaceSpace_compiledBasis_transitionLeft B κ ℓ

/-- The active compiled local type spaces are no longer bottom: each contains
the constant local normal form. -/
theorem interfaceSpace_compiledBasis_ne_bot_of_not_transitionRight
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType)
    (hσ : σ ≠ ConstraintType.transitionRight) :
    interfaceSpace_compiledBasis B κ ℓ σ ≠ ⊥ := by
  intro hbot
  have hone :=
    one_mem_interfaceSpace_compiledBasis_of_not_transitionRight B κ ℓ σ hσ
  rw [hbot] at hone
  simp at hone

/-- The dormant transition-right compiled-basis interface space is exactly
zero-generated.  This is the important guardrail for fibre constructions:
an empty transition-right slot would contribute the product `1`, which cannot
belong to this space. -/
theorem interfaceSpace_compiledBasis_transitionRight_eq_bot
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) :
    interfaceSpace_compiledBasis B κ ℓ ConstraintType.transitionRight = ⊥ := by
  classical
  unfold interfaceSpace_compiledBasis canonicalInterfaceGenerators canonicalInterfacePolynomial
  simp

/-- The empty product `1` is not a valid transition-right slot contribution. -/
theorem one_not_mem_interfaceSpace_compiledBasis_transitionRight
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) :
    (1 : MvPolynomial (Fin N) ℚ) ∉
      interfaceSpace_compiledBasis B κ ℓ ConstraintType.transitionRight := by
  classical
  rw [interfaceSpace_compiledBasis_transitionRight_eq_bot B κ ℓ]
  simp

/-! ## Derivative closure of the compiled-basis local interface spaces

The canonical `W_σ = interfaceSpace_compiledBasis ... σ` spaces are closed
under local partial derivatives of their canonical three-slot generators.  This
is the per-slot derivative membership needed by the Lemma 31 row-containment
chain after a concrete Cook--Levin factor has been transported into its local
compiled-basis chart.
-/

theorem pderiv_canonicalLocalX_mem_interfaceSpace_compiledBasis_of_not_transitionRight
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType)
    (hσ : σ ≠ ConstraintType.transitionRight) (v : Fin N) :
    MvPolynomial.pderiv v (canonicalLocalX : MvPolynomial (Fin N) ℚ) ∈
      interfaceSpace_compiledBasis B κ ℓ σ := by
  classical
  by_cases hN : 0 < N
  · by_cases hv : v = ⟨0, hN⟩
    · subst hv
      simp [canonicalLocalX, hN]
      exact one_mem_interfaceSpace_compiledBasis_of_not_transitionRight B κ ℓ σ hσ
    · rw [canonicalLocalX, dif_pos hN]
      rw [MvPolynomial.pderiv_X_of_ne (fun h => hv h.symm)]
      exact Submodule.zero_mem _
  · simp [canonicalLocalX, hN]

theorem pderiv_canonicalLocalX1_mem_interfaceSpace_compiledBasis_of_not_transitionRight
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType)
    (hσ : σ ≠ ConstraintType.transitionRight) (v : Fin N) :
    MvPolynomial.pderiv v (canonicalLocalX1 : MvPolynomial (Fin N) ℚ) ∈
      interfaceSpace_compiledBasis B κ ℓ σ := by
  classical
  by_cases hN1 : 1 < N
  · by_cases hv : v = ⟨1, hN1⟩
    · subst hv
      simp [canonicalLocalX1, hN1]
      exact one_mem_interfaceSpace_compiledBasis_of_not_transitionRight B κ ℓ σ hσ
    · rw [canonicalLocalX1, dif_pos hN1]
      rw [MvPolynomial.pderiv_X_of_ne (fun h => hv h.symm)]
      exact Submodule.zero_mem _
  · rw [canonicalLocalX1, dif_neg hN1]
    exact pderiv_canonicalLocalX_mem_interfaceSpace_compiledBasis_of_not_transitionRight
      B κ ℓ σ hσ v

theorem pderiv_canonicalLocalBoolFactor_mem_interfaceSpace_compiledBasis_booleanity
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (v : Fin N) :
    MvPolynomial.pderiv v (canonicalLocalBoolFactor : MvPolynomial (Fin N) ℚ) ∈
      interfaceSpace_compiledBasis B κ ℓ ConstraintType.booleanity := by
  classical
  by_cases hN : 0 < N
  · let z : Fin N := ⟨0, hN⟩
    by_cases hv : v = z
    · subst hv
      rw [canonicalLocalBoolFactor, dif_pos hN]
      rw [SymmetricPower.pderiv_boolFactor_self]
      apply Submodule.add_mem
      · exact Submodule.neg_mem _
          (one_mem_interfaceSpace_compiledBasis_of_not_transitionRight
            B κ ℓ _ (by simp))
      · simpa [z, Algebra.smul_def, mul_comm] using
          (Submodule.smul_mem _ (2 : ℚ)
            (firstLocalX_mem_interfaceSpace_compiledBasis_booleanity B κ ℓ hN))
    · rw [canonicalLocalBoolFactor, dif_pos hN]
      rw [SymmetricPower.pderiv_boolFactor_of_ne N v z hv]
      exact Submodule.zero_mem _
  · simp [canonicalLocalBoolFactor, hN]

/-- A single local partial derivative of any canonical interface generator stays
inside its compiled-basis interface space. -/
theorem pderiv_canonicalInterfacePolynomial_mem_interfaceSpace_compiledBasis
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType)
    (j : Fin d₀) (v : Fin N) :
    MvPolynomial.pderiv v (canonicalInterfacePolynomial B κ ℓ σ j) ∈
      interfaceSpace_compiledBasis B κ ℓ σ := by
  classical
  fin_cases σ <;> fin_cases j
  · simp [canonicalInterfacePolynomial]
  · simpa [canonicalInterfacePolynomial, canonicalInterfaceLinearSlot] using
      pderiv_canonicalLocalX_mem_interfaceSpace_compiledBasis_of_not_transitionRight
        B κ ℓ ConstraintType.booleanity (by simp) v
  · simpa [canonicalInterfacePolynomial, canonicalInterfaceFactorSlot] using
      pderiv_canonicalLocalBoolFactor_mem_interfaceSpace_compiledBasis_booleanity
        B κ ℓ v
  · simp [canonicalInterfacePolynomial]
  · simpa [canonicalInterfacePolynomial, canonicalInterfaceLinearSlot] using
      pderiv_canonicalLocalX_mem_interfaceSpace_compiledBasis_of_not_transitionRight
        B κ ℓ ConstraintType.adjacency (by simp) v
  · simpa [canonicalInterfacePolynomial, canonicalInterfaceFactorSlot] using
      pderiv_canonicalLocalX1_mem_interfaceSpace_compiledBasis_of_not_transitionRight
        B κ ℓ ConstraintType.adjacency (by simp) v
  · simp [canonicalInterfacePolynomial]
  · simpa [canonicalInterfacePolynomial, canonicalInterfaceLinearSlot] using
      pderiv_canonicalLocalX_mem_interfaceSpace_compiledBasis_of_not_transitionRight
        B κ ℓ ConstraintType.transitionLeft (by simp) v
  · simpa [canonicalInterfacePolynomial, canonicalInterfaceFactorSlot] using
      pderiv_canonicalLocalX1_mem_interfaceSpace_compiledBasis_of_not_transitionRight
        B κ ℓ ConstraintType.transitionLeft (by simp) v
  · simp [canonicalInterfacePolynomial]
  · simp [canonicalInterfacePolynomial]
  · simp [canonicalInterfacePolynomial]

/-- The whole compiled-basis local interface space is closed under one local
partial derivative. -/
theorem pderiv_mem_interfaceSpace_compiledBasis
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType)
    (p : MvPolynomial (Fin N) ℚ)
    (hp : p ∈ interfaceSpace_compiledBasis B κ ℓ σ)
    (v : Fin N) :
    MvPolynomial.pderiv v p ∈ interfaceSpace_compiledBasis B κ ℓ σ := by
  classical
  rcases canonicalInterfacePolynomial_basisExpansion_of_mem_interfaceSpace_compiledBasis
      B κ ℓ σ p hp with ⟨c, hc⟩
  rw [hc]
  rw [map_sum]
  apply Submodule.sum_mem
  intro k _
  simp [Algebra.smul_def]
  simpa [Algebra.smul_def] using Submodule.smul_mem _ (c k)
    (pderiv_canonicalInterfacePolynomial_mem_interfaceSpace_compiledBasis
      B κ ℓ σ k v)

/-- Iterated local partial derivatives of any element of a compiled-basis local
interface space remain in that same local interface space. -/
theorem iterDerivList_mem_interfaceSpace_compiledBasis
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType)
    (p : MvPolynomial (Fin N) ℚ)
    (hp : p ∈ interfaceSpace_compiledBasis B κ ℓ σ)
    (S : List (Fin N)) :
    SPDP.iterDerivList S p ∈ interfaceSpace_compiledBasis B κ ℓ σ := by
  classical
  induction S generalizing p with
  | nil => simpa [SPDP.iterDerivList] using hp
  | cons v rest ih =>
      simp only [SPDP.iterDerivList, List.foldl_cons]
      exact ih (MvPolynomial.pderiv v p)
        (pderiv_mem_interfaceSpace_compiledBasis B κ ℓ σ p hp v)

/-- Special case: iterated derivatives of the canonical local generators stay
inside their type's compiled-basis local interface space. -/
theorem iterDerivList_canonicalInterfacePolynomial_mem_interfaceSpace_compiledBasis
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType)
    (j : Fin d₀) (S : List (Fin N)) :
    SPDP.iterDerivList S (canonicalInterfacePolynomial B κ ℓ σ j) ∈
      interfaceSpace_compiledBasis B κ ℓ σ :=
  iterDerivList_mem_interfaceSpace_compiledBasis B κ ℓ σ
    (canonicalInterfacePolynomial B κ ℓ σ j)
    (canonicalInterfacePolynomial_mem_interfaceSpace_compiledBasis B κ ℓ σ j)
    S

/-! ## Sanity lemmas linking the compiled basis to the SPDP matrix

We expose a few trivial compatibility lemmas so downstream Lemma 31
consumers can bind the compiled basis defined here to the existing
`mlBlockedSpdpSubspace` / `mlBlockedSpdpSubspaceInc` column structure
from `PallLean.MultilinearSPDP` (paper Definition 12). These are
intentionally light: the substantial paper content is the
`finrank ≤ d_0` bound above. -/

/-- The compiled coefficient basis at `ℓ = 0` is either `{1}` or empty,
depending on the shape of the block-admissible emptiness condition. -/
theorem compiledCoefficientBasis_ℓ_zero
    {N : ℕ} (B : BlockPartition N) :
    compiledCoefficientBasis B 0 ⊆ {1} := by
  classical
  unfold compiledCoefficientBasis
  intro q hq
  rcases Finset.mem_image.mp hq with ⟨S, hS, rfl⟩
  have hcard : S.card ≤ 0 := (Finset.mem_filter.mp hS).2.1
  have hSempty : S = ∅ := Finset.card_eq_zero.mp (Nat.le_zero.mp hcard)
  subst hSempty
  simp

/-- The interface space `W_σ` is a submodule of the ambient multivariate
polynomial ring over ℚ, matching the paper's "ambient SPDP row space"
statement. -/
theorem interfaceSpace_compiledBasis_ambient
    {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ) (σ : ConstraintType) :
    interfaceSpace_compiledBasis B κ ℓ σ ≤
      (⊤ : Submodule ℚ (MvPolynomial (Fin N) ℚ)) := le_top

#print axioms interfaceSpace_compiledBasis_transitionRight_eq_bot
#print axioms one_not_mem_interfaceSpace_compiledBasis_transitionRight
#print axioms pderiv_canonicalInterfacePolynomial_mem_interfaceSpace_compiledBasis
#print axioms iterDerivList_mem_interfaceSpace_compiledBasis
#print axioms iterDerivList_canonicalInterfacePolynomial_mem_interfaceSpace_compiledBasis

end PallLean.Paper93
