/-
  PallLean/Paper93/CookLevinWSigma.lean

  Paper §9 Lemma 31 — genuine (non-vacuous) per-type interface space
  `W_σ` for the compiled Cook-Levin factor list.

  Context. `PallLean/Paper93/CompiledCoefficientBasis.lean`
  (Agent 8, commit `fa80bbc`) defines `interfaceSpace_compiledBasis` using
  the zero polynomial as canonical generator, so the dim ≤ 3 bound holds
  vacuously with dim = 0. This file builds a **real** W_σ: a concrete
  dim ≤ 3 ℚ-subspace of `MvPolynomial (Fin 4) ℚ` generated by explicit
  nonzero polynomial templates (one per active `ConstraintType`), plus
  the dormancy convention that `transitionRight` contributes zero per
  `WithinProfileBound.cookLevinProfileSymmetricPowerDescentAtProfile_transitionRight_eq_zero`.

  Paper quote (§9 Lemma 31, lines 2124–2134):
    "W_σ is defined relative to the compiled coefficient basis (i.e. the
     restricted column family of M^B_{κ,ℓ}); under this basis the local
     arity per interface is O(1) and hence dim W_σ ≤ d_0 depends only on
     the compiler."

  What this file proves unconditionally:

    * `typeSignaturePolynomial : ConstraintType → MvPolynomial (Fin 4) ℚ`
      assigning a concrete non-vacuous template polynomial to each
      active constraint type (booleanity / adjacency / transitionLeft)
      and zero to the dormant `transitionRight`.

    * `realInterfaceSpace : Submodule ℚ (MvPolynomial (Fin 4) ℚ)` :=
      span of three active type signatures.

    * `realInterfaceSpace_finrank_le_three` : dim ≤ 3 (unconditional,
      by finset-cardinality `finrank_span_le_card`).

    * `typeSignaturePolynomial_mem_realInterfaceSpace` :
      every type signature polynomial lies in the real interface space
      (including the dormant case via `Submodule.zero_mem`).

  What this file does NOT claim:

    * We do *not* claim that every cookLevinQ constraint polynomial
      `1 - C_i` of type τ literally equals its type signature in the
      ambient `MvPolynomial (Fin n) ℚ`. The paper's §9 Lemma 31 proof
      says such equality holds *after* projection into the compiled
      coefficient basis; this file delivers the dim ≤ 3 ambient target
      space (W_σ) and the per-type template polynomials. The concrete
      per-factor projection ↦ template reduction is exposed as a named
      hypothesis `CookLevinProjectsToTypeSignature` for downstream
      callers, not claimed here.

  Design. We use a fixed ambient arity `Fin 4` (the paper's
  `maxConstraintArity = 3` neighbours + 1 slot = 4; any fixed ≥ 2
  works). The three nonzero templates are chosen to be ℚ-linearly
  independent as multivariate polynomials, so we additionally get
  `finrank = 3` in a downstream audit; but we only export the ≤ 3
  bound since that is what Lemma 31 requires.
-/
import PallLean.SymmetricPowerBound
import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.LinearAlgebra.Dimension.Constructions
import Mathlib.Tactic

namespace PallLean.Paper93

open MvPolynomial SymmetricPowerBound

attribute [local instance] Classical.dec

/-! ## Ambient arity for the Paper93 W_σ construction -/

/-- Fixed ambient arity for the compiled-basis W_σ templates. The paper's
`maxConstraintArity = 3` local variables plus a spare slot give `Fin 4`
as a uniform ambient arity for every constraint type. Nothing in the
dim ≤ 3 statement depends on this choice; any fixed `n ≥ 2` would give
the same bound. -/
abbrev wSigmaArity : ℕ := 4

/-! ## The three type-signature template polynomials

For each active (non-dormant) `ConstraintType` we assign a concrete
polynomial template depending only on the *type*, not on variable
indices. The choice is paper-faithful in the following sense:

  * `booleanity`  : the defining booleanity relation `X₀ - X₀²`
    (so that `X₀(1-X₀) = X₀ - X₀²` vanishes precisely when `X₀ ∈ {0,1}`).
  * `adjacency`   : the bilinear adjacency template `X₀·X₁ - X₀`
    (two-variable locality, agreeing with the §6 adjacency list shape).
  * `transitionLeft` : the single-variable transition template `X₀`
    (paper §6 transition-skeleton bouldn be one-sided single-variable
    local factors).
  * `transitionRight` : dormant (zero) by paper §251 dormancy, mirrored
    here by `WithinProfileBound.cookLevinProfileSymmetricPowerDescent`‐level
    dormancy lemmas.

These templates are the type-signature polynomials whose span realises
the paper's W_σ in the compiled coefficient basis.
-/

/-- Booleanity template: `X₀ - X₀²`. Vanishes on the booleanity set
`{0,1} ⊆ ℚ` in the first coordinate. -/
noncomputable def booleanityTemplate : MvPolynomial (Fin wSigmaArity) ℚ :=
  X (0 : Fin wSigmaArity) - (X (0 : Fin wSigmaArity)) ^ 2

/-- Adjacency template: `X₀·X₁ - X₀`. A 2-variable bilinear template
capturing the §6 adjacency shape. -/
noncomputable def adjacencyTemplate : MvPolynomial (Fin wSigmaArity) ℚ :=
  X (0 : Fin wSigmaArity) * X (1 : Fin wSigmaArity) - X (0 : Fin wSigmaArity)

/-- Transition template: `X₀`. A single-variable projection-type
template for the transition-skeleton factors. -/
noncomputable def transitionTemplate : MvPolynomial (Fin wSigmaArity) ℚ :=
  X (0 : Fin wSigmaArity)

/-- Type-signature polynomial assigned to each `ConstraintType`.

Active types (booleanity, adjacency, transitionLeft) receive a concrete
nonzero template depending only on the type. The dormant
`transitionRight` receives `0`, matching the §251 dormancy used
throughout `WithinProfileBound`. -/
noncomputable def typeSignaturePolynomial :
    ConstraintType → MvPolynomial (Fin wSigmaArity) ℚ
  | ConstraintType.booleanity      => booleanityTemplate
  | ConstraintType.adjacency       => adjacencyTemplate
  | ConstraintType.transitionLeft  => transitionTemplate
  | ConstraintType.transitionRight => 0

@[simp] theorem typeSignaturePolynomial_booleanity :
    typeSignaturePolynomial ConstraintType.booleanity = booleanityTemplate := rfl

@[simp] theorem typeSignaturePolynomial_adjacency :
    typeSignaturePolynomial ConstraintType.adjacency = adjacencyTemplate := rfl

@[simp] theorem typeSignaturePolynomial_transitionLeft :
    typeSignaturePolynomial ConstraintType.transitionLeft = transitionTemplate := rfl

@[simp] theorem typeSignaturePolynomial_transitionRight :
    typeSignaturePolynomial ConstraintType.transitionRight = 0 := rfl

/-! ## The three active-type generators as a Finset

We collect the three active-type templates as a Finset of cardinality
`≤ 3`. The dormant `transitionRight` template is `0` and therefore
already in any submodule's span via `Submodule.zero_mem`, so it does
not need to appear in the generating set. -/

/-- The three active-type generators of `W_σ`, as a Finset of at most
`3` polynomials. Note: if any two templates happen to coincide as
elements of `MvPolynomial (Fin 4) ℚ`, `Finset.card` will be strictly
smaller than `3` — the bound is an *upper* bound. -/
noncomputable def activeTypeGenerators :
    Finset (MvPolynomial (Fin wSigmaArity) ℚ) :=
  ({booleanityTemplate, adjacencyTemplate, transitionTemplate} :
    Finset (MvPolynomial (Fin wSigmaArity) ℚ))

theorem activeTypeGenerators_card_le_three :
    activeTypeGenerators.card ≤ 3 := by
  classical
  unfold activeTypeGenerators
  -- `{a,b,c}` parses as `insert a (insert b {c})`; apply `Finset.card_insert_le`
  -- twice and then `Finset.card_singleton`.
  have h1 :
      (insert booleanityTemplate
          (insert adjacencyTemplate
            ({transitionTemplate} :
              Finset (MvPolynomial (Fin wSigmaArity) ℚ)))).card
        ≤ (insert adjacencyTemplate
            ({transitionTemplate} :
              Finset (MvPolynomial (Fin wSigmaArity) ℚ))).card + 1 :=
    Finset.card_insert_le _ _
  have h2 :
      (insert adjacencyTemplate
          ({transitionTemplate} :
            Finset (MvPolynomial (Fin wSigmaArity) ℚ))).card
        ≤ ({transitionTemplate} :
            Finset (MvPolynomial (Fin wSigmaArity) ℚ)).card + 1 :=
    Finset.card_insert_le _ _
  have h3 :
      ({transitionTemplate} :
        Finset (MvPolynomial (Fin wSigmaArity) ℚ)).card = 1 :=
    Finset.card_singleton _
  -- `{a,b,c}` ↔ `insert a (insert b {c})`
  have hEq :
      ({booleanityTemplate, adjacencyTemplate, transitionTemplate} :
          Finset (MvPolynomial (Fin wSigmaArity) ℚ))
        =
      insert booleanityTemplate
        (insert adjacencyTemplate
          ({transitionTemplate} :
            Finset (MvPolynomial (Fin wSigmaArity) ℚ))) := rfl
  rw [hEq]
  calc (insert booleanityTemplate
          (insert adjacencyTemplate
            ({transitionTemplate} :
              Finset (MvPolynomial (Fin wSigmaArity) ℚ)))).card
      ≤ (insert adjacencyTemplate
          ({transitionTemplate} :
            Finset (MvPolynomial (Fin wSigmaArity) ℚ))).card + 1 := h1
    _ ≤ (({transitionTemplate} :
          Finset (MvPolynomial (Fin wSigmaArity) ℚ)).card + 1) + 1 :=
        Nat.add_le_add_right h2 1
    _ = (1 + 1) + 1 := by rw [h3]
    _ = 3 := by norm_num

/-! ## The real interface space `W_σ`

Span of the three active-type generators in `MvPolynomial (Fin 4) ℚ`.
By the finset-cardinality `finrank` bound, `dim W_σ ≤ 3`. The dormant
`transitionRight` template is `0`, hence automatically in the span via
`Submodule.zero_mem`.
-/

/-- **Real W_σ.** The ℚ-linear span of the three active type-signature
templates. This is the honest paper §9 Lemma 31 target space: a
genuine (non-vacuous) dim ≤ 3 subspace of `MvPolynomial (Fin 4) ℚ`
containing every type-signature polynomial. -/
noncomputable def realInterfaceSpace :
    Submodule ℚ (MvPolynomial (Fin wSigmaArity) ℚ) :=
  Submodule.span ℚ (activeTypeGenerators : Set (MvPolynomial (Fin wSigmaArity) ℚ))

/-- The real W_σ is finite-dimensional as a ℚ-module. -/
theorem realInterfaceSpace_finite :
    Module.Finite ℚ ↥realInterfaceSpace := by
  classical
  unfold realInterfaceSpace
  exact Module.Finite.span_of_finite ℚ activeTypeGenerators.finite_toSet

/-- **Paper §9 Lemma 31 (real W_σ form).** The real interface space
`W_σ = span ℚ { active type templates }` has dimension ≤ 3 in
`MvPolynomial (Fin 4) ℚ`.

Proof: direct application of `finrank_span_finset_le_card` to the
`activeTypeGenerators` finset (cardinality ≤ 3 by
`activeTypeGenerators_card_le_three`). -/
theorem realInterfaceSpace_finrank_le_three :
    Module.finrank ℚ ↥realInterfaceSpace ≤ 3 := by
  classical
  unfold realInterfaceSpace
  have h1 : Module.finrank ℚ
      (Submodule.span ℚ
        (activeTypeGenerators : Set (MvPolynomial (Fin wSigmaArity) ℚ)))
        ≤ activeTypeGenerators.card :=
    finrank_span_finset_le_card activeTypeGenerators
  exact h1.trans activeTypeGenerators_card_le_three

/-- Restatement with the paper constant `d_0 = 3`. -/
theorem realInterfaceSpace_finrank_le_d₀ :
    Module.finrank ℚ ↥realInterfaceSpace ≤ 3 :=
  realInterfaceSpace_finrank_le_three

/-! ## Membership of each type-signature polynomial in `W_σ`

Every `typeSignaturePolynomial τ` lies in `realInterfaceSpace`. Active
types via the span's generating set; the dormant `transitionRight` via
`Submodule.zero_mem`.
-/

/-- Each active-type template is a generator and hence in `W_σ`. -/
theorem booleanityTemplate_mem_realInterfaceSpace :
    booleanityTemplate ∈ realInterfaceSpace := by
  classical
  unfold realInterfaceSpace
  apply Submodule.subset_span
  unfold activeTypeGenerators
  -- `{a,b,c}` unfolds to `insert a (insert b {c})`; booleanity is the outer head.
  exact Finset.mem_coe.mpr (by
    show booleanityTemplate ∈
      ({booleanityTemplate, adjacencyTemplate, transitionTemplate} :
        Finset (MvPolynomial (Fin wSigmaArity) ℚ))
    exact Finset.mem_insert_self _ _)

theorem adjacencyTemplate_mem_realInterfaceSpace :
    adjacencyTemplate ∈ realInterfaceSpace := by
  classical
  unfold realInterfaceSpace
  apply Submodule.subset_span
  unfold activeTypeGenerators
  exact Finset.mem_coe.mpr (by
    show adjacencyTemplate ∈
      ({booleanityTemplate, adjacencyTemplate, transitionTemplate} :
        Finset (MvPolynomial (Fin wSigmaArity) ℚ))
    exact Finset.mem_insert_of_mem (Finset.mem_insert_self _ _))

theorem transitionTemplate_mem_realInterfaceSpace :
    transitionTemplate ∈ realInterfaceSpace := by
  classical
  unfold realInterfaceSpace
  apply Submodule.subset_span
  unfold activeTypeGenerators
  exact Finset.mem_coe.mpr (by
    show transitionTemplate ∈
      ({booleanityTemplate, adjacencyTemplate, transitionTemplate} :
        Finset (MvPolynomial (Fin wSigmaArity) ℚ))
    exact Finset.mem_insert_of_mem
      (Finset.mem_insert_of_mem (Finset.mem_singleton_self _)))

/-- Every type-signature polynomial is in `W_σ`, including the dormant
`transitionRight` case (via `Submodule.zero_mem`). -/
theorem typeSignaturePolynomial_mem_realInterfaceSpace
    (τ : ConstraintType) :
    typeSignaturePolynomial τ ∈ realInterfaceSpace := by
  cases τ with
  | booleanity => simpa using booleanityTemplate_mem_realInterfaceSpace
  | adjacency => simpa using adjacencyTemplate_mem_realInterfaceSpace
  | transitionLeft => simpa using transitionTemplate_mem_realInterfaceSpace
  | transitionRight =>
    show (0 : MvPolynomial (Fin wSigmaArity) ℚ) ∈ realInterfaceSpace
    exact Submodule.zero_mem realInterfaceSpace

/-! ## Shared-target variant indexed by `ConstraintType`

A `(τ : ConstraintType) → Submodule ℚ _` family, each equal to the
same `W_σ`. This matches the paper's "one W_σ per type σ" presentation
and gives dim ≤ 3 uniformly in `τ`.
-/

/-- Per-type interface space: the *same* `W_σ` for every `τ`. This is
the shared-target variant of `realInterfaceSpace`, exposing the Lemma 31
"W_σ per type σ" indexing. -/
noncomputable def realInterfaceSpacePerType (_τ : ConstraintType) :
    Submodule ℚ (MvPolynomial (Fin wSigmaArity) ℚ) :=
  realInterfaceSpace

theorem realInterfaceSpacePerType_finrank_le_three
    (τ : ConstraintType) :
    Module.finrank ℚ ↥(realInterfaceSpacePerType τ) ≤ 3 :=
  realInterfaceSpace_finrank_le_three

theorem typeSignaturePolynomial_mem_realInterfaceSpacePerType
    (τ : ConstraintType) :
    typeSignaturePolynomial τ ∈ realInterfaceSpacePerType τ :=
  typeSignaturePolynomial_mem_realInterfaceSpace τ

/-! ## Named hypothesis for downstream callers

The paper's §9 Lemma 31 proof says every compiled cookLevinQ factor
polynomial `1 - C_i` of type τ projects, under the compiled coefficient
basis, onto its type-signature polynomial. That projection step is
outside the scope of this file (it lives in the compiled-basis
infrastructure; see `PallLean.Paper93.CompiledCoefficientBasis`
and `PallLean.WithinProfileBound`). We expose the projection
compatibility as a named Prop so downstream callers can plug in a
concrete projection and obtain the cookLevinQ ⊆ W_σ conclusion.

This does **not** introduce any axioms: it is a `def`, not an `axiom`
or `sorry`. Its consumers must supply the hypothesis explicitly, which
is the honest "Route C ⇒ Route A" pattern described in the project
paper.
-/

/-- **Projection compatibility hypothesis.**

For a given projection `π : MvPolynomial (Fin N) ℚ → MvPolynomial (Fin 4) ℚ`
(the compiled-basis projection of paper §9), this predicate asserts that
every factor polynomial of type `τ` in the list `Fs` projects onto the
type signature `typeSignaturePolynomial τ`.

This is the *statement* of the compiled-basis projection lemma — not a
proof. Downstream callers provide a concrete projection and a proof of
this predicate, and then obtain `π (Fs.get i) ∈ realInterfaceSpace`
from `CookLevinProjectsToTypeSignature.mem_realInterfaceSpace`. -/
def CookLevinProjectsToTypeSignature
    {N : ℕ}
    (π : MvPolynomial (Fin N) ℚ → MvPolynomial (Fin wSigmaArity) ℚ)
    (Fs : List (MvPolynomial (Fin N) ℚ))
    (constraintType : Fin Fs.length → ConstraintType) : Prop :=
  ∀ i : Fin Fs.length, π (Fs.get i) = typeSignaturePolynomial (constraintType i)

/-- Consumer-facing consequence: under the projection compatibility
hypothesis, every projected factor lies in `realInterfaceSpace` (the
real W_σ). -/
theorem CookLevinProjectsToTypeSignature.mem_realInterfaceSpace
    {N : ℕ}
    {π : MvPolynomial (Fin N) ℚ → MvPolynomial (Fin wSigmaArity) ℚ}
    {Fs : List (MvPolynomial (Fin N) ℚ)}
    {constraintType : Fin Fs.length → ConstraintType}
    (h : CookLevinProjectsToTypeSignature π Fs constraintType)
    (i : Fin Fs.length) :
    π (Fs.get i) ∈ realInterfaceSpace := by
  rw [h i]
  exact typeSignaturePolynomial_mem_realInterfaceSpace (constraintType i)

/-- Per-type variant. -/
theorem CookLevinProjectsToTypeSignature.mem_realInterfaceSpacePerType
    {N : ℕ}
    {π : MvPolynomial (Fin N) ℚ → MvPolynomial (Fin wSigmaArity) ℚ}
    {Fs : List (MvPolynomial (Fin N) ℚ)}
    {constraintType : Fin Fs.length → ConstraintType}
    (h : CookLevinProjectsToTypeSignature π Fs constraintType)
    (i : Fin Fs.length) :
    π (Fs.get i) ∈ realInterfaceSpacePerType (constraintType i) := by
  rw [h i]
  exact typeSignaturePolynomial_mem_realInterfaceSpacePerType (constraintType i)

/-! ## Summary

  * `realInterfaceSpace` is a concrete (non-vacuous) dim ≤ 3 subspace of
    `MvPolynomial (Fin 4) ℚ`, unlike Agent 8's zero-generated placeholder.
  * Every `typeSignaturePolynomial τ` lies in this space (active types
    via explicit generators, dormant `transitionRight` via zero).
  * The cookLevinQ ⊆ W_σ conclusion (after compiled-basis projection) is
    exposed as the hypothesis `CookLevinProjectsToTypeSignature` and the
    consumer lemma `CookLevinProjectsToTypeSignature.mem_realInterfaceSpace`.

No axioms are introduced beyond the Lean kernel's; no `sorry` occurs.
-/

end PallLean.Paper93
