/-
  PallLean/Paper93/Unified/IterDerivSubmoduleUnified.lean

  Agent O1 (of 10, parallel) — Unified reconciliation of the two
  `iterDerivSubmodule` definitions in the `PallLean.Paper93.Spanning`
  namespace.

  ## Scope

  Prior to this file, two distinct definitions of `iterDerivSubmodule`
  coexisted in the `PallLean.Paper93.Spanning` namespace, with
  different argument orders and different constructive shapes:

    * `Paper93/Spanning/DerivativeClosure.lean` (Agent H4) —
        `iterDerivSubmodule (W : Submodule …) (S : List (Fin n))
            : Submodule …`
      defined as the iterated left-fold of `derivSubmodule`, matching
      the `iterDerivList` fold convention.  The fold shape exposes the
      finite-rank propagation lemma
      `iterDerivSubmodule_finrank_le` and the `Module.Finite` instance
      `iterDerivSubmodule_finite`, both of which are needed by the
      Route~C effective-dimension pipeline.

    * `Paper93/Spanning/PerDerivativeSpanning.lean` (Agent H5) —
        `iterDerivSubmodule_forH5 (S : List (Fin n)) (W : Submodule …)
            : Submodule …`
      (renamed from `iterDerivSubmodule` to disambiguate; see that
      file's docstring).  It is defined directly via `Submodule.span`
      on the image set `{iterDerivList S p | p ∈ W}`, which is the
      form most convenient for the H5 composition layer used by the
      per-type spanning agents.

  This file provides the reconciliation bridge between the two
  definitions:

    * `iterDerivSubmodule_forH5_le_iterDerivSubmodule` — the H5
        span-definition is contained in H4's fold-definition,
        uniformly in `(S, W)`;

    * `iterDerivSubmodule_le_iterDerivSubmodule_forH5` — the H4
        fold-definition is contained in the H5 span-definition;

    * `iterDerivSubmodule_eq_iterDerivSubmodule_forH5` — on any
        submodule `W`, the two definitions coincide as submodules of
        `MvPolynomial (Fin n) ℚ` (double inclusion); this is the
        "canonical" equivalence theorem.

  These bridges let a downstream file that imports both
  `Paper93/Spanning/DerivativeClosure.lean` and
  `Paper93/Spanning/PerDerivativeSpanning.lean` use whichever
  formulation is more convenient at each call site, and port
  membership / containment facts between the two forms without
  duplicating proof content.

  ## Faithfulness

  All content is standard linear algebra.  The forward direction
  (span ⊆ fold) uses that each generator `iterDerivList S p` for
  `p ∈ W` lies in the fold-definition by Agent H4's transport lemma
  `iterDerivList_mem_iterDerivSubmodule`, together with
  `Submodule.span_le`.  The reverse direction (fold ⊆ span) reduces
  to showing that each element of the fold arises as a
  `Submodule.span`-element, which follows by induction on the list
  `S` using the fact that `derivSubmodule W i` is generated by
  `{pderiv i f | f ∈ W}` and that `span` is closed under linear
  combinations.

  ## Kernel-only

    * No `sorry`.
    * No bespoke axioms; both directions route through
      `Submodule.span_le`, `Submodule.subset_span`, and the standard
      `Submodule.map` / `Submodule.comap` / `LinearMap` lemmas.
    * Verified by `lake build`.

  Expected `#print axioms`:  [propext, Classical.choice, Quot.sound].
-/
import PallLean.Paper93.Spanning.DerivativeClosure
import PallLean.Paper93.Spanning.PerDerivativeSpanning

namespace PallLean
namespace Paper93
namespace Unified

open MvPolynomial SPDP
open PallLean.Paper93.Spanning

/-! ## 0. `iterDerivList` as a `ℚ`-linear map

For the reverse inclusion, we need to move `iterDerivList rest` inside
`Submodule.span` membership via `Submodule.comap` of a `ℚ`-linear map
description of `iterDerivList rest`.  We provide that linear-map
description here. -/

/-- The `ℚ`-linear map realising `iterDerivList rest` as a linear
endomorphism of `MvPolynomial (Fin n) ℚ`, following the left-fold
convention.

Concretely: `iterDerivListLinearMap rest = foldl (fun L i =>
(pderiv i).toLinearMap.comp L) LinearMap.id rest`.

By `iterDerivListLinearMap_apply` below, this linear map agrees
pointwise with `iterDerivList rest` as a plain function.
-/
noncomputable def iterDerivListLinearMap {n : ℕ}
    (rest : List (Fin n)) :
    MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ :=
  rest.foldl
    (fun L i =>
      (MvPolynomial.pderiv (R := ℚ) i).toLinearMap.comp L)
    LinearMap.id

/-- "Fusion" lemma: for any starting accumulator `L0`, applying the
foldl along `rest` to `L0` at `x` equals applying the foldl from
`LinearMap.id` at `L0 x`.  This is the key mechanical fact about the
left-fold definition of `iterDerivListLinearMap`. -/
theorem iterDerivListLinearMap_fuse {n : ℕ} (rest : List (Fin n)) :
    ∀ (L0 : MvPolynomial (Fin n) ℚ →ₗ[ℚ] MvPolynomial (Fin n) ℚ)
      (x : MvPolynomial (Fin n) ℚ),
      (rest.foldl
        (fun L j => (MvPolynomial.pderiv (R := ℚ) j).toLinearMap.comp L)
        L0) x
      = (rest.foldl
          (fun L j => (MvPolynomial.pderiv (R := ℚ) j).toLinearMap.comp L)
          LinearMap.id) (L0 x) := by
  induction rest with
  | nil =>
    intro L0 x
    simp
  | cons j rest ih =>
    intro L0 x
    simp only [List.foldl_cons]
    -- LHS starts at `(pderiv j).toLinearMap.comp L0`;
    -- RHS starts at `(pderiv j).toLinearMap.comp LinearMap.id`.
    rw [ih ((MvPolynomial.pderiv (R := ℚ) j).toLinearMap.comp L0) x]
    rw [ih ((MvPolynomial.pderiv (R := ℚ) j).toLinearMap.comp LinearMap.id)
          (L0 x)]
    rfl

/-- The linear-map description agrees pointwise with the plain
function definition of `iterDerivList`. -/
@[simp] theorem iterDerivListLinearMap_apply {n : ℕ}
    (rest : List (Fin n)) (q : MvPolynomial (Fin n) ℚ) :
    iterDerivListLinearMap (n := n) rest q = iterDerivList rest q := by
  induction rest generalizing q with
  | nil =>
    simp [iterDerivListLinearMap, iterDerivList]
  | cons i rest ih =>
    -- Unfold one foldl step on each side.
    simp only [iterDerivListLinearMap, List.foldl_cons, iterDerivList]
    -- Now LHS:
    --   (rest.foldl (fun L j => (pderiv j).toLinearMap.comp L)
    --      ((pderiv i).toLinearMap.comp LinearMap.id)) q
    -- Apply fusion to move the starting accumulator out.
    rw [iterDerivListLinearMap_fuse rest
          ((MvPolynomial.pderiv (R := ℚ) i).toLinearMap.comp LinearMap.id) q]
    -- Simplify `((pderiv i).toLinearMap.comp LinearMap.id) q = pderiv i q`.
    simp only [LinearMap.comp_apply, LinearMap.id_apply]
    -- Apply IH at `q := pderiv i q`.
    have ih' := ih ((MvPolynomial.pderiv (R := ℚ) i) q)
    simp only [iterDerivListLinearMap] at ih'
    exact ih'

/-! ## 1. Forward direction: H5 span ⊆ H4 fold

The H5 span-definition of `iterDerivSubmodule_forH5 S W` is contained
in the H4 fold-definition `iterDerivSubmodule W S`, for every list
`S` and every submodule `W`.  The proof is direct: every generator
of the span, `iterDerivList S p` for `p ∈ W`, lies in
`iterDerivSubmodule W S` by Agent H4's transport lemma
`iterDerivList_mem_iterDerivSubmodule`. -/

/-- **Span ⊆ Fold.** The H5 span-definition is contained in the H4
fold-definition. -/
theorem iterDerivSubmodule_forH5_le_iterDerivSubmodule
    {n : ℕ}
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ))
    (S : List (Fin n)) :
    iterDerivSubmodule_forH5 S W ≤ iterDerivSubmodule W S := by
  -- `iterDerivSubmodule_forH5 S W = span { iterDerivList S p | p ∈ W }`.
  -- Apply `Submodule.span_le` and show each generator lies in
  -- the fold-definition.
  refine Submodule.span_le.mpr ?_
  rintro q ⟨p, hpW, rfl⟩
  -- `iterDerivList S p ∈ iterDerivSubmodule W S` by H4.
  exact iterDerivList_mem_iterDerivSubmodule W p hpW S

/-! ## 2. Reverse direction: H4 fold ⊆ H5 span

For the reverse inclusion, we induct on the list `S`.  At each cons
step, `iterDerivSubmodule W (i :: rest) =
iterDerivSubmodule (derivSubmodule W i) rest`.  By IH applied to
the submodule `derivSubmodule W i`, this is contained in
`iterDerivSubmodule_forH5 rest (derivSubmodule W i)`.  Every
generator of the latter is `iterDerivList rest q` for
`q ∈ derivSubmodule W i`.

We then use `Submodule.comap` through the linear map
`iterDerivListLinearMap rest` to move the goal
"`iterDerivList rest q ∈ iterDerivSubmodule_forH5 (i :: rest) W`"
into "`q ∈ (iterDerivSubmodule_forH5 (i :: rest) W).comap …`",
which lets us replace `q ∈ derivSubmodule W i` (= a span) by a check
on generators only. -/

/-- Auxiliary: the single-step derivative submodule `derivSubmodule W i`
is the `ℚ`-linear span of the set `{pderiv i f | f ∈ W}`.

This follows from `derivSubmodule W i = W.map (pderiv i).toLinearMap`
and the fact that the linear-map image of a submodule coincides with
the linear span of the underlying set image. -/
theorem derivSubmodule_eq_span {n : ℕ}
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ)) (i : Fin n) :
    derivSubmodule W i =
      Submodule.span ℚ
        { q : MvPolynomial (Fin n) ℚ |
          ∃ f : MvPolynomial (Fin n) ℚ, f ∈ W ∧
            q = MvPolynomial.pderiv (R := ℚ) i f } := by
  apply le_antisymm
  · -- `derivSubmodule W i ≤ span …`.
    -- Every element of `W.map (pderiv i)` is in the span of
    -- `{pderiv i f | f ∈ W}`.
    intro q hq
    -- `hq : q ∈ W.map (pderiv i).toLinearMap`
    unfold derivSubmodule at hq
    rcases hq with ⟨f, hfW, hfq⟩
    -- `hfq : ((pderiv i).toLinearMap) f = q`, i.e. `pderiv i f = q`.
    refine Submodule.subset_span ?_
    exact ⟨f, hfW, hfq.symm⟩
  · -- `span … ≤ derivSubmodule W i`.
    refine Submodule.span_le.mpr ?_
    rintro q ⟨f, hfW, rfl⟩
    -- `pderiv i f ∈ derivSubmodule W i` by H4's `pderiv_mem_derivSubmodule`.
    exact pderiv_mem_derivSubmodule W i hfW

/-- **Fold ⊆ Span.** The H4 fold-definition is contained in the H5
span-definition.

Proof by induction on `S`.  The key step is at the `cons` stage:
`iterDerivSubmodule W (i :: rest) =
iterDerivSubmodule (derivSubmodule W i) rest`.  By IH applied to
the submodule `derivSubmodule W i`, this is contained in
`iterDerivSubmodule_forH5 rest (derivSubmodule W i)`.  We then move
the outer `iterDerivList rest` across a `Submodule.comap` of
`iterDerivListLinearMap rest`, reducing to a generator check that
uses `derivSubmodule_eq_span`. -/
theorem iterDerivSubmodule_le_iterDerivSubmodule_forH5
    {n : ℕ}
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ))
    (S : List (Fin n)) :
    iterDerivSubmodule W S ≤ iterDerivSubmodule_forH5 S W := by
  induction S generalizing W with
  | nil =>
    -- `iterDerivSubmodule W [] = W` and
    -- `iterDerivSubmodule_forH5 [] W = span {iterDerivList [] p | p ∈ W}
    --  ⊇ W` (each `w ∈ W` is the generator at `p := w`).
    intro q hqW
    refine Submodule.subset_span ?_
    refine ⟨q, hqW, ?_⟩
    -- `iterDerivList [] q = q` by definition (`foldl` on `[]`).
    simp [iterDerivList]
  | cons i rest ih =>
    -- `iterDerivSubmodule W (i :: rest)
    --    = iterDerivSubmodule (derivSubmodule W i) rest`.
    rw [iterDerivSubmodule_cons]
    -- IH at `W := derivSubmodule W i` gives the containment into
    -- `iterDerivSubmodule_forH5 rest (derivSubmodule W i)`.
    refine le_trans (ih (derivSubmodule W i)) ?_
    -- Show
    --   `iterDerivSubmodule_forH5 rest (derivSubmodule W i)
    --      ≤ iterDerivSubmodule_forH5 (i :: rest) W`.
    -- Unfold the span on LHS and handle each generator.
    refine Submodule.span_le.mpr ?_
    rintro q ⟨p, hp_in_deriv, rfl⟩
    -- `p ∈ derivSubmodule W i`, i.e. `p = pderiv i f` for some
    -- `f ∈ W` (by `derivSubmodule_eq_span`).
    rw [derivSubmodule_eq_span] at hp_in_deriv
    -- Target submodule (via `Submodule.comap`) to move
    -- `iterDerivList rest` out of the membership claim.
    let target : Submodule ℚ (MvPolynomial (Fin n) ℚ) :=
      (iterDerivSubmodule_forH5 (i :: rest) W).comap
        (iterDerivListLinearMap (n := n) rest)
    -- Reformulate the goal as `p ∈ target` via the linear-map
    -- description of `iterDerivList rest`.
    suffices hpTarget : p ∈ target by
      -- `target` membership unfolds to
      --   `iterDerivListLinearMap rest p ∈ iterDerivSubmodule_forH5 (i :: rest) W`
      -- which by `iterDerivListLinearMap_apply` is
      --   `iterDerivList rest p ∈ iterDerivSubmodule_forH5 (i :: rest) W`.
      have : iterDerivListLinearMap (n := n) rest p
          ∈ iterDerivSubmodule_forH5 (i :: rest) W := hpTarget
      rwa [iterDerivListLinearMap_apply] at this
    -- Prove span membership by checking each generator lies in `target`.
    refine (Submodule.span_le.mpr ?_) hp_in_deriv
    rintro q ⟨f, hfW, rfl⟩
    -- Goal (unfolded): `pderiv i f ∈ target`, i.e.
    --   `iterDerivListLinearMap rest (pderiv i f)
    --     ∈ iterDerivSubmodule_forH5 (i :: rest) W`.
    show iterDerivListLinearMap (n := n) rest
          (MvPolynomial.pderiv (R := ℚ) i f)
        ∈ iterDerivSubmodule_forH5 (i :: rest) W
    rw [iterDerivListLinearMap_apply]
    -- `iterDerivList rest (pderiv i f) = iterDerivList (i :: rest) f`
    -- by the `foldl_cons` unfolding.
    refine Submodule.subset_span ?_
    refine ⟨f, hfW, ?_⟩
    simp [iterDerivList, List.foldl_cons]

/-! ## 3. The two definitions agree

Combining the two inclusions, the H4 fold-definition and the H5
span-definition describe the same submodule of
`MvPolynomial (Fin n) ℚ`. -/

/-- **Unified equivalence.** The H5 span-definition and the H4
fold-definition agree. -/
theorem iterDerivSubmodule_eq_iterDerivSubmodule_forH5
    {n : ℕ}
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ))
    (S : List (Fin n)) :
    iterDerivSubmodule_forH5 S W = iterDerivSubmodule W S :=
  le_antisymm
    (iterDerivSubmodule_forH5_le_iterDerivSubmodule W S)
    (iterDerivSubmodule_le_iterDerivSubmodule_forH5 W S)

/-! ## 4. Transport lemmas across the equivalence

Convenience wrappers that port a membership fact from one form to the
other.  These are the single-call bridges downstream files can use
when they have one form but need the other. -/

/-- Transport: membership in H5 span form implies membership in H4 fold
form. -/
theorem mem_iterDerivSubmodule_of_forH5 {n : ℕ}
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ))
    (S : List (Fin n))
    {q : MvPolynomial (Fin n) ℚ}
    (hq : q ∈ iterDerivSubmodule_forH5 S W) :
    q ∈ iterDerivSubmodule W S :=
  iterDerivSubmodule_forH5_le_iterDerivSubmodule W S hq

/-- Transport: membership in H4 fold form implies membership in H5 span
form. -/
theorem mem_iterDerivSubmodule_forH5_of_fold {n : ℕ}
    (W : Submodule ℚ (MvPolynomial (Fin n) ℚ))
    (S : List (Fin n))
    {q : MvPolynomial (Fin n) ℚ}
    (hq : q ∈ iterDerivSubmodule W S) :
    q ∈ iterDerivSubmodule_forH5 S W :=
  iterDerivSubmodule_le_iterDerivSubmodule_forH5 W S hq

/-! ## 5. Kernel-only axiom trace -/

#print axioms iterDerivListLinearMap_apply
#print axioms iterDerivSubmodule_forH5_le_iterDerivSubmodule
#print axioms iterDerivSubmodule_le_iterDerivSubmodule_forH5
#print axioms iterDerivSubmodule_eq_iterDerivSubmodule_forH5
#print axioms mem_iterDerivSubmodule_of_forH5
#print axioms mem_iterDerivSubmodule_forH5_of_fold

end Unified
end Paper93
end PallLean
