import PallLean.Paper93.DeepMath.PathC.PiPlusNormalizedLeibnizBridge

/-!
# Reducing normalized row-span to a polynomial-level derivative span

The normalized Leibniz payload currently quantifies over SPDP rows
`mlProj (m * iterDerivList S (...))`.  This file removes the multiplier/projection
noise from that obligation: it is enough to prove the polynomial-level statement
that each derivative of the Boolean-normalized transformed constraint product
lies in the ordinary distributed Leibniz span of the unnormalized transformed
local-factor product.

The proof is purely linear algebra via `mlProj_mul_mem_span_image`.
-/

namespace PallLean.Paper93.DeepMath.PathC

open MvPolynomial
open SPDP
open MultilinearSPDP
open PallLean.Paper93.DeepMath.PathB
open PaperFaithfulSeparation
open TuringMachine
open LeibnizProduct

attribute [local instance] Classical.dec
set_option exponentiation.threshold 1000

/-- Polynomial-level normalized derivative span.  This is the sharper remaining
normalization seam: derivatives of the Boolean normal form of the transformed
constraint product should lie in the ordinary Leibniz span generated by
distributed derivatives of the transformed factors. -/
def PiPlusBooleanProjectedNormalizedDerivativePolynomialSpan
    (M : DTM) (n : Nat) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (D : PiPlusSATBlockCoordinateData M n hn2 htb hns) : Prop :=
  ∀ (S : List (Fin (cook_levin_compilation M n hn2 htb hns).numVars)),
    S.length = Nat.log 2 n →
    isBlockAdmissible (cook_levin_compilation M n hn2 htb hns).partition S →
    iterDerivList S
      (zeroProfileBooleanNormalize
        (piPlusBooleanProjectedTransformedConstraintFactors
          M n hn2 htb hns D).prod) ∈
      Submodule.span ℚ
        (distribDerivProds Finset.univ
          (fun i : Fin (piPlusBooleanProjectedTransformedConstraintFactors
              M n hn2 htb hns D).length =>
            (piPlusBooleanProjectedTransformedConstraintFactors
              M n hn2 htb hns D)[i.val]) S)

/-- The polynomial-level normalized derivative span implies the row-level
normalized Leibniz span consumed by the Route-C P-side classifier bridge. -/
theorem normalizedTransformedLeibnizRowSpan_of_polynomialSpan
    (M : DTM) (n : Nat) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (D : PiPlusSATBlockCoordinateData M n hn2 htb hns)
    (hpoly : PiPlusBooleanProjectedNormalizedDerivativePolynomialSpan
      M n hn2 htb hns D) :
    PiPlusBooleanProjectedNormalizedTransformedLeibnizRowSpan
      M n hn2 htb hns D := by
  intro S m hSlen _hmdeg _hmvars hadm
  exact SymmetricPower.mlProj_mul_mem_span_image m _ _
    (hpoly S hSlen hadm)

/-- Paper-scale polynomial-level normalized derivative span. -/
abbrev PaperScalePiPlusBooleanProjectedNormalizedDerivativePolynomialSpan
    (M : DTM) (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ 2 ^ 804) : Prop :=
  PiPlusBooleanProjectedNormalizedDerivativePolynomialSpan
    M (2 ^ 804) paperScale_ge_two htb hns
    (cookLevinPiPlusBlockCoordinateData_paperScale M htb hns)

/-- Paper-scale row-level normalized span from the polynomial-level statement. -/
theorem paperScale_normalizedTransformedLeibnizRowSpan_of_polynomialSpan
    (M : DTM) (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ 2 ^ 804)
    (hpoly : PaperScalePiPlusBooleanProjectedNormalizedDerivativePolynomialSpan
      M htb hns) :
    PaperScalePiPlusBooleanProjectedNormalizedTransformedLeibnizRowSpan
      M htb hns :=
  normalizedTransformedLeibnizRowSpan_of_polynomialSpan
    M (2 ^ 804) paperScale_ge_two htb hns
    (cookLevinPiPlusBlockCoordinateData_paperScale M htb hns) hpoly

/-- Paper-scale P-side row-span classifier from the sharper polynomial-level
normalization span plus the transformed-generator pullback payload. -/
theorem paperScale_factoredRowSpanClassifierOneZero_of_polynomialSpan_and_generatorPullback
    (M : DTM) (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ 2 ^ 804)
    (hpoly : PaperScalePiPlusBooleanProjectedNormalizedDerivativePolynomialSpan
      M htb hns)
    (hpull : PaperScalePiPlusBooleanProjectedTransformedLeibnizGeneratorPullbackOneZero
      M htb hns) :
    PaperScalePiPlusBooleanProjectedFactoredRowSpanClassifierOneZero M htb hns :=
  paperScale_factoredRowSpanClassifierOneZero_of_normalizedTransformedLeibniz
    M htb hns
    (paperScale_normalizedTransformedLeibnizRowSpan_of_polynomialSpan
      M htb hns hpoly)
    hpull

/-! ## Axiom audit anchors -/

#print axioms normalizedTransformedLeibnizRowSpan_of_polynomialSpan
#print axioms paperScale_normalizedTransformedLeibnizRowSpan_of_polynomialSpan
#print axioms paperScale_factoredRowSpanClassifierOneZero_of_polynomialSpan_and_generatorPullback

end PallLean.Paper93.DeepMath.PathC
