import PallLean.Paper93.DeepMath.PathC.PiPlusBoundaryProject
import PallLean.Paper93.CanonicalizationMap
import PallLean.Paper93.RowSpanPreservation

/-!
# Route W1: canonical-window quotient interface

Paper-faithfulness correction for Route W.

Operationally, `Π+` is an invertible block-local basis change.  It is not the
quotient map responsible for the shared `W_τ` profile spaces.  Likewise,
Boolean normalization / multilinearization is a separate quotient operation
(`Xᵢ^k = Xᵢ`) and should not be identified with paper Definition 20.

The paper-faithful quotient/identification object for the `W_τ` compression is
`can(·) : Win_κ → Win_κ`:

* (P6) disjoint-support adjacent swaps;
* (P7) local update-word normal form;
* Lemma 26: `row(w) = row(can(w))` and hence row spans are generated by
  canonical windows.

This file connects the existing abstract `CanonicalizationMap` and
`RowSpanPreservation` APIs to the Route-W story.  It does not yet construct the
Cook--Levin concrete `(P6)/(P7)` scheme; it records the exact kernel-clean
socket that must be instantiated next.
-/

namespace PallLean.Paper93.DeepMath.PathC

open PallLean.Paper93
open Submodule

attribute [local instance] Classical.dec

/-- The paper-faithful Route-W quotient data lives on window indices, not on the
ambient polynomial ring.  A concrete Cook--Levin instance must provide:

* a canonicalization scheme `scheme` implementing Definition 20;
* the P6 adjacent-disjoint-swap relation;
* the P7 local normal-form substitution;
* a row map into the target module;
* Lemma-26 row invariance for that row map.

Once supplied, the generic theorems below give idempotence and row-span
preservation for the canonical-window quotient. -/
structure CanonicalWindowRouteWData
    (κ : ℕ) (BlockIdx LocalOp V : Type)
    [Fintype BlockIdx] [DecidableEq BlockIdx]
    [Fintype LocalOp] [DecidableEq LocalOp]
    [LinearOrder (BlockIdx × LocalOp)]
    [AddCommGroup V] [Module ℚ V] where
  scheme : CanonScheme (BlockIdx := BlockIdx) (LocalOp := LocalOp) κ
  IsAdjacentSwapDisjoint :
    Win κ BlockIdx LocalOp → Win κ BlockIdx LocalOp → Prop
  substNF : Win κ BlockIdx LocalOp → Win κ BlockIdx LocalOp
  row : Win κ BlockIdx LocalOp → V
  row_function :
    RowFunction (κ := κ) (BlockIdx := BlockIdx) (LocalOp := LocalOp)
      IsAdjacentSwapDisjoint substNF
      (fun w => canWindow (κ := κ) scheme w) row

namespace CanonicalWindowRouteWData

variable {κ : ℕ} {BlockIdx LocalOp V : Type}
variable [Fintype BlockIdx] [DecidableEq BlockIdx]
variable [Fintype LocalOp] [DecidableEq LocalOp]
variable [LinearOrder (BlockIdx × LocalOp)]
variable [AddCommGroup V] [Module ℚ V]

/-- The Route-W canonical-window map associated to a data package. -/
def projectWindow
    (D : CanonicalWindowRouteWData κ BlockIdx LocalOp V) :
    Win κ BlockIdx LocalOp → Win κ BlockIdx LocalOp :=
  fun w => canWindow (κ := κ) D.scheme w

/-- Paper Definition 20 idempotence: canonicalizing twice is the same as
canonicalizing once. -/
theorem projectWindow_idempotent
    (D : CanonicalWindowRouteWData κ BlockIdx LocalOp V)
    (w : Win κ BlockIdx LocalOp) :
    D.projectWindow (D.projectWindow w) = D.projectWindow w := by
  exact canWindow_idempotent (κ := κ) D.scheme w

/-- Pointwise Lemma-26 row preservation for the Route-W canonical-window
quotient. -/
theorem row_eq_projectWindow_row
    (D : CanonicalWindowRouteWData κ BlockIdx LocalOp V)
    (w : Win κ BlockIdx LocalOp) :
    D.row w = D.row (D.projectWindow w) := by
  exact row_eq_canRow
    (κ := κ) (BlockIdx := BlockIdx) (LocalOp := LocalOp)
    D.IsAdjacentSwapDisjoint D.substNF
    (fun w => canWindow (κ := κ) D.scheme w)
    D.row D.row_function w

/-- Span-level Lemma 26: Route-W row spans may be indexed by canonical windows.
This is the paper-faithful quotient/identification statement that should feed
the `W_τ` profile compression, rather than treating `Π+` or Boolean
normalization as the canonical-window quotient. -/
theorem rowSpan_eq_projectWindowRowSpan
    (D : CanonicalWindowRouteWData κ BlockIdx LocalOp V) :
    Submodule.span ℚ (Set.range D.row) =
      Submodule.span ℚ (Set.range (D.row ∘ D.projectWindow)) := by
  exact rowSpan_eq_canRowSpan
    (κ := κ) (BlockIdx := BlockIdx) (LocalOp := LocalOp)
    D.IsAdjacentSwapDisjoint D.substNF
    (fun w => canWindow (κ := κ) D.scheme w)
    D.row D.row_function

/-- Set-level version of the same canonical-window reduction. -/
theorem range_eq_range_comp_projectWindow
    (D : CanonicalWindowRouteWData κ BlockIdx LocalOp V) :
    Set.range D.row = Set.range (D.row ∘ D.projectWindow) := by
  exact range_eq_range_comp_canWindow
    (κ := κ) (BlockIdx := BlockIdx) (LocalOp := LocalOp)
    D.IsAdjacentSwapDisjoint D.substNF
    (fun w => canWindow (κ := κ) D.scheme w)
    D.row D.row_function

end CanonicalWindowRouteWData

/-- Route-W1 concrete frontier: instantiate `CanonicalWindowRouteWData` for the
Cook--Levin SPDP row map.  This is intentionally a proposition/socket, not a
fake construction. -/
def CookLevinCanonicalWindowRouteWFrontier
    (κ : ℕ) (BlockIdx LocalOp V : Type)
    [Fintype BlockIdx] [DecidableEq BlockIdx]
    [Fintype LocalOp] [DecidableEq LocalOp]
    [LinearOrder (BlockIdx × LocalOp)]
    [AddCommGroup V] [Module ℚ V] : Prop :=
  Nonempty (CanonicalWindowRouteWData κ BlockIdx LocalOp V)

/-! ## Axiom audit anchors -/

#print axioms CanonicalWindowRouteWData.projectWindow_idempotent
#print axioms CanonicalWindowRouteWData.row_eq_projectWindow_row
#print axioms CanonicalWindowRouteWData.rowSpan_eq_projectWindowRowSpan
#print axioms CanonicalWindowRouteWData.range_eq_range_comp_projectWindow

end PallLean.Paper93.DeepMath.PathC
