import PallLean.Paper93.DeepMath.PathC.PiPlusRestFactorHarmless
import PallLean.Paper93.DeepMath.PathC.PiPlusBooleanProjectedRawPullbackCriterion

/-!
# Factored row-span classifier closeout bridges

The product-level Route-C P-side target is now the factored row-span classifier.
This file gives the sharp bridge from an exact Boolean-projected raw-pullback
row certificate to that classifier, with the one-extra-derivative / zero-extra-
multiplier budget used at paper scale.

This does not assert the remaining product algebra for free: the exact row
certificate is still the hard local/product commutation statement.  What it
proves is that once the Booleanity × rest Leibniz transport is expressed as row
pullbacks, the current factored classifier and all existing P-side compiled
sockets close immediately.
-/

namespace PallLean.Paper93.DeepMath.PathC

open MvPolynomial
open SPDP
open MultilinearSPDP
open PallLean.Paper93.DeepMath.PathB
open PaperFaithfulSeparation
open TuringMachine

attribute [local instance] Classical.dec
set_option exponentiation.threshold 1000

/-- An exact raw-pullback row certificate for the Boolean-projected `Pi+` action
implies the factored row-span classifier.  The classifier can take the singleton
span generated by the target row itself; the row certificate identifies its raw
`Pi+⁻¹` pullback with an ordinary source SPDP row, and the inclusive window
absorbs the requested extra budgets. -/
theorem factoredRowSpanClassifier_of_rawPullbackRowCertificate
    (extraK extraL : Nat)
    (M : DTM) (n : Nat) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (piP : PiPlusSATTransform M n hn2 htb hns)
    (hrow : PiPlusBooleanProjectedRawPullbackRowCertificate
      M n hn2 htb hns piP) :
    PiPlusBooleanProjectedFactoredRowSpanClassifier
      extraK extraL M n hn2 htb hns piP := by
  intro S m hSlen hmdeg hmvars hadm
  let target : SATDeciderGaugeSpace M n hn2 htb hns :=
    mlProj (m * iterDerivList S
      (piPlusBooleanProjectedGauge M n hn2 htb hns piP
        (cookLevinFactoredPoly M n)))
  refine ⟨{target}, ?_, ?_⟩
  · exact Submodule.subset_span (by simp [target])
  · intro q hq
    have hqeq : q = target := by simpa using hq
    subst q
    rcases hrow (Nat.log 2 n) (Nat.log 2 n) (cookLevinFactoredPoly M n)
      S m hSlen hmdeg hmvars hadm with ⟨m', hmdeg', hmvars', hpull⟩
    rw [hpull]
    exact Submodule.subset_span
      ⟨S, m', by omega, by omega, hmvars', hadm, rfl⟩

/-- Paper-scale specialization: the old exact row-certificate target is strong
enough to close the new one-extra-derivative factored row-span classifier. -/
theorem paperScale_factoredRowSpanClassifierOneZero_of_rawPullbackRowCertificate
    (M : DTM) (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ 2 ^ 804)
    (hrow : PaperScalePiPlusBooleanProjectedRawPullbackRowCertificate
      M htb hns) :
    PaperScalePiPlusBooleanProjectedFactoredRowSpanClassifierOneZero
      M htb hns :=
  factoredRowSpanClassifier_of_rawPullbackRowCertificate
    1 0 M (2 ^ 804) paperScale_ge_two htb hns
    (cookLevinPiPlusSATTransform_paperScale M htb hns) hrow

/-- Consequently the exact row certificate closes the paper-scale compiled
raw-pullback membership socket through the new factored classifier route. -/
theorem paperScale_windowedCompiledRawPullbackMembershipOneZero_of_rawPullbackRowCertificate
    (M : DTM) (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ 2 ^ 804)
    (hrow : PaperScalePiPlusBooleanProjectedRawPullbackRowCertificate
      M htb hns) :
    PaperScalePiPlusBooleanProjectedWindowedCompiledRawPullbackMembershipOneZero
      M htb hns :=
  paperScale_windowedCompiledRawPullbackMembershipOneZero_of_rowSpanClassifier
    M htb hns
    (paperScale_factoredRowSpanClassifierOneZero_of_rawPullbackRowCertificate
      M htb hns hrow)

/-- And it closes the compiled P-subspace inclusion socket used by the final
Route-C bridge. -/
theorem paperScale_compiledPSubspaceInclusionOneZero_of_rawPullbackRowCertificate
    (M : DTM) (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ 2 ^ 804)
    (hrow : PaperScalePiPlusBooleanProjectedRawPullbackRowCertificate
      M htb hns) :
    PaperScalePiPlusBooleanProjectedCompiledPSubspaceInclusionOneZero
      M htb hns :=
  paperScale_compiledPSubspaceInclusionOneZero_of_rowSpanClassifier
    M htb hns
    (paperScale_factoredRowSpanClassifierOneZero_of_rawPullbackRowCertificate
      M htb hns hrow)

/-- A factored compiled-row certificate also implies the factored row-span
classifier directly.  This is the product-specific version of the bridge above:
for each target row, use the singleton span generated by that row, then discharge
its raw pullback using the exact factored source row supplied by the certificate.
-/
theorem factoredRowSpanClassifier_of_factoredCompiledRowCertificate
    (extraK extraL : Nat)
    (M : DTM) (n : Nat) (hn2 : n ≥ 2)
    (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ n)
    (piP : PiPlusSATTransform M n hn2 htb hns)
    (hrow : PiPlusBooleanProjectedWindowedFactoredCompiledRowCertificate
      extraK extraL M n hn2 htb hns piP) :
    PiPlusBooleanProjectedFactoredRowSpanClassifier
      extraK extraL M n hn2 htb hns piP := by
  intro S m hSlen hmdeg hmvars hadm
  let target : SATDeciderGaugeSpace M n hn2 htb hns :=
    mlProj (m * iterDerivList S
      (piPlusBooleanProjectedGauge M n hn2 htb hns piP
        (cookLevinFactoredPoly M n)))
  refine ⟨{target}, ?_, ?_⟩
  · exact Submodule.subset_span (by simp [target])
  · intro q hq
    have hqeq : q = target := by simpa using hq
    subst q
    rcases hrow S m hSlen hmdeg hmvars hadm with
      ⟨κ', ℓ', S', m', hκ', hℓ', hSlen', hmdeg', hmvars', hadm', hpull⟩
    rw [hpull]
    exact Submodule.subset_span
      ⟨S', m', by rwa [hSlen'], le_trans hmdeg' hℓ', hmvars', hadm', rfl⟩

/-- Paper-scale product-specific bridge from the exact factored row certificate
to the one-zero factored row-span classifier. -/
theorem paperScale_factoredRowSpanClassifierOneZero_of_factoredCompiledRowCertificate
    (M : DTM) (htb : M.timeBound ≤ 4) (hns : M.numStates ≤ 2 ^ 804)
    (hrow : PaperScalePiPlusBooleanProjectedFactoredCompiledRowCertificateOneZero
      M htb hns) :
    PaperScalePiPlusBooleanProjectedFactoredRowSpanClassifierOneZero
      M htb hns :=
  factoredRowSpanClassifier_of_factoredCompiledRowCertificate
    1 0 M (2 ^ 804) paperScale_ge_two htb hns
    (cookLevinPiPlusSATTransform_paperScale M htb hns) hrow

/-! ## Axiom audit anchors -/

#print axioms factoredRowSpanClassifier_of_rawPullbackRowCertificate
#print axioms factoredRowSpanClassifier_of_factoredCompiledRowCertificate
#print axioms paperScale_factoredRowSpanClassifierOneZero_of_factoredCompiledRowCertificate
#print axioms paperScale_factoredRowSpanClassifierOneZero_of_rawPullbackRowCertificate
#print axioms paperScale_windowedCompiledRawPullbackMembershipOneZero_of_rawPullbackRowCertificate
#print axioms paperScale_compiledPSubspaceInclusionOneZero_of_rawPullbackRowCertificate

end PallLean.Paper93.DeepMath.PathC
