import GodMoveRationalClearing

/-!
# Explicit binary serialization of cleared integer coefficients

Little-endian magnitude bits and a separate sign bit represent each supplied
integer. Exact reconstruction requires a stated width bound. Applied to the
denominator-clearing construction, a supplied rational precision budget gives
an explicit polynomial bound on the returned coefficient bit payload.

This is serialization of supplied coefficients, not a precision bound for
coefficients generated by the adaptive row-space algorithm.
-/

namespace GodMoveSignedBinary

open GodMoveRationalClearing

def bitsValue : List Bool → ℕ
  | [] => 0
  | b :: bs => b.toNat + 2 * bitsValue bs

def bitsOf : ℕ → ℕ → List Bool
  | 0, _ => []
  | width + 1, value => decide (value % 2 = 1) :: bitsOf width (value / 2)

theorem bitsOf_length (width value : ℕ) : (bitsOf width value).length = width := by
  induction width generalizing value with
  | zero => rfl
  | succ width ih => simp [bitsOf, ih]

theorem bitsOf_value (width value : ℕ) (hvalue : value < 2 ^ width) :
    bitsValue (bitsOf width value) = value := by
  induction width generalizing value with
  | zero =>
      simp only [pow_zero] at hvalue
      have hz : value = 0 := by omega
      simp [bitsOf, bitsValue, hz]
  | succ width ih =>
      have hdiv : value / 2 < 2 ^ width := by
        apply (Nat.div_lt_iff_lt_mul (by decide : 0 < 2)).mpr
        simpa [pow_succ, Nat.mul_comm] using hvalue
      have hbit : (decide (value % 2 = 1)).toNat = value % 2 := by
        have hm := Nat.mod_lt value (by decide : 0 < 2)
        by_cases h : value % 2 = 1
        · simp [h]
        · have hz : value % 2 = 0 := by omega
          simp [hz]
      rw [bitsOf, bitsValue, ih _ hdiv, hbit]
      omega

structure SignedBits where
  negative : Bool
  bits : List Bool
deriving Repr, DecidableEq

def signedValue (z : SignedBits) : ℤ :=
  if z.negative then -(bitsValue z.bits : ℤ) else (bitsValue z.bits : ℤ)

def encodeInt (width : ℕ) (value : ℤ) : SignedBits :=
  ⟨decide (value < 0), bitsOf width value.natAbs⟩

theorem encodeInt_length (width : ℕ) (value : ℤ) :
    (encodeInt width value).bits.length = width := bitsOf_length _ _

theorem encodeInt_value (width : ℕ) (value : ℤ) (hvalue : value.natAbs < 2 ^ width) :
    signedValue (encodeInt width value) = value := by
  unfold signedValue encodeInt
  rw [bitsOf_value width value.natAbs hvalue]
  by_cases h : value < 0
  · simp [h, Int.ofNat_natAbs_of_nonpos (le_of_lt h)]
  · simp [h, Int.ofNat_natAbs_of_nonneg (le_of_not_gt h)]

def coefficientWidth (s b : ℕ) : ℕ := (s + 1) * b + 1

def encodedClearedWeights {s : ℕ} (q : Fin s → ℚ) (b : ℕ) : Fin s → SignedBits :=
  fun i => encodeInt (coefficientWidth s b) (clearedWeights q i)

theorem encodedClearedWeights_value {s : ℕ} (q : Fin s → ℚ) (b : ℕ)
    (hb : CoeffPrecision q b) (i : Fin s) :
    signedValue (encodedClearedWeights q b i) = clearedWeights q i :=
  encodeInt_value _ _ (clearedWeights_fit q b hb i)

/-- Count one explicit sign bit and all magnitude bits for every weight. -/
def coefficientPayload {s : ℕ} (weights : Fin s → SignedBits) : ℕ :=
  ∑ i, ((weights i).bits.length + 1)

theorem encodedClearedWeights_payload {s : ℕ} (q : Fin s → ℚ) (b : ℕ) :
    coefficientPayload (encodedClearedWeights q b) = s * ((s + 1) * b + 2) := by
  simp [coefficientPayload, encodedClearedWeights, encodeInt_length, coefficientWidth,
    Nat.mul_comm, Nat.add_assoc]

end GodMoveSignedBinary

#print axioms GodMoveSignedBinary.bitsOf_length
#print axioms GodMoveSignedBinary.bitsOf_value
#print axioms GodMoveSignedBinary.encodeInt_value
#print axioms GodMoveSignedBinary.encodedClearedWeights_value
#print axioms GodMoveSignedBinary.encodedClearedWeights_payload
