import PallLean.ProfileAssemblyReduction

/-!
# AssemblyMapReduction

This file reduces the remaining verifier profile assembly theorem to a finite multilinear
product-image theorem.

The intended paper-faithful picture is:

* each profile chooses one local clause-factor image space per clause;
* multiplication of those local pieces lands in the corresponding verifier profile slice;
* the slice is contained in the image/span of that finite product assembly.

Once that assembly-image theorem is proved, the previously formalized reduction pipeline
finishes the verifier-side polynomial rank bound.
-/

namespace AssemblyMapReduction

open SPDP
open MultilinearSPDP
open Tseitin
open LocalFactorReduction
open LocalClauseFactorSpace
open ProfileAssemblyReduction
open MvPolynomial

variable {F : Type*} [Field F] [Nontrivial F]

/-- The concrete local space chosen by a profile at clause `i`. -/
noncomputable def profileLocalSpace
    (Φ : TseitinFormula)
    (ρ : ProfileIndex Φ.clauses.length 4)
    (i : Fin Φ.clauses.length) :
    Submodule F (MvPolynomial (Fin (tseitinNumVars Φ)) F) :=
  (verifierLocalFactorSpaceFamily (F := F) Φ) i (ρ i)

/-- Abstract assembly target space for a fixed profile. -/
def ProfileAssemblyTarget
    (Φ : TseitinFormula)
    (ρ : ProfileIndex Φ.clauses.length 4) : Type :=
  ∀ i : Fin Φ.clauses.length, profileLocalSpace (F := F) Φ ρ i

/--
Abstract multilinear assembly theorem.

Interpretation:
- a profile slice is contained in the image/span generated by multiplying one vector from each
  local clause-factor image space chosen by the profile.
-/
def ProfileSliceAssemblesFromLocalProduct
    (Φ : TseitinFormula)
    (κ : ℕ)
    (shift : MvPolynomial (Fin (tseitinNumVars Φ)) F)
    (S : List (Fin (tseitinNumVars Φ)))
    (hS : S.length = κ)
    (ρ : ProfileIndex Φ.clauses.length 4) : Prop :=
  ∃ W : Submodule F (MvPolynomial (Fin (tseitinNumVars Φ)) F),
    profileSliceSubspace (F := F) (κ := κ) (m := Φ.clauses.length) (w := 4)
      shift (verifierFactor (F := F) Φ) S hS ρ ≤ W ∧
    Module.finrank F W ≤ profileLocalDimProduct (F := F) Φ (verifierLocalFactorDimFamily (F := F) Φ) ρ

/--
If every profile slice assembles from the local product in the above sense, then the concrete
verifier profile assembly theorem follows.
-/
theorem verifierProfileAssembly_of_sliceAssembly
    (Φ : TseitinFormula)
    (κ : ℕ)
    (hlocalDims : ∀ (c : Fin Φ.clauses.length) (k : Fin 5),
      Module.finrank F ((verifierLocalFactorSpaceFamily (F := F) Φ) c k)
        ≤ (verifierLocalFactorDimFamily (F := F) Φ) c k)
    (hassembly : ∀ (shift : MvPolynomial (Fin (tseitinNumVars Φ)) F)
      (S : List (Fin (tseitinNumVars Φ)))
      (hS : S.length = κ)
      (ρ : ProfileIndex Φ.clauses.length 4),
      ProfileSliceAssemblesFromLocalProduct (F := F) Φ κ shift S hS ρ) :
    VerifierProfileAssemblyTheorem (F := F) Φ κ := by
  intro shift S hS ρ
  rcases hassembly shift S hS ρ with ⟨W, hsub, hW⟩
  refine ⟨W, hsub, ?_, hW⟩
  intro i
  exact hlocalDims i (ρ i)

end AssemblyMapReduction
