import PallLean.LocalFactorReduction
import Mathlib.LinearAlgebra.Dimension.Finrank

/-!
# LocalClauseFactorSpace

Concrete local clause-factor image spaces for the verifier factors.

Paper-faithful intent:
for a fixed clause factor and fixed derivative-count budget `k ≤ 4`, the relevant local
images live on at most four variables (one selector + three body variables). After
multilinearization, this places them inside the multilinear ambient space on four variables,
so the local dimension is uniformly bounded.

This file formalizes that local endpoint as far as the current library comfortably allows.
-/

namespace LocalClauseFactorSpace

open SPDP
open MultilinearSPDP
open Tseitin
open ProductTransport
open LocalFactorReduction
open MvPolynomial

variable {F : Type*} [Field F] [Nontrivial F]

/-- The local image space for clause factor `c` at derivative count `k`.
    It is generated by multilinearized iterated derivatives where every derivative variable
    lies in the factor's variable set. -/
noncomputable def localClauseFactorSpace
    (Φ : TseitinFormula)
    (c : Fin Φ.clauses.length)
    (k : Fin 5) :
    Submodule F (MvPolynomial (Fin (tseitinNumVars Φ)) F) :=
  Submodule.span F
    { q | ∃ (S : List (Fin (tseitinNumVars Φ))),
        S.length = k.val ∧
        (∀ x ∈ S, x ∈ (verifierFactor (F := F) Φ c).vars) ∧
        q = mlProj (iterDerivList S (verifierFactor (F := F) Φ c)) }

/-- Package the local clause-factor spaces into the family type used by the reduction. -/
noncomputable def verifierLocalFactorSpaceFamily
    (Φ : TseitinFormula) :
    LocalFactorSpaceFamily (F := F) Φ :=
  fun c k => localClauseFactorSpace (F := F) Φ c k

/-- A crude but uniform local dimension datum: every clause-factor image lives in a
    4-variable multilinear ambient space, so one can target a constant bound. -/
noncomputable def verifierLocalFactorDimFamily
    (Φ : TseitinFormula) :
    LocalFactorDimFamily (F := F) Φ :=
  fun _ _ => 16

/-- Every local clause-factor space is finite-dimensional. -/
instance localClauseFactorSpace_finite
    (Φ : TseitinFormula) (c : Fin Φ.clauses.length) (k : Fin 5) :
    Module.Finite F (localClauseFactorSpace (F := F) Φ c k) := by
  -- It suffices to embed into a restrictTotalDegree space; the true constant-dimension
  -- bound is sharpened later by the 4-variable support argument.
  have hle : localClauseFactorSpace (F := F) Φ c k ≤
      MvPolynomial.restrictTotalDegree (Fin (tseitinNumVars Φ)) F 4 := by
    apply Submodule.span_le.mpr
    intro q hq
    rcases hq with ⟨S, hlen, _, rfl⟩
    have hdeg_factor : (verifierFactor (F := F) Φ c).totalDegree ≤ 4 := by
      unfold verifierFactor
      calc
        (1 - X (selectorIdx Φ c) * clauseGadget F Φ c).totalDegree
            ≤ max (1 : MvPolynomial _ F).totalDegree
                ((X (selectorIdx Φ c) * clauseGadget F Φ c).totalDegree) :=
              MvPolynomial.totalDegree_sub _ _
        _ ≤ max 0 (1 + 3) := by
              gcongr
              · simp [MvPolynomial.totalDegree_one]
              · exact le_trans (MvPolynomial.totalDegree_mul _ _)
                  (by simpa [MvPolynomial.totalDegree_X, clauseGadget_totalDegree]
                      using Nat.add_le_add (le_of_eq (MvPolynomial.totalDegree_X _))
                        (clauseGadget_totalDegree F Φ c))
        _ = 4 := by norm_num
    have hdeg_iter : (iterDerivList S (verifierFactor (F := F) Φ c)).totalDegree ≤ 4 :=
      le_trans (totalDegree_iterDerivList_le S _) hdeg_factor
    have hdeg_ml : (mlProj (iterDerivList S (verifierFactor (F := F) Φ c))).totalDegree ≤ 4 :=
      le_trans (totalDegree_mlProj_le _) hdeg_iter
    exact (MvPolynomial.mem_restrictTotalDegree _ _ _).mpr hdeg_ml
  have : Module.Finite F (MvPolynomial.restrictTotalDegree (Fin (tseitinNumVars Φ)) F 4) :=
    MvPolynomial.instFiniteSubtypeMemSubmoduleRestrictTotalDegreeOfFinite _ _ _
  exact Module.Finite.of_injective
    (Submodule.inclusion hle)
    (Submodule.inclusion_injective _)

/--
Local clause-factor dimension theorem: reduced to the 4-variable multilinear ambient bound.

This is the paper-faithful local endpoint.  The actual constant `16` corresponds to the
multilinear ambient on at most 4 variables.  The current theorem isolates that last step as
an explicit local support-to-ambient lemma rather than hiding it inside the global verifier
profile bound.
-/
def LocalClauseFactorImageBound (Φ : TseitinFormula) : Prop :=
  ∀ (c : Fin Φ.clauses.length) (k : Fin 5),
    Module.finrank F (localClauseFactorSpace (F := F) Φ c k) ≤ 16

/-- Package the local theorem into the reduction-family shape. -/
theorem verifierLocalFactorDimFamily_ok
    (Φ : TseitinFormula)
    (hlocal : LocalClauseFactorImageBound (F := F) Φ) :
    ∀ (c : Fin Φ.clauses.length) (k : Fin 5),
      Module.finrank F ((verifierLocalFactorSpaceFamily (F := F) Φ) c k)
        ≤ (verifierLocalFactorDimFamily (F := F) Φ) c k := by
  intro c k
  simpa [verifierLocalFactorSpaceFamily, verifierLocalFactorDimFamily] using hlocal c k

end LocalClauseFactorSpace
