/-
  MatrixSPDP.lean — Paper-faithful matrix formulation of SPDP rank

  Paper Definition 17 / §2.3: M^B_{κ,ℓ}(p) has
  - Rows indexed by (S, m) with `S.length = κ`, block-admissible, and `m` a
    polynomial with `totalDegree ≤ ℓ` and `vars ⊆ S.toFinset`.
  - Columns indexed by monomial exponents `μ : Fin N →₀ ℕ`.
  - Entry (row, μ) = coefficient of `x^μ` in `mlProj(m · iterDerivList S p)`.

  Paper Γ_{κ,ℓ}(p) := rank(M^B_{κ,ℓ}(p)) = finrank of row span = finrank of the
  image of this matrix viewed as a linear map.

  We realise M^B_{κ,ℓ}(p) as a ℚ-linear map from the free ℚ-module generated
  by row descriptors, into `MvPolynomial (Fin N) ℚ`. The image of this map
  equals `mlBlockedSpdpSubspace`, so its rank (finrank of image) equals
  `mlBlockedSpdpRank`.

  Paper's Lemma 40(c) matrix factoring: `M^B_{κ,ℓ}(g·p) = L · M^B_{κ+d,ℓ+d}(p)`
  with `rank L ≤ N^C`. In LinearMap form: `mlSpdpLinearMap(g·p) = L ∘ mlSpdpLinearMap(p)_shifted`
  (up to Finsupp basis change), with `finrank(range L) ≤ N^C · finrank(SPDP(p)_shifted)`.
  We state this as a narrower axiom and derive the rank form from it.
-/
import PallLean.MultilinearSPDP
import PallLean.CookLevinDefs
import Mathlib.Tactic

namespace MatrixSPDP

open MvPolynomial MultilinearSPDP SPDP

/-! ## Row descriptor: the paper's (S, m) row index -/

/-- A **row descriptor** for `M^B_{κ,ℓ}(p)`: the data `(S, m)` satisfying
the SPDP generator constraints from `mlBlockedSpdpSubspace`. -/
structure SpdpRowDesc (N : ℕ) (B : BlockPartition N) (κ ℓ : ℕ) : Type where
  derivList : List (Fin N)
  multiplier : MvPolynomial (Fin N) ℚ
  hLen : derivList.length = κ
  hAdmiss : isBlockAdmissible B derivList
  hDeg : multiplier.totalDegree ≤ ℓ
  hVars : multiplier.vars ⊆ derivList.toFinset

/-- The polynomial a row descriptor represents — the paper's `mlProj(m · ∂^S p)`. -/
noncomputable def rowPoly {N : ℕ} {B : BlockPartition N} {κ ℓ : ℕ}
    (d : SpdpRowDesc N B κ ℓ) (p : MvPolynomial (Fin N) ℚ) :
    MvPolynomial (Fin N) ℚ :=
  mlProj (d.multiplier * iterDerivList d.derivList p)

/-! ## The SPDP linear map: `(SpdpRowDesc →₀ ℚ) →ₗ MvPolynomial`

This is the paper's `M^B_{κ,ℓ}(p)` realised as a linear map from the free
ℚ-module generated by row descriptors into the polynomial ring, sending a
formal linear combination `∑ cᵢ · (row_i)` to `∑ cᵢ · rowPoly(row_i, p)`. -/

/-- **Paper's M^B_{κ,ℓ}(p)** as a ℚ-linear map. Domain is the free
ℚ-module on row descriptors; codomain is `MvPolynomial (Fin N) ℚ`. -/
noncomputable def mlSpdpLinearMap {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ)
    (p : MvPolynomial (Fin N) ℚ) :
    (SpdpRowDesc N B κ ℓ →₀ ℚ) →ₗ[ℚ] MvPolynomial (Fin N) ℚ :=
  Finsupp.linearCombination ℚ (fun d => rowPoly d p)

/-! ## Bridge: range of the linear map = mlBlockedSpdpSubspace -/

/-- **Bridge theorem.** The range of the SPDP linear map equals the
paper's SPDP subspace. -/
theorem range_mlSpdpLinearMap_eq_mlBlockedSpdpSubspace {N : ℕ}
    (B : BlockPartition N) (κ ℓ : ℕ) (p : MvPolynomial (Fin N) ℚ) :
    LinearMap.range (mlSpdpLinearMap B κ ℓ p) = mlBlockedSpdpSubspace B κ ℓ p := by
  -- range = span of image of basis elements = span of rowPolys
  -- mlBlockedSpdpSubspace is explicitly the span of the generator set
  -- The two span sets are equivalent up to unpacking the structure.
  apply le_antisymm
  · -- range ⊆ mlBlockedSpdpSubspace
    rw [LinearMap.range_eq_map, ← Finsupp.supported_univ]
    rw [Finsupp.supported_eq_span_single]
    rw [Submodule.map_span]
    apply Submodule.span_le.mpr
    rintro _ ⟨_, ⟨d, _, rfl⟩, rfl⟩
    -- Now the element is mlSpdpLinearMap _ (Finsupp.single d 1) = rowPoly d p
    show mlSpdpLinearMap B κ ℓ p (Finsupp.single d 1) ∈ _
    unfold mlSpdpLinearMap
    rw [Finsupp.linearCombination_single, one_smul]
    -- Goal: rowPoly d p ∈ mlBlockedSpdpSubspace B κ ℓ p
    unfold rowPoly mlBlockedSpdpSubspace
    apply Submodule.subset_span
    refine ⟨d.derivList, d.multiplier, d.hLen, d.hDeg, d.hVars, d.hAdmiss, rfl⟩
  · -- mlBlockedSpdpSubspace ⊆ range
    unfold mlBlockedSpdpSubspace
    apply Submodule.span_le.mpr
    rintro q ⟨S, m, hLen, hDeg, hVars, hAdmiss, hq⟩
    -- Build a row descriptor
    let d : SpdpRowDesc N B κ ℓ :=
      { derivList := S
        multiplier := m
        hLen := hLen
        hAdmiss := hAdmiss
        hDeg := hDeg
        hVars := hVars }
    have hd : rowPoly d p = q := by
      unfold rowPoly
      rw [hq]
    rw [← hd]
    -- Now show rowPoly d p ∈ range
    refine ⟨Finsupp.single d 1, ?_⟩
    unfold mlSpdpLinearMap
    rw [Finsupp.linearCombination_single, one_smul]

/-- **Bridge theorem (rank form).** The paper's Γ_{κ,ℓ}(p) = rank(M^B_{κ,ℓ}(p))
equals `mlBlockedSpdpRank`. -/
theorem finrank_range_mlSpdpLinearMap {N : ℕ}
    (B : BlockPartition N) (κ ℓ : ℕ) (p : MvPolynomial (Fin N) ℚ) :
    Module.finrank ℚ (LinearMap.range (mlSpdpLinearMap B κ ℓ p)) =
    mlBlockedSpdpRank B κ ℓ p := by
  rw [range_mlSpdpLinearMap_eq_mlBlockedSpdpSubspace]
  rfl

/-! ## Gadget factoring at the LinearMap level (paper's Lemma 40(c))

Paper statement: `M^B_{κ,ℓ}(g·p) = L · M^B_{κ+d,ℓ+d}(p)` with `rank L ≤ N^C`.

In LinearMap form: there exists a ℚ-linear map `L` whose composition with
`mlSpdpLinearMap(p)_shifted` has range containing the range of
`mlSpdpLinearMap(g·p)`, and the rank of `L` (restricted to the relevant
domain) is at most `N^C`.

This is the paper-exact content of Lemma 40(c) at the LinearMap level. -/

/-- A bounded gadget: see `PAC.BoundedGadget`, copied here to avoid a
cyclic import. -/
structure BoundedGadget (N : ℕ) : Type where
  poly : MvPolynomial (Fin N) ℚ
  supportSize : ℕ
  degreeBound : ℕ
  vars_card_le : poly.vars.card ≤ supportSize
  totalDegree_le : poly.totalDegree ≤ degreeBound

/-- **Paper's Lemma 40(c) at the LinearMap level** (axiom).

For a bounded gadget `g` and polynomial `p`, there exists a ℚ-linear map

  `L : (SpdpRowDesc N B (κ+d) (ℓ+d) →₀ ℚ) →ₗ[ℚ] (SpdpRowDesc N B κ ℓ →₀ ℚ)`

such that

  `mlSpdpLinearMap B κ ℓ (g.poly * p) = mlSpdpLinearMap B κ ℓ (g.poly * p) ∘ ...`

No — the paper's identity is that, on the row-space side, the matrix of
`M^B_{κ,ℓ}(g·p)` factors through `M^B_{κ+d,ℓ+d}(p)` via `L`. This means:

  `∀ row descriptor d at (κ, ℓ), rowPoly d (g.poly * p) = Σ L[d, d'] · rowPoly d' p`

for some coefficient matrix `L` with `rank L ≤ N^C`.

Equivalently: `mlBlockedSpdpSubspace B κ ℓ (g·p) ⊆ L-image of mlBlockedSpdpSubspace B (κ+d) (ℓ+d) p`, where L has rank ≤ N^C.

We state the equivalent span-level consequence here, which is what's
needed to derive the rank bound. For the full matrix-rank statement, use
`LinearMap.finrank_range_le` after building a `LinearMap`. -/
axiom gadget_factoring_linearmap_form
    {N : ℕ} (g : BoundedGadget N)
    (B : BlockPartition N) (κ ℓ : ℕ) (p : MvPolynomial (Fin N) ℚ) :
    ∃ (L : MvPolynomial (Fin N) ℚ →ₗ[ℚ] MvPolynomial (Fin N) ℚ),
      mlBlockedSpdpSubspace B κ ℓ (g.poly * p) ≤
        Submodule.map L (mlBlockedSpdpSubspace B (κ + g.degreeBound)
          (ℓ + g.degreeBound) p) ∧
      Module.finrank ℚ (LinearMap.range L) ≤
        N ^ (g.supportSize + g.degreeBound)

/-- **Derived: the paper's rank bound**, via LinearMap range inequalities.

Requires `1 ≤ N` so that `N^C ≥ 1` and the factor `N^C` does not collapse
the bound at `N = 0`. In our use (Cook-Levin compilation at `n ≥ 2^804`),
`N = n ≥ 2` so the hypothesis is trivially satisfied. -/
theorem gadget_multiplication_rank_bound_matrix_form
    {N : ℕ} (hN : 1 ≤ N) (g : BoundedGadget N)
    (B : BlockPartition N) (κ ℓ : ℕ) (p : MvPolynomial (Fin N) ℚ) :
    mlBlockedSpdpRank B κ ℓ (g.poly * p) ≤
    N ^ (g.supportSize + g.degreeBound) *
      mlBlockedSpdpRank B (κ + g.degreeBound) (ℓ + g.degreeBound) p := by
  obtain ⟨L, hSub, hRank⟩ := gadget_factoring_linearmap_form g B κ ℓ p
  unfold mlBlockedSpdpRank
  have hFinMap :
      Module.finrank ℚ
        (Submodule.map L (mlBlockedSpdpSubspace B (κ + g.degreeBound)
          (ℓ + g.degreeBound) p)) ≤
      Module.finrank ℚ
        (mlBlockedSpdpSubspace B (κ + g.degreeBound) (ℓ + g.degreeBound) p) :=
    Submodule.finrank_map_le _ _
  have h1 : Module.finrank ℚ (mlBlockedSpdpSubspace B κ ℓ (g.poly * p)) ≤
            Module.finrank ℚ
              (Submodule.map L (mlBlockedSpdpSubspace B (κ + g.degreeBound)
                (ℓ + g.degreeBound) p)) :=
    Submodule.finrank_mono hSub
  have hPowPos : 0 < N ^ (g.supportSize + g.degreeBound) :=
    Nat.pow_pos hN
  calc Module.finrank ℚ (mlBlockedSpdpSubspace B κ ℓ (g.poly * p))
      ≤ Module.finrank ℚ
          (mlBlockedSpdpSubspace B (κ + g.degreeBound)
            (ℓ + g.degreeBound) p) := le_trans h1 hFinMap
    _ ≤ N ^ (g.supportSize + g.degreeBound) *
          Module.finrank ℚ
            (mlBlockedSpdpSubspace B (κ + g.degreeBound)
              (ℓ + g.degreeBound) p) :=
          Nat.le_mul_of_pos_left _ hPowPos

end MatrixSPDP
