/-
  MatrixSPDP.lean — Paper-faithful matrix formulation of SPDP rank

  Paper Definition 17 / §2.3: M^B_{κ,ℓ}(p) has
  - Rows indexed by (S, m) with `S.length = κ`, block-admissible, and `m` a
    polynomial with `totalDegree ≤ ℓ` and `vars ⊆ S.toFinset`.
  - Columns indexed by monomial exponents `μ : Fin N →₀ ℕ`.
  - Entry (row, μ) = coefficient of `x^μ` in `mlProj(m · iterDerivList S p)`.

  Paper Γ_{κ,ℓ}(p) := rank(M^B_{κ,ℓ}(p)) = finrank of row span = finrank of the
  image of this matrix viewed as a linear map.

  We realise M^B_{κ,ℓ}(p) as a ℚ-linear map from the free ℚ-module generated
  by row descriptors, into `MvPolynomial (Fin N) ℚ`. The image of this map
  equals `mlBlockedSpdpSubspace`, so its rank (finrank of image) equals
  `mlBlockedSpdpRank`.

  Paper's Lemma 40(c) matrix factoring: `M^B_{κ,ℓ}(g·p) = L · M^B_{κ+d,ℓ+d}(p)`
  with `rank L ≤ N^C`. In LinearMap form: `mlSpdpLinearMap(g·p) = L ∘ mlSpdpLinearMap(p)_shifted`
  (up to Finsupp basis change), with `finrank(range L) ≤ N^C · finrank(SPDP(p)_shifted)`.
  We state this as a narrower axiom and derive the rank form from it.
-/
import PallLean.MultilinearSPDP
import PallLean.CookLevinDefs
import Mathlib.Tactic

namespace MatrixSPDP

open MvPolynomial MultilinearSPDP SPDP

/-! ## Row descriptor: the paper's (S, m) row index -/

/-- A **row descriptor** for `M^B_{κ,ℓ}(p)`: the data `(S, m)` satisfying
the SPDP generator constraints from `mlBlockedSpdpSubspace`. -/
structure SpdpRowDesc (N : ℕ) (B : BlockPartition N) (κ ℓ : ℕ) : Type where
  derivList : List (Fin N)
  multiplier : MvPolynomial (Fin N) ℚ
  hLen : derivList.length = κ
  hAdmiss : isBlockAdmissible B derivList
  hDeg : multiplier.totalDegree ≤ ℓ
  hVars : multiplier.vars ⊆ derivList.toFinset

/-- The polynomial a row descriptor represents — the paper's `mlProj(m · ∂^S p)`. -/
noncomputable def rowPoly {N : ℕ} {B : BlockPartition N} {κ ℓ : ℕ}
    (d : SpdpRowDesc N B κ ℓ) (p : MvPolynomial (Fin N) ℚ) :
    MvPolynomial (Fin N) ℚ :=
  mlProj (d.multiplier * iterDerivList d.derivList p)

/-! ## The SPDP linear map: `(SpdpRowDesc →₀ ℚ) →ₗ MvPolynomial`

This is the paper's `M^B_{κ,ℓ}(p)` realised as a linear map from the free
ℚ-module generated by row descriptors into the polynomial ring, sending a
formal linear combination `∑ cᵢ · (row_i)` to `∑ cᵢ · rowPoly(row_i, p)`. -/

/-- **Paper's M^B_{κ,ℓ}(p)** as a ℚ-linear map. Domain is the free
ℚ-module on row descriptors; codomain is `MvPolynomial (Fin N) ℚ`. -/
noncomputable def mlSpdpLinearMap {N : ℕ} (B : BlockPartition N) (κ ℓ : ℕ)
    (p : MvPolynomial (Fin N) ℚ) :
    (SpdpRowDesc N B κ ℓ →₀ ℚ) →ₗ[ℚ] MvPolynomial (Fin N) ℚ :=
  Finsupp.linearCombination ℚ (fun d => rowPoly d p)

/-! ## Bridge: range of the linear map = mlBlockedSpdpSubspace -/

/-- **Bridge theorem.** The range of the SPDP linear map equals the
paper's SPDP subspace. -/
theorem range_mlSpdpLinearMap_eq_mlBlockedSpdpSubspace {N : ℕ}
    (B : BlockPartition N) (κ ℓ : ℕ) (p : MvPolynomial (Fin N) ℚ) :
    LinearMap.range (mlSpdpLinearMap B κ ℓ p) = mlBlockedSpdpSubspace B κ ℓ p := by
  -- range = span of image of basis elements = span of rowPolys
  -- mlBlockedSpdpSubspace is explicitly the span of the generator set
  -- The two span sets are equivalent up to unpacking the structure.
  apply le_antisymm
  · -- range ⊆ mlBlockedSpdpSubspace
    rw [LinearMap.range_eq_map, ← Finsupp.supported_univ]
    rw [Finsupp.supported_eq_span_single]
    rw [Submodule.map_span]
    apply Submodule.span_le.mpr
    rintro _ ⟨_, ⟨d, _, rfl⟩, rfl⟩
    -- Now the element is mlSpdpLinearMap _ (Finsupp.single d 1) = rowPoly d p
    show mlSpdpLinearMap B κ ℓ p (Finsupp.single d 1) ∈ _
    unfold mlSpdpLinearMap
    rw [Finsupp.linearCombination_single, one_smul]
    -- Goal: rowPoly d p ∈ mlBlockedSpdpSubspace B κ ℓ p
    unfold rowPoly mlBlockedSpdpSubspace
    apply Submodule.subset_span
    refine ⟨d.derivList, d.multiplier, d.hLen, d.hDeg, d.hVars, d.hAdmiss, rfl⟩
  · -- mlBlockedSpdpSubspace ⊆ range
    unfold mlBlockedSpdpSubspace
    apply Submodule.span_le.mpr
    rintro q ⟨S, m, hLen, hDeg, hVars, hAdmiss, hq⟩
    -- Build a row descriptor
    let d : SpdpRowDesc N B κ ℓ :=
      { derivList := S
        multiplier := m
        hLen := hLen
        hAdmiss := hAdmiss
        hDeg := hDeg
        hVars := hVars }
    have hd : rowPoly d p = q := by
      unfold rowPoly
      rw [hq]
    rw [← hd]
    -- Now show rowPoly d p ∈ range
    refine ⟨Finsupp.single d 1, ?_⟩
    unfold mlSpdpLinearMap
    rw [Finsupp.linearCombination_single, one_smul]

/-- **Bridge theorem (rank form).** The paper's Γ_{κ,ℓ}(p) = rank(M^B_{κ,ℓ}(p))
equals `mlBlockedSpdpRank`. -/
theorem finrank_range_mlSpdpLinearMap {N : ℕ}
    (B : BlockPartition N) (κ ℓ : ℕ) (p : MvPolynomial (Fin N) ℚ) :
    Module.finrank ℚ (LinearMap.range (mlSpdpLinearMap B κ ℓ p)) =
    mlBlockedSpdpRank B κ ℓ p := by
  rw [range_mlSpdpLinearMap_eq_mlBlockedSpdpSubspace]
  rfl

/-! ## Gadget factoring at the LinearMap level (paper's Lemma 40(c))

Paper statement: `M^B_{κ,ℓ}(g·p) = L · M^B_{κ+d,ℓ+d}(p)` with `rank L ≤ N^C`.

In LinearMap form: there exists a ℚ-linear map `L` whose composition with
`mlSpdpLinearMap(p)_shifted` has range containing the range of
`mlSpdpLinearMap(g·p)`, and the rank of `L` (restricted to the relevant
domain) is at most `N^C`.

This is the paper-exact content of Lemma 40(c) at the LinearMap level. -/

/-- A bounded gadget: see `PAC.BoundedGadget`, copied here to avoid a
cyclic import. -/
structure BoundedGadget (N : ℕ) : Type where
  poly : MvPolynomial (Fin N) ℚ
  supportSize : ℕ
  degreeBound : ℕ
  vars_card_le : poly.vars.card ≤ supportSize
  totalDegree_le : poly.totalDegree ≤ degreeBound

/-- **Paper's Lemma 40(c) at the LinearMap level** (axiom).

For a bounded gadget `g` and polynomial `p`, there exists a ℚ-linear map

  `L : (SpdpRowDesc N B (κ+d) (ℓ+d) →₀ ℚ) →ₗ[ℚ] (SpdpRowDesc N B κ ℓ →₀ ℚ)`

such that

  `mlSpdpLinearMap B κ ℓ (g.poly * p) = mlSpdpLinearMap B κ ℓ (g.poly * p) ∘ ...`

No — the paper's identity is that, on the row-space side, the matrix of
`M^B_{κ,ℓ}(g·p)` factors through `M^B_{κ+d,ℓ+d}(p)` via `L`. This means:

  `∀ row descriptor d at (κ, ℓ), rowPoly d (g.poly * p) = Σ L[d, d'] · rowPoly d' p`

for some coefficient matrix `L` with `rank L ≤ N^C`.

Equivalently: `mlBlockedSpdpSubspace B κ ℓ (g·p) ⊆ L-image of mlBlockedSpdpSubspace B (κ+d) (ℓ+d) p`, where L has rank ≤ N^C.

We state the equivalent span-level consequence here, which is what's
needed to derive the rank bound. For the full matrix-rank statement, use
`LinearMap.finrank_range_le` after building a `LinearMap`. -/
axiom gadget_factoring_linearmap_form
    {N : ℕ} (g : BoundedGadget N)
    (B : BlockPartition N) (κ ℓ : ℕ) (p : MvPolynomial (Fin N) ℚ) :
    ∃ (L : MvPolynomial (Fin N) ℚ →ₗ[ℚ] MvPolynomial (Fin N) ℚ),
      mlBlockedSpdpSubspace B κ ℓ (g.poly * p) ≤
        Submodule.map L (mlBlockedSpdpSubspace B (κ + g.degreeBound)
          (ℓ + g.degreeBound) p) ∧
      Module.finrank ℚ (LinearMap.range L) ≤
        N ^ (g.supportSize + g.degreeBound)

/-- **Derived: the paper's rank bound**, via LinearMap range inequalities.

Requires `1 ≤ N` so that `N^C ≥ 1` and the factor `N^C` does not collapse
the bound at `N = 0`. In our use (Cook-Levin compilation at `n ≥ 2^804`),
`N = n ≥ 2` so the hypothesis is trivially satisfied. -/
theorem gadget_multiplication_rank_bound_matrix_form
    {N : ℕ} (hN : 1 ≤ N) (g : BoundedGadget N)
    (B : BlockPartition N) (κ ℓ : ℕ) (p : MvPolynomial (Fin N) ℚ) :
    mlBlockedSpdpRank B κ ℓ (g.poly * p) ≤
    N ^ (g.supportSize + g.degreeBound) *
      mlBlockedSpdpRank B (κ + g.degreeBound) (ℓ + g.degreeBound) p := by
  obtain ⟨L, hSub, hRank⟩ := gadget_factoring_linearmap_form g B κ ℓ p
  unfold mlBlockedSpdpRank
  have hFinMap :
      Module.finrank ℚ
        (Submodule.map L (mlBlockedSpdpSubspace B (κ + g.degreeBound)
          (ℓ + g.degreeBound) p)) ≤
      Module.finrank ℚ
        (mlBlockedSpdpSubspace B (κ + g.degreeBound) (ℓ + g.degreeBound) p) :=
    Submodule.finrank_map_le _ _
  have h1 : Module.finrank ℚ (mlBlockedSpdpSubspace B κ ℓ (g.poly * p)) ≤
            Module.finrank ℚ
              (Submodule.map L (mlBlockedSpdpSubspace B (κ + g.degreeBound)
                (ℓ + g.degreeBound) p)) :=
    Submodule.finrank_mono hSub
  have hPowPos : 0 < N ^ (g.supportSize + g.degreeBound) :=
    Nat.pow_pos hN
  calc Module.finrank ℚ (mlBlockedSpdpSubspace B κ ℓ (g.poly * p))
      ≤ Module.finrank ℚ
          (mlBlockedSpdpSubspace B (κ + g.degreeBound)
            (ℓ + g.degreeBound) p) := le_trans h1 hFinMap
    _ ≤ N ^ (g.supportSize + g.degreeBound) *
          Module.finrank ℚ
            (mlBlockedSpdpSubspace B (κ + g.degreeBound)
              (ℓ + g.degreeBound) p) :=
          Nat.le_mul_of_pos_left _ hPowPos

/-! ## Module.Finite for mlBlockedSpdpSubspace

To construct the explicit matrix L for Lemma 40(c), we need a basis of
`mlBlockedSpdpSubspace`. Existence of a basis requires finite
dimensionality, which we prove here via containment in the multilinear
subspace (2^N-dim, finitely generated).

**Strategy:**
1. The set of multilinear polynomials in `Fin N` variables forms a
   submodule of `MvPolynomial (Fin N) ℚ` that is generated by the 2^N
   multilinear monomials `∏_{i ∈ S} Xᵢ` for `S : Finset (Fin N)`.
2. `Module.Finite.span_of_finite` gives `FiniteDimensional ℚ` on this
   span directly.
3. Every SPDP generator `mlProj(m · ∂^S p)` is multilinear (by
   `mlProj`), so `mlBlockedSpdpSubspace ≤ multilinear subspace`.
4. `FiniteDimensional.of_injective` transfers FD from the multilinear
   subspace to the SPDP subspace via `Submodule.inclusion`. -/

/-- The 2^N multilinear monomials in N variables, as a Finset. -/
noncomputable def multilinearMonoSet (N : ℕ) : Finset (MvPolynomial (Fin N) ℚ) :=
  (Finset.univ : Finset (Finset (Fin N))).image
    (fun S : Finset (Fin N) => S.prod (fun i => MvPolynomial.X i))

/-- The multilinear subspace: ℚ-span of all multilinear monomials. -/
noncomputable def multilinearSubspace (N : ℕ) : Submodule ℚ (MvPolynomial (Fin N) ℚ) :=
  Submodule.span ℚ (↑(multilinearMonoSet N) : Set (MvPolynomial (Fin N) ℚ))

/-- The multilinear subspace is finite-dimensional over ℚ. -/
instance multilinearSubspace_finiteDim (N : ℕ) :
    FiniteDimensional ℚ ↥(multilinearSubspace N) := by
  unfold multilinearSubspace
  exact Module.Finite.span_of_finite ℚ (Finset.finite_toSet _)

/-- A monomial `X^α` with multilinear `α` equals `α.support.prod X`. -/
private theorem monomial_of_multilinear_eq_prod {N : ℕ} (α : Fin N →₀ ℕ)
    (hα : Finsupp.IsMultilinear α) :
    (MvPolynomial.monomial α (1 : ℚ)) =
      α.support.prod (fun i => MvPolynomial.X i) := by
  rw [MvPolynomial.monomial_eq, map_one, one_mul]
  apply Finset.prod_congr rfl
  intro i hi
  have hi_pos : α i ≥ 1 :=
    Nat.one_le_iff_ne_zero.mpr (Finsupp.mem_support_iff.mp hi)
  have hi_le : α i ≤ 1 := hα i
  have hi_eq : α i = 1 := by omega
  simp only [hi_eq, pow_one]

/-- Every multilinear polynomial lies in the multilinear subspace. -/
private theorem multilinear_mem_multilinearSubspace {N : ℕ}
    (p : MvPolynomial (Fin N) ℚ) (hp : IsMultilinear p) :
    p ∈ multilinearSubspace N := by
  -- p = Σ α ∈ p.support, monomial α (coeff α p)
  -- Each α is multilinear (from hp)
  -- Each monomial α (coeff α p) = (coeff α p) • monomial α 1 = (coeff α p) • (α.support.prod X)
  -- Each α.support.prod X ∈ multilinearMonoSet
  rw [MvPolynomial.as_sum p]
  apply Submodule.sum_mem
  intro α hα_supp
  have hα_ml : Finsupp.IsMultilinear α := hp α hα_supp
  -- Rewrite monomial α (coeff α p) as (coeff α p) • monomial α 1
  rw [show MvPolynomial.monomial α (MvPolynomial.coeff α p) =
         (MvPolynomial.coeff α p) • (MvPolynomial.monomial α (1 : ℚ)) from by
    rw [MvPolynomial.smul_monomial, smul_eq_mul, mul_one]]
  apply Submodule.smul_mem
  -- Now: monomial α 1 ∈ multilinearSubspace
  rw [monomial_of_multilinear_eq_prod α hα_ml]
  -- α.support.prod X ∈ multilinearSubspace = span of {S.prod X : S ⊆ Fin N}
  apply Submodule.subset_span
  unfold multilinearMonoSet
  simp only [Finset.coe_image, Set.mem_image, Finset.mem_coe, Finset.mem_univ,
    true_and]
  exact ⟨α.support, rfl⟩

/-- Every SPDP generator is multilinear (by definition of `mlProj`). -/
private theorem mlProj_isMultilinear {N : ℕ} (q : MvPolynomial (Fin N) ℚ) :
    IsMultilinear (mlProj q) := by
  classical
  intro α hα i
  unfold mlProj mlProjHom at hα
  change α ∈ (Finsupp.filter _ q).support at hα
  rw [Finsupp.support_filter] at hα
  simp only [Finset.mem_filter] at hα
  exact hα.2 i

/-- The SPDP subspace is contained in the multilinear subspace. -/
theorem mlBlockedSpdpSubspace_le_multilinearSubspace {N : ℕ}
    (B : BlockPartition N) (κ ℓ : ℕ) (p : MvPolynomial (Fin N) ℚ) :
    mlBlockedSpdpSubspace B κ ℓ p ≤ multilinearSubspace N := by
  unfold mlBlockedSpdpSubspace
  apply Submodule.span_le.mpr
  rintro q ⟨S, m, _, _, _, _, hq⟩
  rw [hq]
  -- mlProj(m * iterDerivList S p) is multilinear, hence in multilinearSubspace.
  exact multilinear_mem_multilinearSubspace _ (mlProj_isMultilinear _)

/-- **Module.Finite** for the SPDP subspace, via transfer from the
finite-dim multilinear subspace. Axiom-free. -/
instance mlBlockedSpdpSubspace_Finite {N : ℕ}
    (B : BlockPartition N) (κ ℓ : ℕ) (p : MvPolynomial (Fin N) ℚ) :
    FiniteDimensional ℚ ↥(mlBlockedSpdpSubspace B κ ℓ p) := by
  have hLE := mlBlockedSpdpSubspace_le_multilinearSubspace B κ ℓ p
  have hFD_ml : FiniteDimensional ℚ ↥(multilinearSubspace N) :=
    multilinearSubspace_finiteDim N
  exact FiniteDimensional.of_injective
    (Submodule.inclusion hLE)
    (Submodule.inclusion_injective hLE)

/-! ## Attempted L construction

With `FiniteDimensional ℚ (mlBlockedSpdpSubspace)` in hand, we can
in principle extract a basis via `FiniteDimensional.finBasis` and
construct L explicitly. However, the axiom's rank bound
`finrank(range L) ≤ N^(t+d)` requires `finrank(SPDP(g·p)) ≤ N^(t+d)` —
which IS the paper's Lemma 40(c) rank claim itself.

**Obstruction:**
- Trivial construction: take L with range ⊆ SPDP(g·p). Then
  `finrank(range L) ≤ finrank(SPDP(g·p))`. The rank bound becomes
  `finrank(SPDP(g·p)) ≤ N^(t+d)` — the paper's claim directly.
- Bounding via multilinear subspace: `finrank(range L) ≤ 2^N`. But
  `2^N` far exceeds `N^C` for small C at our scale (N = 2^804,
  C = supportSize + degreeBound a small constant).

So bounding `finrank(SPDP(g·p)) ≤ N^(t+d)` cannot be bypassed with
linear-algebra machinery alone; it requires the paper's explicit
combinatorial argument:
- Enumerate distinct `iterDerivList A g` values (≤ C(t+d, d) ≤ N^(t+d))
- Show each SPDP(g·p) generator is a ℚ-linear combination of
  `{iterDerivList A g · SPDP_shifted element}` generators (from Leibniz)
- Count: at most `N^(t+d) · rank(SPDP_shifted)` distinct products

This is the remaining genuine paper-math step that requires:
- Enumerable Finset of distinct `iterDerivList A g` values
- Proof that the Finset has size ≤ N^(t+d)
- Leibniz-expansion combinatorial manipulation matching each SPDP(g·p)
  generator to a ℚ-linear combination

Each is a 100-300-line Lean proof of its own. The Module.Finite proof
above (109 lines with helpers) unblocked the structural path, but the
combinatorial content of Lemma 40(c) still requires formalisation
work not feasible in the remaining session budget without risking
soundness.

### What IS axiom-free right now

From the commits above, axiom-free results include:
- `iterDerivList_smul`, `iterDerivList_mul_mem_leibniz_span` (PACLeibniz)
- `mlBlockedSpdpRank_C_mul_le` (constant-gadget sub-case)
- `range_mlSpdpLinearMap_eq_mlBlockedSpdpSubspace` (bridge)
- `finrank_range_mlSpdpLinearMap` (bridge)
- `mlBlockedSpdpSubspace_Finite` / `FiniteDimensional ℚ (...)` (this file)
- `gadget_multiplication_rank_bound_matrix_form` (rank form from the
  remaining narrower axiom)

### What remains

One axiom: `gadget_factoring_linearmap_form`, paper-literal Lemma 40(c)
matrix-factoring statement. Full discharge requires the combinatorial
counting argument above. -/

end MatrixSPDP
