import PallLean.CompilerNF
import PallLean.CompiledSoS
import PallLean.MultilinearSPDP
import PallLean.NPWitness
import PallLean.Compiler
import PallLean.GodMoveMonotonicity
import Mathlib.Tactic

/-!
# RestrictionPipeline — paper-consistent interface for §32–33 + Theorem 12 (Steps 2–5)

This file now names assumptions by paper role (for auditability), instead of bundling
all restriction-side obligations into opaque placeholders.

Named paper interfaces:
- Lemma 33 / Cor. 185: restriction rank monotonicity.
- Lemma 160 + §32.3: derandomized switching / explicit family yields a good `ρ*`.
- Lemma 171 + Step 4: depth collapse implies polynomial P-side rank.
- Step 5: NP identity-minor lower bound survives under the same `ρ*`.
-/

namespace RestrictionPipeline

open SPDP MultilinearSPDP NPWitness Compiler TuringMachine CompiledSoS
open CompilerInvariance CompilerNF MvPolynomial

/-- Partial assignment used by restrictions. -/
inductive VarAssignment where
  | free : VarAssignment
  | fixed : ℚ → VarAssignment

/-- Apply a restriction: free vars stay symbolic, fixed vars are substituted. -/
noncomputable def applyRestriction {N : ℕ}
    (ρ : Fin N → VarAssignment)
    (p : MvPolynomial (Fin N) ℚ) :
    MvPolynomial (Fin N) ℚ :=
  MvPolynomial.aeval (fun i => match ρ i with
    | VarAssignment.free => X i
    | VarAssignment.fixed v => MvPolynomial.C v) p

/-- Lemma 33 / Cor. 185 interface (proved via existing GodMove monotonicity primitive):
restriction (partial evaluation + projection-style substitution) is rank-monotone.

Note: this statement is on `blockedSpdpRank` (the base SPDP rank), which is the
paper-level object used by the monotonicity primitive. -/
theorem restriction_rank_monotone_L33_C185 {N : ℕ}
    (B : BlockPartition N) (κ ℓ : ℕ)
    (p : MvPolynomial (Fin N) ℚ)
    (ρ : Fin N → VarAssignment) :
    blockedSpdpRank B κ ℓ (applyRestriction ρ p) ≤
    blockedSpdpRank B κ ℓ p := by
  let restrict : MvPolynomial (Fin N) ℚ →ₐ[ℚ] MvPolynomial (Fin N) ℚ :=
    MvPolynomial.aeval (fun i => match ρ i with
      | VarAssignment.free => X i
      | VarAssignment.fixed v => MvPolynomial.C v)
  simpa [applyRestriction, restrict] using
    GodMoveMonotonicity.blockedSpdpRank_restriction_le
      (F := ℚ) (B := B) (κ := κ) (ℓ := ℓ) restrict p

/-- Canonical seed restriction used for scaffolding the explicit family interface.
Currently this is the all-`free` restriction. In the full §32.3 formalization,
this will be replaced by `Gen σ` from the derandomized PRG construction. -/
def canonicalRestriction (M : DTM) (n : ℕ) :
    Fin (numVars M n (Nat.log 2 n)) → VarAssignment :=
  fun _ => VarAssignment.free

/-- §32.3 explicit family (scaffold version): singleton family generated by one seed.
This keeps the API shape while we have not yet formalized PRG-based generation. -/
def explicitRestrictionFamily_S32_3 (M : DTM) (n : ℕ) :
    Set (Fin (numVars M n (Nat.log 2 n)) → VarAssignment) :=
  {ρ | ρ = canonicalRestriction M n}

/-- §32.3 membership predicate: `ρ` is in the explicit restriction family. -/
def in_explicit_family_S32_3 (M : DTM) (n : ℕ)
    (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment) : Prop :=
  ρ ∈ explicitRestrictionFamily_S32_3 M n

/-- Scaffold sanity: the canonical restriction is in the explicit family. -/
theorem canonicalRestriction_in_family (M : DTM) (n : ℕ) :
    in_explicit_family_S32_3 M n (canonicalRestriction M n) := by
  simp [in_explicit_family_S32_3, explicitRestrictionFamily_S32_3]

/-- Lemma 171-side property: under `ρ`, all relevant bounded-width subformulas collapse
    to logarithmic canonical decision-tree depth. -/
axiom depth_collapse_L171 (M : DTM) (n : ℕ)
    (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment) : Prop

/-- Step 5-side property encoded directly as the restricted NP lower bound:
under `ρ`, the identity-minor witness survives with the required exponent.

This is defined as a proposition (not axiomatized) so downstream usage is explicit
and auditable. -/
def identity_minor_survives_Step5 (M : DTM) (n : ℕ)
    (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment) : Prop :=
  ∀ (hn : n ≥ 32) (heven : 2 ∣ n)
    (h_le : npNumVars n ≤ numVars M n (Nat.log 2 n))
    (κ : ℕ) (hκ : κ ≥ 5),
      mlBlockedSpdpRank (compiledPartition M n) κ κ
        (applyRestriction ρ (fullCompiledPoly ℚ M n h_le)) ≥ n ^ (κ / 4)

/-- Good restriction = explicit-family member + depth collapse + NP survival. -/
def GoodRestriction (M : DTM) (n : ℕ)
    (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment) : Prop :=
  in_explicit_family_S32_3 M n ρ ∧
  depth_collapse_L171 M n ρ ∧
  identity_minor_survives_Step5 M n ρ

/-- §32.3 existence claim (scaffold theorem form):
if the canonical family member satisfies depth-collapse and NP-survival,
then a good restriction exists (choose the canonical witness).

This removes a global axiom and surfaces the two substantive obligations
as explicit hypotheses. -/
theorem explicit_restriction_exists_S32_3 (M : DTM) (n : ℕ) (hn : n ≥ 32)
    (hdepth : depth_collapse_L171 M n (canonicalRestriction M n))
    (hminor : identity_minor_survives_Step5 M n (canonicalRestriction M n)) :
    ∃ (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment),
      GoodRestriction M n ρ := by
  refine ⟨canonicalRestriction M n, ?_⟩
  exact ⟨canonicalRestriction_in_family M n, hdepth, hminor⟩

/-- Step 4 interface: depth collapse implies polynomial P-side rank after restriction. -/
axiom pside_rank_from_depthcollapse_Step4 (M : DTM) (n : ℕ)
    (hn : n ≥ max 4 M.numStates)
    (h_le : npNumVars n ≤ numVars M n (Nat.log 2 n))
    (κ : ℕ) (hκ : κ ≥ 5) (hκ_le : κ ≤ Nat.log 2 n)
    (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment)
    (hdepth : depth_collapse_L171 M n ρ) :
    mlBlockedSpdpRank (compiledPartition M n) κ κ
      (applyRestriction ρ (fullCompiledPoly ℚ M n h_le)) ≤ n ^ 215

/-- Step 5 interface: identity-minor survival under restriction gives NP lower bound.
Now discharged by unfolding the Step-5 predicate definition. -/
theorem npside_rank_from_identity_minor_Step5 (n : ℕ) (hn : n ≥ 32) (heven : 2 ∣ n)
    (M : DTM)
    (h_le : npNumVars n ≤ numVars M n (Nat.log 2 n))
    (κ : ℕ) (hκ : κ ≥ 5)
    (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment)
    (hminor : identity_minor_survives_Step5 M n ρ) :
    mlBlockedSpdpRank (compiledPartition M n) κ κ
      (applyRestriction ρ (fullCompiledPoly ℚ M n h_le)) ≥ n ^ (κ / 4) :=
  hminor hn heven h_le κ hκ

/-- Compatibility wrappers with previous names (for downstream files). -/
theorem pside_restricted_rank (M : DTM) (n : ℕ)
    (hn : n ≥ max 4 M.numStates)
    (h_le : npNumVars n ≤ numVars M n (Nat.log 2 n))
    (κ : ℕ) (hκ : κ ≥ 5) (hκ_le : κ ≤ Nat.log 2 n)
    (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment)
    (hgood : GoodRestriction M n ρ) :
    mlBlockedSpdpRank (compiledPartition M n) κ κ
      (applyRestriction ρ (fullCompiledPoly ℚ M n h_le)) ≤ n ^ 215 :=
  pside_rank_from_depthcollapse_Step4 M n hn h_le κ hκ hκ_le ρ hgood.2.1

theorem npside_restricted_rank (n : ℕ) (hn : n ≥ 32) (heven : 2 ∣ n)
    (M : DTM)
    (h_le : npNumVars n ≤ numVars M n (Nat.log 2 n))
    (κ : ℕ) (hκ : κ ≥ 5)
    (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment)
    (hgood : GoodRestriction M n ρ) :
    mlBlockedSpdpRank (compiledPartition M n) κ κ
      (applyRestriction ρ (fullCompiledPoly ℚ M n h_le)) ≥ n ^ (κ / 4) :=
  npside_rank_from_identity_minor_Step5 n hn heven M h_le κ hκ ρ hgood.2.2

/-- Backward-compatible alias for existence theorem. -/
abbrev explicit_restriction_exists := explicit_restriction_exists_S32_3

/-- Pure contradiction combiner for Steps 4 + 5 once exponent separation is provided. -/
theorem restricted_rank_contradiction
    (M : DTM) (n : ℕ) (hn : n ≥ 32) (hnM : n ≥ max 4 M.numStates) (heven : 2 ∣ n)
    (h_le : npNumVars n ≤ numVars M n (Nat.log 2 n))
    (κ : ℕ) (hκ : κ ≥ 5) (hκ_le : κ ≤ Nat.log 2 n)
    (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment)
    (hgood : GoodRestriction M n ρ)
    (hexp : n ^ 215 < n ^ (κ / 4)) : False := by
  have hP := pside_restricted_rank M n hnM h_le κ hκ hκ_le ρ hgood
  have hNP := npside_restricted_rank n hn heven M h_le κ hκ ρ hgood
  have hle : n ^ (κ / 4) ≤ n ^ 215 := le_trans hNP hP
  exact (not_lt_of_ge hle) hexp

end RestrictionPipeline
