import PallLean.CompiledSoS
import PallLean.MultilinearSPDP
import PallLean.NPWitness
import PallLean.Compiler
import Mathlib.Tactic

/-!
# RestrictionPipeline — paper-consistent interface for §32–33 + Theorem 12 (Steps 2–5)

This file now names assumptions by paper role (for auditability), instead of bundling
all restriction-side obligations into opaque placeholders.

Named paper interfaces:
- Lemma 33 / Cor. 185: restriction rank monotonicity.
- Lemma 160 + §32.3: derandomized switching / explicit family yields a good `ρ*`.
- Lemma 171 + Step 4: depth collapse implies polynomial P-side rank.
- Step 5: NP identity-minor lower bound survives under the same `ρ*`.
-/

namespace RestrictionPipeline

open SPDP MultilinearSPDP NPWitness Compiler TuringMachine CompiledSoS
open MvPolynomial

/-- Partial assignment used by restrictions. -/
inductive VarAssignment where
  | free : VarAssignment
  | fixed : ℚ → VarAssignment

/-- Apply a restriction: free vars stay symbolic, fixed vars are substituted. -/
noncomputable def applyRestriction {N : ℕ}
    (ρ : Fin N → VarAssignment)
    (p : MvPolynomial (Fin N) ℚ) :
    MvPolynomial (Fin N) ℚ :=
  MvPolynomial.aeval (fun i => match ρ i with
    | VarAssignment.free => X i
    | VarAssignment.fixed v => MvPolynomial.C v) p

/- Lemma 33 / Cor. 185 (restriction monotonicity) is already subsumed by the
active contradiction chain here: we use direct Step-4/Step-5 bounds on the same
restricted object, so no separate monotonicity lemma is required in this file. -/

/-- Canonical seed restriction used for scaffolding the explicit family interface.
Currently this is the all-`free` restriction. In the full §32.3 formalization,
this will be replaced by `Gen σ` from the derandomized PRG construction. -/
def canonicalRestriction (M : DTM) (n : ℕ) :
    Fin (numVars M n (Nat.log 2 n)) → VarAssignment :=
  fun _ => VarAssignment.free

/-- §32.3 explicit family (scaffold version): singleton family generated by one seed.
This keeps the API shape while we have not yet formalized PRG-based generation. -/
def explicitRestrictionFamily_S32_3 (M : DTM) (n : ℕ) :
    Set (Fin (numVars M n (Nat.log 2 n)) → VarAssignment) :=
  {ρ | ρ = canonicalRestriction M n}

/-- §32.3 membership predicate: `ρ` is in the explicit restriction family. -/
def in_explicit_family_S32_3 (M : DTM) (n : ℕ)
    (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment) : Prop :=
  ρ ∈ explicitRestrictionFamily_S32_3 M n

/-- Applying the canonical all-free restriction is identity. -/
theorem applyRestriction_canonical (M : DTM) (n : ℕ)
    (p : MvPolynomial (Fin (numVars M n (Nat.log 2 n))) ℚ) :
    applyRestriction (canonicalRestriction M n) p = p := by
  change (MvPolynomial.bind₁ (fun i : Fin (numVars M n (Nat.log 2 n)) => X i) p) = p
  exact congrArg (fun φ => φ p)
    (MvPolynomial.bind₁_X_left (R := ℚ)
      (σ := Fin (numVars M n (Nat.log 2 n))))

/-- Scaffold sanity: the canonical restriction is in the explicit family. -/
theorem canonicalRestriction_in_family (M : DTM) (n : ℕ) :
    in_explicit_family_S32_3 M n (canonicalRestriction M n) := by
  simp [in_explicit_family_S32_3, explicitRestrictionFamily_S32_3]

/-- Lemma 171-side property encoded as the Step-4 consequence needed downstream:
under `ρ`, the restricted compiled object satisfies the polynomial P-side rank bound.

Defined (not axiomatized) as the exact quantified obligation consumed by Step 4. -/
def depth_collapse_L171 (M : DTM) (n : ℕ)
    (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment) : Prop :=
  ∀ (hn : n ≥ max 4 M.numStates)
    (h_le : npNumVars n ≤ numVars M n (Nat.log 2 n))
    (κ : ℕ) (hκ : κ ≥ 5) (hκ_le : κ ≤ Nat.log 2 n),
      mlBlockedSpdpRank (compiledPartition M n) κ κ
        (applyRestriction ρ (fullCompiledPoly ℚ M n h_le)) ≤ n ^ 215
/-- NP lower-bound threshold extracted from `np_ml_lower_bound` (F = ℚ). -/
noncomputable def npLowerThreshold : ℕ :=
  Classical.choose (np_ml_lower_bound (F := ℚ))

/-- Specialization of `np_ml_lower_bound` at the extracted threshold. -/
theorem np_ml_lower_bound_at_threshold (n : ℕ)
    (hnNP : n ≥ npLowerThreshold) (heven : 2 ∣ n) :
    mlBlockedSpdpRank (tseitinPartition n) (Nat.log 2 n) (Nat.log 2 n)
      (tseitinPoly ℚ n) ≥ n ^ (Nat.log 2 n / 4) := by
  have hspec := Classical.choose_spec (np_ml_lower_bound (F := ℚ))
  exact hspec n hnNP heven

/-- Step 5-side property (log-regime form):
under `ρ`, the restricted compiled object has NP lower bound at κ = log₂ n.

This is exactly the quantity used in the final contradiction wrapper. -/
def identity_minor_survives_Step5 (M : DTM) (n : ℕ)
    (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment) : Prop :=
  ∀ (hn : n ≥ 32) (hnNP : n ≥ npLowerThreshold) (heven : 2 ∣ n)
    (h_le : npNumVars n ≤ numVars M n (Nat.log 2 n)),
      mlBlockedSpdpRank (compiledPartition M n) (Nat.log 2 n) (Nat.log 2 n)
        (applyRestriction ρ (fullCompiledPoly ℚ M n h_le)) ≥ n ^ (Nat.log 2 n / 4)

/-- Good restriction = explicit-family member + depth collapse + NP survival. -/
def GoodRestriction (M : DTM) (n : ℕ)
    (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment) : Prop :=
  in_explicit_family_S32_3 M n ρ ∧
  depth_collapse_L171 M n ρ ∧
  identity_minor_survives_Step5 M n ρ

/-- §32.3 existence claim (scaffold theorem form):
if the canonical family member satisfies depth-collapse and NP-survival,
then a good restriction exists (choose the canonical witness).

This removes a global axiom and surfaces the two substantive obligations
as explicit hypotheses. -/
theorem explicit_restriction_exists_S32_3 (M : DTM) (n : ℕ) (hn : n ≥ 32)
    (hdepth : depth_collapse_L171 M n (canonicalRestriction M n))
    (hminor : identity_minor_survives_Step5 M n (canonicalRestriction M n)) :
    ∃ (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment),
      GoodRestriction M n ρ := by
  refine ⟨canonicalRestriction M n, ?_⟩
  exact ⟨canonicalRestriction_in_family M n, hdepth, hminor⟩

/-- Canonical restriction satisfies the Step-4 depth-collapse obligation,
using the existing compiled P-side bound on `fullCompiledPoly`. -/
theorem depth_collapse_canonical (M : DTM) (n : ℕ) :
    depth_collapse_L171 M n (canonicalRestriction M n) := by
  intro hn h_le κ hκ hκ_le
  simpa [applyRestriction_canonical] using
    compiled_spdp_rank_bound M n hn h_le κ hκ hκ_le

/-- Step 4 theorem: immediate from the `depth_collapse_L171` obligation. -/
theorem pside_rank_from_depthcollapse_Step4 (M : DTM) (n : ℕ)
    (hn : n ≥ max 4 M.numStates)
    (h_le : npNumVars n ≤ numVars M n (Nat.log 2 n))
    (κ : ℕ) (hκ : κ ≥ 5) (hκ_le : κ ≤ Nat.log 2 n)
    (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment)
    (hdepth : depth_collapse_L171 M n ρ) :
    mlBlockedSpdpRank (compiledPartition M n) κ κ
      (applyRestriction ρ (fullCompiledPoly ℚ M n h_le)) ≤ n ^ 215 :=
  hdepth hn h_le κ hκ hκ_le

/-- Canonical restriction satisfies the Step-5 NP lower-bound obligation,
by chaining NP witness lower bound with extraction monotonicity. -/
theorem identity_minor_survives_canonical (M : DTM) (n : ℕ) :
    identity_minor_survives_Step5 M n (canonicalRestriction M n) := by
  intro hn hnNP heven h_le
  have hκ : Nat.log 2 n ≥ 5 := by
    have : Nat.log 2 32 = 5 := by native_decide
    exact le_trans (by omega) (Nat.log_mono_right hn)
  have hnp : mlBlockedSpdpRank (tseitinPartition n) (Nat.log 2 n) (Nat.log 2 n)
      (tseitinPoly ℚ n) ≥ n ^ (Nat.log 2 n / 4) :=
    np_ml_lower_bound_at_threshold n hnNP heven
  have hextract := extraction_rank_monotone (F := ℚ) n M trivial hn h_le
    (Nat.log 2 n) (Nat.log 2 n) hκ
  have hfull : n ^ (Nat.log 2 n / 4) ≤
      mlBlockedSpdpRank (compiledPartition M n) (Nat.log 2 n) (Nat.log 2 n)
        (fullCompiledPoly ℚ M n h_le) := by
    exact le_trans hnp hextract
  simpa [applyRestriction_canonical] using hfull

/-- Step 5 interface: identity-minor survival under restriction gives NP lower bound
at κ = log₂ n. -/
theorem npside_rank_from_identity_minor_Step5 (n : ℕ)
    (hn : n ≥ 32) (hnNP : n ≥ npLowerThreshold) (heven : 2 ∣ n)
    (M : DTM)
    (h_le : npNumVars n ≤ numVars M n (Nat.log 2 n))
    (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment)
    (hminor : identity_minor_survives_Step5 M n ρ) :
    mlBlockedSpdpRank (compiledPartition M n) (Nat.log 2 n) (Nat.log 2 n)
      (applyRestriction ρ (fullCompiledPoly ℚ M n h_le)) ≥ n ^ (Nat.log 2 n / 4) :=
  hminor hn hnNP heven h_le

/-- Compatibility wrappers with previous names (for downstream files). -/
theorem pside_restricted_rank (M : DTM) (n : ℕ)
    (hn : n ≥ max 4 M.numStates)
    (h_le : npNumVars n ≤ numVars M n (Nat.log 2 n))
    (κ : ℕ) (hκ : κ ≥ 5) (hκ_le : κ ≤ Nat.log 2 n)
    (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment)
    (hgood : GoodRestriction M n ρ) :
    mlBlockedSpdpRank (compiledPartition M n) κ κ
      (applyRestriction ρ (fullCompiledPoly ℚ M n h_le)) ≤ n ^ 215 :=
  pside_rank_from_depthcollapse_Step4 M n hn h_le κ hκ hκ_le ρ hgood.2.1

theorem npside_restricted_rank (n : ℕ)
    (hn : n ≥ 32) (hnNP : n ≥ npLowerThreshold) (heven : 2 ∣ n)
    (M : DTM)
    (h_le : npNumVars n ≤ numVars M n (Nat.log 2 n))
    (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment)
    (hgood : GoodRestriction M n ρ) :
    mlBlockedSpdpRank (compiledPartition M n) (Nat.log 2 n) (Nat.log 2 n)
      (applyRestriction ρ (fullCompiledPoly ℚ M n h_le)) ≥ n ^ (Nat.log 2 n / 4) :=
  npside_rank_from_identity_minor_Step5 n hn hnNP heven M h_le ρ hgood.2.2

/-- Backward-compatible alias for existence theorem. -/
abbrev explicit_restriction_exists := explicit_restriction_exists_S32_3

/-- Pure contradiction combiner for Steps 4 + 5 in the log-regime κ = log₂ n. -/
theorem restricted_rank_contradiction
    (M : DTM) (n : ℕ)
    (hn : n ≥ 32) (hnNP : n ≥ npLowerThreshold)
    (hnM : n ≥ max 4 M.numStates) (heven : 2 ∣ n)
    (h_le : npNumVars n ≤ numVars M n (Nat.log 2 n))
    (ρ : Fin (numVars M n (Nat.log 2 n)) → VarAssignment)
    (hgood : GoodRestriction M n ρ)
    (hexp : n ^ 215 < n ^ (Nat.log 2 n / 4)) : False := by
  have hκ : Nat.log 2 n ≥ 5 := by
    have : Nat.log 2 32 = 5 := by native_decide
    exact le_trans (by omega) (Nat.log_mono_right hn)
  have hP := pside_restricted_rank M n hnM h_le (Nat.log 2 n) hκ (le_rfl) ρ hgood
  have hNP := npside_restricted_rank n hn hnNP heven M h_le ρ hgood
  have hle : n ^ (Nat.log 2 n / 4) ≤ n ^ 215 := le_trans hNP hP
  exact (not_lt_of_ge hle) hexp

end RestrictionPipeline
